### ISSUE TITLE
How to add categorical features using the model

### ISSUE THREAD

**Issue by Hari7696** [awslabs/gluon-ts#100]
Hi, I doubt if we can actually harness the deepar estimator package here.
Even if i add categories to the data, The model is not processing the category variables. I am stuck. Can you anyone explain me how do we add categorical features to the model.

Temp is a dataframe consisting of No. of PART1's(articles) sold from the stores. The stores are label encoded.

train_ds = [{'start': start ,'feat_dynamic_cat':[x], 'target': list(temp[temp['Store']== x]['PART1'])[:-prediction_length] } for x in temp['R Store'].unique()]
test_ds = [{'start': start, 'feat_dynamic_cat':[x] , 'target': list(temp[temp['Store']==x]['PART1']) } for x in temp[' Store'].unique()]

**Comment by mbohlkeschneider** [comment]
Hi Hari7696,

what are the 'feat_dynamic_cat' features in your case? Are the article identifiers that are constant over the time series? If yes, please try to use 'feat_static_cat' as the field name instead. Please not that categorical features need to be processed to be numerical values by label encoding, one hot encoding etc. 

Hope that helps. Please reach out again if the issue persists.

**Comment by mbohlkeschneider** [comment]
Here is an example for valid input data: 

`
train_data = [
        {"start": "2019-01-01 00:00:00", "target": [1.0, 2.0, 3.0, 4.0],
         "feat_static_cat": [0]},
        {"start": "2019-01-01 00:00:00", "target": [1.0, 2.0, 3.0, 4.0, 5.0],
         "feat_static_cat": [1]}
    ]
`

Here, `feat_dynamic_cat` is the item identifier.

**Comment by Hari7696** [comment]
I am passing the data in the same format as you mentioned, after training the model , if i remove the feat_static_cat in the test data while doing the prediction, the model should throw an error but it is not throwing any error, so i guess while training the model is not processing the feat_static_cat

 [ {'start': Timestamp('2019-07-01 00:00:00', freq='4H'),
 'feat_static_cat': [1],
 'target': [12,19,44,79,64,27,6,10 ]
}, .......]

**Comment by mbohlkeschneider** [comment]
Hi Hari7696,

we have some guardrails in place in case the `feat_static_cat` field is not given, see here: 

https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepar/_estimator.py#L194

This will set the `feat_static_cat` features to [0] if they are not passed. Thus, removing them in test data will not cause the model to fail (but it might not perform as well as when passing the field). The `feat_static_cat` features should be used and processed during training. 

Best,
Michael

**Comment by Hari7696** [comment]
Thank you mbohlkeschneider, I got my answer
