### ISSUE TITLE
DeepAR how to extend create_transform?

### ISSUE THREAD

**Issue by Worulz** [awslabs/gluon-ts#1014]
Hi, I was hoping to extend the create_transform function in the DeepAR estimator, is there anyway to do this? I haven't found the extended [tutorial](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#2.1-Define-a-transformation) showing how even though it shows you how to define a transformation. 

https://github.com/awslabs/gluon-ts/blob/19040125268ac0b13290e148a60d19272ab6ae02/src/gluonts/model/deepar/_estimator.py#L236

hoping to add simple rolling averages etc.

**Comment by PascalIversen** [comment]
Hey @Worulz, you could extend the `DeepAREstimator` and overwrite `create_transformation` with your custom transformation:
```
class MyEstimator(DeepAREstimator):
    def create_transformation(self) -> Transformation:
        # your custom transformation
        pass
```
Does that help you?

**Comment by Worulz** [comment]
@PascalIversen thank you! I'll play around with it.
