### ISSUE TITLE
Release 0.5.1: recent code from master not included

### ISSUE THREAD

**Issue by MaximilianProll** [awslabs/gluon-ts#1015]
Hi,

I just installed version 0.5.1 via `pip install --upgrade mxnet==1.6 gluonts` and stumbled into an error using the `OffsetSplitter`.
The traceback is the following:
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-9-157d13f7a285> in <module>
      1 splitter = OffsetSplitter(prediction_length=24, split_offset=24)
----> 2 train, test = splitter.split(items=whole_dataset)

~/opt/anaconda3/envs/tmp_dem/lib/python3.8/site-packages/gluonts/dataset/split/splitter.py in split(self, items)
    195         split = TrainTestSplit()
    196 
--> 197         for item in map(TimeSeriesSlice.from_time_series_item, items):
    198             train = self._train_slice(item)
    199             test = self._trim_history(self._test_slice(item))

~/opt/anaconda3/envs/tmp_dem/lib/python3.8/site-packages/gluonts/dataset/split/splitter.py in from_time_series_item(cls, item, freq)
     76     ) -> "TimeSeriesSlice":
     77         if freq is None:
---> 78             freq = item.start.freq
     79 
     80         index = pd.date_range(

AttributeError: 'dict' object has no attribute 'start'

```
The failing line was already fixed in [master in this PR](https://github.com/awslabs/gluon-ts/pull/890).

That got me wondering how the old implementation ended up in the release.

I think that the released version [0.5.1](https://github.com/awslabs/gluon-ts/releases) is of a different branch than `master`, previous releases were of the branch `master`. 
The tagged commit `22e7aa7` ([link](https://github.com/awslabs/gluon-ts/commit/22e7aa78a2fcaa6e07b0730a45551bf937fd9193)) is associated to a PR for the branch `v0.5.x`.

Is it possible to get the recent master fixes included in the new releases?

**Comment by MaximilianProll** [comment]
Using the latest master via `pip install git+git://github.com/awslabs/gluon-ts.git#egg=gluon-ts` on the other hand works like a charm and no errors are raised. 
So the issue is that the latest release does not include recent master changes.

**Comment by lostella** [comment]
@MaximilianProll this seems like a missing backport, I'll try to write down a list of fixes that are needed in the 0.5.x branch

**Comment by lostella** [comment]
@MaximilianProll can you confirm that this is fixed in 0.5.2?

**Comment by MaximilianProll** [comment]
Wow, you guys are fast! 🚀  Thank you, yes, version 0.5.2 now includes the relevant fixes for the `OffsetSplitter`.

Could this PR also be included in the recent releases or was that left out on purpose?
- Scale the negative binomial's gamma() #909

**Comment by lostella** [comment]
Good point! Added that to #1016, feel free to comment there if you spot anything else.

Closing this, thanks a lot for pointing this out.
