### ISSUE TITLE
How to import a model ? I have an error : 'mxnet.context' has no attribute 'num_gpus'

### ISSUE THREAD

**Issue by Harry-N** [awslabs/gluon-ts#1027]
Hi everyone ! 

I have previously installed pip install mxnet. I followed the tutorial but when I want to import a model (For example : from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator). 
I have this error which appears : 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-1fca1cb620ad> in <module>
----> 1 from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
      2 from gluonts.trainer import Trainer

~\AppData\Roaming\Python\Python36\site-packages\gluonts\model\simple_feedforward\__init__.py in <module>
     13 
     14 # Relative imports
---> 15 from ._estimator import SimpleFeedForwardEstimator
     16 
     17 __all__ = ["SimpleFeedForwardEstimator"]

~\AppData\Roaming\Python\Python36\site-packages\gluonts\model\simple_feedforward\_estimator.py in <module>
     39 
     40 
---> 41 class SimpleFeedForwardEstimator(GluonEstimator):
     42     """
     43     SimpleFeedForwardEstimator shows how to build a simple MLP model predicting

~\AppData\Roaming\Python\Python36\site-packages\gluonts\model\simple_feedforward\_estimator.py in SimpleFeedForwardEstimator()
    101         freq: str,
    102         prediction_length: int,
--> 103         trainer: Trainer = Trainer(),
    104         num_hidden_dimensions: Optional[List[int]] = None,
    105         context_length: Optional[int] = None,

~\AppData\Roaming\Python\Python36\site-packages\gluonts\core\component.py in init_wrapper(*args, **kwargs)
    435                 self.__class__.__repr__ = validated_repr
    436 
--> 437             return init(self, **all_args)
    438 
    439         # attach the Pydantic model as the attribute of the initializer wrapper

~\AppData\Roaming\Python\Python36\site-packages\gluonts\trainer\_base.py in __init__(self, ctx, epochs, batch_size, num_batches_per_epoch, learning_rate, learning_rate_decay_factor, patience, minimum_learning_rate, clip_gradient, weight_decay, init, hybridize)
    148         self.init = init
    149         self.hybridize = hybridize
--> 150         self.ctx = ctx if ctx is not None else get_mxnet_context()
    151         self.halt = False
    152 

~\AppData\Roaming\Python\Python36\site-packages\gluonts\core\component.py in get_mxnet_context(gpu_number)
    496     Returns either CPU or GPU context
    497     """
--> 498     if num_gpus():
    499         logger.info("Using GPU")
    500         return mx.context.gpu(gpu_number)

~\AppData\Roaming\Python\Python36\site-packages\gluonts\core\component.py in num_gpus(refresh)
    484         n = 0
    485         try:
--> 486             n = mx.context.num_gpus()
    487         except mx.base.MXNetError as e:
    488             logger.error(f"Failure when querying GPU: {e}")

AttributeError: module 'mxnet.context' has no attribute 'num_gpus'

I don't know how to solve it… In advance, thank you very much for any help !

**Comment by PascalIversen** [comment]
Hey @Harry-N,
I think you are using the wrong version of mxnet.
Try again after`pip install --upgrade mxnet==1.6`.

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by Harry-N** [comment]
Hi Pascal, 
Thanks for your quick reply, it works ! In fact, I had already tried your suggestion before but the problem was that I had also installed on my virtual environment conda install -c anaconda mxnet so I uninstalled everything and i try again after pip install --upgrade mxnet = = 1.6.

Thank you again and have a nice day ! :)

**Comment by PascalIversen** [comment]
Great, have fun using GluonTS! 

Could you please close the issue? 

Thanks, you have a nice day too!
