### ISSUE TITLE
fbprophet 0.7 breaking build

### ISSUE THREAD

**Issue by slowjazz** [awslabs/gluon-ts#1029]
## Description
The dependency `fbprophet` 0.7 release is breaking the build because of conflicting version requirements for the `holidays` package.

fbprophet: `holidays>=0.10.2`
https://github.com/facebook/prophet/commit/3a436ec60343802e2dcc3251fe455fed7abc85d8

Gluon-ts: `holidays>=0.9,<0.10`
https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements.txt

Gluon-ts: `fbprophet>=0.4.*`
https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements-extras-prophet.txt

## To Reproduce
Run the setup: `pip install --upgrade mxnet==1.6 gluonts`

## Error message or code output

Building gluon-ts yields the error message during setup.py install for fbprophet:
```
 ImportError: cannot import name 'Turkey'
```

## Environment
- Operating system: Amazon Linux
- Python version: 3.6
- GluonTS version: 0.5.2
- MXNet version: 1.6

**Comment by jaheba** [comment]
Hello Kenneth,

thanks for filing the issue. I'm actually not sure why we fixed the dependency on holidays. I suspect updating the dependency should just work.

Do you want to give it a try?

**Comment by slowjazz** [comment]
Looks like removing the `<0.10` restriction from `holidays>=0.9,<0.10` results in a working build.
