### ISSUE TITLE
Test tutorial notebooks in CI.

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#104]
When having notebooks, we should make sure that new changes don't break them.

It's possible to extract the code from a notebook using https://pypi.org/project/nbless/ (`nbextract`).

/cc @mbohlkeschneider

**Comment by lostella** [comment]
Notebooks are generated from md files, see https://github.com/awslabs/gluon-ts/tree/master/docs/examples/forecasting, and run in the pipeline

cc @jgasthaus @benidis

**Comment by jaheba** [comment]
I think nbextract only works with the original jupyter-notebook files.

Shouldn't we aim to also publish these as tutorials?

**Comment by lostella** [comment]
We do, but the other way around:
* from https://github.com/awslabs/gluon-ts/tree/master/docs/examples/forecasting
* to a webpage http://gluon-ts.mxnet.io/examples/forecasting/tutorial.html *and* downloadable notebook http://gluon-ts.mxnet.io/_downloads/forecasting.zip

Note that the webpage shows the output of the notebook cells, so I'm assuming that if the notebook fails, Jenkins fails, but others may have more context on this latter point.
