### ISSUE TITLE
Question about feat_static_cat

### ISSUE THREAD

**Issue by NielsRogge** [awslabs/gluon-ts#1046]
In the [extended tutorial](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#2.1-Define-a-transformation), `feat_static_cat` is explained as: "static (over time) categorical features, list with dimension equal to the number of features"

What are examples of static categorical features? Are these features to identify individual time series, in case one wants to perform multivariate time series forecasting?

**Comment by timoschowski** [comment]
Example: If you have 5 different categorical features, the dimension needs to be 5.

Typically, you can have a categorical feature to identify groups of time series. E.g., all time series with categorical features A have a certain time of seasonality or a high volume or something, whereas time series with another feature behave differently.

**Comment by alexhallam** [comment]
Hi @timoschowski, I was just searching for `feat_static_cat` guidance also. If you don't mind I have a simple reproducible example that would clarify this for me. 

At the moment this trains fine, but it is not using `key` as a categorical feature. Could you show me how to modify this code to make that happen? 

```
from gluonts.dataset import common
from gluonts.model import deepar
from gluonts.model.deepar import DeepAREstimator
from gluonts.distribution.neg_binomial import NegativeBinomialOutput
from gluonts.trainer import Trainer

import pandas as pd
data = "https://gist.githubusercontent.com/alexhallam/f0410e546fde69e8bda92e89878386fe/raw/b582d71840de595e8329efec899ec3bfe17db32a/car_train.csv"
df = pd.read_csv(data)
df_cats = pd.get_dummies(df['key'], prefix='part')
data = common.ListDataset([{
    "start": df.date[0],
    "target": df.value,
    'feat_static_cat': df_cats
}],freq="d")
estimator = DeepAREstimator(
    prediction_length=6,
    freq="D",
    distr_output = NegativeBinomialOutput(),
    #use_feat_static_cat=True,
    trainer=Trainer(
        epochs=5
    )
)
predictor = estimator.train(training_data=data)
prediction = next(predictor.predict(data))
print(prediction.mean)
prediction.plot(output_file='graph.png')
```

**Comment by NielsRogge** [comment]
@alexhallam is this a single or multivariate time series?

**Comment by alexhallam** [comment]
Well, I know that I can model each of these series individually, but I also wanted to compare those results with using each time series key as a feature. A pooled vs non-pooled set up. What I am trying to do above is use each time series as a categorical feature.

**Comment by StatMixedML** [comment]
@alexhallam You might want to try the following for creating your dataset (using the code-snippet from above)

```python
from gluonts.dataset.common import ListDataset
from gluonts.dataset.field_names import FieldName

data_list = ListDataset(
    [
        {FieldName.START: pd.Timestamp(df_cats.iloc[:, col_idx].index[0], freq = "d"),
         FieldName.TARGET: df_cats.iloc[:, col_idx].values,
         FieldName.ITEM_ID: df_cats.columns[col_idx],
         FieldName.FEAT_STATIC_CAT: np.array([col_idx]),
        }
        for col_idx in range(df_cats.shape[1])
    ],
    freq="d"
)
```
It creates the dataset that can be used for model training. You can check out some of the entries of `gluonts.dataset.common.ListDataset` 

```python
data_list.list_data[0]
```
showing 

```python
{'start': Timestamp('1970-01-01 00:00:00', freq='D'),
 'target': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'item_id': 'part_10055165',
 'feat_static_cat': array([0])}
```
The categorical feature `feat_static_cat`  corresponds to the numeric index of the loop, `item_id` is the column name.

**Comment by alexhallam** [comment]
This answers the question for me. What do you think @NielsRogge?
