### ISSUE TITLE
Add Temporal Fusion Transformer (TFT)

### ISSUE THREAD

**Issue by skybullet1987** [awslabs/gluon-ts#1049]
## Description
Add Temporal Fusion Transformer (TFT)

## References
- https://arxiv.org/pdf/1912.09363.pdf
- https://github.com/jdb78/pytorch-forecasting

**Comment by timoschowski** [comment]
There's a PR open here: https://github.com/awslabs/gluon-ts/pull/962 

this is coming.

**Comment by skybullet1987** [comment]
Awesome! Thanks!

**Comment by lostella** [comment]
@skybullet1987 #962 got merged

**Comment by alexcombessie** [comment]
Hi @lostella,

I am quite interested in this model. I saw that it was merged, but I can't find it in the documentation or the milestone.

I am not in a particular rush about this, but I am just curious to know when this will make it into an official release?

Cheers,

Alex

**Comment by lostella** [comment]
@alexcombessie the model will be included in the next release v0.6.0; we've been delaying this release a bit, but all necessary commits should be there, so this should be released somewhere next week. In the mean time, if you want to try it out you can play with the `master` branch

**Comment by lostella** [comment]
@alexcombessie [v0.6.0](https://github.com/awslabs/gluon-ts/releases/tag/v0.6.0) was released, is available on PyPI, and contains the TFT implementation

**Comment by alexcombessie** [comment]
I saw that yesterday, thanks for the kind message. I am genuinely amazed by the release, not just for the new TFT model. You are doing amazing work!
