### ISSUE TITLE
Robustness of DeepAR for long prediction horizons

### ISSUE THREAD

**Issue by kasungayan** [awslabs/gluon-ts#1076]
Hi Team,

I am working on a daily time series dataset with different lengths (a mix of short and long time series with different start dates). Following is a subset of the dataset (2 time series out of >1000 time series)

**training_list:**

```
array([array([4.143, 4.116, 4.101, 4.124, 4.111, 4.102, 4.117, 4.085, 4.058,
       4.055, 4.1  , 4.129, 4.118, 4.109, 4.148, 0.   , 4.151, 4.898,
       9.213, 4.072, 4.112, 4.109, 4.15 , 4.134, 4.133, 4.174, 4.19 ],
      dtype=float32),
       array([21.407, 17.804, 20.556,  0.   , 16.361,  0.   , 19.773, 17.068,
       24.182,  0.   , 15.687, 18.706, 17.409, 17.141, 23.274, 18.599,
       18.15 , 15.012, 19.974,  0.   ,  0.   , 13.805, 14.718, 16.294,
       11.539, 15.861, 13.928, 19.041, 14.169, 17.969,  0.   ,  0.   ,
       15.521, 26.825, 22.265, 15.191, 18.416, 22.759, 19.754, 20.173
       ], dtype=float32)], dtype=object)
```

Following are the starting date list:

**start_dates**
```
array([Timestamp('2017-08-01 00:00:00', freq='D'),
       Timestamp('2017-10-01 00:00:00', freq='D'),
       Timestamp('2017-09-01 00:00:00', freq='D')], dtype=object)
```
Following is the construction of ListDataset object for the above dataset (training)

`train_ds = ListDataset([{'target': x, 'start': start} 
                        for (x, start) in zip(training_list, start_dates)], freq= 'D')`

I use the default DeepAR estimator as following (Just for training purposes). Notice my prediction horizon is 365. There are a few time series with the training length of 365, but most of them are shorter than this (around 30, 40, 50 , 100)

`estimator = DeepAREstimator(
    prediction_length= 365,
    freq='D',
    num_layers=2,
    num_cells=20,
    trainer=Trainer(ctx="cpu", 
                    epochs=5, 
                    learning_rate=1e-3, 
                    num_batches_per_epoch=1
                   )
)`

When I execute the following code, I notice that the model training gets lagged (iterations freezes), however when I set the **prediction_length** to a shorter value (10,20, 50), the model training continues as usual

`predictor = estimator.train(train_ds)`

Is this a known issue or are there any better ways to deal with these types of forecasting problems in GluonTS ? (short time series, but the prediction horizons are bigger than the training set in a single time series) )?

Thanks.

**Comment by PascalIversen** [comment]
Hey @kasungayan,
DeepAR employs the `InstanceSplitter` transformation which currently cannot handle time series that are shorter than the `prediction_length`. 
This is usually not needed because for most applications the `prediction_length` is much smaller than the length of the time series in the dataset.
The training lags because most instances which are picked from your dataset are discarded, as only a few have length 365.
For this dataset, you should lower your `prediction_length`, maybe to a few days.

Note also, that the `context_length` defaults to the `prediction_length`.

**Comment by PascalIversen** [comment]
Closing this for now, feel free to reopen if you have any concerns.
