### ISSUE TITLE
Import of Trainer fails: ModuleNotFoundError: No module named 'gluonts.mx'

### ISSUE THREAD

**Issue by FlorisCalkoen** [awslabs/gluon-ts#1089]
### Description

In section 3.1 of the [extended gluon ts tutorial](https://github.com/awslabs/gluon-ts/blob/master/docs/examples/extended_forecasting_tutorial/extended_tutorial.md) I am not able to import the ``` cls Trainer```. 

When running ```from gluonts.mx.trainer import Trainer``` it fails with the following error: 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-80-36acdcf26161> in <module>()
      1 from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
----> 2 from gluonts.mx.trainer import Trainer

ModuleNotFoundError: No module named 'gluonts.mx'
```

It seems that this is just a small bug in the tutorial which can be fixed by importing the ```cls Trainer``` from ```gluonts.trainer``` instead.

**Comment by dai-ichiro** [comment]
Duplicate?
https://github.com/awslabs/gluon-ts/pull/1005

**Comment by lostella** [comment]
@FlorisCalkoen hi, your link is to the documentation on the `master` branch, which contains yet-to-be-released changes. If you're using `0.5.2` you need to follow the "stable" documentation (see link on top of the README on GitHub): there the tutorial imports the `Trainer` correctly, see e.g. [this section](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#3.1-Configuring-an-estimator)

**Comment by lostella** [comment]
I'm updating the other links in the README, that point to the `master` version of things

**Comment by Pratik325** [comment]
No module named 'gluonts.trainer' 

@lostella  same issue...

**Comment by lostella** [comment]
@Pratik325 Please try

```python
from gluonts.mx.trainer import Trainer
```

**Comment by naivomah3** [comment]
Hi @lostella 
From which (stable)version `gluonts.mx.trainer` is supported? And which Mxnet version is required?

**Comment by lostella** [comment]
@naivomah3 that import path is enabled since gluonts 0.7.0, which requires mxnet 1.7 (although I would recommend using 1.8)
