### ISSUE TITLE
time_feature for Easter raised error for target date on 2018-10-06

### ISSUE THREAD

**Issue by Xiaolu-Zhu** [awslabs/gluon-ts#1094]
I encountered error message "ssertionError: No closest holiday for the date index 2018-10-06 00:00:00 found." when creating time feature for holidays. The current setting MAX_WINDOW = 183 + 4 failed for Easter Sunday with target date index on 2018-10-06. And here is the source code I am looking at: src/gluonts/time_feature/holiday.py.

**Comment by PascalIversen** [comment]
Thanks for reporting this @Xiaolu-Zhu. The `MAX_WINDOW` is too short, as the earliest possible date for eastern is March, 22 and the last possible date is April, 25. `MAX_WINDOW =183+17` should work for eternity.

**Comment by PascalIversen** [comment]
This is now fixed on the master branch and will be part of the next GluonTS release (0.6.0).
