### ISSUE TITLE
What the time_feat mean in Deep Factors for Forecasting?

### ISSUE THREAD

**Issue by zhaopengfei12345** [awslabs/gluon-ts#1098]
(Please state your question in the title, and add here any relevant details,
like a description of the problem, code snippets, examples, and so on.)

**Comment by zhaopengfei12345** [comment]
Is it the history data or time feature of every time series?

**Comment by zhaopengfei12345** [comment]
Or the history data of all time series?

**Comment by zhaopengfei12345** [comment]
feat_static_cat: Tensor,  # (batch_size, 1)
        time_feat: Tensor,  # (batch_size, history_length, num_features)
    ) -> (Tensor, Tensor):  # both of size (batch_size, history_length, 1)

**Comment by dcmaddix** [comment]
Yes it is `feat_dynamic_real` for DeepFactors.  In the transformation chain here https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deep_factor/_estimator.py#L158,  we set it equal to the time feature of every time series.
