### ISSUE TITLE
Confidence intervals too large?

### ISSUE THREAD

**Issue by mariosantosprivate** [awslabs/gluon-ts#1110]
Hello everyone, 

I've recently been using Gluon TS in particular the Deep AR estimator. 
The dataset I'm working on consists of roughly 1000 time series, each representing total daily sales for different stores. 
The time series length is roughly 900 days. I'm using both real dynamic features and static categorical features.
I'm also using the Negative Binomial distribution.

After training the model, the median prediction values come close to the actual values however the range of the prediction intervals seems too large. I've tried changing the default hyper-parameters but no changes have improved this.

(prediction_length for this image is 56 days)
![assdasdasd](https://user-images.githubusercontent.com/25696878/97213819-0fb7ed00-17ba-11eb-8520-e9e6948b3b5e.png)

I thought this might be due to the variance of daily sales in each store, (some stores selling thousands while others hundreds), so I tried training the model with only 1 of the time series (for only 1 store), and again the median prediction values are close but the intervals again seem too large:

(prediction_length in this image is 14 days)
![assdasdasd23](https://user-images.githubusercontent.com/25696878/97214628-43474700-17bb-11eb-8e19-59d64d76ae54.png)

What might be happening here?

**Comment by kaijennissen** [comment]
@mariosantosprivate Which distribution are you using?

**Comment by mariosantosprivate** [comment]
> @mariosantosprivate Which distribution are you using?

Oh sorry, forgot to mention, I'm using the Negative Binomial distribution

**Comment by kashif** [comment]
kindly try the master branch for a fix (see #909)

**Comment by mariosantosprivate** [comment]
> kindly try the master branch for a fix (see #909)

@kashif Thank you so much, that fixed it!
