### ISSUE TITLE
Could you please implement full list of models available in Gluonts

### ISSUE THREAD

**Issue by valeman** [awslabs/gluon-ts#1118]
## Description
(A clear and concise description of what the feature is.)
- If the proposal is about a new model, provide description of what the model is.
- If the proposal is about an API, provide mock examples if possible.

## References
- list reference and related literature
- list known implementations

**Comment by lostella** [comment]
Yes, this should definitely have a dedicated section of the documentation -- thanks for pointing this out!

**Comment by lostella** [comment]
This is now part of the documentation (since a while, actually) see https://ts.gluon.ai/dev/getting_started/models.html
