### ISSUE TITLE
Are all required tracked inside py3-master.yml ? #1119

### ISSUE THREAD

**Issue by kaijennissen** [awslabs/gluon-ts#1120]
## Description
It seems as if not all required dependencies are tracked inside `env/cpu/*`  or am I missing something?
Running the commands described below the following modules are highlighted as missing: `xgboost`, `pytorch`and `sklearn`

## To Reproduce
```
git clone https://github.com/awslabs/gluon-ts
cd gluon-ts
conda env create --name gluon-ts --file ./env/cpu/py3-master.yml
conda activate gluon-ts
pip install -e ".[shell]"
pytest --collect-only
```

**Comment by lostella** [comment]
Hey @kaijennissen I think those files are somewhat outdated, they were used by another continuous integration pipeline that we used, but we currently rely on GitHub Workflows only — to run the full test suite you can rely on all the `pip install`s which are listed here: https://github.com/awslabs/gluon-ts/blob/master/.github/workflows/tests.yml
