### ISSUE TITLE
How to feed transformed data into a trainer?   

### ISSUE THREAD

**Issue by FlorisCalkoen** [awslabs/gluon-ts#1123]
### Issue: 

When I'm feeding transformed time series data into the trainer, processing appears to start, but actually doesn't make any progress.

### Description:
With ```gluonts.transform.Chain``` I am trying to transform my ```ListDataset``` to a richer dataset which will hopefully improve my predictions. However, when I am trying to train an estimator on this transformed dataset processing appears to get stuck. Debugging I found out that the object returned by the transformation is a ```generator``` and not a ```ListDataset```. The structure of data inside this generator is similar to structure of the data inside the original ```ListDataset```, although the generator does not contain ```target``` key.  

How do I successfully train estimators on a transformed dataset? 

### Replicate 

To replicate this issue I converted my problem into a notebook using some tutorial data. Please find it at the following link: 

https://colab.research.google.com/drive/1xvVRY8wrWVuT8VydJoUAOgWfFvawXqb1?usp=sharing

**Comment by jgasthaus** [comment]
If you want to change the transformation chain used by a pre-defined model, the simplest way is to subclass the model and override the ```create_transformation``` method, e.g. in your example

```
from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator

class MySimpleFeedForward(SimpleFeedForwardEstimator):

  def create_transformation(self):
    return Chain(
        [
            AddObservedValuesIndicator(
                target_field=FieldName.TARGET,
                output_field=FieldName.OBSERVED_VALUES,
            ),
            AddAgeFeature(
                target_field=FieldName.TARGET,
                output_field=FieldName.FEAT_AGE,
                pred_length=self.prediction_length,
                log_scale=True,
            ),
            InstanceSplitter(
                target_field=FieldName.TARGET,
                is_pad_field=FieldName.IS_PAD,
                start_field=FieldName.START,
                forecast_start_field=FieldName.FORECAST_START,
                train_sampler=ExpectedNumInstanceSampler(num_instances=1),
                past_length=self.context_length,
                future_length=self.prediction_length,
                time_series_fields=[
                    FieldName.FEAT_AGE,
                    FieldName.FEAT_DYNAMIC_REAL,
                    FieldName.OBSERVED_VALUES,
                ],
            ),
        ]
    )
```

The alternative is to use a ```transformation.TransformedDataset``` to apply a transformation to a dataset and obtain a new dataset. However, in that case the transformation declared in the model will still be applied, and you have to make sure that whatever you are applying additionally can be combined (e.g. in your example, it doesn't make sense to apply InstanceSplitter twice).

**Comment by FlorisCalkoen** [comment]
Cheers, that helps! I'm closing this issue.
