### ISSUE TITLE
GluonPredictor should accept a Dataset as argument to `as_symbol_block_predictor`

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#1133]
## Description

[This method](https://github.com/awslabs/gluon-ts/blob/13eb1f5396240232ddc6ea04ad37eb8fbf3af150/src/gluonts/mx/model/predictor.py#L136-L138) is not really easy to use, since coming up with a batch requires applying transformations and so on. The predictor itself knows how to do it, so the method could get a `Dataset` instead (e.g. the one that one wants to get predictions out of) and extract a single batch out of it automatically.

cc @timforby

**Comment by timforby** [comment]
For now I have this quick little hack that __seems__ to work:
```python
    def as_symbol_block_predictor(
        self, dataset: Dataset
    ) -> SymbolBlockPredictor:
        inference_data_loader = InferenceDataLoader(
            dataset,
            transform=self.input_transform,
            batch_size=self.batch_size,
            stack_fn=partial(batchify, ctx=self.ctx, dtype=self.dtype)
        )
        batch = next(iter(inference_data_loader))
        ...
```

**Comment by lostella** [comment]
that's pretty much the change I was thinking about, I think

**Comment by lostella** [comment]
@timforby could you open a PR for this?
