### ISSUE TITLE
Correct shape for target_values? len(test_ds) giving time series length instead of number of time series

### ISSUE THREAD

**Issue by mariosantosprivate** [awslabs/gluon-ts#1144]
Hello, I'm having some trouble regarding the correct shape for the target_values list.

I have a dataset of daily sales per store, containing 934 time series (stores), each with 894 time points (daily sales and other features)

I found in an old issue (https://www.gitmemory.com/issue/awslabs/gluon-ts/280/531170377) that:

target shape: (num_series, ts_length)
feat_dynamic_real shape: (num_series, num_features, ts_length)

So my test_target_values.shape = (934, 894)

However, when computing the metrics using the default evaluator:

agg_metrics_deepAR, item_metrics_deepAR = evaluator(iter(tss), iter(forecasts), num_series=len(test_ds))

the num_series = len(test_ds) is 894 (time series length), instead of 934 (actual number of time series)
And if I try to manually insert num_series = 934 I get the error:

AssertionError: num_series=934 did not match number of elements=894

Is this in fact a bug or am I doing something wrong?

**Comment by PascalIversen** [comment]
Closing this as we are discussing this over at #1143
