### ISSUE TITLE
How to properly use the DeepFactorEstimator?

### ISSUE THREAD

**Issue by kaijennissen** [awslabs/gluon-ts#1149]
I'm currently working on a problem for which (I think) the DeepFactorEstimator would be a good fit.
Since I was not able to produce resonable results, I went back to the `electricity` dataset in which the DeepFactorEstimator, according to the "DeepFactor for Forecasting" paper, showed good performance. 
Unfortunately my results are not even close to the results reported in the paper (MAPE of DeepAR ~0.272+-0.078, MAPE of DeepFactor 0.112 +-0.012). 
Below you can find the results of DeepAR and DeepFactor that I run. DeepAR is much better than reported in the paper, but results of DeepFactor are terrible.
What am I doing wrong? 

Results from **DeepAR**:

- MASE: 0.9355505522219449
- **MAPE: 0.10065016337373792**
- sMAPE: 0.1194762484355239
- QuantileLoss[0.1]: 13170011.724641949
- QuantileLoss[0.9]: 25599926.93581094
- Coverage[0.1]: 0.03719774514167038
- Coverage[0.9]: 0.8366340305592641

and **DeepFactorEstimator**

- MASE: 35.23259980872068
- **MAPE: 6.789305935703429**
- sMAPE: 1.0137435779683674
- QuantileLoss[0.1]: 227314447.33551025
- QuantileLoss[0.9]: 511438013.5109009
- Coverage[0.1]: 0.7345287543885675
- Coverage[0.9]: 0.7475955595114473

```
from gluonts.dataset.repository.datasets import get_dataset
from gluonts.evaluation import Evaluator
from gluonts.evaluation.backtest import make_evaluation_predictions
from gluonts.model.deep_factor import DeepFactorEstimator
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer
from gluonts.mx.distribution import StudentTOutput


dataset = get_dataset("electricity")
metadata = dataset.metadata

deepar = DeepAREstimator(
    freq=metadata.freq,
    prediction_length=72,
    context_length=168,
    num_layers=1,
    num_cells=50,
    cell_type="lstm",
    dropout_rate=0.1,
    scaling=True,
    distr_output=StudentTOutput(),
    trainer=Trainer(),
)

deepfactor = DeepFactorEstimator(
    freq=metadata.freq,
    prediction_length=72,
    context_length=168,
    num_layers_global=1,
    num_hidden_global=50,
    num_factors=10,
    num_layers_local=1,
    num_hidden_local=5,
    cell_type="lstm",
    distr_output=StudentTOutput(),
    trainer=Trainer(),
)


def main(estimator):

    predictor = estimator.train(
        training_data=dataset.train, num_workers=8)

    QUANTILES = [0.1, 0.9]
    evaluator = Evaluator(
        quantiles=QUANTILES,
        num_workers=8
    )

    forecast_it, ts_it = make_evaluation_predictions(
        dataset=dataset.test,
        num_samples=200,
        predictor=predictor,
    )

    forecasts = list(forecast_it)
    tss = list(ts_it)
    agg_metrics, item_metrics = evaluator(tss, forecasts)

    metrics = [
        "MASE",
        "MAPE",
        "sMAPE",
    ] + \
        [
        f"QuantileLoss[{QUANTILES[i]}]" for i in range(len(QUANTILES))] + \
        [
        f"Coverage[{QUANTILES[i]}]" for i in range(len(QUANTILES))
    ]

    for metric in metrics:
        print(f"{metric}: {agg_metrics[metric]}")


if __name__ == "__main__":

    main(deepar)
    main(deepfactor)

```

**Comment by kaijennissen** [comment]
I've figured out, that I have to set `cardinality` to the number of time series in the training dataset.

**Comment by Erxiong222** [comment]
DeepFactorEstimator no scaling.
