### ISSUE TITLE
What if I have some features that are not known in the future

### ISSUE THREAD

**Issue by Roxyi** [awslabs/gluon-ts#1163]
Hi,
I guess for most models in gluon-ts, associated feature time series should be known in the future. What if I have some strong indicators that are not known in the future but still want to use them in some gluon-ts models? For example, I would like to predict the repay amount of credit cards and the loan amount would be a good feature. How to make this case work in gluon-ts?

**Comment by mbohlkeschneider** [comment]
Hi @Roxyi,

Thank you for your interest in GluonTS. 

I'm not sure what the current state is, but I think [MQCNN](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/seq2seq/_seq2seq_estimator.py) could be able to do this. DeepAR will need the features to be known in the future. 

Maybe @dcmaddix can confirm? 

Best,
Michael

**Comment by cesans** [comment]
In the case of DeepAR, isn't it also reasonable to include those features as part of the target (as a multivariate series)? I haven't tried this, but I think the GluonTS implementation supports it.

Ideally you would exclude the output for the feature in the loss during training... but I think this could help anyway.

**Comment by Roxyi** [comment]
@mbohlkeschneider Thank you Michael, I'll do some experiments with MQCNN first.

**Comment by Roxyi** [comment]
@cesans Thanks for the suggestion! I guess when you said that "include those features as part of the target", you mean to expand the dimension of the target with features? If so, maybe GPVAR or DeepVAR would be better, cuz DeepAR doesn't work for multidimensional target. But we can add those features as separate time series so the target of each time series is still one dimensional.
