### ISSUE TITLE
How to set multi GPU train model?

### ISSUE THREAD

**Issue by k-user** [awslabs/gluon-ts#1164]
I can't find how to set up multi-GPU training in the document.But I see it in branch, how do I use it？Thanks!

**Comment by zhl410** [comment]
@k-user  I meet same problems as you,  do you find the correct solutions? 
I try to use multi GPU:
`import mxnet as mx
deviec_ctx= [mx.gpu(4), mx.gpu(5)]
# device_ctx = mx.gpu(4)
estimator = MyEstimator(
    prediction_length=dataset.metadata.prediction_length,
    context_length=100,
    freq=dataset.metadata.freq,
    trainer=Trainer(ctx = str([mx.gpu(4), mx.gpu(5)]),
                    epochs=5,
                    learning_rate=1e-3,
                    num_batches_per_epoch=100
                   )
)
`
But  It did't work, give below errors:
`
ValidationError: 1 validation error for TrainerModel
ctx
  bad MXNet context [gpu(4), gpu(5)], expected either an mx.context.Context or its string representation (type=value_error)
`
However in class Trainer, I find init parameters _ctx_ can accept a list of  Context:
`class Trainer:
    r"""
    @validated()
    def __init__(
        self,
        ctx: Optional[mx.Context] = None,
       # ctx = None,
        epochs: int = 100,
        batch_size: int = 32,
        num_batches_per_epoch: int = 50,
        learning_rate: float = 1e-3,
        learning_rate_decay_factor: float = 0.5,
        patience: int = 10,
        minimum_learning_rate: float = 5e-5,
        clip_gradient: float = 10.0,
        weight_decay: float = 1e-8,
        init: Union[str, mx.initializer.Initializer] = "xavier",
        hybridize: bool = True,
        avg_strategy: Union[
            AveragingStrategy, IterationAveragingStrategy
        ] = SelectNBestMean(num_models=1),
        post_initialize_cb: Optional[Callable[[mx.gluon.Block], None]] = None,
    ) -> None:


......
 net.initialize(ctx=self.ctx, init=self.init) # It should also ok in muti GPU
.......
`

**Comment by zhl410** [comment]
It seems a bad news,  currently estimator functions accept a Context object. Context can support only one gpu. Please refer to issue#162 and #657.

**Comment by k-user** [comment]
I use queries about GPU usage and memory to allocate processes to the GPU with less footprint. @zhl410
