### ISSUE TITLE
ModuleNotFoundError: No module named 'gluonts.dataset'; 'gluonts' is not a package

### ISSUE THREAD

**Issue by eholgersson** [awslabs/gluon-ts#1177]
Hi,
I'm facing a weird error using gluonts.

I'm trying to go through this example: [https://ts.gluon.ai/examples/extended_forecasting_tutorial/extended_tutorial.html](url)

In the initial steps I try to load datasets from GluonTS repo using:
from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes

However, this causes the following error when executing the script using visual studio code:
ModuleNotFoundError: No module named 'gluonts.dataset'; 'gluonts' is not a package

The weird part is that it works when I execute the code line by line, also using visual studio code.

Has anybody come across this behaviour before?

**Comment by deltawi** [comment]
I've got the same error doing : 
`from gluonts.dataset.repository import get_dataset`
Getting: 

`ImportError: cannot import name 'get_dataset' from 'gluonts.dataset.repository' (/usr/local/lib/python3.7/dist-packages/gluonts/dataset/repository/__init__.py)`
