### ISSUE TITLE
Attribute Error when import deepar  using from gluonts.model import deepar

### ISSUE THREAD

**Issue by vishyML** [awslabs/gluon-ts#1207]
(Please state your question in the title, and add here any relevant details,
like a description of the problem, code snippets, examples, and so on.)

**Comment by vishyML** [comment]
The attribute error i get is as follows.
from gluonts.model import deepar
AttributeError                            Traceback (most recent call last)
<ipython-input-6-54d69aa4595e> in <module>
----> 1 from gluonts.mx.model.estimator import GluonEstimator

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gluonts\mx\model\estimator.py in <module>
     22 from gluonts.dataset.common import Dataset
     23 from gluonts.dataset.loader import TrainDataLoader, ValidationDataLoader
---> 24 from gluonts.model.estimator import Estimator
     25 from gluonts.model.predictor import Predictor
     26 from gluonts.mx.batchify import as_in_context, batchify

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gluonts\model\estimator.py in <module>
     24 from gluonts.dataset.common import Dataset
     25 from gluonts.dataset.loader import TrainDataLoader, ValidationDataLoader
---> 26 from gluonts.model.predictor import Predictor
     27 from gluonts.transform import SelectFields, Transformation
     28 

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gluonts\model\predictor.py in <module>
     32 from gluonts.core.serde import dump_json, load_json
     33 from gluonts.dataset.common import DataEntry, Dataset
---> 34 from gluonts.model.forecast import Forecast
     35 
     36 if TYPE_CHECKING:  # avoid circular import

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gluonts\model\forecast.py in <module>
    298 
    299 
--> 300 class SampleForecast(Forecast):
    301     """
    302     A `Forecast` object, where the predicted distribution is represented

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gluonts\model\forecast.py in SampleForecast()
    318 
    319     @validated()
--> 320     def __init__(
    321         self,
    322         samples: np.ndarray,

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gluonts\core\component.py in validator(init)
    290 
    291         if base_model is None:
--> 292             PydanticModel = create_model(
    293                 f"{init_clsnme}Model",
    294                 __config__=BaseValidatedInitializerModel.Config,

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\main.py in create_model(__model_name, __config__, __base__, __module__, __validators__, **field_definitions)
    842         namespace['Config'] = inherit_config(__config__, BaseConfig)
    843 
--> 844     return type(__model_name, (__base__,), namespace)
    845 
    846 

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\main.py in __new__(mcs, name, bases, namespace, **kwargs)
    250                     ):
    251                         continue
--> 252                     fields[ann_name] = inferred = ModelField.infer(
    253                         name=ann_name,
    254                         value=value,

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\fields.py in infer(cls, name, value, annotation, class_validators, config)
    307         field_info.alias = field_info.alias or field_info_from_config.get('alias')
    308         annotation = get_annotation_from_field_info(annotation, field_info, name)
--> 309         return cls(
    310             name=name,
    311             type_=annotation,

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\fields.py in __init__(self, name, type_, class_validators, model_config, default, default_factory, required, alias, field_info)
    269         self.shape: int = SHAPE_SINGLETON
    270         self.model_config.prepare_field(self)
--> 271         self.prepare()
    272 
    273     def get_default(self) -> Any:

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\fields.py in prepare(self)
    343 
    344         self._set_default_and_type()
--> 345         self._type_analysis()
    346         if self.required is Undefined:
    347             self.required = True

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\fields.py in _type_analysis(self)
    437                 self.outer_type_ = self.type_
    438                 # re-run to correctly interpret the new self.type_
--> 439                 self._type_analysis()
    440             else:
    441                 self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]

c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pydantic\fields.py in _type_analysis(self)
    480             self.shape = SHAPE_SEQUENCE
    481         elif issubclass(origin, Mapping):
--> 482             self.key_field = self._create_sub_type(self.type_.__args__[0], 'key_' + self.name, for_keys=True)
    483             self.type_ = self.type_.__args__[1]
    484             self.shape = SHAPE_MAPPING

c:\users\administrator\appdata\local\programs\python\python39\lib\typing.py in __getattr__(self, attr)
    646         if '__origin__' in self.__dict__ and not _is_dunder(attr):
    647             return getattr(self.__origin__, attr)
--> 648         raise AttributeError(attr)
    649 
    650     def __setattr__(self, attr, val):

AttributeError: __args__

​

**Comment by vishyML** [comment]
Any help will be useful

**Comment by lostella** [comment]
What version of GluonTS are you using? What version of Python? What operating system are you on?

**Comment by lostella** [comment]
You appear to be using Python 3.9 on Windows. Could you try switching to 3.8 or 3.7?

**Comment by vishyML** [comment]
Yes, I am using Python 3.9.  I am using the version gluonts version which
come with pip install on Windows 10 . I will try using Python < 3.8

**Comment by vishyML** [comment]
I switched python to version 3.8 and it worked
Thanks

**Comment by adasiitm** [comment]
I am getting similar error. Please help. Thanks!
Versions:
mxnet==1.6.0
gluonts==0.7.0
Python 3.7.10
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-43edc605a3a1> in <module>
      4 from gluonts.mx.trainer import Trainer
      5 
----> 6 from gluonts.model.estimator import GluonEstimator
      7 from gluonts.model.predictor import Predictor#, RepresentableBlockPredictor
      8 from gluonts.core.component import validated

ImportError: cannot import name 'GluonEstimator' from 'gluonts.model.estimator' (/opt/conda/lib/python3.7/site-packages/gluonts/model/estimator.py)`

**Comment by lostella** [comment]
@adasiitm please try replacing the failing import with

```python
from gluonts.mx.model.estimator import GluonEstimator
```

**Comment by adasiitm** [comment]
Thanks @lostella for the quick response! Worked for me. Also reverting back to older version helps w/o mx.

**Comment by rhljain** [comment]
hey @lostella I am using gluonts DeepAR algorithm but I am getting different predictions every time I train the model on same dataset (timeseries) and for same period and with same hyperparameters.

Any help will be greatly appreciated!

Thanks

**Comment by rhljain** [comment]
Hi, @lostella I am fitting DeepAR and getting the different predictions and MAPE values though I set the same hyperparameters and same training data....

Any help will be greatly appreciated!

**Comment by lostella** [comment]
@rhljain this is expected to some extent: there are sources of randomness throughout the training loop, when iterating over the data; in addition to that, DeepAR predictions are obtained by randomly sampling sequences from the predictive distributions, so even with the same model, predicting twice may lead to slightly different statistics (eg mean, quantiles) in the predictions.

For the first issue, you can check what loss value you are reach in different runs, to see whether training is just finishing at significantly different points. If that’s the case, you could try training longer epochs. Another thing to consider is providing validation data (although this is not well documented).

This is a general issue, for which we plan on providing a more “robust” default training loop, so that two training runs of the same estimator on the same data will likely result in very similar models, but I don’t have an ETA for that.

**Comment by rhljain** [comment]
Thanks @lostella, is there any other frameworks available which we can use to develop DeepAR models and Deep renewal Model?

Thanks

**Comment by rhljain** [comment]
I am dealing with lot of lumpy and intermittent data, so tried all the traditional models like Holt winters, Croston, ML models,
anything related to deep learning which you have tried and tested while dealing with lumpy and intermittent data??

**Comment by lostella** [comment]
@rhljain the DeepAR model is also implemented in PyTorch within GluonTS, and that uses the PyTorch Lightning training loop: https://github.com/awslabs/gluon-ts/tree/dev/src/gluonts/torch/model/deepar

Only a handful of models are available that are implemented in PyTorch, but we're planning on growing the set

**Comment by rhljain** [comment]
@lostella Thanks for quick reply really appreciable!
