### ISSUE TITLE
Split dependencies

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#122]
We should think about splitting the dependencies. For example, `matplotlib` is only useful if you want to display data, but not needed when running training on a server.

We could use "extras" in `setup.py`  and have something like:

```sh
    # barebone
    $ pip install gluonts

    # full-installation
    $ pip install "gluonts[notebook]"
```

**Comment by aalexandrov** [comment]
👍 in general, if we can scope a bigger chunk of dependencies. Do you have other candidates besides `matplotlib`?

We are already using the extras for the ARIMA and ETS models.

**Comment by AaronSpieler** [comment]
We have split the requirements across multiple files now, but `matplotlib` is still one of the default requirements.
Can we still close this issue @jaheba?

**Comment by jaheba** [comment]
These are the requirements listed in `requirements.txt`:

```
holidays>=0.9,<0.10
matplotlib~=3.0
numpy~=1.16
pandas~=1.0
pydantic~=1.1
tqdm~=4.23
ujson~=1.35
```

Of these `matplotlib`  looks like a clear outlier.

I think, `tqdm` we don't strictly need, same probably with `ujson` (can use `json` instead) and `holidays`.  


This would leave us with a minimal requirements list of:

```
numpy~=1.16
pandas~=1.0
pydantic~=1.1
```

Which looks about right.

---

Let's keep this issue open until we have come up with a plan how to handle requirements.

**Comment by aalexandrov** [comment]
> same probably with `ujson` (can use `json` instead)

If I remember correctly there was a dramatic difference between using `ujson` and `json` to read time series from a JSONLine format, [see these tests](https://github.com/awslabs/gluon-ts/blob/master/test/dataset/test_loader.py#L47-L56).

**Comment by lostella** [comment]
Closing as this is mainly done (and ever-evolving anyways)
