### ISSUE TITLE
How to save the trained estimator

### ISSUE THREAD

**Issue by Hari7696** [awslabs/gluon-ts#126]
HI
I ddin't find any documentation related to saving the trained model. I want to save my model for further usage.

Thanks

**Comment by geoalgo** [comment]
Given a predictor, (see [this link](https://github.com/awslabs/gluon-ts/blob/master/examples/evaluate_model.py) for instance to see how to get one), you can do:

```
predictor = estimator.train(dataset.train)

# save the trained model in tmp/
from pathlib import Path
predictor.serialize(Path("/tmp/"))

# loads it back
from gluonts.model.predictor import Predictor
predictor_deserialized = Predictor.deserialize(Path("/tmp/"))
```

**Comment by Hari7696** [comment]
Hi geoalgo
I tried to save the model in traditional way
predictor.serialize("/tmp/")
but it didnt work

thank you

**Comment by lostella** [comment]
@Hari7696 how doesn’t it work? Can you paste the error that you obtain? What happens? What OS and Python version are you running?

**Comment by lostella** [comment]
I’m reopening the issue since this is now a documentation problem

**Comment by mbohlkeschneider** [comment]
Hi @Hari7696. 
Can you make sure that the path you are saving to exists? I just tested the code from @geoalgo  and it worked fine on MacOS Sierra.

**Comment by Hari7696** [comment]
Hi @lostella @mbohlkeschneider 

I am getting the folllowing error when I dont use the `Path` from `pathlib`
`predictor.serialize("/tmp/")
`
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/gluonts/model/predictor.py in serialize(self, path)
     91             # serialize Predictor type
---> 92             with (path / 'type.txt').open('w') as fp:
     93                 fp.write(fqname_for(self.__class__))

TypeError: unsupported operand type(s) for /: 'str' and 'str'

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
<ipython-input-509-b19f9136069e> in <module>
----> 1 predictor.serialize("/tmp/")

~/.local/lib/python3.7/site-packages/gluonts/model/predictor.py in serialize(self, path)
    324     def serialize(self, path: Path) -> None:
    325         # call Predictor.serialize() in order to serialize the class name
--> 326         super().serialize(path)
    327 
    328         # serialize every GluonPredictor-specific parameters

~/.local/lib/python3.7/site-packages/gluonts/model/predictor.py in serialize(self, path)
     95             raise IOError(
     96                 f'Cannot serialize {fqname_for(self.__class__)}'
---> 97             ) from e
     98 
     99     @classmethod

OSError: Cannot serialize gluonts.model.predictor.RepresentableBlockPredictor


**But when I use `Path` from `pathlib`** 

`predictor.serialize(Path("/tmp/"))`

I am not having an issue.

O.S : Ubuntu 16.04
conda environment

**Comment by mbohlkeschneider** [comment]
Great! Hope that helped.

**Comment by jaheba** [comment]
@Hari7696 

Can you use ``` for [code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)? That makes it easier to read your posts.
