### ISSUE TITLE
plot the  probabilty forecasts of multiple time series in subplots

### ISSUE THREAD

**Issue by wangyueer97** [awslabs/gluon-ts#1264]
Hi,
   I want to plot the probability forecasts ( observations,median prediction, prediction interval) of  multiple time series (64) in one figure which has 64 subplots.

Here is my code:
`def plot_prob_forecasts(ts_entry, forecast_entry,plot_length,grid_point,nrow,ncol):
    prediction_intervals = (20.0, 90.0) 
    legend = ["observations", "median prediction"] + [f"{k}% prediction interval" for k in prediction_intervals][::-1]
    fig,ax=plt.subplots(nrow,ncol,figsize=(20,10))
    ts_entry[-plot_length:].plot(ax=ax)  # plot the time series
    forecast_entry.plot(prediction_intervals=prediction_intervals, color='g',ax=ax)
    plt.grid(which="both")
    plt.legend(legend, loc="upper left")
    plt.title(f"grid point {grid_point}")
    plt.show()
    
    
for row in range(nrow):
    for col in range(ncol):
        idx=row*ncol+col
        if idx<len(tss):
           plot_prob_forecasts(tss[idx],forecasts[idx],120,idx,8,8)  `

## Error message or code output

```

``plot_prob_forecasts(tss[idx],forecasts[idx],120,idx,8,8)
Traceback (most recent call last):

  File "<ipython-input-32-6e07b9ef1b02>", line 5, in <module>
    plot_prob_forecasts(tss[idx],forecasts[idx],120,idx,8,8)

  File "<ipython-input-31-ee4b6d0d7178>", line 5, in plot_prob_forecasts
    ts_entry[-plot_length:].plot(ax=ax)  # plot the time series

  File "C:\ProgramData\Anaconda3\envs\mxnet_gluonts\lib\site-packages\pandas\plotting\_core.py", line 949, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\mxnet_gluonts\lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 61, in plot
    plot_obj.generate()

  File "C:\ProgramData\Anaconda3\envs\mxnet_gluonts\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 270, in generate
    self._setup_subplots()

  File "C:\ProgramData\Anaconda3\envs\mxnet_gluonts\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 331, in _setup_subplots
    fig = self.ax.get_figure()

AttributeError: 'numpy.ndarray' object has no attribute 'get_figure'`

I'm looking forward for your help.

**Comment by dai-ichiro** [comment]
Sample script for 2 time series

```
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  
    predictor=predictor,  
    num_samples=100
    )

forecasts = list(forecast_it)
tss = list(ts_it)

ts_entry = tss[0]
forecast_entry = forecasts[0]

for i in range(2):
    plt.subplot(2,1,i+1)
    ts_entry[i].plot()
    forecast_entry.copy_dim(i).plot(color='g', prediction_intervals=(50.0, 90.0))
plt.show()
```

or, more simply

```
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  
    predictor=predictor,  
    num_samples=100
    )

for x, y  in zip(ts_it, forecast_it):
    for i in range(2):
        plt.subplot(2,1,i+1)
        x[i].plot()
        y.copy_dim(i).plot(color='g', prediction_intervals=(50.0, 90.0))
plt.show()
```

Hope this helps.

**Comment by wangyueer97** [comment]
@dai-ichiro I gratefully thank you for your prompt help!  But I still have some problems with this, I modified my code according to your suggestion.
`forecast_it, ts_it = make_evaluation_predictions(
    dataset=dataset.test,  # test dataset
    predictor=predictor,  # predictor
    num_samples=100,  # number of sample paths we want for evaluation
)

forecasts = list(forecast_it)
tss = list(ts_it)

for i in range(4):
    plt.subplot(2,2,i+1)
    ts_entry=tss[i]
    forecast_entry=forecasts[i]
    ts_entry[-120:].plot()
    forecast_entry.plot(color='g', prediction_intervals = (50.0, 90.0))
    plt.show`

after running the code, the picture below is obtained:
![ZOF2% 26MKG9@W ARH7)X}K](https://user-images.githubusercontent.com/57401330/104579986-ab5d4900-5697-11eb-875c-45ec10a075fb.png)
It is strange that it comes out five pictures, in which  four  pictures are empty. 
 
Sorry, I didn't make myself clear. Actually, I want to obtain a picture like this:
![4](https://user-images.githubusercontent.com/57401330/104580313-0ee77680-5698-11eb-8df2-3e999566698a.png)

**Comment by dai-ichiro** [comment]
I think this is the correct script.

```
forecast_it, ts_it = make_evaluation_predictions(
dataset=dataset.test, # test dataset
predictor=predictor, # predictor
num_samples=100, # number of sample paths we want for evaluation
)

forecasts = list(forecast_it)
tss = list(ts_it)

ts_entry = tss[0]                      #<-this line is needed
forecast_entry = forecasts[0]  #<-this line is needed

for i in range(4):
    plt.subplot(2,2,i+1)
    ts_entry[i][-120:].plot()
    forecast_entry.forecast_entry.copy_dim(i).plot(color='g', prediction_intervals = (50.0, 90.0))
plt.show
```

Hope this helps.

**Comment by dai-ichiro** [comment]
Is your model is singlevariant?
I misunderstood it was multivariate analysis.
I'm sorry.

if your model is singlevariant, this is the correct sample scripts.

```
import numpy as np
from matplotlib import pyplot as plt

from gluonts.dataset.common import ListDataset
from gluonts.model.deepar import DeepAREstimator
from gluonts.mx.distribution.multivariate_gaussian import MultivariateGaussianOutput
from gluonts.mx.trainer import Trainer
import pandas as pd 

N = 10  # number of time series
T = 100  # number of timesteps
prediction_length = 24
freq = "1H"
custom_dataset = np.random.normal(size=(N, T))
start = pd.Timestamp("01-01-2019", freq=freq)

# train dataset: cut the last window of length "prediction_length", add "target" and "start" fields
train_ds = ListDataset([{'target': x, 'start': start}
                        for x in custom_dataset[:, :-prediction_length]],
                       freq=freq)
# test dataset: use the whole dataset, add "target" and "start" fields
test_ds = ListDataset([{'target': x, 'start': start}
                       for x in custom_dataset],
                      freq=freq)

estimator = DeepAREstimator(
    prediction_length=prediction_length,
    freq=freq,
    trainer=Trainer(epochs=5)
)

predictor = estimator.train(train_ds)

from gluonts.evaluation.backtest import make_evaluation_predictions

for i in range(4):
    forecast_it, ts_it = make_evaluation_predictions(
        dataset=test_ds,  
        predictor=predictor,  
        num_samples=100
        )

    forecasts = list(forecast_it)
    tss = list(ts_it)

    ts_entry = tss[0]
    forecast_entry = forecasts[0]

    plt.subplot(2,2,i+1)
    ts_entry[0].plot()
    forecast_entry.plot(color='g', prediction_intervals=(50.0, 90.0))

plt.show()
```

you will get this figure.
![Figure_1](https://user-images.githubusercontent.com/53703225/104662048-46dcd100-570d-11eb-815a-06ddba8c4ce5.png)

**Comment by wangyueer97** [comment]
@dai-ichiro This worked !! :)   I really appreciate your help. You are sooooo kind! This is the first time that I ask for help on github, and I never thought I can get reply so quickly.
Best wishes to you!
