### ISSUE TITLE
Issue with predict() function

### ISSUE THREAD

**Issue by hannahyess** [awslabs/gluon-ts#1279]
I want to generate forecast values for future. Unlike for evaluation purpose (which i used make_evaluation_prediction), there is no actual future value. So i used predict() function. 
```
forecast_it= predictor.predict(
                        dataset=test_ds,
                        num_samples=100
                        )
forecasts = list(forecast_it)
```
But i get error of 

> ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 119 and the array at index 2 has size 106

Below is the data sizes used. As seen the data size is all 106. But my prediction length trained in the predictor is 13, i suppose in somewhere this 13 is added to 106 hence the size 119? 

How can i fix this?

```
test_ds = ListDataset([
    {
        FieldName.TARGET: target,
        FieldName.START: start,
        #FieldName.FEAT_STATIC_REAL: static_real,
        FieldName.FEAT_STATIC_CAT: [static_cat],
        FieldName.FEAT_DYNAMIC_REAL: [dynamic_cat]
    }
    for (target, start, static_cat, dynamic_cat) in zip(test_target_values,
                                         start_date,
                                        #stat_real_features, 
                                        stat_cat_features,
                                        test_dynamic_cat_features
                              )
], freq="W-SAT")

print('Shapes of test data:')
print(test_target_values.shape)
print(np.array(start_date).shape)
print(np.array(stat_cat_features).shape)
print(test_dynamic_cat_features.shape)
```

> Shapes of test data:
(251, 106)
(251,)
(251,)
(251, 106)

**Comment by lostella** [comment]
@hannahyess it's not clear how you obtained the predictor, so I'm not sure what the model is, but my best guess is the following: dynamic features should extend to the prediction time range as well, so while the target data has length 106, the dynamic features should have length 119

**Comment by hannahyess** [comment]
Hey @lostella wow that works! yes that makes sense that dynamic feature should extend into future. thanks.
