### ISSUE TITLE
Can't import gluonts.distribution module 

### ISSUE THREAD

**Issue by alexhallam** [awslabs/gluon-ts#1320]
## Description

Using master

`from gluonts.distribution import NegativeBinomialOutput`

and 

`from gluonts.distribution.neg_binomial import NegativeBinomial`

> ModuleNotFoundError: No module named 'gluonts.distribution'

both return the following

## To Reproduce

```python
`from gluonts.distribution.neg_binomial import NegativeBinomial`
```

## Error message or code output

```
ModuleNotFoundError: No module named 'gluonts.distribution'
```

## Environment
- Operating system:  `Ubuntu 20.04.1 LTS x86_64`
- Python version: `Python 3.8.5`
- GluonTS version: `0.5.1.dev236+gb4d8144`
- MXNet version: `1.7.0`

**Comment by lostella** [comment]
@alexhallam mxnet-specific modules were moved to `gluonts.mx`, so you should be able to import 

```from gluonts.mx.distribution import NegativeBinomial```

**Comment by alexhallam** [comment]
Perfect! Thanks
