### ISSUE TITLE
No module named 'gluonts.itertools'

### ISSUE THREAD

**Issue by turmeric-blend** [awslabs/gluon-ts#1332]
## Description
When I run: `from gluonts.itertools import Cyclic, PseudoShuffled, Cached`

I get error:

> ModuleNotFoundError: No module named 'gluonts.itertools'

## To Reproduce
`from gluonts.itertools import Cyclic, PseudoShuffled, Cached`

## Error message or code output
> ModuleNotFoundError: No module named 'gluonts.itertools'

## Environment
- Operating system: Ubuntu 18.04
- Python version: 3.7.9
- GluonTS version: 0.6.6
- MXNet version: 1.7.0

**Comment by lostella** [comment]
@turmeric-blend the `gluonts.itertools` module was introduced post-0.6.x, so it’s currently only available on the `master` branch (and will be available on 0.7.x)
