### ISSUE TITLE
TQDM Version breaks training

### ISSUE THREAD

**Issue by DeastinY** [awslabs/gluon-ts#1333]
## Description
With `tqdm 4.56.2 I` get an` AtrributeError: __error__ in trainer/_base.py at line 276:                     `
`with tqdm(batch_iter, total=num_batches_to_use) as it:`
 Installing tqdm==4.23.0 fixes this

**Comment by jaheba** [comment]
Hello @DeastinY,

can you share the whole error message and/or code which helps us to reproduce the issue?

Thanks!

**Comment by DeastinY** [comment]
Hey, sorry for the late reply. I'm currently a little swamped with work and can't easily roll back.
I'll see if I can reproduce it by installing gluon-ts and tqdm in a clean environment.
Cheers

**Comment by DeastinY** [comment]
Couldn't reproduce with fresh installation.
Maybe it was a broken environment on my side?

**Comment by jaheba** [comment]
Thanks for updating the ticket. Let us know once it stops working again :)
