### ISSUE TITLE
Keep pandas 1.0 in version 0.7

### ISSUE THREAD

**Issue by alexcombessie** [awslabs/gluon-ts#1335]
## Description
My application has a hard dependency on pandas 1.0. I am thus a happy user of gluon-ts v0.6 😄 

I have seen on the master branch that pandas has been updated to 1.1. Would it be possible to relax that requirement to keep pandas 1.0 along with pandas 1.1, i.e. use `pandas>=1.0`

Pandas 1.0 is barely one-year-old, IMO it's reasonable to wait a bit before forcing a switch to the 6-month old 1.1 release.

## References
https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements.txt

**Comment by jaheba** [comment]
Hello Alex,

the requirement was changed in #1233. I'm not 100% why, maybe @lostella can shed some light here :)

Generally, gluon-ts should work with `pandas==1.0` though.

**Comment by lostella** [comment]
@jaheba @alexcombessie looking at it again, I suppose that requirement bump was not really necessary.

@jaheba did you mean compatible with `pandas~=1.0`?

**Comment by jaheba** [comment]
> @jaheba did you mean compatible with `pandas~=1.0`?

What I meant is that `gluon-ts` should work if you install `pandas==1.0`.

We should change the dependency to `pandas~=1.0` still :)

**Comment by jaheba** [comment]
@alexcombessie Do you want to do the change?

**Comment by alexcombessie** [comment]
Hi @jaheba,

Thanks, that's kind of you to offer 🙏  Here is a short PR: #1344 

Cheers,

Alex

**Comment by jaheba** [comment]
PR is merged

**Comment by lostella** [comment]
Coming back to this: the restriction was actually required because `DatetimeIndex.isocalendar()` was introduced in `pandas==1.1` cc @Schmedu
