### ISSUE TITLE
Streamline "freq", "time_granularity" naming

### ISSUE THREAD

**Issue by mbohlkeschneider** [awslabs/gluon-ts#134]
Find a naming that is consistent and change it throughout the code for freq/time_granularity.

**Comment by geoalgo** [comment]
Given that Pandas use 'freq'  ([link](http://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html)), this is probably the best option.

**Comment by mbohlkeschneider** [comment]
I agree with that. We should make this distinction clear somewhere in the documentation, though, that this is not confused with seasonality frequency.

**Comment by jaheba** [comment]
I'm currently looking into the shell (essentially integrating with SageMaker) and noticed this too.

In [SageMaker DeepAR](https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_hyperparameters.html) we use `time_freq` and I think there is an argument to be made that we should aim for consistency.

**Comment by mbohlkeschneider** [comment]
Consistency is a good argument. But consistency with SageMaker might not necessarily be the right thing in a library. Pandas uses `freq` for generating time series Series objects and I think it would be good to stick to that.

**Comment by jaheba** [comment]
I'm fine with either, but at least we should be consistent within GluonTS.

Do we have a set of required hyper-parameters? Besides `freq` `prediction_length` comes to mind.

**Comment by geoalgo** [comment]
`freq` and `prediction_length` are the only two required hyper-parameters. Pandas is much more frequent than Sagemaker, so I also `freq` will be nicer.

**Comment by lostella** [comment]
addressed in #172 and #173
