### ISSUE TITLE
Prediction runs endless with deserialized DeepAREstimator

### ISSUE THREAD

**Issue by DeastinY** [awslabs/gluon-ts#1354]
1. Train  `DeepAREstimator` and serialize it 
2. Deserialize the predictor
3. Try to predict and it  runs forever `(nextforecast_it))`.

While it may not be endless I didn't get any result in two hours on a Tesla V100 before I stopped it.

Some code snippets:

```
estimator = DeepAREstimator(
        freq="30min", 
        prediction_length=horizon, 
        trainer=trainer,
        use_feat_dynamic_real=True
    )
predictor = estimator.train(ds_train)
predictor.serialize(Path("model"))
predictor = Predictor.deserialize(Path("model"))
forecast_it, ts_it = make_evaluation_predictions(
    dataset=ds_test,  
    predictor=predictor,  
    num_samples=100,  
)

ts_entry = next(forecast_it)
forecast_entry = next(ts_it)  # <<<< HANGS HERE
```

**Comment by mbohlkeschneider** [comment]
Hi @DeastinY. Thank you for raising that issue. Can you provide a snippet with dummy data so we can reproduce that bug? From that snippet, it is not clear whether it is the serialization or the data.

**Comment by DeastinY** [comment]
Hi @mbohlkeschneider !
If I leave out the serialization it works, so I guess that covers that :stuck_out_tongue: 
If needed I can still create an example with dummy data

**Comment by mbohlkeschneider** [comment]
Yes, a full, runnable snipped would be great.

**Comment by DeastinY** [comment]
**Had some NaN in the ds_test data. That had DeepAR run in circles. **
Realized while preparing the sample.
Thanks for the hel!
