### ISSUE TITLE
Tracking: MXNet 1.8 compatibility

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#1374]
Our tests currently break because of the new mxnet release.

**Comment by lostella** [comment]
Running tests locally (macOS, py37, mxnet==1.8.0.post0) I only get the following failures:

```
test/activation/test_activations.py
test/distribution/test_issue_287.py
```

In total, 2 test cases failed. Was anything else observed on different platforms? If not, this may be not too bad.

**Comment by lostella** [comment]
Windows wheels for mxnet 1.8 are not available yet, see discussion here https://github.com/apache/incubator-mxnet/issues/18800#issuecomment-813465016
