### ISSUE TITLE
generate_rolling_dataset with real dynamic features

### ISSUE THREAD

**Issue by GabrielDeza** [awslabs/gluon-ts#1390]
I saw that there is a way to generate a rolling dataset in the master version. This is useful for me as I had to implement my own  a couple months ago and it was incredibly messy and I could not get the evaluator to work with my implementation. 

Using the implementation in the master repo, without any dynamic features, the evaluator works with generate_rolling_datasets. When you add in dynamic features, although the resulting target is getting sliced shorter step_size every time, the associated dynamic features are not which gives you this error:
```
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
I was able to overcome this by cutting the dynamic features myself when I want to plot things, as shown below:
```
for i,train_dict in enumerate(dataset_rolled):
    feat_dynamic= train_dict['feat_dynamic_real']
    feat_dynamic_changed = feat_dynamic[:,:feat_dynamic.shape[1]-i * step_size]
    train_data = ListDataset([{"start": train_dict['start'], "target": train_dict['target'], 
                               "feat_dynamic_real" : feat_dynamic_changed}],freq="1B")
    
   for test_entry, forecast in zip(train_data, predictor.predict(train_data)):
        to_pandas(test_entry).plot(linewidth=1, color='b', zorder=0, figsize=(13, 7))
        forecast.plot(color='g', prediction_intervals=prediction_intervals, show_mean=True, zorder=10)
```
However, I now want to get some metrics for my rolled dataset using this function call:
```
forecast_it, ts_it = make_evaluation_predictions(
        dataset_rolled, predictor=predictor, num_samples=100)
training_agg_metrics, _ = Evaluator(num_workers = 0)(ts_it, forecast_it)
```
This of course gives me the same error as above as (likely) the dynamic features is not being cut down. I tried to look into the _base.py code of the evaluator class but I am bit confused. I know that this is not in the stable version yet, but if someone can point to where in the evaluator code I can change, that would great.

Thank you for the great library and the rolling dataset implementation,
Cheers

**Comment by arangatang** [comment]
Hi @GabrielDeza, thank you for the issue. 

I have been looking into the issue and you are right, none of the `feat_dynamic_real` gets truncated when calling `generate_rolling_dataset` the same goes for the other feature vectors. 

The lines which cause this are [these](https://github.com/awslabs/gluon-ts/blob/1ff7db6d5dd9ddeb97a1babac054f6ee59488cd5/src/gluonts/dataset/rolling_dataset.py#L215-L217). 

I solved this on my local branch by truncating the lengths of the `feat_dynamic_real` to match the length of the target.

**Comment by arangatang** [comment]
A fix for this was merged in #1392, @GabrielDeza is your problem solved and can I close the issue?

**Comment by GabrielDeza** [comment]
Yeah this fixed my problem, I'll close this issue. Thank you so much @arangatang for your help, this library is amazing :D

**Comment by GabrielDeza** [comment]
Are rolling datasets compatible with multivariate datasets (ie: datasets for models like DeepVAR or GPVAR)? I am trying to make it work but I am getting a dimensionality error and it would be great to know if this is a mistake in my implementation or not.
