### ISSUE TITLE
it seems target length and feat_dynamic_real length can be the same at prediction time

### ISSUE THREAD

**Issue by houying-aws** [awslabs/gluon-ts#1415]
## Description
use deepar algorithm in Gluonts, trained a model. When prepare the inference data, it seems target length and feat_dynamic_real length can be the same when call predictor.predict() method. This is a different behavior from sagemaker built-in deepar algo, where dynamic_feat_length = target_length + prediction_length. 

## To Reproduce
prepare target and feat_dynamic_real as the same length. 

```python
put code here
```

## Error message or code output
no error message, this is not expected. 

## Environment
- Operating system: sagemaker studio 
- Python version: 3.7.10
- GluonTS version: '0.6.7'
- MXNet version: '1.8.0'

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@houying-aws I cannot reproduce this: the following snippet fails as expected.

Note that you need to explicitly enable additional features with `use_feat_dynamic_real=True`

```python
from gluonts.dataset.common import ListDataset
from gluonts.model.deepar import DeepAREstimator
from gluonts.mx.trainer import Trainer


training_dataset = ListDataset(
    data_iter=[
        {"start": "2020-01-01", "target": [1.0] * 100, "feat_dynamic_real": [[1.0] * 100]}
        for _ in range(10)
    ],
    freq="1H",
)

estimator = DeepAREstimator(
    freq="1H",
    prediction_length=24,
    batch_size=32,
    use_feat_dynamic_real=True,
    trainer=Trainer(epochs=3, num_batches_per_epoch=2),
)

predictor = estimator.train(training_dataset)

test_dataset = ListDataset(
    data_iter=[
        {"start": "2020-06-01", "target": [1.0] * 100, "feat_dynamic_real": [[1.0] * 100]}
        for _ in range(10)
    ],
    freq="1H",
)

forecasts = predictor.predict(test_dataset)

for f in forecasts:
    print(f)
```
