### ISSUE TITLE
Implement NBEATSx

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#1449]
It would greatly add to gluonts, if you'd add [NBEATSx: Neural basis expansion analysis with exogenous variables](https://github.com/cchallu/nbeatsx). As the name suggests, NBEATSx extends the NBEATS model to incorporate exogenous factors.

**Comment by baniasbaabe** [comment]
Is NBEATSx included now? Can't find it but the issue is closed :/
