### ISSUE TITLE
GluonTS transformation issue

### ISSUE THREAD

**Issue by miteshyadav** [awslabs/gluon-ts#1475]
## Description
In order to handle missing values in the dataset, I am using GluonTS's ObservedValueIndicator transformation function to flag missing and observed values. After applying the transformation on the dataset, the training stagnates at 0% and wouldn't progress. I followed the exact template given in the Extended Forecasting Tutorial in GluonTS and the error still persists. I wonder if there is any workaround to instead just create my own flag for missing values using feat_dynamic_cat field. Let me know your thoughts. Thanks

**Comment by lostella** [comment]
@miteshyadav can you include a runnable example of the code that you're running?

**Comment by miteshyadav** [comment]
Sure @lostella 

Example is exactly the same as here: https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/tutorials/forecasting/extended_tutorial.html

I use the train_tf object generated after transformation to feed it into the estimator:
predictor = estimator.train(training_data=train_tf)

That is when the training halts at 0% forever and doesn't budge.

**Comment by lostella** [comment]
The `train_tf` object defined in cell 34

```
train_tf = transformation(iter(train_ds), is_train=True)
```

is a generator (see output of cell 35). This means that once it gets iterated once, it will be exhausted. So it is not an object that should be used for training purposes: there, one usually wants to iterate over the dataset multiple times to fit the model well.

To apply a transformation persistently you should use the `TransformedDataset` class, see here: https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/api/gluonts/gluonts.transform.dataset.html#module-gluonts.transform.dataset
