### ISSUE TITLE
Support for category fields with multiple values

### ISSUE THREAD

**Issue by miteshyadav** [awslabs/gluon-ts#1476]
## Description

Is there a functionality to incorporate many- to-many (multi-label) categorical feature in GLuonTS? It would be helpful to have a feature like that. Currently it just supports one to one mapping. FOr example, a product may belong to multiple categories and not just one

**Comment by lostella** [comment]
@miteshyadav for the models that support the `feat_static_cat` feature (eg DeepAR) that's already the case: you just need to put there an array of length > 1.

I'm moving this into the discussions, if you don't mind, so that others can find this answer.
