### ISSUE TITLE
How to train a model on data containing missing values?

### ISSUE THREAD

**Issue by miteshyadav** [awslabs/gluon-ts#1478]
## Description
I'm trying to run a DEEPAR model with multiple time series that contain a lot of missing/empty/NaN values.  Im refraining to impute missing values with 0, because that would be fallacious and the model wouldn't learn properly. Does GluonTS handle empty values by itself? Are there any other ideas or workaround this problem?

**Comment by lostella** [comment]
Could you include a minimal example of data that causes the issue?

In general, please include code examples that can be copy-pasted to reproduce the issue, otherwise it is hard for us to identify the problem.

**Comment by lostella** [comment]
Generally speaking though: If you include `None` in your “target” fields, DeepAR will handle them properly and treat them as missing.
