### ISSUE TITLE
Avg Epoch Loss in DeepAR

### ISSUE THREAD

**Issue by anandmohan4143** [awslabs/gluon-ts#1509]
Hi Members, I am new to time series forcasting and installed gluonts=0.5.0. While using DeepAR algorithm, I was getting avg_epoch_loss during model training with student t distribution, I am not sure what is that loss and how it is being calculated. I went through the code and saw using mx.metric.Loss in _base.py and later weighted loss in _network.py in deepar folder. Also saw the issues answered in github saying they are using negative likelihood of the model distribution. Can anyone kindly guide me on how the avg_epoch_loss is being calculated in 0.5.0 version. Also can it be used in model validation?

**Comment by nalexus** [comment]
Hello @anandmohan4143 .
Did you get an answer on how the avg_epoch_loss is being calculated?
