### ISSUE TITLE
Introduce Pylint

### ISSUE THREAD

**Issue by borchero** [awslabs/gluon-ts#1547]
## Description

[Pylint](https://www.pylint.org/) allows to perform static code analysis and complements Black and MyPy to ensure a consistent coding style. On top of that, it allows identifying plenty of bugs, dead code, ensures documentation, ...

Using PyLint would likely expose a couple of hard-to-find and subtle bugs and ensure a better coding style in general.

**Comment by jaheba** [comment]
I had a look at `pylint src/gluonts/core`:

```$ pylint --py3k --disable=all --enable=W --enable=E --disable W1618 src/gluonts/core```

outputs

```
************* Module gluonts.core.exception
src/gluonts/core/exception.py:48:35: W0622: Redefining built-in 'type' (redefined-builtin)
src/gluonts/core/exception.py:48:4: W0231: __init__ method from base class 'GluonTSException' is not called (super-init-not-called)
src/gluonts/core/exception.py:83:4: W0107: Unnecessary pass statement (unnecessary-pass)
src/gluonts/core/exception.py:91:4: W0107: Unnecessary pass statement (unnecessary-pass)
src/gluonts/core/exception.py:99:4: W0107: Unnecessary pass statement (unnecessary-pass)
src/gluonts/core/exception.py:107:4: W0107: Unnecessary pass statement (unnecessary-pass)
src/gluonts/core/exception.py:197:20: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
src/gluonts/core/exception.py:199:20: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
************* Module gluonts.core.settings
src/gluonts/core/settings.py:110:0: W0613: Unused argument 'args' (unused-argument)
src/gluonts/core/settings.py:148:28: W0622: Redefining built-in 'type' (redefined-builtin)
src/gluonts/core/settings.py:193:12: W0104: Statement seems to have no effect (pointless-statement)
src/gluonts/core/settings.py:363:11: W0212: Access to a protected member _let of a client class (protected-access)
src/gluonts/core/settings.py:368:11: W0212: Access to a protected member _inject of a client class (protected-access)
************* Module gluonts.core.ty
src/gluonts/core/ty.py:16:0: W0611: Unused import itertools (unused-import)
src/gluonts/core/ty.py:17:0: W0611: Unused Optional imported from typing (unused-import)
************* Module gluonts.core.component
src/gluonts/core/component.py:186:18: W0613: Unused argument 'v' (unused-argument)
************* Module gluonts.core.serde._base
src/gluonts/core/serde/_base.py:61:15: E1101: Instance of 'Stateless' has no '__init_args__' member (no-member)
************* Module gluonts.core.serde._repr
src/gluonts/core/serde/_repr.py:13:0: W0611: Unused import ast (unused-import)
src/gluonts/core/serde/_repr.py:14:0: W0611: Unused import importlib (unused-import)
src/gluonts/core/serde/_repr.py:18:0: W0611: Unused import re (unused-import)
src/gluonts/core/serde/_repr.py:23:0: W0611: Unused numpy imported as np (unused-import)
************* Module gluonts.core.serde.__init__
src/gluonts/core/serde/__init__.py:19:1: W0511: TODO: remove (fixme)
************* Module gluonts.core.serde._parse
src/gluonts/core/serde/_parse.py:55:11: W1636: map built-in referenced when not iterating (map-builtin-not-iterating)
src/gluonts/core/serde/_parse.py:56:13: W1636: map built-in referenced when not iterating (map-builtin-not-iterating)
```


Besides the import-warnings, most of these messages appear to be false positives.

Do you have an example of where `pylint` would improve our existing code?

**Comment by borchero** [comment]
This might be a personal preference but even messages such as `unused-import`, `unnecessary-pass` or `raise-missing-from` contribute to clearer code. Also, e.g. not being allowed to access protected members seems like a sane thing to do.

I think, there are a couple of cases where it actually catches bugs though:

- `super-init-not-called` is often an issue. Even if it doesn't show it can easily break when changes are introduces.
- GluonTS has empty lists in initializers all over the place, which can quickly lead to errors when lists are modified (`dangerous-default-value`)
- `unexpected-keyword-arg` catches invalid usages of classes/functions. For example, `DeepRenewalProcessEstimator` fails when calling `create_validation_data_loader`.

**Comment by jaheba** [comment]
> * GluonTS has empty lists in initializers all over the place, which can quickly lead to errors when lists are modified (`dangerous-default-value`)

Yes, but that's actually fine since these should be all in `validated`-decorated `__init__`-s. So most of them should be false positives. That's the issue with `pylint`, that it checks what normally makes sense, but in this case it's actually fine.

> * `unexpected-keyword-arg` catches invalid usages of classes/functions. For example, `DeepRenewalProcessEstimator` fails when calling `create_validation_data_loader`.

This one actually looks useful :)

**Comment by borchero** [comment]
If we have plenty of false positives e.g. due to the usage of `@validated`, we can just disable these checks in pylint. I guess, there are is still plenty of helpful checks that allow for catching bugs, esp. when larger new features are introduced.

**Comment by jaheba** [comment]
I think we could, but that would require quite some work to get useful information out of it.

In the meantime we could add `flake8`, which seems to do less deep linting.
