### ISSUE TITLE
Converting data to gluon-ts format

### ISSUE THREAD

**Issue by sege01** [awslabs/gluon-ts#1584]
### Discussed in https://github.com/awslabs/gluon-ts/discussions/1582

<div type='discussions-op-text'>

<sup>Originally posted by **sege01** June 22, 2021</sup>
Hello,
Thank you for the excellent library.
I am new to gluon-ts and trying to learn. I have some queries.
I am trying to use stallion_data(https://www.kaggle.com/utathya/future-volume-prediction) for volume forecasting.

How can I convert this data to gluon-ts Listdatset format to further pass it to the model?
Data looks like this:- 
![image](https://user-images.githubusercontent.com/85530006/122917064-e60d9080-d35d-11eb-996a-afda01fc7c30.png)

In the dataframe, each entry consists of 'Agency' and 'SKU', whose combination makes an entry unique. 
So, according to that, the one-time series will be consisting of the unique combination of 'agency' and 'SKU' with data for a certain period(start date to end date).

Thank you in advance. </div>

**Comment by lostella** [comment]
Closing since this is not an issue, replying in the discussion.
