### ISSUE TITLE
Gluonts Deepar giving abrupt negetive forecasting values  while forecasting on the test_ds!! 

### ISSUE THREAD

**Issue by AyswaryaS95** [awslabs/gluon-ts#1600]
<b>I'm using deepar estimator on walmart weekly sales forecasting !!The below estimator was predicting fine !!Later on I performed some hyperparameter tuning by changing values of the following parameters like context length,num_layers etc etc!! my forecasts on the validation sets are showing negetive values. and values are in negative exponentiations. Please check out the below img which is my current output !! and i'm unable to retrieve any relevent predictions like before even after changing the parameters back and training them!!!!</b>

some hyperparamters for tuning whch i tried using in a for loop!!
context_length = [29,36,50]
num_layers = [2,3]
num_cells = [64,80,103]
learning_rate = [0.01,0.001]
patience = [2,3]
epochs = [10,30,40]
num_batches_per_epoch = [40,50]

<b>forecasts now : gluonts.model.forecast.SampleForecast(freq="W", info=None, item_id=None, samples=numpy.array([1.0312467893514032e-11, 4.9218840808551434e-11, -1.882126052232813e-11, -2.1451685913720375e-12, -1.3539548822383285e-11, 7.620450277745494e-12, -9.395779987375619e-11, 1.0052871729504531e-11, 4.65650400183204e-11, -4.358102420609633e-12..........</b><br>
<b>Actual values :array([[24924.5 ], [46039.49],[41595.55], [19403.54], [21827.9 ], [21043.39],.............</b>

estimator = DeepAREstimator(freq='W',
                        context_length=50,## how much past we need to go
                        prediction_length=29,## future steps
                        use_feat_static_cat=True, ## for identifying each category of time series
                        num_layers=2,
                        cardinality = [1],
                        scaling=True,
                        cell_type='lstm',
                        dropout_rate=0.1,
                        num_cells=80,
                        trainer=Trainer(learning_rate=0.01,
                                        learning_rate_decay_factor = 0.0005,
                                        patience=2,
                                        epochs=40,
                                        num_batches_per_epoch=40))

predictor =  estimator.train(training_data = train_ds)
forecast_it,ts_it = make_evaluation_predictions(dataset=test_ds,predictor=predictor,num_samples=100)

tss =  list(iter(ts_it))
forecasts = list(iter(forecast_it))
<br><center>forecasts before</center><br>
![image](https://user-images.githubusercontent.com/46446383/124308172-7f227f80-db86-11eb-8d30-161c19aae347.png)
<br><center>forecasts now</center><br>
![image](https://user-images.githubusercontent.com/46446383/124304228-079e2180-db81-11eb-9188-253376c637bf.png)

Kindly help on this one!! I'm unable to figure out the reason or solve them!And Also suggests methods to perform parameter tuning effectively on gluonts deepar without sagemaker and using for loops !!

#gluonts #negetive-forecasts #DeepAREstimator#predictor-issue
@lostella

**Comment by lostella** [comment]
@AyswaryaS95 picking this up a little late: there is an example of hyperparameter tuning using Optuna in the documentation for the `dev` branch: https://ts.gluon.ai/dev/tutorials/advanced_topics/hp_tuning_with_optuna.html

Note that this is a rather minimal example, as stressed in the tutorial, and likely requires increasing training time and tuning trials to provide meaningful results in practice.

**Comment by mygitpv** [comment]
@AyswaryaS95 I am running into the same issue. I tried updating the parameters but I am still getting negative forecasts although the training data is positive.Did you have any luck on identifying the rot cause?

This is my estimator,
deepar_estimator = DeepAREstimator(freq="1D", 
                                   context_length=90,
                                   prediction_length=90,
                                   num_layers=2,
                                   scaling=True,
                                   cell_type='lstm',
                                    dropout_rate=0.1,
                                    num_cells=80,
                                    trainer=Trainer(learning_rate=0.01,
                                    epochs=40))
