### ISSUE TITLE
Broken incompatible docs

### ISSUE THREAD

**Issue by erezinman** [awslabs/gluon-ts#1619]
Take, for example the following API docs:

https://ts.gluon.ai/api/gluonts/gluonts.trainer.html

Yet no such module exists in the latest release. Note that _**ALL**_ the tutorials rely on `gluonts.trainer.Trainer`, and hence do not work out of the box.

**Comment by lostella** [comment]
@erezinman thanks for pointing this out, there must have been an issue in the deployment of the documentation for the latest release, we'll fix that.

In the time being, you can use the documentation for the master branch, which is currently in line with `v0.8.0` https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/api/gluonts/gluonts.mx.trainer.html

**Comment by lostella** [comment]
The website was updated and the API docs above should disappear shortly

> Note that ALL the tutorials rely on gluonts.trainer.Trainer, and hence do not work out of the box.

I believe the tutorials in the documentation for the stable release now rely on the `gluonts.mx.trainer.Trainer` @erezinman  could you point me to a place where `gluonts.trainer.Trainer` is used?

Tutorial notebooks that are on the website are executed against the corresponding gluonts release as part of the documentation build, so they should work out of the box.

**Comment by erezinman** [comment]
Yes the "hidden" master version of the docs is good, thanks.

**Comment by lostella** [comment]
To clarify: now also the official documentation should be OK (https://ts.gluon.ai) the only thing that needs to be sorted out is the page linked in the OP, which is still accessible but should not be there. Keeping this issue open.

**Comment by lostella** [comment]
The page linked in the OP is not accessible anymore, resolving this.
