### ISSUE TITLE
Optimization Features for MXNet training

### ISSUE THREAD

**Issue by cyrusmvahid** [awslabs/gluon-ts#163]
The training is not optimized and it is nice to be able to pass parameters for training optimization rather than inheriting new classes and adding optimization features.
Most wanted list:

- num_workers for data loader. Increasing num_workers to `mp.cou_count()-3` increases performance by using more cpus for data loading.
- option for nvidia amp and casting network to float 16. I know it has a more dramatic effect on CNN and computer vision cases, but might still be useful.
- ability to add parameters for hybridization. `hybridize(static_aloc=True, static_shape=True)`. These options improve training performance.

**Comment by AaronSpieler** [comment]
- we have multiprocessing support for the data-loader now
- we do have a `hybridise` all MXNet based models
