### ISSUE TITLE
DeepVAR and DeepGPVAR: ValidationError: 1 validation error for DeepVAREstimatorModel target_dim   field required (type=value_error.missing)

### ISSUE THREAD

**Issue by Mirzoe** [awslabs/gluon-ts#1637]
### Discussed in https://github.com/awslabs/gluon-ts/discussions/1634

<div type='discussions-op-text'>

<sup>Originally posted by **Mirzoe** July 20, 2021</sup>
Hi, 

i have i problem while building the DeepVAR and the DeepGPVAR Model.

i produced some sample data to reproduce the error

      import pandas as pd
      import numpy as np
      import matplotlib.pyplot as plt
      from random import seed
      from random import shuffle
      from random import randint
      from gluonts.model.deepvar import DeepVAREstimator
      from gluonts.mx.trainer import Trainer
      from gluonts.dataset.common import ListDataset
      from gluonts.evaluation import make_evaluation_predictions
      from gluonts.evaluation import Evaluator
      from randomtimestamp import randomtimestamp

     #build sample dataset
     sample_dict = {}
     for key in np.arange(20, 50, 1):
        target_values = [round (i) for i in np.sort(np.linspace(70, 96, 20))][::-1]
        value_df = pd.DataFrame({'target': target_values, 'feature1': [round(i) for i in 
       (np.linspace(100, (key * 1000), len(target_values)))],
        'feature2': [randint(90, 130)]*len(target_values), 'feature3': [randint(0, 1)] 
        *len(target_values), 'feature4': [randint(0, 1)]*len(target_values)})
        
         sample_dict[key] = value_df

     #build test and train dataset
     prediction_length = 6
     freq = "1M"
     
     train_ds = ListDataset([{'target': sample_dict[df]['target'][:-prediction_length], 'start': 
                                            randomtimestamp(start_year=1998, end_year=2018),
                                            'feat_dynamic_cat': [sample_dict[df]['feature3'][:-prediction_length],
                                                                             sample_dict[df]['feature4'][:-prediction_length]],
                                            'feat_dynamic_real':[sample_dict[df]['feature1'][:-prediction_length],
                                                                              sample_dict[df]['feature2'][:-prediction_length]]} for df in sample_dict.keys()],
                                            freq=freq)
        
     test_ds = ListDataset([{'target': sample_dict[df]['target'], 'start': randomtimestamp(start_year=1998, end_year=2018),
                                          'feat_dynamic_cat': [sample_dict[df]['feature3'],
                                                                            sample_dict[df]['feature4']],
                                          'feat_dynamic_real':[sample_dict[df]['feature1'],
                                                                            sample_dict[df]['feature2']]} for df in sample_dict.keys()],
                                          freq=freq) 

     # built model
     model = DeepVAREstimator(freq = "1M", prediction_length = prediction_length,context_length=prediction_length,  trainer=                     
     Trainer(epochs = 10))

By executing the code i am getting the below error:

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-111-926c1d10971f> in <module>
      1 # built model
----> 2 model = DeepVAREstimator(freq = "1M", prediction_length = prediction_length,context_length=prediction_length,  trainer= Trainer(epochs = 10))
      3 

~\Anaconda3\envs\glutonts\lib\site-packages\gluonts\core\component.py in init_wrapper(*args, **kwargs)
    324                 if name != "self"
    325             }
--> 326             model = PydanticModel(**{**nmargs, **kwargs})
    327 
    328             # merge nmargs, kwargs, and the model fields into a single dict

~\Anaconda3\envs\glutonts\lib\site-packages\pydantic\main.cp36-win_amd64.pyd in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for DeepVAREstimatorModel
target_dim
  field required (type=value_error.missing)

---------------------------------------------------------------------------

I already build the DeepAR model without any problems and and came across the the `target_dim` param. I inserted `target_dim = 1`   which leads to the following error: 

##GluonTSDataError: Input for field "target" does not have the requireddimension (field: target, ndim observed: 1, expected ndim: 2)

For my interpretation the `target_dim `is 1 because my target values are one dimensional. Im wrong with this assumption ? 
Or im doing something else wrong ? 

Can someone please help.

Thank you
</div>

**Comment by yitao-yu** [comment]
GPVAR and DeepVAR are multi-dimensional models. If your target is one-dimensional, try other models(DeepAR).
