### ISSUE TITLE
_tsf_reader.convert_base doesn't handle "10 minutes" frequency correctly

### ISSUE THREAD

**Issue by marcotet** [awslabs/gluon-ts#1649]
## Description
For Monash datasets with the "10 minutes" frequency, the frequency converter will convert it to a frequency 10 MonthEnd (10M), instead of the expect 10 Minutes (10T) frequency.

There is already code to properly handle the "minutely" frequency, but it checks for that string explicitly, so it doesn't catch the "10 minutes" case.

## To Reproduce
One dataset which has this frequency is the 10 minutes observation Solar dataset: https://zenodo.org/record/4656144
filename: `"solar_10_minutes_dataset.zip"`
record: `"4656132"`

**Comment by lostella** [comment]
If I get this right, changing [this](https://github.com/awslabs/gluon-ts/blob/eb89e4ee2dd7308842381b6c425197bb3ae6eed6/src/gluonts/dataset/repository/_tsf_reader.py#L51) for something like

```python
if text.lower() in ["minutely", "minutes"]:
```

should do the trick, but then maybe we want to review the datasets specs here to make sure this mechanism is robust enough.
