### ISSUE TITLE
Can't run the example in the readme.md

### ISSUE THREAD

**Issue by rambam613** [awslabs/gluon-ts#1653]
## Description
Simple code in co-lab is breaking on internal typing issue.

## To Reproduce
Open new colab notebook

```python
!pip install --upgrade mxnet~=1.7 gluonts
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/nyc_load.csv', index_col=[0])
df.index = pd.to_datetime(df.index)
df = df.resample('D').mean().dropna(0)

y_train = df['load']['1/1/2014':'1/1/2017']
y_test = df['load']['5/1/2017':]

from gluonts.model.deepar import DeepAREstimator
from gluonts.mx.trainer import Trainer
from gluonts.dataset.common import ListDataset

estimator = DeepAREstimator(freq="D",
                            prediction_length=365,
                            trainer=Trainer(epochs=10,
                                            #ctx="gpu"
                                            ))

data = ListDataset([{"start": y_train.index[0], "target": y_train}], freq='D')

predictor = estimator.train(data)


## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```

/usr/local/lib/python3.7/dist-packages/gluonts/json.py:46: UserWarning: Using `json`-module for json-handling. Consider installing one of `orjson`, `ujson` to speed up serialization and deserialization.
  "Using `json`-module for json-handling. "
  0%|          | 0/50 [00:00<?, ?it/s]
learning rate from ``lr_scheduler`` has been overwritten by ``learning_rate`` in optimizer.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-5f32e21dab2b> in <module>()
     12 data = ListDataset([{"start": y_train.index[0], "target": y_train}], freq='D')
     13 
---> 14 predictor = estimator.train(data)

14 frames
/usr/local/lib/python3.7/dist-packages/mxnet/gluon/utils.py in _check_all_np_ndarrays(out)
    477         raise TypeError("Block's output ndarrays/symbols must be of type `mxnet.numpy.ndarray`"
    478                         " or `mxnet.symbol.numpy._Symbol`, while got output type {}"
--> 479                         .format(str(type(out))))
    480     elif isinstance(out, (list, tuple)):
    481         for i in out:

TypeError: Block's output ndarrays/symbols must be of type `mxnet.numpy.ndarray` or `mxnet.symbol.numpy._Symbol`, while got output type <class 'mxnet.symbol.symbol.Symbol'>
```

```

## Environment
- Operating system: linux (colab)
- Python version: 3.8
- GluonTS version: 0.0.8
- MXNet version:  mxnet~=1.7

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@rambam613 thanks for spotting this! I cannot reproduce the issue, could you try to adapt the snippet so that it can be copy-pasted to reproduce the issue?
