### ISSUE TITLE
Exception while Training GluonTS Deepar model with Time Series of Variable Length

### ISSUE THREAD

**Issue by sayedathar11** [awslabs/gluon-ts#1724]
Hello Team GluonTS,
I am working on time series forecasting for multiple timeseries , what we have here is the time series can be of variable length , for example for a time series with id = 1 , it could start at "2018 - 01 - 01" and end at "2019-12-01"(YY-MM-DD format)  , Frequency of time series is monthly, but for other  time series they need not be within this same timestamp , they could have different start and end time .

I prepared GluonTS List Dataset for above Time series , and feed it to DeepAR Model , it ran for 5-6 Epochs but after that it threw an exception . I am attaching the screenshot of the Exception that I am facing can you please help me with it . This is new type of exception I am facing with GluonTS Deepar model.
![gluonts_exception](https://user-images.githubusercontent.com/17905011/136518851-17e228f5-16a1-477c-8a0a-367a71f3913a.PNG)
.

**Comment by mbohlkeschneider** [comment]
hi @sayedathar11, 

thank you for your question. This can happen if you have a lot of very short time series, relative to `context_length` and `prediction_length`. You can try increasing [this value](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/transform/_base.py#L170), but this will only work to some extent. If you have many very short sequences you could consider to filter them from the data before training. 

Hope that helps!
