### ISSUE TITLE
remove pandas frequency workaround

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#177]
As of pandas 0.24.2, some workarounds are needed because of a bug, see #79. These are apparently solved in pandas `master`, and should be included in the upcoming 0.25.0 release.

To do, after pandas 0.25.0 has been released:
* bump requirement to `>=0.25.0`
* remove workarounds such as the one added in #79

**Comment by jaheba** [comment]
Can't we just downgrade the version for now?

**Comment by lostella** [comment]
@jaheba we can just leave the workaround in place for now, it's not a big deal I think. This is more of a note, rather than an issue

**Comment by jaheba** [comment]
@lostella can we close this issue?
