### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by geoalgo** [awslabs/gluon-ts#178]
## Description
Evaluations stored in https://github.com/awslabs/gluon-ts/tree/master/evaluations are generated manually. This causes several issue: 1. manual mistakes can happen 2. it can take a long time before we detect an issue impacting accuracy. Such evaluations could be done at a regular basis to make it easier to check when accuracy regression happens.

**Comment by jaheba** [comment]
Closing in favour of #379
