### ISSUE TITLE
Bug in NPTS.log_weighted_distance_kernel - np.ndarray instead of np.array

### ISSUE THREAD

**Issue by VictorJouault** [awslabs/gluon-ts#1832]
## Description

The `NPTS.log_weighted_distance_kernel` function uses `np.ndarray` (https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy-ndarray) instead of `np.array` (https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) to construct an array, producing an error every time when trying to use the function.

## To Reproduce

from gluonts.model.npts._model import NPTS
f = NPTS.log_weighted_distance_kernel([1.0, 2.0])

## Error message or code output

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_47725/4255820772.py in <module>
      2 # from gluonts.model.npts import NPTSEstimator
      3 
----> 4 f = NPTS.log_weighted_distance_kernel([1.0, 2.0])

~/.../python3.7/site-packages/gluonts/model/npts/_model.py in log_weighted_distance_kernel(kernel_weights)
    187         kernel_weights: List[float],
    188     ) -> Callable[[np.ndarray, np.ndarray], float]:
--> 189         kernel_weights_nd = np.ndarray(kernel_weights, dtype=np.float32)
    190         return lambda x, y: cast(
    191             float, -np.sum(kernel_weights_nd * np.abs(x - y))

TypeError: 'float' object cannot be interpreted as an integer

## Environment
- Operating system: MacOS and Linux
- Python version: 3.7.10
- GluonTS version: '0.8.1'
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
Fixed in #1848
