### ISSUE TITLE
Trouble with installing GluonTS in combination with GPU enabled Mxnet

### ISSUE THREAD

**Issue by NilsLusch** [awslabs/gluon-ts#1837]
## Description
After I installed Mxnet cu-102 my import for GluonTS stopped working. 
## To Reproduce

```python
!pip install mxnet-cu102
!pip install gluonts

import mxnet as mx
from mxnet import gluon
```

## Error message or code output
 OSError: libcudnn.so.8: cannot open shared object file: No such file or directory

**Comment by jaheba** [comment]
Hello,

this looks unrelated to GluonTS, but appears to be an issue with your mxnet installation.

I'm afraid, there is nothing we can do about it.
