### ISSUE TITLE
Where are the transformer modules?

### ISSUE THREAD

**Issue by Freemanzxp** [awslabs/gluon-ts#186]
## Description
- I have seen transformer's experiment in paper but have not found it in this project
- How to find it and how to use it
- If not, please let us know

**Comment by benidis** [comment]
Hi Freemanzxp,

We have a transformer implementation that is not currently in gluonts. However, we are planing to include it in the library soon (probably next couple of weeks). I will update the issue when we merge it to master.

**Comment by Freemanzxp** [comment]
Thank you for your reply and look forward to your update.
