### ISSUE TITLE
dataset "start" field as timestamp type

### ISSUE THREAD

**Issue by kashif** [awslabs/gluon-ts#1868]
## Description
At the moment the start field is a string. Which gets converted to a timestamp. I was wondering if it would be possible for this function https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/dataset/common.py#L318
to take a timestamp or a string and then not do the conversion if it's already a timestamp?

Thanks!

**Comment by jaheba** [comment]
To me it looks like this should already work, since we just pass the argument to `pd.Timestamp`, which should handle other timestamps just as well. We actually do it in the example in the `README`:

```py
from gluonts.dataset.common import ListDataset
training_data = ListDataset(
    [{"start": df.index[0], "target": df.value[:"2015-04-05 00:00:00"]}],
    freq = "5min"
)
```

We could change the type-annotation though.

**Comment by kashif** [comment]
ah ok yes i thought it might throw an error... so i was converting things to strings for nothing haha good to know... let me confirm and then I can close this issue.

**Comment by kashif** [comment]
issue #1876

**Comment by jaheba** [comment]
I think we can close this one.
