### ISSUE TITLE
DeepAR with NegativeBinomial cannot generate values above 1e6

### ISSUE THREAD

**Issue by mharvan** [awslabs/gluon-ts#1881]
## Description
A DeepAR model with NegativeBinomial output distribution cannot generate values significantly above 1e6.

## To Reproduce
I attach a jupyter notebook where I generate artificial timeseries with values between 0 and 1e8, train a model and plot the forecast. I compressed the notebook with zip as .ipynb files are not supported as attachments.

[1e6.ipynb.zip](https://github.com/awslabs/gluon-ts/files/8069187/1e6.ipynb.zip)

## Error message or code output
Please see the attached notebook.

![image](https://user-images.githubusercontent.com/16802400/154065593-3cfa3573-f5d5-4baf-a87e-714400f6e804.png)

## Environment
- Operating system: Ubuntu 20.04, linux kernel 5.13.0-28-generic
- Python version: 3.8.10
- GluonTS version: 0.8.1
- MXNet version: 1.9.0

I vaguely recall that 
I observed this issue alredy in gluonts versions 0.4.x.

**Comment by lostella** [comment]
@mharvan thanks for the very detailed report! I suspect the issue is with this line:

https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/mx/distribution/neg_binomial.py#L95

In fact, all the arbitrary clipping happening there should be revisited.

**Comment by mharvan** [comment]
Thanks @lostella !
