### ISSUE TITLE
How can I consume a listdataset to represent my model as a symbol block predictor in gluonts?

### ISSUE THREAD

**Issue by venkativaturi** [awslabs/gluon-ts#1892]
### Discussed in https://github.com/awslabs/gluon-ts/discussions/1891

<div type='discussions-op-text'>

<sup>Originally posted by **venkativaturi** February 16, 2022</sup>
I am using gluonts to implement a deep state estimator. I want to convert from the mxnet framework it is built in to the ONNX framework. In order to do so, I am trying to convert my Representable Block Predictor object to a symbol block predictor, so I can export the model. I am currently trying to pass my training ListDataset to the symbol block predictor.

Im currently building my ListDataset like this:
`Im currently building my ListDataset like this:
indices = pd.date_range(start = "2018-12-31", end = "2021-11-30",freq='M')

    
    for time_series in target:

        train_time_series_dicts.append([{"item_id": item_id,"target": train_target,"start":start_train,"feat_static_cat": [ts_volume]})
        
        test_time_series_dicts.append({"item_id": item_id,"target": test_target,"start": start_test,"feat_static_cat": [ts_volume])
        
    
    train_df = train_time_series_dicts
    train_ds = ListDataset(train_time_series_dicts,freq='M')
    #print(train_ds)
    test_df = test_time_series_dicts
    test_ds = ListDataset(test_time_series_dicts,freq='M')`

2. After I run my trials and generate a predictor object, I am trying to extract the symbol file and the parameter json file. In order to extract the symbol object, I tried:
`predictor.as_symbol_block_predictor(dataset=[train_ds])
`
3. The Error Message: I am getting the error 'ListDataset' object has no attribute 'copy'. Here is the trace:
`   --> 123         for data_entry in data_it:
        124             try:
        125                 yield self.map_transform(data_entry.copy(), is_train)
    
    /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
        121         self, data_it: Iterable[DataEntry], is_train: bool
        122     ) -> Iterator:
    --> 123         for data_entry in data_it:
        124             try:
        125                 yield self.map_transform(data_entry.copy(), is_train)
    
    /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
        121         self, data_it: Iterable[DataEntry], is_train: bool
        122     ) -> Iterator:
    --> 123         for data_entry in data_it:
        124             try:
        125                 yield self.map_transform(data_entry.copy(), is_train)
    
    /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
        125                 yield self.map_transform(data_entry.copy(), is_train)
        126             except Exception as e:
    --> 127                 raise e
        128 
        129     @abc.abstractmethod`</div>

**Comment by lostella** [comment]
Closed for double posting: anyone interested please refer to the discussion linked in the OP
