### ISSUE TITLE
Explanation regarding setting the maximum number of training windows creation/sampling as a hyperparameter for the DeepAREstimator

### ISSUE THREAD

**Issue by vamp-ire-tap** [awslabs/gluon-ts#1897]
### Discussed in https://github.com/awslabs/gluon-ts/discussions/1889

<div type='discussions-op-text'>

<sup>Originally posted by **vamp-ire-tap** February 16, 2022</sup>
Hello, can anyone explain how the training windows are generated in the default call to the DeepAREstimator? I see that on the following line:

https://github.com/awslabs/gluon-ts/blob/8132e2462b649455ade4dbc66cc36114df1796bc/src/gluonts/model/deepar/_estimator.py#L271

There is a call to create the ExpectedNumInstanceSampler(num_instances=1.0, min_future=prediction_length) if there is no train_sampler is provided. By looking at the definition of the ExpectedNumInstanceSampler on the following: 

https://github.com/awslabs/gluon-ts/blob/8132e2462b649455ade4dbc66cc36114df1796bc/src/gluonts/transform/sampler.py#L139

I see that num_instances=1.0 tells the sampling of training windows can occur by choosing any valid point in time series history and sampling some points before and after it to create a training window. However, the main problem I am having is to understand what hyperparameter dictates *how many* training windows should be sampled at max. If we look at the DeepAR paper at https://arxiv.org/pdf/1704.04110.pdf, then in table 3 it is stated that they take #500K training examples for the traffic dataset for example. How can I set this 500K hyperparameter by calling the DeepAREstimator or the ExpectedNumInstanceSampler?

</div>

**Comment by lostella** [comment]
Closed for double posting: anyone interested please refer to the discussion linked in the OP

**Comment by vamp-ire-tap** [comment]
it is not so much a discussion but an explanation that is requested from the developers/maintainers of the library, that is why it was posted here as an issue as well. I hope one of the contributors can help answer this question above

**Comment by lostella** [comment]
@vamp-ire-tap I understand, however, we rely on issues in order to track actionable items like missing features, bugs, proposals, and so on. I think discussions are better suited for questions and answers: They don’t get “closed” and have ranked answers.

Of course if a discussion turns out to identify an actual issue, it makes perfect sense to turn it into an issue so that developers can pick it up.

**Comment by vamp-ire-tap** [comment]
I understand, I hope I receive a response soon there then; plus i'd be grateful to you if you could answer maybe

**Comment by vamp-ire-tap** [comment]
Could the authors/contributors of the library answer the question posted above?
