### ISSUE TITLE
https://ts.gluon.ai/ website link broken

### ISSUE THREAD

**Issue by DickJC123** [awslabs/gluon-ts#1901]
## Description
https://ts.gluon.ai/ returns 'page not found'

**Comment by DickJC123** [comment]
FWIW, current link response is:
```This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8J284NJB4MJGF0MZ</RequestId>
<HostId>tULYqBu6ilnV4HBLHEGA5mGhrqquYMdFnjlVPmeyvMJmrWAKmZlDxgiaqQ0Wu2kT9U+QgcHqI2A=</HostId>
</Error>
```

**Comment by lostella** [comment]
The issue should be fixed; pages should be accessible once again, as soon as the CloudFront cache expires.

**Comment by DickJC123** [comment]
I'm getting a different behavior- while there is no error, clicking the ts.gluon.ai link on the right side of the https://github.com/awslabs/gluon-ts page invokes a download, it does not display a new page.

**Comment by DickJC123** [comment]
Web link confirmed to be working now, thanks.
