### ISSUE TITLE
How to normalize dataset?

### ISSUE THREAD

**Issue by Narsiss** [awslabs/gluon-ts#191]
I'm trying to predict factories product  yield monthly.
I've tried normalize all dataset to train in an estimator, and normalize data in two different way:
1. (x-mean)/std
2. (x-min)/(max-min)
but both way trained a negative epoch_loss
![Screen Shot 2019-07-11 at 12 18 00 PM](https://user-images.githubusercontent.com/5062214/61021891-f8db6480-a3d5-11e9-9f78-7ab54852415d.png)

**Comment by lostella** [comment]
@Narsiss can you be more specific, and post code snippets instead of screenshots? What estimator are we talking about exactly? I'm assuming that the loss is negative log-likelihood, and there's nothing wrong with it being negative. What is the issue?

**Comment by Narsiss** [comment]
@lostella 
My problem is the negative epoch_loss, cause it is first time I met in this model.
Now I will continue to complete my model.
Thanks for your answer.
By the way , is there any documentation about the 'epoch_loss'?
