### ISSUE TITLE
from gluonts.model.deephier import DeepHierEstimator ModuleNotFoundError: No module named 'gluonts.model.deephier'

### ISSUE THREAD

**Issue by Mady1121** [awslabs/gluon-ts#1943]
## Description
(A clear and concise description of what the bug is.)

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)

```python
put code here
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
put error or undesired output here
```

## Environment
- Operating system:
- Python version:
- GluonTS version:
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@Mady1121 indeed, the module you are trying to import from (`gluonts.model.deephier`) does not exist in GluonTS, so the error is expected.

Maybe you are trying to run code from some other repository or branch? Or maybe you are looking for `DeepVARHierarchicalEstimator`?

**Comment by Mady1121** [comment]
Hi, I have been reproducing the DeepVAR model recently, but I have encountered many problems. I did not get the experimental results by running _estimator.py and _network.py, and I also did not get any results by running other ones. If I want to ask you for the complete code, thank you, looking forward to your reply.(Note: I want to achieve the following results)









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "awslabs/gluon-ts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [awslabs/gluon-ts] from gluonts.model.deephier import DeepHierEstimator ModuleNotFoundError: No module named 'gluonts.model.deephier' (Issue #1943)





 
@Mady1121 indeed, the module you are trying to import from (gluonts.model.deephier) does not exist in GluonTS, so the error is expected.
 
Maybe you are trying to run code from some other repository or branch? Or maybe you are looking for DeepVARHierarchicalEstimator?

**Comment by lostella** [comment]
@Mady1121, it is not clear to me what is not working: can you share a minimal and self-contained example that reproduces the issue you are encountering?
