### ISSUE TITLE
MXNet Error: Cannot use gluonts because MXNet does not install on Apple M1 MacOS chip

### ISSUE THREAD

**Issue by babaniyi** [awslabs/gluon-ts#1992]
## Description
I cannot use gluonts on MacOS because I cannot install MXNet. I have tried all I could from the documentation but it does not work.

@lostella @jaheba any help on this?

```python
pip install --upgrade mxnet~=1.7
pip install gluonts
```

## Error message or code output

```
ERROR: Could not find a version that satisfies the requirement mxnet~=1.7 (from versions: 1.6.0)
ERROR: No matching distribution found for mxnet~=1.7
```

## Environment
- Operating system: MacOS Monterey 12.2.1 (21D62)
- Python version:3.8.9
- GluonTS version:
- MXNet version: 1.7

**Comment by lostella** [comment]
@babaniyi if you don't strictly need to use MXNet-based models, you don't need to install MXNet. For example, you can use [the PyTorch version of `DeepAR`](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/torch/model/deepar/estimator.py) in case that works for you and pytorch installs on M1 (which I don't know).

Which model(s) are you interested in working with?

If you really need to use MXNet ones, the best thing to do at the moment is to open an issue with MXNet, I believe

**Comment by lostella** [comment]
@babaniyi you can import the estimator class with

```python
from gluonts.torch.model.deepar import DeepAREstimator
```

However we don't have the PyTorch version of the zero-inflated distributions, we mostly rely on [distributions directly offered by PyTorch](https://pytorch.org/docs/stable/distributions.html). You can still use a `NegativeBinomial` with

```python
from gluonts.torch.distributions import NegativeBinomialOutput
```

**Comment by babaniyi** [comment]
> @babaniyi you can import the estimator class with
> 
> ```python
> from gluonts.torch.model.deepar import DeepAREstimator
> ```
> 
> However we don't have the PyTorch version of the zero-inflated distributions, we mostly rely on [distributions directly offered by PyTorch](https://pytorch.org/docs/stable/distributions.html). You can still use a `NegativeBinomial` with
> 
> ```python
> from gluonts.torch.distributions import NegativeBinomialOutput
> ```

Thanks for your replies.
After several hours, I think the solution is to use MacOS that are not M1 otherwise there will be lots of issues.
