### ISSUE TITLE
Dataset Formats

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#2003]
See: #2000, #1261

---

Currently, we support `jsonlines` datasets in GluonTS. The format is simple, easy to generate and human readable. However, the format is inefficient w.r.t file-size and loading. Thus, we are locking for alternatives to complement jsonlines.

Apache Arrow provides support for three storage formats:

* Parquet
* Streaming
* Random Access

While parquet is standardised and has widespread support, it's designed as an archival format and is optimised more for file-size than extraction speed.

The two other formats are arrow-specific, are optimised for loading, but not for storage (in-memory usage should be similar to disk-size).

All three formats can be used in Arrow and thus support a similar interface.

## Columnar Design

Arrow is build on a column-oriented design, meaning that the contents of each column is stored together. For example, this table

```
a 1
b 2
c 3
```

woulb be stored as `[a, b, c], [1, 2, 3]`. A row-based storage strategy would use a format like `[(a, 1), (b, 2), (c, 3)]`.

There are benefits to column-orientation, if only operating on certain columns of the table. Alas, we are always interested in each entire row, one by one.

Even though the format is not optimal for our use-case, we still benefit from efficient storing and loading of binary data.

## Performance

To provide an idea of how fast each method is, I ran some simple benchmarks.

I've used the `electricity` dataset, which consists of `321` time-series and added `5` additional `dynamic_features` to it. Then, I'm generating an endless stream for each format, and slice 1 million lines from it:

| Format             | Throughput ts/s |
| ------------------ |----------------:|
| jsonlines          | `69`            |
| Table* (in-memory) | `23_389`         |
| Table (in-memory)  | `11_114`         |
| Streaming*         | `5_405`          |
| Streaming          | `4_085`          |
| Parquet            | `469`           |

The `*` marked formats use an optimisation to load the 2d `feat_dynamic_real` arrays more efficiently.

For comparison, running on a a much simpler dataset (`m4_yearly`):

| Format             | Throughput ts/s |
| ------------------ |----------------:|
| jsonlines          | `7_431`          |
| Table (in-memory)  | `25_929`         |
| Streaming          | `33_389`         |
| Parquet            | `32_784`         |

**However**, caching the dataset in Python (via `list(dataset)`), the throughput is `> 100x` higher.

## Discussion

Arrow provides access to three efficient dataset foramts. They can be much faster to use than our current `jsonlines` datasets.

While `parquet` offers a significant speedup of about `10x` in more complex cases, Apaches `streaming` format can add another `10x` improvement.

In testing, the arrow `random-access` format was slower when using it for streaming access, but was more performant when loading the entire table into memory.
However, listifying the dataset offers much higher access with the same memory footprint.

## Conclusion

Adding support for `parquet` and Arrow's `streaming` dataset to GluonTS offer real benefits. Data access can be much faster than with `jsonlines`, while also offering a more efficient storage format.

There is not much benefit to the `random-access` format yet: It is slower than calling `list` on the dataset, whilst offering no memory-usage advantage; and it is slower than the `streaming` format for streaming. However, when we want to support random-access and need to support very large datasets, which do not fit into memory, we should revisit this format.

**Comment by lostella** [comment]
Is the optimization for loading arrays (marked with `*`) the one enable with `flatten_arrays` option in #2000?

**Comment by jaheba** [comment]
I've run some comparisons using the current version of #2000:


**electricity**

```
+-----------------+------------+--------+----------------+
|     Dataset     | Throughput | Factor | File Size (MB) |
+-----------------+------------+--------+----------------+
|   FileDataset   |    485     |  1.00  |     328.75     |
|    ArrowFile    |   56848    | 117.18 |     181.27     |
| ArrowStreamFile |   22057    | 45.46  |     181.27     |
|   ParquetFile   |    2712    |  5.59  |     84.90      |
+-----------------+------------+--------+----------------+
```


**traffic**

```
+-----------------+------------+--------+-----------+
|     Dataset     | Throughput | Factor | Fill Size |
+-----------------+------------+--------+-----------+
|   FileDataset   |    559     |  1.00  |   640.41  |
|    ArrowFile    |   59062    | 105.59 |   325.45  |
| ArrowStreamFile |   25247    | 45.14  |   325.45  |
|   ParquetFile   |    3308    |  5.91  |   130.10  |
+-----------------+------------+--------+-----------+
```

**m4_yearly**

```
+-----------------+------------+--------+----------------+
|     Dataset     | Throughput | Factor | File Size (MB) |
+-----------------+------------+--------+----------------+
|   FileDataset   |   31932    |  1.00  |      9.18      |
|    ArrowFile    |   68646    |  2.15  |      3.85      |
| ArrowStreamFile |   68312    |  2.14  |      3.85      |
|   ParquetFile   |   59436    |  1.86  |      4.09      |
+-----------------+------------+--------+----------------+
```

**Comment by jaheba** [comment]
Also interesting, running the `FileDataset` for longer can speed up the average throughput:

**m4_yearly**

```
+------------------+------------+--------+----------------+
|     Dataset      | Throughput | Factor | File Size (MB) |
+------------------+------------+--------+----------------+
|   FileDataset    |   63721    |  1.00  |      7.98      |
|    ArrowFile*    |   70151    |  1.10  |      3.32      |
|    ArrowFile     |   71222    |  1.12  |      3.32      |
| ArrowStreamFile* |   71309    |  1.12  |      3.32      |
| ArrowStreamFile  |   62910    |  0.99  |      3.32      |
|   ParquetFile*   |   62259    |  0.98  |      3.47      |
|   ParquetFile    |   50316    |  0.79  |      3.47      |
+------------------+------------+--------+----------------+
```
