### ISSUE TITLE
`DataFramesDataset` should take `index` for timestamp field if available.

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#2026]
Currently, we require that the `timestamp` field is a column in the passed datasets, but don't support it if it is the `index` of the `DataFrame`.

Ideally, it would try to use the `index` for it by default, raising an error if neither `timestamp` was passed nor the index can be used for it. 

- [ ] #2042

**Comment by kashif** [comment]
thanks! this should work out nicely with the #1973 stuff
