### ISSUE TITLE
Improving train/test splitters and test datasets

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#2041]
This is related to #1447, but a more concrete proposal.
Work in progress on part of this is in #2031

## Context

In GluonTS, data and tools provided for evaluating models accuracy on test data work a bit backwards (in a bad sense). Datasets are provided in terms of “train” and “test” portions, where test data is essentially (simplifying a bit here) a “continuation” of training data. So we have things like:

```
training entry = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
test entry     = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
```

There is an implicit assumption on how test data will be used: the final portion of it (the “label” if you want) will be taken out, the rest will be given as input to a predictor producing a forecast, and the forecast can then be compared back to the label for evaluation.

This implicit assumption is so pervasive that `make_evaluation_prediction`, the main entry point for getting evaluation out of models, has it baked in (it splits test entries into input and label internally).

### Representing test data better

*Edit: refer to the discussion below for updated details on this*

A better way to represent test data is to have `(input, label)` pairs explicitly exposed, like in any supervised learning setting:

```python
@dataclass
class TestDataset:
    input_label_pairs: Iterable[Tuple[DataEntry, pd.Series]]  # can use something else other than a pd.Series

    def __iter__(self):
        return input_output_pairs

    @property
    def inputs(self):
        for pair in self.input_output_pairs:
            yield pair[0]

    @property
    def labels(self):
        for pair in self.input_output_pairs:
            yield pair[1]
```

### Splitters to construct test data

*Edit: refer to the discussion below for updated details on this*

Once one has a `Dataset`, intended as an `Iterable[DataEntry]`, they can come up with various kinds of test scenarios using [splitters](https://github.com/awslabs/gluon-ts/blob/dev/src/gluonts/dataset/split/splitter.py):

```
training_data, test_data = OffsetSplitter(
    prediction_length=24
    split_offset=-24,
).split(data)
```

Here `training_data: Dataset` and `test_data: TestDataset` as defined above. Training data will satisfy the property that it does not overlap with any of the labels in `test_data`. One can define more complex test cases for rolling evaluation as follows:

```
training_data, test_data = OffsetSplitter(
    prediction_length=24
    split_offset=-24,
    windows=7,
    distance=24, # 7 non-overlapping test windows of length 24, out of each original series
).split(data)
```

Instead of splitting based on an integer offset, one can split according to a date (timestamp) using `DateSplitter` and doing simple or rolling splits just like the examples above.

Note that further splits (for example for validation) can be obtained by applying a splitter once more on the `training_data` out of the first split.

### Updating datasets

We can update the way test data is exposed in [`TrainDataset`](https://github.com/awslabs/gluon-ts/blob/bc82d85a8109186db16bf600d4be37ebbdf0fea2/src/gluonts/dataset/common.py#L121) (not the best name for this class I believe) by using the `TestDataset` class proposed above. Note that this can be done in a backward-compatible way wrt persisted datasets (that is, anyone having the datasets persisted on disk will still be able to use those, they will just be exposed as different Python objects).

### Remove the need for `make_evaluation_predictions`

With the above changes, evaluating models should be very easy and not require someone do "manipulate" the data for you in any way. Something like the following should be possible:

```python
model = estimator.train(training_data)
forecasts = model.predict(test_data.inputs)
metrics = evaluator(forecasts, test_data.labels)
```

In fact, `make_evaluation_predictions` could simply consist of the second line in the above snippet.

**Comment by jaheba** [comment]
I think I would like to see some more flexibility what I can do with test data and what I want see supported is both:

* Pool of potential time-series which could be used for evaluation.
* Concrete collection of time-series used for evaluation.


Say, for a given dataset I choose a point which marks the end for training, where everything after the mark *can* be used for testing:

```py
data = np.arange(10_000)
P = 7_000
train, potential_test = split(data, P)
```

Then I can train a model normally:

```py
model = estimator.train(train)
```

but have some more freedom when doing evaluation:

```py
rolling_test = potential_test.windows(prediction_length=24, windows=7, ...)
evaluator(model, rolling_test)

take_last = potential_test.take_last(prediction_length=24)
evaluator(model, take_last)
```

Both concrete test-datasets would implement your proposed interface, but the initial splitter would provide me some flexibility on how to construct the actual scenario.

**Comment by lostella** [comment]
Ok I think this is essentially an "opposite" take on what the splitter does: in my mind, the splitter gives you test instances, plus data that you *can* use for training if you want (some models don't require training; you may also want to further split into training + validation), but maybe your way is also fine for this purpose

**Comment by lostella** [comment]
So in your idea, `potential_test` just holds `data` and `P` to use them later?

**Comment by lostella** [comment]
## Updated proposal

Splitting training data out of the original `dataset`:

```python
training_dataset, test_template = split(dataset, date="2022-03-04")
```

Here `training_dataset: Dataset` is a regular dataset (an `Iterable[DataEntry]`) while `test_template` allows to generating test instances:

```python
test_data = test_template.generate_instances(
    prediction_length=7,
    windows=3
)
```

Iterating the above will produce pairs `(input, label)`, three of them for each original entry in the dataset, with non-overlapping `label`s of length 7. One can have overlapping windows by doing instead


```python
test_data = test_template.generate_instances(
    prediction_length=7,
    windows=3,
    distance=1,
)
```

in which case each of the three windows will start one time point after the previous one.

**Comment by lostella** [comment]
This was partially addressed, see
- #2031 
- #2223 
- #2259 
- #2314 
- #2315 

Test data in datasets from the repository is still unchanged: we can track changes to that in a separate story.
