### ISSUE TITLE
[Story] Rework `Evaluator`

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#2048]
The current `Evaluator` is inflexible and difficult to use.

The metrics which are used are fixed and it's not possible to choose which metrics should be calculated.

#1778 proposes a more flexible approach, where it's easier to define new metrics and to select which metrics should be calculated. Further, it caches intermediate results and can calculate multiple time-series at once resulting in improved performance.

A second focus should be on usability. #2045 makes using the `evaluator` more simple, and removes the use for `make_evaluation_prediction`.

There is further discussion on how one can create test-datasets and what their format should be: #2041

**Comment by lostella** [comment]
Essentially done in #2450
