### ISSUE TITLE
potential bottleneck in training

### ISSUE THREAD

**Issue by kashif** [awslabs/gluon-ts#2052]
## Description
I profiled my training which was taking too long and here is what I believe the part that is taking the longest:

```
Profile stats for: run_training_epoch
         309984 function calls (302234 primitive calls) in 82.921 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   82.921   82.921 base.py:168(run)
    520/2    0.000    0.000   82.921   41.460 {built-in method builtins.next}
        2    0.000    0.000   82.792   41.396 fetching.py:271(_fetch_next_batch)
        4    0.000    0.000   82.792   20.698 apply_func.py:73(apply_to_collection)
        2    0.000    0.000   82.792   41.396 supporters.py:547(__next__)
        2    0.000    0.000   82.792   41.396 supporters.py:555(request_next_batch)
        2    0.000    0.000   82.792   41.396 itertools.py:174(__iter__)
        2    0.000    0.000   82.792   41.396 dataloader.py:639(__next__)
        2    0.001    0.000   82.792   41.396 dataloader.py:680(_next_data)
        2    0.001    0.001   82.791   41.395 fetch.py:24(fetch)
      512    0.000    0.000   82.777    0.162 util.py:140(__iter__)
  992/512    0.001    0.000   82.777    0.162 _base.py:102(__iter__)
 5312/512    0.018    0.000   82.776    0.162 _base.py:121(__call__)
      512    0.005    0.000   82.773    0.162 _base.py:174(__call__)
      479    0.001    0.000   81.289    0.170 itertools.py:68(__iter__)
      479    0.013    0.000   78.146    0.163 feature.py:354(map_transform)
      479    0.014    0.000   76.209    0.159 feature.py:367(<listcomp>)
     2395    0.026    0.000   73.799    0.031 extension.py:67(fget)
    14851    0.015    0.000   73.575    0.005 {built-in method builtins.getattr}
     2395    0.020    0.000   73.559    0.031 period.py:97(f)
     2395   73.505    0.031   73.505    0.031 {pandas._libs.tslibs.period.get_period_field_arr}
        1    0.000    0.000   42.221   42.221 training_epoch_loop.py:157(advance)
...
```

To reproduce kindly train the pytorch DeepAR estimator with:

```
...
trainer_kwargs=dict(..., profiler="advanced"),
...
```

and train with `num_workers=0`

**Comment by kashif** [comment]
So I believe the `pandas._libs.tslibs.period.get_period_field_arr` is taking too long by the looks of it...

**Comment by jaheba** [comment]
Hi @kashif, was training faster before or is it that you are just unhappy how fast it currently is?

**Comment by kashif** [comment]
i believe it was always slow... its just that i was training on datasets where the time sequences are much larger e.g. 500K time steps... and there it really begins to show and I am unable to train...

**Comment by kashif** [comment]
Also, I believe the move from datetime to period didn't help the situation either as that in my initial experiments seem a bit slower too...

**Comment by lostella** [comment]
@kashif this is affecting time; is it also explaining the allocation issue in your use case? (discussed separately)

**Comment by kashif** [comment]
@lostella  I believe this is just the time issue... and CPU being at 100% etc. the memory issue is not related to this as far as I can tell...

**Comment by jaheba** [comment]
@kashif What kind of dataset are you using? Something which can speed things up by a lot is to convert the dataset into a list, since then repeated loading of the data becomes obsolete.

**Comment by kashif** [comment]
so I am using an arrow-based dataset `pip install -U datasets`:

```python
import functools

import pandas as pd
from datasets import load_dataset

from gluonts.dataset.common import Dataset


@functools.lru_cache(10_000)
def _as_period(val, freq):
    return pd.Period(val, freq)

@dataclass
class HFDataset(Dataset):
    def __init__(self, dataset, freq):
        self.dataset = dataset.with_format("np")
        self.freq = to_offset(freq)
    
    def __iter__(self):
        for data in self.dataset:
            yield {
                "start": _as_period(data["start"], self.freq),
                "target": data["target"],
                "item_id": data['item_id'],
            }

    def __len__(self) -> int:
        len(self.dataset)

hf_dataset = load_dataset("monash_tsf", "wind_farms_minutely")
train_ds = HFDataset(hf_dataset["train"].shuffle(), freq="1T")

```

**Comment by jaheba** [comment]
I've tried comparing the throughput of your example with using our `arrow` dataset implementation.

The throughput of the `HFDataset` is around `2000 ts/s`, whilst our arrow dataset is around `17000 ts/s`.

However, I would recommend using a list:

```py
train_ds = list(train_ds)
``` 

Which should make this much, much faster (getting around 2 million ts/s).

**Comment by kashif** [comment]
ah i see... let me try thank you!

**Comment by jaheba** [comment]
In my view, the only reason ever not to use `list` is if the dataset is too large to fit into memory -- but this looks to be around `~650 mb`.

**Comment by jaheba** [comment]
@kashif Any updates on the throughput?

**Comment by kashif** [comment]
yes so the issue still remains when creating batches even if its converted to a list, the pandas features method just saturates the CPU and takes too long when the target seq is very long....

**Comment by jaheba** [comment]
I see -- ideally we would make some of the transformations cacheable -- but we are not there yet.

**Comment by kashif** [comment]
yes that is what i am thinking... perhaps in my `HFDataset` I can already add the time features... and then in my model if that field is there it should do no transformation....

**Comment by kashif** [comment]
oh and i believe HF datasets let you cache transformed datasets so in theory i would need to do this once...

**Comment by jaheba** [comment]
What model are you using?

Here is a proposal how we could rework the dataloading: https://github.com/awslabs/gluon-ts/issues/1000

**Comment by kashif** [comment]
thank you @jaheba I will have a look at the proposal... currently I am writing a bunch of transformer based models https://github.com/kashif/pytorch-transformer-ts
