### ISSUE TITLE
Rename `DataFramesDataset` to `PandasDataset`

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#2056]
After some discussion with @lostella we want to 

- [x] rename `DataFramesDataset` to `PandasDataset`
- [x] support `pandas.Series` objects as a dataset with only a `target` column
- [x] treat a `DataFrame` with just one column like a `Series` object

As part of this we should also

- [x] fix naming used in the documentation notebook from #2051

**Comment by jaheba** [comment]
I believe there is a potential downside to this: If the model doesn't use `target`, we would still rename a single column which might use the correct name to `target`, which then leads to errors.

**Comment by lostella** [comment]
> If the model doesn't use `target`

Models model `target`, how can they not use it? Edit: I probably don't understand what you mean by "not using `target`"

**Comment by rsnirwan** [comment]
Renaming to `PandasDataset` sound good.

I was also thinking about supporting `pandas.Series`.
However,  I propose to internally postprocess `pandas.Series` to `pandas.DataFrame`. Otherwise, we have to maintain 2 different types.

I think the only addition would be: 
```
if input is series:
  assert series.index is date_range or period_range
  convert series to dataframe: pd.DataFrame(series, columns=["target"])
```

**Comment by jaheba** [comment]
> > If the model doesn't use `target`
> 
> Models model `target`, how can they not use it? Edit: I probably don't understand what you mean by "not using `target`"

This is more hypothetical at the moment, but what forces a model to use `target`?

On the other hand, we currently have baked the schema into `DataFramesDataset`, so we probably have to revisit the design in the future anyway.

**Comment by lostella** [comment]
I see, yes, a model may not use the (past) target as input to get predictions, and only use it in the loss computation during training.

**Comment by jaheba** [comment]
> Renaming to `PandasDataset` sound good.
> 
> I was also thinking about supporting `pandas.Series`. However, I propose to internally postprocess `pandas.Series` to `pandas.DataFrame`. Otherwise, we have to maintain 2 different types.
> 
> I think the only addition would be:
> 
> ```
> if input is series:
>   assert series.index is date_range or period_range
>   convert series to dataframe: pd.DataFrame(series, columns=["target"])
> ```

Sounds reasonable to me. This would just amount to `series.to_frame("target")`, right?

**Comment by jaheba** [comment]
> I see, yes, a model may not use the (past) target as input to get predictions, and only use it in the loss computation during training.

I'm not even sure about that. If I look at the TPP model, it could take in the data in other columns than `target`, say `event` and `arrival_time`. If it would do it, this abstraction becomes unusable, since it assumes that there is a `target`.

But maybe that's just fine and this kind of dataset wouldn't be a good fit anyway.
