### ISSUE TITLE
Multivariate Hierarchical Timeseries Forecasting

### ISSUE THREAD

**Issue by AkshtaChoudhary** [awslabs/gluon-ts#2067]
Trying to add features to hierarchical model (Multivariate time series)  using DeepVARHierarchicalEstimator)

I have 3 dataframes , data_df, feature1, feature2 which are of the size (21 x 36). There are 36 time periods and 21 are the individual time series including TOTAL

I have created training dataset in the following format

# CODE 

--# Forecast Length
forecast_length = 6

--# Frequency
freq = 'M'

-- #Dataframes
train_df = data_df.iloc[:,:-forecast_length]
f1_train_df = f1_df.iloc[:,:-forecast_length]
f2_train_df = f2_df.iloc[:,:-forecast_length]

 --# Creating Dictionary for training data 
traindict ={}

for x in train_df.index:
    traindict[x] = {'target': train_df[train_df.index=='Total'],
                           'start' : train_df.columns[0],
                           'features': np.vstack((f1_train_df [f1_train_df .index==x].values.flatten(),
                                                            f2_train_df [f2_train_df .index==x].values.flatten()))}

--# Training List Dataset
train_ds = ListDataset([{'target': traindict[df]['target'].values.flatten(), 'start':  traindict[df]['start'],
                                     'feat_dynamic_real': traindict[df]['features'] } for df in traindict.keys()],
                                    freq=freq,one_dim_target=False)  

--# S Matrix 
total_s = np.ones((1,len(brand_list))) -- #Creating 1's for the total level data
id_mat = np.eye(len(brand_list)) -- # Identity matrix of RegionState level combination
sum_matrix_rand =np.concatenate((total_s,id_mat)) --# Creating the S matrix for all the levels

--# Estimator
hier_estimator = DeepVARHierarchicalEstimator(freq = freq,
                                              prediction_length = forecast_length,
                                              target_dim = data_df.shape[0],
                                              S = sum_matrix_rand,
                                              trainer=Trainer(epochs=25, hybridize=False, learning_rate=0.1),
                                              context_length=10,
                                              num_layers=10)

--# Predictor
hier_predictor = hier_estimator.train(training_data=train_ds)
 
# ERROR   
I am getting the below error :

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_46940\2690552091.py in <module>
      1 # Predictor
----> 2 hier_predictor = hier_estimator.train(training_data=train_ds)

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\model\estimator.py in train(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, cache_data, **kwargs)
    198             num_prefetch=num_prefetch,
    199             shuffle_buffer_length=shuffle_buffer_length,
--> 200             cache_data=cache_data,
    201         ).predictor

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\model\estimator.py in train_model(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, cache_data)
    170             net=training_network,
    171             train_iter=training_data_loader,
--> 172             validation_iter=validation_data_loader,
    173         )
    174 

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\trainer\_base.py in __call__(self, net, train_iter, validation_iter)
    437                     epoch_no,
    438                     train_iter,
--> 439                     num_batches_to_use=self.num_batches_per_epoch,
    440                 )
    441 

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\trainer\_base.py in loop(epoch_no, batch_iter, num_batches_to_use, is_training)
    332                     if first_forward:
    333                         first_forward = False
--> 334                         _ = net(*batch.values())
    335 
    336                         self.callbacks.on_network_initializing_end(

~\Anaconda3\envs\python3.7_env\lib\site-packages\mxnet\gluon\block.py in __call__(self, *args)
    680             hook(self, args)
    681 
--> 682         out = self.forward(*args)
    683 
    684         for hook in self._forward_hooks.values():

~\Anaconda3\envs\python3.7_env\lib\site-packages\mxnet\gluon\block.py in forward(self, x, *args)
   1252                     params = {k: v.data(ctx) for k, v in self._reg_params.items()}
   1253 
-> 1254                 return self.hybrid_forward(ndarray, x, *args, **params)
   1255         params = {i: j.var() for i, j in self._reg_params.items()}
   1256         with self.name_scope():

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar\_network.py in hybrid_forward(self, F, target_dimension_indicator, past_time_feat, past_target_cdf, past_observed_values, past_is_pad, future_time_feat, future_target_cdf, future_observed_values)
    835             future_time_feat,
    836             future_target_cdf,
--> 837             future_observed_values,
    838         )
    839 

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar\_network.py in train_hybrid_forward(self, F, target_dimension_indicator, past_time_feat, past_target_cdf, past_observed_values, past_is_pad, future_time_feat, future_target_cdf, future_observed_values)
    498             future_time_feat=future_time_feat,
    499             future_target_cdf=future_target_cdf,
--> 500             target_dimension_indicator=target_dimension_indicator,
    501         )
    502 

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar\_network.py in unroll_encoder(self, F, past_time_feat, past_target_cdf, past_observed_values, past_is_pad, future_time_feat, future_target_cdf, target_dimension_indicator)
    363             target_dimension_indicator=target_dimension_indicator,
    364             unroll_length=subsequences_length,
--> 365             begin_state=None,
    366         )
    367 

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar\_network.py in unroll(self, F, lags, scale, time_feat, target_dimension_indicator, unroll_length, begin_state)
    213         assert_shape(
    214             lags_scaled,
--> 215             (-1, unroll_length, self.target_dim, len(self.lags_seq)),
    216         )
    217 

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\util.py in assert_shape(x, expected_shape)
     84                 assert (
     85                     i == j
---> 86                 ), f"shape mismatch got {x.shape} expected {expected_shape}"
     87 
     88 

AssertionError: shape mismatch got (32, 16, 1, 2) expected (-1, 16, 21, 2)

## Environment
- Operating system:  Windown
- Python version: 3.7.13
- GluonTS version: 0.9.4
- MXNet version: 1.7.0.post2

**Comment by lostella** [comment]
@AkshtaChoudhary could you enclose the code example and error trace in triple-backticks (`) so that they are more readable?

```
like this
```

Also, if possible, make sure the code example can be copy-pasted and executed as-is to reproduce the error.

**Comment by AkshtaChoudhary** [comment]
```
--# Forecast Length
forecast_length = 6

--# Frequency
freq = 'M'

-- #Dataframes
train_df = data_df.iloc[:,:-forecast_length]
f1_train_df = f1_df.iloc[:,:-forecast_length]
f2_train_df = f2_df.iloc[:,:-forecast_length]

--# Creating Dictionary for training data
traindict ={}

for x in train_df.index:
traindict[x] = {'target': train_df[train_df.index=='Total'],
'start' : train_df.columns[0],
'features': np.vstack((f1_train_df [f1_train_df .index==x].values.flatten(),
f2_train_df [f2_train_df .index==x].values.flatten()))}

--# Training List Dataset
train_ds = ListDataset([{'target': traindict[df]['target'].values.flatten(), 'start': traindict[df]['start'],
'feat_dynamic_real': traindict[df]['features'] } for df in traindict.keys()],
freq=freq,one_dim_target=False)

--# S Matrix
total_s = np.ones((1,len(brand_list))) -- #Creating 1's for the total level data
id_mat = np.eye(len(brand_list)) -- # Identity matrix of RegionState level combination
sum_matrix_rand =np.concatenate((total_s,id_mat)) --# Creating the S matrix for all the levels

--# Estimator
hier_estimator = DeepVARHierarchicalEstimator(freq = freq,
prediction_length = forecast_length,
target_dim = data_df.shape[0],
S = sum_matrix_rand,
trainer=Trainer(epochs=25, hybridize=False, learning_rate=0.1),
context_length=10,
num_layers=10)

--# Predictor
hier_predictor = hier_estimator.train(training_data=train_ds)
```

Error
```
AssertionError Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_46940\2690552091.py in
1 # Predictor
----> 2 hier_predictor = hier_estimator.train(training_data=train_ds)

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\model\estimator.py in train(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, cache_data, **kwargs)
198 num_prefetch=num_prefetch,
199 shuffle_buffer_length=shuffle_buffer_length,
--> 200 cache_data=cache_data,
201 ).predictor

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\model\estimator.py in train_model(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, cache_data)
170 net=training_network,
171 train_iter=training_data_loader,
--> 172 validation_iter=validation_data_loader,
173 )
174

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\trainer_base.py in call(self, net, train_iter, validation_iter)
437 epoch_no,
438 train_iter,
--> 439 num_batches_to_use=self.num_batches_per_epoch,
440 )
441

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\trainer_base.py in loop(epoch_no, batch_iter, num_batches_to_use, is_training)
332 if first_forward:
333 first_forward = False
--> 334 _ = net(*batch.values())
335
336 self.callbacks.on_network_initializing_end(

~\Anaconda3\envs\python3.7_env\lib\site-packages\mxnet\gluon\block.py in call(self, *args)
680 hook(self, args)
681
--> 682 out = self.forward(*args)
683
684 for hook in self._forward_hooks.values():

~\Anaconda3\envs\python3.7_env\lib\site-packages\mxnet\gluon\block.py in forward(self, x, *args)
1252 params = {k: v.data(ctx) for k, v in self._reg_params.items()}
1253
-> 1254 return self.hybrid_forward(ndarray, x, *args, **params)
1255 params = {i: j.var() for i, j in self._reg_params.items()}
1256 with self.name_scope():

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar_network.py in hybrid_forward(self, F, target_dimension_indicator, past_time_feat, past_target_cdf, past_observed_values, past_is_pad, future_time_feat, future_target_cdf, future_observed_values)
835 future_time_feat,
836 future_target_cdf,
--> 837 future_observed_values,
838 )
839

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar_network.py in train_hybrid_forward(self, F, target_dimension_indicator, past_time_feat, past_target_cdf, past_observed_values, past_is_pad, future_time_feat, future_target_cdf, future_observed_values)
498 future_time_feat=future_time_feat,
499 future_target_cdf=future_target_cdf,
--> 500 target_dimension_indicator=target_dimension_indicator,
501 )
502

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar_network.py in unroll_encoder(self, F, past_time_feat, past_target_cdf, past_observed_values, past_is_pad, future_time_feat, future_target_cdf, target_dimension_indicator)
363 target_dimension_indicator=target_dimension_indicator,
364 unroll_length=subsequences_length,
--> 365 begin_state=None,
366 )
367

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\model\deepvar_network.py in unroll(self, F, lags, scale, time_feat, target_dimension_indicator, unroll_length, begin_state)
213 assert_shape(
214 lags_scaled,
--> 215 (-1, unroll_length, self.target_dim, len(self.lags_seq)),
216 )
217

~\Anaconda3\envs\python3.7_env\lib\site-packages\gluonts\mx\util.py in assert_shape(x, expected_shape)
84 assert (
85 i == j
---> 86 ), f"shape mismatch got {x.shape} expected {expected_shape}"
87
88

AssertionError: shape mismatch got (32, 16, 1, 2) expected (-1, 16, 21, 2)
```

**Comment by lostella** [comment]
@AkshtaChoudhary thanks; the code cannot run because of the `--` in front of comment lines.

Do you think you can also include something that generates random dataframes the way you have them? So that the snippet can be run and the error reproduced

**Comment by AkshtaChoudhary** [comment]
```import os
import pandas as pd
import numpy as np
import mxnet as mx
from gluonts.dataset.common import ListDataset
from gluonts.model.deepvar_hierarchical import DeepVARHierarchicalEstimator
from gluonts.mx.trainer import Trainer
from gluonts.evaluation.backtest import make_evaluation_predictions
from gluonts.evaluation.metrics import smape,mape
from datetime import datetime
from time import strptime
import openpyxl

# Forecast Length
forecast_length = 6

# Frequency
freq = 'M'

# Date ranges
dt_rnge = pd.date_range(start='2019-04-01', freq=freq, periods=36)

# Series
series_list = ['A','B','C','D']

# Creating dataframe
data_df = pd.DataFrame(np.random.randint(0,100000,size=(len(series_list),len(dt_rnge)), index=series_list,columns=dt_rnge)
f1_df= pd.DataFrame(np.random.randint(0,100,size=(len(series_list),len(dt_rnge)), index=series_list,columns=dt_rnge)
f2_df= pd.DataFrame(np.random.randint(0,50,size=(len(series_list),len(dt_rnge)), index=series_list,columns=dt_rnge)

def add_total_dataframe(data_df):
    # Creating a dataframe similar to the input dataframe
    total_df = pd.DataFrame()
    # Aggregating at the total level
    total_df['Total'] = data_df.agg('sum').T
    # Concatenating with actuall dataframe
    data_df1 = pd.concat([total_df,data_df])
    return data_df1

# Adding the total values to each dataframe
data_df1 = add_total_dataframe(data_df)
f1_df1= add_total_dataframe(f1_df)
f2_df1= add_total_dataframe(f2_df)

#Dataframes selecting for train for target, f1, f2
train_df = data_df1.iloc[:,:-forecast_length]
f1_train_df = f1_df1.iloc[:,:-forecast_length]
f2_train_df = f2_df1.iloc[:,:-forecast_length]

# Creating Dictionary for training data
traindict ={}

for x in train_df.index:
traindict[x] = {'target': train_df[train_df.index=='x'],
'start' : train_df.columns[0],
'features': np.vstack((f1_train_df [f1_train_df .index==x].values.flatten(),
f2_train_df [f2_train_df .index==x].values.flatten()))}

# Training List Dataset
train_ds = ListDataset([{'target': traindict[df]['target'].values.flatten(), 'start': traindict[df]['start'],
'feat_dynamic_real': traindict[df]['features'] } for df in traindict.keys()],
freq=freq,one_dim_target=False)

# Creating 1's for the total level data
total_s = np.ones((1,len(series_list)))
# Identity matrix of RegionState level combination
id_mat = np.eye(len(series_list))  
# Creating the S matrix for all the levels
sum_matrix_rand =np.concatenate((total_s,id_mat)) 

# Estimator
hier_estimator = DeepVARHierarchicalEstimator(freq = freq,
prediction_length = forecast_length,
target_dim = data_df.shape[0],
S = sum_matrix_rand,
trainer=Trainer(epochs=25, hybridize=False, learning_rate=0.1),
context_length=10,
num_layers=10)

# Predictor
hier_predictor = hier_estimator.train(training_data=train_ds)

**Comment by rshyamsundar** [comment]
Hi @AkshtaChoudhary , as @lostella  mentioned it is essential to have a code snippet that runs and reproduces the error so that the real issue can be found quickly.

But, your code snippet does not even run because of syntax errors:
* missing right `)` on the lines creating the variables `data_df`, `f1_df` and `f2_df`
* required indentation missing after the `for` statement that creates `train_dict`

After fixing these, I realized that your data preparation itself is wrong. Have you examined the values of the input dataframes you constructed, e.g., `train_df` before opening an issue? What shape do you expect for them? Why is there time index both on rows and columns? If you check them you will also realize that `target` is actually empty in `train_dict` because of an incorrect check (see the second bullet point below).

**Here are the fixes for your data preparation:**
* The concatenation in `add_total_dataframe` is wrong because the transpose in the statement `total_df['Total'] = data_df.agg('sum').T`  is not done on the whole data frame. You could instead do this: 
```data_df1 = pd.concat([total_df.T,data_df])```
* This statement that creates `target` compares with string literal `'x'` instead of the variable `x` :
`'target': train_df[train_df.index=='x']`! Change it to `x` as you did for `features`.

Finally, for hierarchical datasets, the target is assumed to be of shape `num_ts x T` and all the time series are assumed to have same features. So the following changes are further needed to run:

```
target = [
    traindict[df]['target'].values.flatten()
    for df in traindict.keys()
]

# Features are assumed to same for all time series. So we take from the `Total` time series.
features = traindict['Total']['features']

train_ds = ListDataset(
    [
        {
            'target': target,
            'start': dt_rnge[0],
            'feat_dynamic_real': features,
        }
    ],
    freq=freq,one_dim_target=False
)
```

Also, the `target_dim` is the number of total time series including `Total` , so it is 5 in your case. This means you should pass `target_dim = train_df.shape[0]` instead of `data_df.shape[0]`.

With these changes I am able to run the model without any problems. So it is just a data-preparation issue!

**Comment by AkshtaChoudhary** [comment]
Hello @rshyamsundar 

Thanks for the reply. However I have a question, you mentioned that "Features are assumed to same for all time series. So we take from the `Total` time series." But what if we have features different for time series & also have it at Total level ? How should that be assigned to the feat_dynamic_real?

**Comment by rshyamsundar** [comment]
Hi @AkshtaChoudhary, one could pass features that are different for different time series in the following way:

```
features = [
    traindict[df]['features']
    for df in traindict.keys()
]

# Features of different time series need to be collapsed in to the first dimension.
features = np.reshape(features, (-1, f1_train_df.shape[1]))
```

I am attaching here the full working code for reference:

```
import pandas as pd
import numpy as np
import mxnet as mx
from gluonts.dataset.common import ListDataset
from gluonts.model.deepvar_hierarchical import DeepVARHierarchicalEstimator
from gluonts.mx.trainer import Trainer
from gluonts.evaluation.backtest import make_evaluation_predictions
from gluonts.evaluation.metrics import smape,mape
from datetime import datetime
from time import strptime

# Forecast Length
forecast_length = 6

# Frequency
freq = 'M'

# Date ranges
dt_rnge = pd.date_range(start='2019-04-01', freq=freq, periods=36)

# Series
series_list = ['A','B','C','D']

# Creating dataframe
data_df = pd.DataFrame(np.random.randint(0,100000,size=(len(series_list),len(dt_rnge))), index=series_list,columns=dt_rnge)
f1_df= pd.DataFrame(np.random.randint(0,100,size=(len(series_list),len(dt_rnge))), index=series_list,columns=dt_rnge)
f2_df= pd.DataFrame(np.random.randint(0,50,size=(len(series_list),len(dt_rnge))), index=series_list,columns=dt_rnge)

def add_total_dataframe(data_df):
    # Creating a dataframe similar to the input dataframe
    total_df = pd.DataFrame()
    # Aggregating at the total level
    total_df['Total'] = data_df.agg('sum')
    # Concatenating with actuall dataframe
    data_df1 = pd.concat([total_df.T,data_df])
    return data_df1

# Adding the total values to each dataframe
data_df1 = add_total_dataframe(data_df)
f1_df1= add_total_dataframe(f1_df)
f2_df1= add_total_dataframe(f2_df)

#Dataframes selecting for train for target, f1, f2
train_df = data_df1.iloc[:,:-forecast_length]
f1_train_df = f1_df1.iloc[:,:-forecast_length]
f2_train_df = f2_df1.iloc[:,:-forecast_length]

# Creating Dictionary for training data
traindict ={}

for x in train_df.index:
    traindict[x] = {
        'target': train_df[train_df.index==x],
        'start' : train_df.columns[0],
        'features': np.vstack(
            (
                f1_train_df [f1_train_df .index==x].values.flatten(),
                f2_train_df [f2_train_df .index==x].values.flatten()
            )
        )
    }

target = [
    traindict[df]['target'].values.flatten()
    for df in traindict.keys()
]

features = [
    traindict[df]['features']
    for df in traindict.keys()
]

# Features of different time series need to be collapsed in to the first dimension.
features = np.reshape(features, (-1, f1_train_df.shape[1]))

train_ds = ListDataset(
    [
        {
            'target': target,
            'start': dt_rnge[0],
            'feat_dynamic_real': features,
        }
    ],
    freq=freq,one_dim_target=False
)

# Creating 1's for the total level data
total_s = np.ones((1,len(series_list)))
# Identity matrix of RegionState level combination
id_mat = np.eye(len(series_list))
# Creating the S matrix for all the levels
sum_matrix_rand =np.concatenate((total_s,id_mat))

# Estimator
hier_estimator = DeepVARHierarchicalEstimator(freq = freq,
prediction_length = forecast_length,
target_dim = train_df.shape[0],
S = sum_matrix_rand,
trainer=Trainer(epochs=25, hybridize=False, learning_rate=0.1),
context_length=10,
num_layers=10)

# Predictor
hier_predictor = hier_estimator.train(training_data=train_ds)
```

**Comment by rshyamsundar** [comment]
For future reference, adding here the link to the tutorial that explains how to use the hierarchical model:
https://ts.gluon.ai/dev/tutorials/forecasting/hierarchical_model_tutorial.html

**Comment by AkshtaChoudhary** [comment]
Thank you !
