### ISSUE TITLE
Improving `PandasDataset` tutorial

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#2089]
The tutorial on `PandasDataset` should be improved to cover common workflows like:
- loading data from a single "long" CSV file
- doing a `groupby` on it to then cast the groups to have a certain frequency using `asfreq` (and filling the gaps)
- loading data from a "wide" CSV file, where each column is a separate univariate target

Essentially, it would be nice to expose all common ways one can bring data from a file to GluonTS via Pandas, with common adjustments/preprocessing that might be needed, instead of randomly generating the `DataFrame` objects directly.

**Comment by greenpau** [comment]
@lostella , thank you for opening the issue!

An example, please consider incorporating the following "story".

A business wants to make predictions about future customer orders for specific items on a monthly basis. The dataset is customer placed orders for an item with order_id, quantity, and timestamps.

```csv
timestamp,order_id,item_id,quantity
2022-05-15 15:20:12,ODR123,foobar,1234
```

```
timestamp            order_id  item_id  quantity
2022-05-15 15:20:12  ODR123    foobar   1234
```

The more advanced would be adding `item_cat` column, which would hold the category of an item, e.g. tshirts, sweaters, etc.

**Comment by greenpau** [comment]
Notably, a particular `item_id` could be ordered every other month, creating gaps in the time-series.

**Comment by lostella** [comment]
> Notably, a particular `item_id` could be ordered every other month, creating gaps in the time-series.

I think those cases should be disambiguated by the user: if there are gaps in the time index, it could be that an observation is missing, or that it can be assumed to be zero. The safest thing to do is not to accept gaps in the data, and require the user to fill them in: this is something the tutorial should be very clear about, and provide examples on how to do that I believe.
