### ISSUE TITLE
UserWarning: Using `json`-module for json-handling

### ISSUE THREAD

**Issue by greenpau** [awslabs/gluon-ts#2099]
## Description

Getting `UserWarning: Using `json`-module for json-handling`.

## To Reproduce

N/A

## Error message or code output

```
.local/lib/python3.8/site-packages/gluonts/json.py:101: UserWarning: Using `json`-module for json-handling. Consider installing one of `orjson`, `ujson` to speed up serialization and deserialization.
```

## Environment
- Operating system: AL2
- Python version: `Python 3.8.13`
- GluonTS version: `gluonts               0.dev0+g9f0f70e`
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@greenpau if you follow the suggestion in the warning, you will get faster data loading

**Comment by greenpau** [comment]
> if you follow the suggestion in the warning, you will get faster data loading

@lostella , the warning comes from `gluonts/json.py`. How can I control/provider options to use `orjson`?

**Comment by lostella** [comment]
@greenpau just install it and it will be used internally
