### ISSUE TITLE
Model unexpectedly quits during training

### ISSUE THREAD

**Issue by RMaron** [awslabs/gluon-ts#211]
## Description
DeepAREstimator hangs and freezes during training. Completes 0 training iterations and epochs. Sometimes will freeze entire OS.

I'm able to allocate memory to the GPU via NDArray, as well as converge a CNN MNIST model with normal Gluon. I have tried disabling CUDNN autotune.

## To Reproduce
Code:
```
df = pd.read_csv("test.csv", header=0, index_col=0)
td = ListDataset([{"start": df.index[0], "target": df.value}], freq="1min")

estimator = DeepAREstimator(freq="1min", prediction_length=60, trainer=Trainer(epochs=1, ctx=mx.gpu(0)))
predictors = estimator.train(training_data=td)
```
Dataset (test.csv):
```
time           value
1279425840     4.00
1279425900     5.00
...                ...
1551063419  2254.00
1551063479  2257.00
```

## Error Message
```
  0%|                                                    | 0/50 [00:00<?, ?it/s]
Killed
```

## Environment
- Operating system: Ubuntu 18.04
- Python version: 3.6.8
- GluonTS version: 0.2.3
- MXNet version: cu101mkl 1.5.0
-GPU: GTX 1070 (responds to nvidia-smi)
-CUDA: Release 10.1

**Comment by lostella** [comment]
I believe `df.value` will yield a `pd.Series` object. Can you try using
```python
df.value.tolist()
```
instead?

**Comment by RMaron** [comment]
Doing that still yields the same "error". One interesting thing I noticed is that if I encounter the error in the python interpreter, the entire interpreter quits instead of continuing execution.

**Comment by RMaron** [comment]
Update: It looks like installing gluonts also installs the normal `mxnet` package as a dependency. It doesn't use the preexisting `mxnet-cu101mkl` package I have installed. I think this problem may have something to do with the fact that I now have duplicate packages installed.

**Comment by lostella** [comment]
Oh, I had missed that gpu context. Yes, that might be the problem. For now, you should be able to work around it with 

```
pip install gluonts 
pip uninstall mxnet 
pip install mxnet-cu101mkl
```

In the future we may want to remove `mxnet` from `requirements.txt`

**Comment by RMaron** [comment]
After doing that and resolving a numpy version conflict, the same thing happens. Interestingly, GPU utilization before the crash is around 0. CPU is at 100%. More importantly, the model is killed because, as I have just discovered, it uses 100% of my memory of 32gb.

**Comment by RMaron** [comment]
Update: it runs on a smaller dataset but encounters the following error:
`mxnet.base.MXNetError: vector::_M_range_insert`
whenever I try to predict anything in any capacity.

**Comment by lostella** [comment]
@RMaron are you using `mxnet==1.5.0`? If so, try downgrading it to `mxnet==1.4.1`, there is some incompatibility with MXNet 1.5.0 which needs to be solved, [see e.g. this CI job here](http://ci.mxnet.io/blue/organizations/jenkins/GluonTS-py3-cpu-unittest/detail/PR-214/1/pipeline).

**Comment by lostella** [comment]
> @RMaron are you using `mxnet==1.5.0`?

Yes you are :-)

**Comment by RMaron** [comment]
That fixed it! Thank you.

**Comment by lostella** [comment]
> To anyone reading this: the Killed error was caused by 100% utilization of memory.
> **Solution: use a smaller dataset.**

This doesn't sound right: how long is `df.value.tolist()` in your case?

**Comment by lostella** [comment]
> To anyone reading this: the Killed error was caused by 100% utilization of memory.
> **Solution: use a smaller dataset.**

This doesn't sound right: how long is `df.value.tolist()` in your case?

**Comment by RMaron** [comment]
4,504,326 values.
