### ISSUE TITLE
TrainDataset.save default behaviour deletes everything

### ISSUE THREAD

**Issue by natashaklingenbrunn** [awslabs/gluon-ts#2120]
## Description
TrainDataset.save deletes all files in a folder as default behaviour (i.e. overwrite = True by default). Providing "." as path deletes all files in cwd which can cause lots of trouble for someone unfamiliar with the code. Proposal would be to set default behaviour to overwrite = False.

## To Reproduce

```python
from gluonts.dataset.repository.datasets import get_dataset  # type: ignore
from pathlib import Path

dataset_name = "m4_hourly"
dataset = get_dataset(dataset_name, regenerate=False)
dataset.save(str(".")) 
```

**Comment by jaheba** [comment]
`get_dataset` will already stores the dataset on disk and uses `.save` for it.

I think it makes sense to set `overwrite` to `False`, but set it to true when using `get_dataset`.

@nklingen Do you want to give this a try?
