### ISSUE TITLE
Interrupting training should lead to end of training instead of error.

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#2128]
When training is running, a CTRL-C interrupt should end training and return a result instead of bubbling the error.

We would need to catch `KeyboardInterrupt` in our trainers.

**Comment by lostella** [comment]
I thought we had this at some point, but I cannot find it. The nice thing is that this would make our own training loop consistent with PyTorch Lightning's, see note in https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
