### ISSUE TITLE
TypeError: PandasDataset() takes no arguments for PandasDataset.from_long_dataframe

### ISSUE THREAD

**Issue by strakehyr** [awslabs/gluon-ts#2140]
Following as described in https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html#Use-case-3---Loading-data-with-missing-values I could not get it to work with my own DF nor the example given:

```
ds = PandasDataset.from_long_dataframe(df, target="target", item_id="item_id")
Traceback (most recent call last):

  File "C:\\AppData\Local\Temp/ipykernel_33648/388385624.py", line 1, in <module>
    ds = PandasDataset.from_long_dataframe(dfx, target="target", item_id="item_id")

  File "C:\\Anaconda3\lib\site-packages\gluonts\dataset\pandas.py", line 182, in from_long_dataframe
    return cls(dataframes=dict(list(dataframe.groupby(item_id))), **kwargs)

TypeError: PandasDataset() takes no arguments
```

Also wanted to know if there are any plans of adding a methodology to achieve the same result starting from a wide DF, but (unlike the wide df example) incorporating a way to pass a list of feat_dynamic_cat, feat_static_cat, and so on (in same shape as the width of the wide df).

**Comment by lostella** [comment]
@strakehyr are you running on Python 3.9 or newer? If so, this may be related to #2133

**Comment by strakehyr** [comment]
> @strakehyr are you running on Python 3.9 or newer? If so, this may be related to #2133

Yes using Python 3.9.
