### ISSUE TITLE
Errors when training the `SelfAttentionEstimator`.

### ISSUE THREAD

**Issue by yuhaod** [awslabs/gluon-ts#2160]
## Description
(A clear and concise description of what the bug is.)

Errors related to class `TransformedDataset` when training the `SelfAttentionEstimator`.

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)
```python
from gluonts.model.san import SelfAttentionEstimator
from gluonts.dataset.repository.datasets import get_dataset

dataset = get_dataset("m4_hourly", regenerate=False)
estimator = SelfAttentionEstimator(freq=dataset.metadata.freq,
        prediction_length=dataset.metadata.prediction_length)
predictor = estimator.train(dataset.train)
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

![Screen Shot 2022-07-13 at 11 54 30 AM](https://user-images.githubusercontent.com/38566250/178809940-357f2247-dc8e-478f-a5e3-572ae31689ec.png)

## Environment
- Operating system: EC2 amazon-linux-2
- Python version: 3.9
- GluonTS version: 0.10.x
- MXNet version: 1.7.0.post1

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
Related to #1976

**Comment by yuhaod** [comment]
> Related to #1976

Yes, but it seems that #1976 was not fixed yet ...

**Comment by jaheba** [comment]
The default for `use_feat_dynamic_real` is `True`, so it expects the field to be there. The `m4_hourly` dataset does not have it, so we get the above error.

Setting `use_feat_dynamic_real = False` should work, but then there is #1976.

Something we don't do well is error reporting. We should have some consistency checks which would fetch this.

**Comment by lostella** [comment]
Model being moved to `gluonts.nursery` in #2534
