### ISSUE TITLE
Include forecast_start in Evaluator output item_metrics 

### ISSUE THREAD

**Issue by dmitra79** [awslabs/gluon-ts#2172]
## Description

When examining results of evaluation (ex. from call to `backtest.backtest_metrics()`, especially on a rolling dataset, it is useful to keep track of forecast_start for each item. With this information aggregations/breakdowns over different time periods can be easily computed.

Currently, only item_id is included by Evaluator in the output. One simple way around this is overwriting Evaluator (example below), but it would be much nicer if this was already done by Evaluator itself
```
class NewEvaluator(Evaluator):
        
    def get_metrics_per_ts(self, time_series: Union[pd.Series, pd.DataFrame],
                       forecast: Forecast) -> Dict[str, Union[float, str, None]]:
        metrics=super().get_metrics_per_ts(time_series, forecast)
        metrics.update({FieldName.FORECAST_START: forecast.start_date})
        return metrics
```

**Comment by dmitra79** [comment]
Hello, @lostella it looks like this is now covered by Evaluator (ex. based on tutorial - https://ts.gluon.ai/stable/tutorials/forecasting/quick_start_tutorial.html#Visualize-and-evaluate-forecasts) - did this start in v0.11? (I can't figure it out from the merge tickets).  
Thank you!

**Comment by lostella** [comment]
@dmitra79 yes, this is from 0.11.0 onwards. You can verify this by:
- going to the PR that solved this issue (https://github.com/awslabs/gluonts/pull/2312)
- at the bottom of the PR, clicking on the commit that the PR merge resulted in (https://github.com/awslabs/gluonts/commit/9f1cc3239472ed977438fb54e6cbd90a1bd0ea1e)
- expanding the “tags” detail in the commit information, which will show you all the tags (= versions) that include the change

**Comment by dmitra79** [comment]
Thank you!
