### ISSUE TITLE
MQCNN quantiles are not monotone

### ISSUE THREAD

**Issue by StanislasGuinel** [awslabs/gluon-ts#2178]
## Description
The quantile predictions of a MQCNN model are not always monotonic (quantile 0.1 can be bigger than quantile 0.2).
I have only seen that for MQCNN so far, is that a bug ?

## To Reproduce

This code outputs a dataframe of quantiles and we see for instance that quantile 0.3 is bigger than quantile 0.4.

```python
import mxnet as mx
import numpy as np
from gluonts.dataset.common import ListDataset
from gluonts.mx.trainer import Trainer
from gluonts.model.seq2seq import MQCNNEstimator

np.random.seed(42)
mx.random.seed(42)

estimator = MQCNNEstimator(
    freq="D",
    prediction_length=1,
    trainer=Trainer(ctx="cpu", epochs=1, batch_size=32),
)

gluon_dataset = ListDataset([{
        "target": [20.7, 17.9, 18.8, 14.6, 15.8, 15.8, 15.8, 17.4, 21.8, 20. ,16.2, 13.3, 16.7, 21.5, 25. , 20.7, 20.6, 24.8, 17.7, 15.5],
        "start": "2020-01-01",
    }],
    freq="D"
)

predictor = estimator.train(gluon_dataset)
forecasts = next(predictor.predict(gluon_dataset))

quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

d = {}
for i, quantile in enumerate(quantiles):
    d[quantile] = forecasts.quantile(quantile)

df_quantiles = pd.DataFrame(d)
print(df_quantiles)
```

## Code output
We can see that quantiles are not always increasing.
<img width="848" alt="Screenshot 2022-07-22 at 11 11 26" src="https://user-images.githubusercontent.com/60091564/180406252-70830915-5ab0-480d-8cdc-fe1c4af83745.png">

**Comment by jgasthaus** [comment]
Hi Stanislas, 

thank you for reporting this. 

Which version of GluonTS are you using?

The "plain" version of MQCNN _can_ have non-monotonic quantile values. However, in recent versions of GluonTS, MQCNN defaults to using the "Incremental Quantile Function" approach (https://proceedings.mlr.press/v151/park22a.html), which should avoid this quantile crossing issue. You can control this behavior with the ```is_iqf``` parameter, which defaults to ```True```. https://github.com/awslabs/gluon-ts/blob/73968889531af054e5c5b57b833dc11b1929233d/src/gluonts/mx/model/seq2seq/_mq_dnn_estimator.py#L168

If you see non-monotonic quantile values when ```is_iqf``` is set to ```True``` this is indeed a bug and we need to investigate further.

**Comment by lostella** [comment]
@StanislasGuinel it looks indeed like quantiles are sorted correctly in `dev`, `v0.10.2`, and also `v0.9.6`. Are you running an earlier version?

**Comment by StanislasGuinel** [comment]
Thanks for your answer, indeed I was using an earlier version (`0.8.1`), it's fixed with this `is_iqf` parameter.

**Comment by shreya976** [comment]
Try using 
from gluonts.mx.model.seq2seq  import MQCNNEstimator




        0.1       0.2        0.3        0.4        0.5        0.6        0.7  
0  5.357293  8.392515  10.374102  12.183992  15.109001  15.964971  15.964971   
         0.8        0.9  
  15.964971  15.964971
