### ISSUE TITLE
Significant Speed-up of Parquet Data Reader

### ISSUE THREAD

**Issue by mr-1993** [awslabs/gluon-ts#2195]
## Description

@emptymalei , @julian-sieber and myself were investigating a potential speed-up of your Parquet data reader since we use a similar implementation in a project of ours. What we found out is that there is a large potential in speeding it up. The difference in the implementation is essentially in the _arrow_to_py methods seen below. Instead of using a numpy-mediated conversion, we rely on pandas. In fact, this gives us a significant speed-up as the benchmarking section of the [attached notebook](https://gist.github.com/mr-1993/ee7dc378ba33d7f7f978be40af2cd8b0) suggests.  If you agree that this is a significant improvement of your current implementation, we would be happy to create a PR and implement the necessary changes.

https://github.com/awslabs/gluon-ts/blob/f0743d944a291d06d3a80561a0ec7368491e47b0/src/gluonts/dataset/arrow/dec.py#L23-L41

**Comment by jaheba** [comment]
Thanks! Yes, that would be very helpful :)

One thing we need to check is to translate the flattened arrays.

**Comment by mr-1993** [comment]
Hi @jaheba, thank you very much for your interest in this enhancement! Just as a clarification so that we can run more experiments: what exactly do you mean with "flattened arrays"? do you have a small example? thank you!

**Comment by jaheba** [comment]
We use an optimisation to support arrays with 2 or more dimensions:

https://github.com/awslabs/gluon-ts/blob/4c78ecfac2357935ab523e93d6e857cd8749aad6/src/gluonts/dataset/arrow/enc.py#L61-L70

This is something we also need to handle during decoding:

https://github.com/awslabs/gluon-ts/blob/4c78ecfac2357935ab523e93d6e857cd8749aad6/src/gluonts/dataset/arrow/dec.py#L74-L78

This enables zero-copy reads for arrays with 2 or more dimensions.

**Comment by jaheba** [comment]
@mr-1993 @emptymalei If you need any additional help, let me know! We can have a quick chat if you want.

**Comment by mr-1993** [comment]
That would actually be great, thank you! I am having a bit of trouble understanding how the schema is generated. Would you have a few minutes between 11:30 am and 1 pm?

**Comment by jaheba** [comment]
11:30 sounds good.
