### ISSUE TITLE
num_samples in make_evaluation_predictions for DeepAr, how to fix the outcome prediction?

### ISSUE THREAD

**Issue by Msaleh87** [awslabs/gluon-ts#2247]
### Discussed in https://github.com/awslabs/gluon-ts/discussions/2246

<div type='discussions-op-text'>

<sup>Originally posted by **Msaleh87** August 25, 2022</sup>
I have an electric load data for about a year, I trained the model for a data set from Mar 2021 until Mar 2022. After I trained my deepAr model, whenever I change num_samples, I get a different prediction. My understanding is that num_samples is the average of different probabilistic paths (like the ave of multiple forecasts). Is there a way to get somehow fixed prediction? When I increase num_samples to 100 or more, the forecast somehow stays the same, however, I no longer have the fluctuations details of the profile.

Here is my code:
```
estimator = DeepAREstimator(freq = '5min',
                           context_length = 7*24*12,  #The previous data points I look at to predict. It's like n_forecast in Neural Prophet 
                           prediction_length = 1*24*12,
                           num_layers = 2,
                           num_cells = 64,
                           cell_type = 'lstm',
                           use_feat_dynamic_real =True,
                           trainer = Trainer(epochs= 50))

from gluonts.dataset.common import ListDataset
training_data = ListDataset([{"start": df_input.index[0],
                              "target": df_input.Load[:'2022-03-07 04:50:00'],
                              'feat_dynamic_real': [df_input.DofW[:'2022-03-07 04:50:00']]}],
                           freq = "5min")

predictor = estimator.train(training_data = training_data)

test_data = ListDataset(
    [
        {"start": df_input.index[0], "target": df_input.Load[:'2022-03-08 04:50:00'], 'feat_dynamic_real': [df_input.DofW[:'2022-03-08 04:50:00']]}, # one day
        {"start": df_input.index[0], "target": df_input.Load[:'2022-03-09 04:50:00'], 'feat_dynamic_real': [df_input.DofW[:'2022-03-09 04:50:00']]}   # two days
    
    ],

freq = "5min")

forecast_it, ts_it = make_evaluation_predictions(
    dataset = test_data,
    predictor = predictor,
    num_samples = 100 #
)
```</div>

**Comment by lostella** [comment]
Closing in favor of the discussion: please avoid cross-posting discussion as issues, unless the discussion results in an actionable issue that requires attention.
