### ISSUE TITLE
How to get a distribution-output over positive number only?

### ISSUE THREAD

**Issue by Joachim96** [awslabs/gluon-ts#225]
Hello, 

I am looking for distribution-output over positive number only (such as Gamma distribution for example). I didn't find any in the API, did I miss it?

If not, is there a way to implement it? 

Thank you very much for your help

**Comment by jgasthaus** [comment]
GluonTS currently doesn't have support for Gamma distributed output, but it would be easy to add by creating a new `Distribution` subclass. You can look for example at 

https://github.com/awslabs/gluon-ts/blob/3d5b9629931b3c329cd9a6eccbf1f0fd8c3524cc/src/gluonts/distribution/neg_binomial.py#L25

to see which methods are required. In a nutshell, it would be a function for computing the log-likelihood and a function for sampling from a Gamma distribution (MXNet supports this). You also would need to define a corresponding `DistributionOutput` that describes the mapping from the unconstrained outputs of a dense layer to the domains of the parameters. (If you do implement it, please consider contributing it to the library by opening a pull request).

We do currently support `NegativeBinomial` output for positive integers. Alternatively, you can use a `TransformedDistribution`, combining e.g. a Normal distribution with an exponential transform to get a log-Normal distribution.

**Comment by lostella** [comment]
closing this, feel free to continue the discussion if needed
