### ISSUE TITLE
[DOC] In list of models links to implementation do not work 

### ISSUE THREAD

**Issue by shagn** [awslabs/gluon-ts#2254]
## Description
Hi, 
I noticed that in the documentation in [Available models](https://ts.gluon.ai/stable/getting_started/models.html) the links in the column "Implementation" do not work for models with "MXNET" implementation. 

E.g. the link `https://github.com/awslabs/gluon-ts/blob/dev/src/gluonts/model/deepar/_estimator.py` should probably be `https://github.com/awslabs/gluon-ts/blob/dev/src/gluonts/mx/model/deepar/_estimator.py`

## Error message or code output
![image](https://user-images.githubusercontent.com/16029092/186920140-53c7f9c0-8ee7-403c-a267-0793fe19f760.png)

**Comment by lostella** [comment]
@shagn thanks! We actually already fixed this, see #2211, but forgot to backport it, will do it now. Thanks again!

**Comment by lostella** [comment]
Works now
