### ISSUE TITLE
How to use early_stopping_patience with deepAr? Also, some questions about the hyperparameters in the documentation

### ISSUE THREAD

**Issue by Msaleh87** [awslabs/gluon-ts#2260]
### Discussed in https://github.com/awslabs/gluon-ts/discussions/2255

<div type='discussions-op-text'>

<sup>Originally posted by **Msaleh87** August 26, 2022</sup>
So I tried to put early_stopping_patience = 6 in my code and it gave me a keyword error. 

```
estimator = DeepAREstimator(freq = '5min',
                           context_length = 2*24*12,  #The previous data points I look at to predict. It's like n_forecast in Neural Prophet 
                           prediction_length = 1*24*12,
                           num_layers = 2,
                           num_cells = 64,
                           cell_type = 'lstm', 
                           #cardinality = 'auto',
                           scaling = True,
                           use_feat_dynamic_real =True, 
                           early_stopping_patience = 6,  # <-----------
                           trainer = Trainer(epochs= 9, num_batches_per_epoch = 100, hybridize = True )) # increase the number of epochs
```
I have few questions regarding DeepAr parameters, I read this from Amazon: https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_hyperparameters.html
"early_stopping_patience" was mentioned, but didn't say how
What exactly is hybridize = True?
What other cell_type I could use?
what is the difference between batch_size and num_batches_per_epoch?
Can the likelihood impact the actual forecast or only the confidence intervals? How to know which likelihood function to use, or is it based on trial, or are there cues I could look at?</div>

**Comment by mbohlkeschneider** [comment]
Hi @Msaleh87,

Thank you for raising this issue. 

> I have few questions regarding DeepAr parameters, I read this from Amazon: https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_hyperparameters.html
"early_stopping_patience" was mentioned, but didn't say how

This documentation refers to DeepAR in SageMaker as a first-party algorithm, which is a different implementation then the GluonTS DeepAR. Thus, this documentation does not apply to GluonTS. 

Here is a snipped to set the `patience` correctly for early stopping. It is a bit convoluted: 

```
from gluonts.model.deepar import DeepAREstimator
from gluonts.mx.trainer import Trainer
from gluonts.mx.trainer.learning_rate_scheduler import LearningRateReduction

learning_rate = 0.001

scheduler = LearningRateReduction(patience=20, base_lr=learning_rate, objective='min')
trainer = Trainer(learning_rate=learning_rate, callbacks=[scheduler])
est = DeepAREstimator(freq='H', prediction_length=1, trainer=trainer)
```

> What exactly is hybridize = True?

`hybridize=True` compiles the computation graph and runs the code in symbolic mode. You only need to ever switch this off for debugging purposes. 

> What other cell_type I could use?

Here are the available cell types: https://github.com/awslabs/gluon-ts/blob/dev/src/gluonts/mx/model/deepar/_estimator.py#L93

> what is the difference between batch_size and num_batches_per_epoch?

`batch_size` is the size of the batch and `num_batches_per_epoch` are the number of batches that are drawn for one epoch. Note that GluonTS does not use the standard notion of an epoch that is cycling to all data once but instead has a defined number of batches drawn. 

> Can the likelihood impact the actual forecast or only the confidence intervals? How to know which likelihood function to use, or is it based on trial, or are there cues I could look at?

You might decide from your data. For example, if you have count data you might want to use negative binomial. Other than that, it is trial and error.

**Comment by mbohlkeschneider** [comment]
Closed. Please refer to #2255  for further discussion.

**Comment by Msaleh87** [comment]
Thanks, @mbohlkeschneider, really appreciate your help! 
I am using this documentation: https://ts.gluon.ai/stable/tutorials/forecasting/extended_tutorial.html#Configuring-an-estimator
If you know of any other please let me know.
I have a couple of questions:
When you said, "GluonTS does not use the standard notion of an epoch that is cycling to all data once but instead has a defined number of batches drawn." So what is the best practice when selecting the numbers for those two? Because obviously, if I try to increase the batch_size, the training time will be longer. 
As for the Likelihood, here is what I am working on: comparing different tools/ algorithms to predict the electrical load of an electrical Microgird (a Microgrid, is a miniaturized version of the electric grid, it has solar panels, batteries, and could have other assets as well, and is connected to the main electric grid. It trades electricity with the grid based on the energy prices and could operate independently in case of grid failure). Now for the data-driven Microgrid controller to operate/ optimize the MG operation, cost-wise, it is essential and crucial to have a good accurate forecast of what is going to happen, so that the controller takes the forecast of the 24/48 hours ahead of the electric loads and solar panels and the rest of the resources and decide what would be the best action accordingly. A simple example, is during high prices, relaying as less as possible on the main electric grid and using the solar panels and batteries (or whatever assets it has).
I have been using FbProphet, Neural Prophet, DeepAr and tuning their hyperparameters to compare their forecast.
A sample of the data I have been dealing with is shown in the 2 pics below. I have data from March 2021 --> May 2022 with 1 min resolution, I resample it to 5 min. As you can see the electric load profile in 2021 was a bit noisy, but in 2022, it has more shape. Do you think from looking at these curves I could decide on the Likelihood? 

Another question: Do you think data processing would help the forecast, like a Fast Fourier Transform or rolling average with a specific window? And can any of these data pre-processing techniques be included by a specific command within the estimator?

![Figure 10](https://user-images.githubusercontent.com/42920113/187769768-a3ab50f7-f2ca-49b4-add3-a9653eaecc91.png)
![Figure 11](https://user-images.githubusercontent.com/42920113/187769795-3429e792-b3b3-4dcb-b6db-edd5b3820eb3.png)

Thanks again for your time.
