### ISSUE TITLE
How to deal with time series that is undefined for certain hours of the day? (i.e., points are not missing, they simply don't and cannot exist)

### ISSUE THREAD

**Issue by bfreis** [awslabs/gluon-ts#227]
Hi!

First of all, congratulations on GluonTS, it's an amazing project!

I have used it with a few different problems and it's been pretty useful! I now encountered a situation where I might need some guidance.

I have some 30-min frequency time series that are only defined during business hours. I'm wondering how to deal with these with DeepAR?

Basically, all the time series have values for each of the sixteen 30-min periods between 9am and 5pm. But there are no values outside of that range. It's not that the values are missing — they simply don't make sense outside of those hours.

My questions are:

1) How should I pass the target series data to DeepAR if it is undefined outside of a daily period of time?

- Should I create multiple JSON objects, each one containing the sixteen 30-minute periods for which data exists?

- Or should I just pass `null` for all the 30-min periods that don't exist? My concern here is that somehow DeepAR might interpret that I have missing data that I'd like it to "recover" for me, which is not the case.

2) When generating predictions, what should the context look like? There are 2 cases here:

- Imagine that, at night, I want the predictions for all the sixteen 30-minute periods of the following day. In this case, I could use prediction length = 16, as well as context length = 16, then I pass as context the data for the most recent day: today's sixteen 30-minute periods, and I ask for predictions starting at the following day at 9am. Sounds reasonable, right?

- But what if I'm at the middle of the day and I want predictions for the rest of the day and tomorrow's first half of the day? For example, say it's 1pm, and I have data for 8 30-min periods of today. I imagine I could use that for context to help DeepAR improve its prediction. In this case, the context of 16 periods would be 8 from yesterday between 1pm and 5pm, and 8 from this morning starting at 9am. How should I pass the context data, and how would I request the prediction periods with this "time discontinuity"?

If I understood the docs correctly, my biggest challenge here is related to the automatically defined "derived time features". For question 1, if they didn't exist, I could possibly concatenate all the data I have without even adding "nulls" (since the time series is fully defined — for part of the day). For question 2, I could simply request "the next 16 periods", regardless of the time of the day.

One solution I imagined would be to possibly disable the derived time features, and I could pass them myself as dynamic features. This way, the algorithm could still capture seasonality across multiple time frames (which exists and is strong, from what I can tell from the dataset), and I wouldn't be restricted to the "a day has 24 hours, therefore 48 30-minute periods" issue (that is, "my" day has only 16 30-minute periods for this problem). If I did this, is the "start" time relevant for something?

Any ideas on how to approach such problem?

Thanks a lot!

Bruno

**Comment by mbohlkeschneider** [comment]
Hi Bruno, 

thank you for reaching out to us. 

We currently do not support such a kind of custom "business hours frequency". 

Here are a couple of ideas: 
1. Filling "outside business hours" as missing values. We do mask the loss when we encounter a missing value so they will actually not contribute to the loss. Long stretches of missing values might make trouble, but it is the easiest think to try and I would check that first and see whether you are happy with the performance. One issue could be the context range (as you pointed out correctly), but maybe it would still work. All other aspects of the algorithm (time features and lags) should still do what they are supposed to. I would try that first. 
2. Not passing filler values. This might play better with the context range issue but creates all kinds of problems with the time features - and perhaps even more importantly - with the lags. You can try removing `AddTimeFeatures` [here](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepar/_estimator.py#L214) from the transformation chain. 

Also if you have strong custom features, you should pass them too!

For the lags you could pass an empty list as the `lags_seq` argument to DeepAR. However, especially the lags are usually very important for good performance, so you might lose out on a lot of predictive power when doing this. You can also try to play around with custom lags. 

3. Implement a "discontinuous custom" time frequency That feature could be configurable to define valid time ranges and extracts the correct (defined) lags and features according to the frequency. However, think this is quite a lot of work. 

Hope that helps

**Comment by lostella** [comment]
closing this, feel free to continue the discussion if needed

**Comment by NeoWang9999** [comment]
I have the same issue here. Is there any better way to try?

> Hi Bruno,
> 
> thank you for reaching out to us.
> 
> We currently do not support such a kind of custom "business hours frequency".
> 
> Here are a couple of ideas:
> 
> 1. Filling "outside business hours" as missing values. We do mask the loss when we encounter a missing value so they will actually not contribute to the loss. Long stretches of missing values might make trouble, but it is the easiest think to try and I would check that first and see whether you are happy with the performance. One issue could be the context range (as you pointed out correctly), but maybe it would still work. All other aspects of the algorithm (time features and lags) should still do what they are supposed to. I would try that first.
> 2. Not passing filler values. This might play better with the context range issue but creates all kinds of problems with the time features - and perhaps even more importantly - with the lags. You can try removing `AddTimeFeatures` [here](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepar/_estimator.py#L214) from the transformation chain.
> 
> Also if you have strong custom features, you should pass them too!
> 
> For the lags you could pass an empty list as the `lags_seq` argument to DeepAR. However, especially the lags are usually very important for good performance, so you might lose out on a lot of predictive power when doing this. You can also try to play around with custom lags.
> 
> 3. Implement a "discontinuous custom" time frequency That feature could be configurable to define valid time ranges and extracts the correct (defined) lags and features according to the frequency. However, think this is quite a lot of work.
> 
> Hope that helps
