### ISSUE TITLE
How to subplot (サブプロットのやり方)

### ISSUE THREAD

**Issue by ken-take-it-so-so** [awslabs/gluon-ts#2296]
## Description
Hello.  
This is my first time post in GitHub. I am not familiar with GluonTS.  
I use multivariate dataset and the dimension is 8. I want to plot the probability forecasts(observations, median prediction and prediction interval) in one figure which has 8 subplot.  
However it doesn't work well. I referred to #1264, but still go wrong.  
I would appreciate your cooperation.  
<br/>

(こんにちは．  
今回がGitHubへの初めての投稿になります．GluonTSには慣れていません．  
次元が8であるような多変量データセットを使っています．予測結果(観測値，予測の中央値，予測区間)を8つのサブプロットで一つの図にプロットしたいと考えております．  
しかしうまくいきません．#1264も見てみたのですが，やはりだめです．  
どなたかご教授していただけると嬉しいです．)

## To Reproduce
This is my code. It's different from #1264 slightly.  
(これがコードです．#1264とは少し違います．)

```python
import mxnet as mx
from mxnet import gluon
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json

from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes
from gluonts.dataset.util import to_pandas
from gluonts.model.deepar import DeepAREstimator
from gluonts.mx import Trainer
from gluonts.evaluation import make_evaluation_predictions

def subplot_prob_forecasts(tss, forecasts):
    plot_length=150
    prediction_intervals = (50.0, 90.0)
    legend = ["observations", "median prediction"] + [f"{k}% prediction interval" for k in prediction_intervals][::-1]
    rows = 2
    cols = 4

    for i in range(rows * cols):
        plt.subplot(rows, cols, i+1)
        tss[i][-plot_length:].plot() # plot the time series
        forecasts[i].plot(prediction_intervals=prediction_intervals, color="g")
    plt.show()
    plt.savefig("deepar_exchange2.png")
    plt.clf()
    plt.close()

def main():
    dataset = get_dataset("exchange_rate_nips")

    estimator = DeepAREstimator(
        freq = dataset.metadata.freq,
        prediction_length=dataset.metadata.prediction_length,
        context_length=dataset.metadata.prediction_length,
        trainer=Trainer(epochs=5,
                        learning_rate=1e-3, 
                        num_batches_per_epoch=100,
                        batch_size=64)
    )
    predictor = estimator.train(dataset.train)

    forecast_it, ts_it = make_evaluation_predictions(
        dataset=dataset.test, # test dataset
        predictor=predictor, # predictor
        num_samples=100 # number of sample paths we want for evaluation
    )

    tss = list(ts_it)
    forecasts = list(forecast_it)

    subplot_prob_forecasts(tss, forecasts)

if __name__ == "__main__":
    main()
```

## Error message or code output
The output is here.  I struggle with treating below.  
(出力は以下の通りです．以下の扱いに苦戦しています．)
```
forecasts[i].plot(prediction_intervals=prediction_intervals, color="g")
```

![deepar_exchange2](https://user-images.githubusercontent.com/109563059/189829767-ae0fcca2-89ff-4216-a4a8-21b3ab1cdeac.png)

**Comment by dai-ichiro** [comment]
Can you tell me a little more about exchange_rate_nips dataset?
Dataset for train has 8 time series but dataset for test has 40 time series.
So, len(tss) or len(forecasts) returns 40.

**Comment by ken-take-it-so-so** [comment]
@dai-ichiro, thank you for your response !  
I think below page(Datasets, Provided datasets) explains the source of the dataset.  GruonTS prepares many datasets and exchange_rate_nips is the one of them.  
[Quick Start Tutorial](https://ts.gluon.ai/stable/tutorials/forecasting/quick_start_tutorial.html)  
I want to answer your question using two pictures.  
<br/>
(@dai-ichiro さん，ご返信ありがとうございます！  
以下のページ(Datasets, Provided datasets)に，そのデータセットの由来が書いてあると思います．GluonTSはたくさんのデータセットを用意していて，exchange_rate_nipsはそのうちの一つです．  
[Quick Start Tutorial](https://ts.gluon.ai/stable/tutorials/forecasting/quick_start_tutorial.html)   
あなたの質問に，2つの画像を使ってお答えしたいと思います．)
![how_to_subplot1](https://user-images.githubusercontent.com/109563059/190020391-aaf87981-39ea-45f7-b5f3-38c0d7edc3b9.png)
![how_to_subplot2](https://user-images.githubusercontent.com/109563059/190021228-043a6a84-ae56-46e6-a532-0bc19bff810d.png)

It's sufficient to plot the first 8 time series.  
I hope you can understand what I mean.  
<br/>
(最初の8つの時系列をプロットするので十分です．  
私の言おうとしていることが伝わることを願っています．)

**Comment by dai-ichiro** [comment]
Thank you, [ken-take-it-so-so](https://github.com/ken-take-it-so-so).

Try this script.

```
tss = list(ts_it)
forecasts = list(forecast_it)

prediction_intervals = (50.0, 90.0)
legend = ["observations", "median prediction"] + [f"{k}% prediction interval" for k in prediction_intervals][::-1]
rows = 2
cols = 4

plot_length = 150

for i in range(rows * cols):
    plt.subplot(rows, cols, i+1)
    tss[i][0][-plot_length:].plot()  # <=modified only this line
    forecasts[i].plot(prediction_intervals=prediction_intervals, color="g")

plt.show()
```

Hope this helps.

**Comment by ken-take-it-so-so** [comment]
It worked well !!  
I really appreciate you ! I'm happy that my first chat partner is you.  
This is the successful plot.(Size change, space change and legend are made.)
![deepar_exchange2](https://user-images.githubusercontent.com/109563059/190096296-33b4916f-1d9a-42eb-9e01-f5448e4e1a2e.png)

Best regards,
