### ISSUE TITLE
hyperparameters for results

### ISSUE THREAD

**Issue by zhykoties** [awslabs/gluon-ts#231]
Hello, can you release a list of hyperparameters that are used to achieve the performance listed here?

https://github.com/awslabs/gluon-ts/tree/master/evaluations/electricity

**Comment by geoalgo** [comment]
All models are run with default hyperparameters.

From https://github.com/awslabs/gluon-ts/tree/master/evaluations:

> Also models are run with default parameters, they should only require as parameters the time frequency of the data and the number of prediction steps needed. All others should be fixed or adapted automatically to the data.
