### ISSUE TITLE
Access denied to API docs in ts.gluon.ai

### ISSUE THREAD

**Issue by cserpell** [awslabs/gluon-ts#2327]
## Description

When looking at doc web pages, sometimes API link does not appear, and when it does, the web page (located `https://ts.gluon.ai/stable/api/gluonts/gluonts.html`) gives the following error message:

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>G54YF75DFD5TJSYD</RequestId>
  <HostId>
    UHpBCvh7JJKKG1dn3+EoAiITMppAs03eO4PDD1MOTilUbCUiQYq+EYDhNs9Q19ocAB9/VaDrR3c=
  </HostId>
</Error>
```

## To Reproduce

Just go to `https://ts.gluon.ai/stable/`, then the API link does not appear at the left list. Then click at "Background", then it does. Then click "API Docs".

## Error message or code output

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>G54YF75DFD5TJSYD</RequestId>
  <HostId>
    UHpBCvh7JJKKG1dn3+EoAiITMppAs03eO4PDD1MOTilUbCUiQYq+EYDhNs9Q19ocAB9/VaDrR3c=
  </HostId>
</Error>
```

## Environment

- Firefox 105.0.1.
- Ubuntu 22.04.1.

**Comment by lostella** [comment]
Woops, an undesired change slipped in I believe, fixing it in #2328

**Comment by lostella** [comment]
Fixed
