### ISSUE TITLE
Produce Json-compliant results in serve (Nan)

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#234]
When the forecast contain NaN values, Python's `json` library encodes this as `Nan` and not as a the string `"Nan"`. This is not compliant to the json spec and some parsers don't know how to handle these values.

**Comment by lostella** [comment]
When does it make sense to have NaN in forecasts?

**Comment by jaheba** [comment]
Good question, but I didn't want to rule it out generally.

With that said, ETS seems to produce NaN results under some circumstances, so I at least want to give algorithms the option to emit these.
