### ISSUE TITLE
Unable to load Dominick dataset

### ISSUE THREAD

**Issue by haskarb** [awslabs/gluon-ts#2355]
## Description
(A clear and concise description of what the bug is.)
![Screenshot 2022-10-10 at 15 59 08](https://user-images.githubusercontent.com/20501023/194883529-a032d8eb-f1c8-457c-9893-9b9d848ee4dc.png)

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)

```python
from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes
get_dataset('dominick')
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
FileNotFoundError
```

## Environment
- Operating system: macOS Monterey
- Python version: 3.9.6
- GluonTS version: dev
- MXNet version:1.9.1

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
I'm getting a different error:

```python
>>> dataset = get_dataset('dominick', regenerate=True)
ValueError: Cannot obtain default prediction length from frequency `W-SUN`.
```

**Comment by haskarb** [comment]
Yep, that is what Sigrid got. Maybe some issue with Mxnet.

**Comment by lostella** [comment]
I think if you add `regenerate=True` you will run into the same issue, for which a fix is welcome :-)

**Comment by haskarb** [comment]
Yep, that's the issue. Alright, I will look into this bug :)
