### ISSUE TITLE
AttributeError when importing DeepAREstimator: module 'mxnet.gluon' has no attribute 'ParameterDict'

### ISSUE THREAD

**Issue by tmbsundar** [awslabs/gluon-ts#2451]
## Description
When importing DeepAREstimator from gluonts, looks like the component.py code checks the mxnet (imported as mx) - mx.gluon and fails with an AttributeError - module 'mxnet.gluon' has no attribute 'ParameterDict'

Machine: Mac M1
Python version: Tried 3.9.12 and 3.8.12
mxnet: compiled from source & installed gluonts with pip 

## To Reproduce
This works: 

```python
from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes
from gluonts.dataset.util import to_pandas
```

This gives error:

```python
from gluonts.mx import DeepAREstimator
from gluonts.mx.model.deepar import DeepAREstimator
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [6], line 2
      1 #from gluonts.mx import DeepAREstimator
----> 2 from gluonts.mx.model.deepar import DeepAREstimator

File ~/gluone/.gluone/lib/python3.8/site-packages/gluonts/mx/__init__.py:28
     25 # Tensor type for HybridBlocks in Gluon
     26 Tensor = typing.Union[mx.nd.NDArray, mx.sym.Symbol]
---> 28 from . import prelude as _
     29 from .batchify import as_in_context, batchify
     30 from .block.scaler import MeanScaler, NOPScaler

File ~/gluone/.gluone/lib/python3.8/site-packages/gluonts/mx/prelude.py:16
      1 # Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License").
   (...)
     13 
     14 # flake8: noqa: F401
---> 16 from .component import *
     17 from .serde import *
     18 from .model.forecast_generator import *

File ~/gluone/.gluone/lib/python3.8/site-packages/gluonts/mx/component.py:26
     16 import mxnet as mx
     18 from gluonts.core.component import (
     19     equals,
     20     equals_default_impl,
     21     skip_encoding,
     22     tensor_to_numpy,
     23 )
---> 26 @equals.register(mx.gluon.ParameterDict)
     27 def equals_parameter_dict(
     28     this: mx.gluon.ParameterDict, that: mx.gluon.ParameterDict
     29 ) -> bool:
     30     """
     31     Structural equality check between two :class:`~mxnet.gluon.ParameterDict`
     32     objects.
   (...)
     60         Dispatching function.
     61     """
     62     if type(this) != type(that):

AttributeError: module 'mxnet.gluon' has no attribute 'ParameterDict'

```

## Environment
- Operating system: Mac OS Monterey 12.6
- Python version: 3.8.12 or 3.9.12
- GluonTS version: 0.11.2
- MXNet version: Built from source following instructions here: https://mxnet.apache.org/versions/1.9.1/get_started/osx_setup.html
The version installed is 2.0.0

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@tmbsundar gluonts is not compatible with mxnet 2.0, please downgrade to 1.9 and everything should be working fine

**Comment by tmbsundar** [comment]
Thanks @lostella.

I downgraded to MXNet 1.9.1 with Python 3.7.13 combination (not sure the latter matters.- but that is from the official Docker Container working combination.). Seems to be working now. Will update if there are any other issues further.
