### ISSUE TITLE
Integrating N-Linear and D-Linear

### ISSUE THREAD

**Issue by baniasbaabe** [awslabs/gluon-ts#2516]
Are there any plans to integrate those models as proposed in 

Zeng, A., Chen, M., Zhang, L., & Xu, Q. (2022). Are Transformers Effective for Time Series Forecasting?. arXiv preprint arXiv:2205.13504.

Darts already implemented them. These models are also probabilistic.

https://unit8co.github.io/darts/generated_api/darts.models.forecasting.dlinear.html#r844e17822ca3-1

**Comment by kashif** [comment]
see PR #2748
