### ISSUE TITLE
Wrong splitting when generating rolling datasets on multivariate DataFrame

### ISSUE THREAD

**Issue by BEbillionaireUSD** [awslabs/gluon-ts#2528]
## Description
When calling `generate_rolling_dataset` on a multivariate dataset (`dataset = PandasDataset(dict(df_wide))`), it will generates some time series with different lengths in rolled (`rolled = generate_rolling_dataset(dataset=dataset, strategy = StepStrategy(prediction_length=1`). Let the lengths be `[5, 6, 7, 8, 9]` and the target dim (i.e., the number of variates) be 3 for simplicity.

If I use `MultivariateGrouper` on the rolled, it will split the rolled into several ``data entries`` (in `multivariate_grouper`). We hope that series in each ``data entry`` share the same length, where series in different ``data entries`` have different lengths.
Which means, hopefully, we will have five data entries (with length of 5, 6, 7, 8, 9) and each entry contains three (corresponding to the variate number) time series. We denote this as: (5,5,5), (6,6,6),..., (9,9,9)

However, the series in each data entry have different lengths, like (5,6,7),(5,7,8),(5,7,9)...., meaning that these series are not assigned as we hope.

## To Reproduce
df_wide = 
$\quad\quad \quad$ || series 1 || series2
2000-01-01 || 0 || 1
2000-01-02 || 0 || 1
2000-01-03 || 0 || 1
2000-01-05 || 1 || 0
...
2000-01-09 || 1 || 0

```python
dataset = PandasDataset(dict(df_wide))
rolled = generate_rolling_dataset(dataset=dataset, strategy = StepStrategy(prediction_length=2),start_time="2000-01-04")

test_grouper = MultivariateGrouper(num_test_dates=5, max_target_dim=2)
dataset_test = test_grouper(rolled)
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py:197: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return {FieldName.TARGET: np.array([funcs(data) for data in dataset])}
Traceback (most recent call last):
......
  File "/home/cheryl/workspace/diff/Ongoing/dataload.py", line 80, in for_pred
    dataset_test = test_grouper(rolled)
  File "/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py", line 87, in __call__
    return self._group_all(dataset)
  File "/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py", line 125, in _group_all
    grouped_dataset = self._prepare_test_data(dataset)
  File "/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py", line 162, in _prepare_test_data
    list(dataset_at_test_date), dtype=np.float32
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (21,) + inhomogeneous part.
```

## Environment
- Operating system: Linux Ubuntu
- Python version: 3.7
- GluonTS version: 0.10.0
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@cherylLbt two things to note:
* `generate_rolling_dataset` has been removed in favor of new data splitting functionality, see https://ts.gluon.ai/stable/tutorials/data_manipulation/dataset_splitting_example.html
* `MultivariateGrouper` is there join together univariate series into a single multivariate one, and can be used for multivariate time series modeling. Applying it on top of the "rolling" series that I understand you want to generate seems strange: what are you trying to do?

**Comment by BEbillionaireUSD** [comment]
> 

@lostella Thanks for the reply. I have a multivariate time series and want to make many-to-many predictions on it at each time step (rolling predictions). 

For example, given the MTS data from 2020-01-01 to 2020-01-10, I want to predict the data on 2021-01-11; Then, given the MTS data from 2020-01-02 to 2020-01-11, I want to predict the data on 2021-01-12. The predictions should be multi-variate.

**Comment by Tonyvariety** [comment]
> ## Description
> When calling `generate_rolling_dataset` on a multivariate dataset (`dataset = PandasDataset(dict(df_wide))`), it will generates some time series with different lengths in rolled (`rolled = generate_rolling_dataset(dataset=dataset, strategy = StepStrategy(prediction_length=1`). Let the lengths be `[5, 6, 7, 8, 9]` and the target dim (i.e., the number of variates) be 3 for simplicity.
> 
> If I use `MultivariateGrouper` on the rolled, it will split the rolled into several `data entries` (in `multivariate_grouper`). We hope that series in each `data entry` share the same length, where series in different `data entries` have different lengths. Which means, hopefully, we will have five data entries (with length of 5, 6, 7, 8, 9) and each entry contains three (corresponding to the variate number) time series. We denote this as: (5,5,5), (6,6,6),..., (9,9,9)
> 
> However, the series in each data entry have different lengths, like (5,6,7),(5,7,8),(5,7,9)...., meaning that these series are not assigned as we hope.
> 
> ## To Reproduce
> df_wide = || series 1 || series2 2000-01-01 || 0 || 1 2000-01-02 || 0 || 1 2000-01-03 || 0 || 1 2000-01-05 || 1 || 0 ... 2000-01-09 || 1 || 0
> 
> ```python
> dataset = PandasDataset(dict(df_wide))
> rolled = generate_rolling_dataset(dataset=dataset, strategy = StepStrategy(prediction_length=2),start_time="2000-01-04")
> 
> test_grouper = MultivariateGrouper(num_test_dates=5, max_target_dim=2)
> dataset_test = test_grouper(rolled)
> ```
> 
> ## Error message or code output
> (Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)
> 
> ```
> /home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py:197: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
>   return {FieldName.TARGET: np.array([funcs(data) for data in dataset])}
> Traceback (most recent call last):
> ......
>   File "/home/cheryl/workspace/diff/Ongoing/dataload.py", line 80, in for_pred
>     dataset_test = test_grouper(rolled)
>   File "/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py", line 87, in __call__
>     return self._group_all(dataset)
>   File "/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py", line 125, in _group_all
>     grouped_dataset = self._prepare_test_data(dataset)
>   File "/home/cheryl/anaconda3/envs/diff/lib/python3.7/site-packages/gluonts/dataset/multivariate_grouper.py", line 162, in _prepare_test_data
>     list(dataset_at_test_date), dtype=np.float32
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (21,) + inhomogeneous part.
> ```
> 
> ## Environment
> * Operating system: Linux Ubuntu
> * Python version: 3.7
> * GluonTS version: 0.10.0
> * MXNet version:
> 
> (Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by mtomic123** [comment]
@lostella 

I split data as per your link, however it is still unclear how to backtest the whole dataset.
I trained a `DeepVAR `model with `prediction_length=24` and then did the following:

```
prediction_length = 24
training_dataset, test_template = split(
    df, date=pd.Period("2022-09-01 07:00:00", freq="1H")
)
test_pairs = test_template.generate_instances(
    prediction_length=prediction_length,
    windows=3,
)
```

and then wanted to use `backtest_metrics`, however it is unclear how to use in this case.
I passed a manually created `ds_test `  dataset into:

`backtest_metrics(test_dataset=ds_test, predictor=predictor, evaluator=MultivariateEvaluator())`

however it computed metrics only for the last 24 rows as my prediction_length=24.

What we want are rolling predictions for the whole dataset.

**Comment by BEbillionaireUSD** [comment]
> @cherylLbt two things to note:
> 
> * `generate_rolling_dataset` has been removed in favor of new data splitting functionality, see https://ts.gluon.ai/stable/tutorials/data_manipulation/dataset_splitting_example.html
> * `MultivariateGrouper` is there join together univariate series into a single multivariate one, and can be used for multivariate time series modeling. Applying it on top of the "rolling" series that I understand you want to generate seems strange: what are you trying to do?

I believe the previous issue is caused by my misunderstanding of the functions. I have achieved the rolling prediction via ListDataset. I'll close this issue.

**Comment by JasonZhou8686** [comment]
@BEbillionaireUSD How did you achieve the rolling prediction via ListDataset? can you show me how to do it? Thanks in advance
