### ISSUE TITLE
LICENSE and NOTICE files missing in source distribution on PyPI

### ISSUE THREAD

**Issue by giswqs** [awslabs/gluon-ts#2564]
I am trying to add gluonts to conda-forge and noticed that the LICENSE and NOTICE are not included in the [source distribution](https://pypi.org/project/gluonts/#files) on PyPI. It would be great to add these two files in the next release. 

https://github.com/conda-forge/staged-recipes/pull/21722#issuecomment-1382576584

**Comment by arturdaraujo** [comment]
This would be great! I upvote this feature 100%!

**Comment by jaheba** [comment]
Hi, thanks for raising the issue and thanks for contributing gluonts to conda!

This is still pending release, but I think we just do that over the coming days.
