### ISSUE TITLE
gluonts.core.components.py does not have Dtype function, it is being used in other library function

### ISSUE THREAD

**Issue by dipti-gupta-2105** [awslabs/gluon-ts#2575]
## Description
(A clear and concise description of what the bug is.)

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)

```python
put code here
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
put error or undesired output here
```

## Environment
- Operating system:
- Python version:
- GluonTS version:
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@dipti-gupta-2105 hi, is this a bug or a feature request? could you be more specific what the problem is?

**Comment by dipti-gupta-2105** [comment]
Thanks @lostella for your quick response!!
I was looking for an older version actually but I can manage with new version, we  can close the issue.
