### ISSUE TITLE
Expose NBEATSEnsemble aggregation_method and wrong dimensions

### ISSUE THREAD

**Issue by gorold** [awslabs/gluon-ts#2592]
## Description
(A clear and concise description of what the bug is.)
1. NBEATSEnsemblePredictor has the option of selecting aggregation_method, but it is not exposed to the estimator class. This means that there is no natural way of selecting this parameter. It is possible to interpret the forecasts from the ensemble as samples, and calculate the quantiles from an ensemble. This parameter should be exposed to the estimator class.
2. Manually selecting the aggregation_method="none" still leads to a bug, wrong dimension size for SampleForecast. The bug fails silently when evaluated with the Evaluator class, and leads to erroneous metrics.

https://github.com/awslabs/gluonts/blob/784a882b16fc7704e346cb46cbeb33891b565b99/src/gluonts/mx/model/n_beats/_ensemble.py#L171-L196
Issue should be from here, where  output is shape (N, 1, T)

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)

```python
from gluonts.mx import NBEATSEnsembleEstimator, NBEATSEnsemblePredictor
from gluonts.dataset.repository.datasets import get_dataset

dataset = get_dataset("airpassengers")

training_data, test_gen = split(dataset.train, offset=-36)
model = NBEATSEnsembleEstimator(
    prediction_length=12, freq="M", 
    meta_context_length=[2], meta_bagging_size=1,
    trainer=Trainer(epochs=1)
).train(training_data)

predictor = NBEATSEnsemblePredictor(12, model.predictors, "none")
test_data = test_gen.generate_instances(12)
forecast_it = predictor.predict(test_data.input)
forecast = next(forecast_it)

print(forecast.samples.shape)
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
(3, 1, 12)
```

Desired dimensionality should be (3, 12)

## Environment
- Operating system:
- Python version:
- GluonTS version: 0.11.6
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@gorold both points make perfect sense, thank you. A fix is ready in #2598, do you want to take a look?
