### ISSUE TITLE
An error in the Extended Forecasting Tutorial

### ISSUE THREAD

**Issue by MajorDavidZhang** [awslabs/gluon-ts#260]
In the extended forecasting tutorial, it says "feat_dynamic_real: dynamic (over time) real features, array with shape equal to (target length, number of features)". But when I use the DeepAREstimator, I discover that the shape of the feat_dynamic_real should be (number of features, target length).
Link to the Extended Forecasting Tutorial
[https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html](url)

**Comment by lostella** [comment]
@MajorDavidZhang Thanks for reporting this, that (as well as the previous line) indeed looks like a mistake in the text. Will update it very soon.
