### ISSUE TITLE
Off-by-one bug in PyTorch DeepAR implementation

### ISSUE THREAD

**Issue by gorold** [awslabs/gluon-ts#2616]
## Description
(A clear and concise description of what the bug is.)

Please correct me if I'm wrong, but there might be an off by 1 error in the below code snippet. What should happen is that ```time_feat``` at time step **t** should be concatenated with ```target``` at time step **t-1.** But because lags is taken as the input without concatenating the target itself, what is happening is that ```time_feat``` **t+1** is concatenated with ```target``` **t-1**.

https://github.com/awslabs/gluonts/blob/60e1767d80e1d5b932d5e94cc2b51439a970dca9/src/gluonts/torch/model/deepar/module.py#L267-L283

I think the below change should be made? 

```python
 time_feat = ( 
     torch.cat( 
         ( 
             past_time_feat[..., -self.context_length :, :], 
             future_time_feat, 
         ), 
         dim=-2, 
     ) 
     if future_time_feat is not None 
     else past_time_feat[..., -self.context_length :, :] 
 ) 
```

**Comment by gorold** [comment]
Sorry I misunderstood the lagged_sequence_values function

**Comment by lostella** [comment]
Hi @gorold I think you're right, thanks for the deep dive! This suggests the `Module` class could use some refactoring and added testing.

How I reproduced it:

```python
import torch

from gluonts.torch.model.deepar import DeepARModel

model = DeepARModel(
    freq="D",
    context_length=5,
    prediction_length=2,
    lags_seq=[1, 2, 7],
    scaling=False,
)

# the following batch conforms with `model.input_shapes()` and `model.input_types()`
batch = {
    "feat_static_cat": torch.tensor([[0]], dtype=torch.int64),
    "feat_static_real": torch.tensor([[0.0]], dtype=torch.float32),
    "past_time_feat": torch.arange(12, dtype=torch.float32).unsqueeze(0).unsqueeze(-1),
    "past_target": torch.arange(12, dtype=torch.float32).unsqueeze(0),
    "past_observed_values": torch.arange(12, dtype=torch.float32).unsqueeze(0),
    "future_time_feat": torch.arange(12, 14, dtype=torch.float32).unsqueeze(0).unsqueeze(-1),
}

model(**batch)
```

and putting a break-point to inspect the values of `lags` and `features`. Since `past_target` and `past_time_features` have the same value, the lag values should differ by `1`, `2,` and `7`, respectively, from the last channel in `features`. But I get instead

```
lags[0, :, 0] == tensor([ 6.,  7.,  8.,  9., 10.])
lags[0, :, 1] == tensor([5., 6., 7., 8., 9.])
lags[0, :, 2] == tensor([0., 1., 2., 3., 4.])
features[0, :, -1] == tensor([ 8.,  9., 10., 11., 12.], grad_fn=<SelectBackward0>)
```

i.e. they differ by `2`, `3,` and `8` instead.

**Comment by lostella** [comment]
In practice, this may not be a big issue as far as "calendar" features are concerned, since they are cyclic anyways, but it may be more serious in case custom features are provided like indicators that are meant to have specific impact on the prediction.
