### ISSUE TITLE
Remove "dataclasses" from requirements. 

### ISSUE THREAD

**Issue by melanopsis** [awslabs/gluon-ts#2622]
Gluonts requires the "dataclasses" package which conflicts with Python's built-in dataclasses module on systems with Python > 3.6.

**Comment by lostella** [comment]
@melanopsis since #2542, Python 3.7+ is required. So this should be doable. Do you want to open a PR?

**Comment by melanopsis** [comment]
@lostella I wish I could but I'm not a user of this package. It was reported as an issue on the platform that I maintain.

**Comment by melanopsis** [comment]
@lostella I'm sorry, I didn't realize you were just asking for the removal of the dependency as PR.  I thought some other changes would be required to drop "dataclasses". Thank you for prompt action. Any chance of a point release soon?

**Comment by lostella** [comment]
No worries at all! Yes, I think we'll issue a bugfix release soon, if not even today
