### ISSUE TITLE
Support optional inputs for models

### ISSUE THREAD

**Issue by gorold** [awslabs/gluon-ts#2624]
## Description
(A clear and concise description of what the feature is.)
GluonTS currently does not support optional inputs. 
The current paradigm is that if a model has optional inputs, the estimator class needs to define a transformation to include dummy values. However, it would be preferable to completely skip the processing of the unavailable inputs, rather than processing some additional dummy values:

```python
def forward(
    self, 
    past_target,  
    past_time_feat, 
    future_time_feat,
    feat_static_cat = None,  # optional
    feat_static_real = None  # optional
):
    if feat_static_cat is not None:
        ...
    if feat_static_real is not None:
        ...
```

Currently GluonTS does not really support this paradigm even if the model handles this logic. For example, because of how 
ForecastGenerators are defined, the below definition for ```create_predictor``` causes issues. 
https://github.com/awslabs/gluonts/blob/66a129ec258ad8f9ea087ec02c145cc37f5713b1/src/gluonts/model/forecast_generator.py#L155

```python
def create_predictor(
    self,
    transformation,
    module
):
    ...
    return PyTorchPredictor(
        input_names=["past_target", "past_time_feat", "future_time_feat", "feat_static_real"]
        ...
    )
```

Namely, because a list is fed into the model, ```feat_static_real``` is treated as ```feat_static_cat```. We can easily fix this by ```inputs = {k: batch[k] for k in input_names}``` and editing ```predict_to_numpy``` accordingly. However, I am not too sure whether there are any other parts of the library which would fail if this change is made.

## References
- list reference and related literature
- list known implementations

**Comment by jaheba** [comment]
Hi @gorold,

I like the suggestion! I was looking into something similar recently, but mxnet does not allow to pass values by name but uses positional arguments instead...

I think we can make it work with another layer of abstraction for mxnet which invokes the model with positional arguments. 

Afaik, ONNX also wants named arguments when invoking their models so another reason for doing this. 

On another note, ForecastGenerator should hopefully be not needed too much longer.
