### ISSUE TITLE
Loading datasets requires very deep imports

### ISSUE THREAD

**Issue by abdulfatir** [awslabs/gluon-ts#2636]
## Description

Currently, loading datasets from the dataset repository requires the following import:
```
from gluonts.dataset.repository.datasets import get_dataset
```
IMO the import is too "deep". The `.datasets` after `repository` is redundant. We can either move the code in `src/gluonts/dataset/repository/datasets.py` to `src/gluonts/dataset/repository/__init__.py` or import relevant functions in `__init__.py`. 

cc @jaheba @lostella

**Comment by jaheba** [comment]
I want to rework and move the dataset repository to `gluonts.labs`. That's one reason why we haven't touched that yet.

**Comment by lostella** [comment]
Let's break this in 0.13 then

**Comment by lostella** [comment]
See also #1196, #2012
