### ISSUE TITLE
Getting empty ds using function PandasDataset.from_long_dataframe

### ISSUE THREAD

**Issue by iamyihwa** [awslabs/gluon-ts#2677]
## Description
I was following examples from [here](https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html), when I am trying to load long pandas dataframe, using the function PandasDataset.from_long_dataframe(), it gives empty result. 

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)
<img width="124" alt="image" src="https://user-images.githubusercontent.com/12494156/220125843-98b7f274-37b3-4a8a-af74-854209b3e0af.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/12494156/220126064-2fa9b7eb-cdd9-43eb-94fe-971a26271368.png">

```
from gluonts.dataset.pandas import PandasDataset

ds = PandasDataset.from_long_dataframe(cur_df, target="target", item_id="item_id")
ds
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
put error or undesired output here
```

## Environment
- Operating system: Linux
- Python version: 3.8.10
- GluonTS version: 0.12.2
- MXNet version:1.9.1

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@iamyihwa to check if it's empty, you can do

```python
len(ds)
```

or just iterate the dataset and print its entries

```python
for entry in ds:
    print(entry)
```

**Comment by lostella** [comment]
To display a summary of the dataset, please do

```python
print(ds)
```

**Comment by iamyihwa** [comment]
Thanks @lostella !
