### ISSUE TITLE
KeyError: 'feat_static_cat' with 

### ISSUE THREAD

**Issue by runesuhr** [awslabs/gluon-ts#2678]
I get a bug when trying to run the deepar estimator with the (as i understand new) system of specifying static categorical features in pd dataframe with one row per time series.

I configure the data set as:

```python
gluonts_val_pre_covid = PandasDataset(
    validation_pre_covid,
    timestamp = "timestamp",
    target=data_parameters['target'],
    static_features = pre_covid_static_cols,
    freq= data_parameters['frequency']
)
```

with validation_pre_covid a dictionary of pd dataframes, and pre_covid_static_cols a pd dataframe with the same number of rows as the number of keys in the validation_pre_covid dictionary.

The DeepAr estimator is configured as:

```python
estimator_with_features = DeepAREstimator(
    freq=data_parameters['frequency'],
    prediction_length=data_parameters['forecast_length'],
    use_feat_static_cat=True,
    cardinality=[values for key, values in cardinalities_dict.items()],
    trainer=Trainer(epochs=10),
)
```

but running:

```python
predictor = estimator_with_features.train(gluonts_val_pre_covid)
```

yields:

```
KeyError: 'feat_static_cat'.
```

I'm just trying to follow the framework in the tutorial https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html, but it doesn't seem to work :(

**Comment by lostella** [comment]
@runesuhr could you try running

```python
print(gluonts_val_pre_covid)
```

and post the output?

**Comment by runesuhr** [comment]
PandasDataset<size=3289, freq=M, num_feat_dynamic_real=0, num_past_feat_dynamic_real=0, num_feat_static_real=5, num_feat_static_cat=0, static_cardinalities=[]>

i smell that there's an issue here, but i'm not quite sure how.

**Comment by lostella** [comment]
You're getting 5 static real features. Probably all columns of `pre_covid_static_cols` are numeric. You can check it with

```python
pre_covid_static_cols.dtypes
```

If you check out the example at https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html#Include-static-and-dynamic-features, some of the columns of the static features data frame are constructed with `pd.Categorical`. You can also set a column to be categorical with

```python
pre_covid_static_cols[name] = pre_covid_static_cols[name].astype("category")
```

**Comment by runesuhr** [comment]
Ah, thanks a lot! I will try this. (It's late evening here, so I don't have time to run it today, I posted the question at this time as I didn't really expect such a quick answer. MUCH appreciated!)

**Comment by lostella** [comment]
@runesuhr any news? Feel free to close the issue if the above suggestion does the trick, otherwise we can look into it further

**Comment by runesuhr** [comment]
Yes, it worked, thank you very much for the help!
