### ISSUE TITLE
Change pandas requirement to allow pandas==2.0.0

### ISSUE THREAD

**Issue by aiwalter** [awslabs/gluon-ts#2706]
## Description
New `pandas==2.0.0` is about to come this March, `2.0.0rc0` already available. I have seen the `gluonts` is currently not compatible with that. When are you planning to bump the requirement `pandas~=1.0` https://github.com/awslabs/gluonts/blob/1a117ef90479b5d86bfba9e84add081c2e9db414/requirements/requirements.txt#L2

## References
- https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html
- https://github.com/scikit-time/scikit-time/pull/153

**Comment by jaheba** [comment]
Hi Martin,

I think there is nothing preventing us from using pandas 2.0 -- from a quick glimpse at the release notes there are not many breaking changes.

For what it's worth, we are working on removing pandas as a core dependency and only have it as an optional dependency for things like `PandasDataset`.

**Comment by aiwalter** [comment]
great, would appreciate this in next release. Soft-dependency sounds also a very good idea, but just bumping the upper bound would already satisfy me for now :)

**Comment by lostella** [comment]
Fixed in #2710, #2713
