### ISSUE TITLE
DeepRenewalProcess with multiple variables

### ISSUE THREAD

**Issue by baniasbaabe** [awslabs/gluon-ts#2717]
## Description
I looked into the Code of DeepRenewalProcess and when I‘m correct, it can‘t take multiple features. I saw an custom implementation of Manu Joseph for this particular Model in gluonts with mxnet.

## References
- https://github.com/manujosephv/deeprenewalprocess

**Comment by melopeo** [comment]
Hi @baniasbaabe,

thanks for this request. @canerturkmen , @lovvge , @timoschowski are experts in this model. Maybe they can give a quick check on this.

**Comment by canerturkmen** [comment]
Hi @baniasbaabe thanks for the question. I was not aware Manu Joseph's version included time series features, but if so, I would recommend using that. Neither the paper nor the code in GluonTS considers time series features.
