### ISSUE TITLE
Documentation for Rotbaum Package

### ISSUE THREAD

**Issue by baniasbaabe** [awslabs/gluon-ts#2723]
## Description
I guess there are no documentation available for the Rotbaum package. Maybe it would be helpful to include some :)

## References
-Empty documentation page https://ts.gluon.ai/stable/api/gluonts/gluonts.ext.rotbaum.html?highlight=rotbaum

**Comment by jaheba** [comment]
Thanks for raising the issue. It looks like we did not install the dependencies in our docs build, which is now fixed on `dev`:

https://ts.gluon.ai/dev/api/gluonts/gluonts.ext.rotbaum.html
