### ISSUE TITLE
Retraining a saved GluonTS model

### ISSUE THREAD

**Issue by Hari7696** [awslabs/gluon-ts#273]
After deserializing the saved GluonTS model, I am unable to retrain it on the new data. Is there a way to do retraining instead of training it over all the data again.

**Comment by lostella** [comment]
Hi, I agree that would be a nice feature to have. Is this the same as #272?

**Comment by Hari7696** [comment]
Yes

**Comment by lostella** [comment]
Ok, I'll close this to keep the avoid spreading the discussion in multiple places. Thank!
