### ISSUE TITLE
Error in definition of coverage metric?

### ISSUE THREAD

**Issue by dwolffram** [awslabs/gluon-ts#2736]
## Description
I'm wondering why there is a strict inequality in the definition of the (quantile) coverage (https://github.com/awslabs/gluonts/blob/dev/src/gluonts/evaluation/metrics.py#L84):

`np.mean(target < forecast)`

Shouldn't this be `np.mean(target <= forecast)`? Right now, if you predict 0 and observe 0, it does not count as covered. Or am I missing something?

Thanks!

**Comment by lostella** [comment]
Related: the same definition is used in `gluonts.ev`, see https://github.com/awslabs/gluonts/blob/dev/src/gluonts/ev/stats.py#L50
