### ISSUE TITLE
Handling covariate with different granularity

### ISSUE THREAD

**Issue by davidlkl** [awslabs/gluon-ts#274]
Thank you team for bringing us this awesome library and I have found this is very useful for my problem.

However, there are some covariates that has higher/lower granularity than the target series. For those with lower granularity, I can do aggregation to avoid it. However for those with higher granularity, I am not sure what would be the best approach. I will try a naive approach (equal-splitting) v.s. omitting this covariate.  But it would be great to know if the model can be extended to handle mixed-frequency time series.

**Comment by jaheba** [comment]
Hello @davidlkl,

I'm glad you like gluon-ts!

Sadly, I think this problem is out of scope for gluon-ts. If we were to add this, then I think we would end up with some sort of "smart" averaging and then this could be just done as well as a data preprocessing step.

Hope that answers your question.
