### ISSUE TITLE
Different DeepAR output when deserializing same model depending on presence of a GPU

### ISSUE THREAD

**Issue by pbruneau** [awslabs/gluon-ts#2741]
## Description
Let us consider a DeepAR model learned and serialized on a GPU-equipped machine. This model yields different output when deserialized, depending on whether a GPU is available on the target host.

## To Reproduce
I am refererring to the [code in this gist](https://gist.github.com/pbruneau/5b58bca5f36e4114d38f1e91f1f0f5b8):
- Uncommenting l25
- Running the script on a GPU-equipped host (gluonts==v0.11.7, mxnet-cu112==1.9.1)
- Copying the `temp` folder to an environment without recognized GPU
- Commenting l25
- Running the script on the no-GPU host (gluonts==v0.11.7, mxnet==1.9.1)

## Error message or code output
In my case, on the GPU host, I get the following (repeatable) result:
```
[339.40637 351.20044 379.8592  393.2618  423.4558  482.6555  526.3845  513.7207  448.98022 379.16498 348.40985 373.92563]
```
On the no-GPU host, I get:
```
[338.82394 346.36243 380.36224 390.79517 421.0258  482.7877  529.1254  511.45355 449.05988 382.2138  351.5098  372.49072]
```
Here the difference is moderate, but depending on the dataset and DeepAR parametrization, it can become dramatic... Is there a way to ensure that I get the same results, irrespective of the presence of a GPU on the target host?

Best regards

## Environment
- Operating system: Ubuntu 18.04
- Python version: Tested with 3.6.9 and 3.7.10
- GluonTS version: v0.11.7
- MXNet version: mxnet-cu112==1.9.1 or mxnet==1.9.1 (depending on case above)

**Comment by mbohlkeschneider** [comment]
Hi @pbruneau,

I'm not sure whether there is a serialization issue with GPU, so thank you for raising this. However, irrespective of that it is completely the expectation that the model output is *not* exactly the same between to training runs (again, irrespective of the devise you are training on). There are several factors that lead to this (random weight initialization, random sampling etc.). It's not a bug, it's a feature :-). Some methods to increase model stability are model averaging and iterative model averaging which is implemented [here](https://github.com/awslabs/gluonts/blob/dev/src/gluonts/mx/trainer/model_averaging.py=) and [here](https://github.com/awslabs/gluonts/blob/dev/src/gluonts/mx/trainer/model_iteration_averaging.py). 

Hope that helps!

**Comment by pbruneau** [comment]
Hi @mbohlkeschneider,

The point of commenting l25 above is to reuse the same trained model. If I re-run my gist above (with l25 commented, after having run it at least once with l25 uncommented) on a GPU-equipped machine 10 times, I get 10 times the *exactly* same output (let's say A), to the 5th digit at least. If I run it on the no-GPU machine (after having collected the model folder), I get 10 times the same result (B), different from A.

I am totally aware of your point, and totally agree, but this was not the point I was trying to raise. I'm just saying that one would expect that the same model, applied on the same data, would yield the same result. Besides ensuring reproducibility, I have cases where the results on the no-GPU host become completely non-sensical (almost only NaN, when the same model outputs perfectly fine results on the GPU-equipped host).

I am aware that forecasts depend on random sampling with DeepAR: however, in the case above, running the example 10 times on the GPU machine led to the same result up to the 5th digit. Similarly, the no-GPU machine outputs the same result 10 times in a row, up to the 5th digit. However, in the example above, you see that differences between A and B range from 0.5 to 5, roughly: you'll agree that 5 orders of magnitude are way beyond statistical significance :)

**Edit**: I've added seeds to the gist just before the `predict` to remove the effect of sampling at prediction time.

**Comment by mbohlkeschneider** [comment]
Hi @pbruneau,

I see, thank you for clarifying. I remember from my early days of parallel programming that often different seeds are initialized on a parallel operating device (talking about compute nodes and C++/MPI here). Might something like this be the issue here? If so, I'm not sure we can fix that (mxnet/pytorch would have to allow us specify this on the devices). 

PyTorch's documentation says: "[Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.](https://pytorch.org/docs/stable/notes/randomness.html)" PyTorch as the backend framework does not seem to provide this. If anyone knows a solution here, I'm happy to learn :-).

**Comment by lostella** [comment]
Related, but for mxnet: https://github.com/apache/mxnet/discussions/7410#discussioncomment-62013

In general, same seed + different devices => different results. @pbruneau for DeepAR this means that predictive samples are drawn starting from different seeds, you could try verifying that increasing the number of samples (from 100 to 1000) reduces the gap between the medians. For that it should be sufficient to do

```
model.predict(test_data.input, num_samples=1000)
```

in your script.

**Comment by lostella** [comment]
@pbruneau the issue your facing comes from the fact that the model is loaded onto the GPU memory if a GPU is detected, and on CPU otherwise (through [this utility](https://github.com/awslabs/gluonts/blob/8380b98aef667caaa39ed6d638883676f0093288/src/gluonts/mx/context.py#L71-L81)).

So another way to fix this is to force loading on CPU with

```
model = Predictor.deserialize(path, ctx="cpu")
```

Then the question is: is "default to loading on GPU if present, and CPU otherwise" the best policy here? For some models it certainly makes sense, although arguably not for RNN-based models.

**Comment by pbruneau** [comment]
Hi @mbohlkeschneider and @lostella, thank you for you answers and comments,

I went throught more thorough experiments, trying to delineate the effect of random sampling from a potential systematic bias due to the presence of a GPU, and could not find any statistically significant evidence. I guess the issue is tied to my specific problem and implementation, but now I know that I don't have to investigate at the level of mxnet, at least. This closes the issue/question, then.

A final note, regarding your comment @lostella:
> Then the question is: is "default to loading on GPU if present, and CPU otherwise" the best policy here? For some models it certainly makes sense, although arguably not for RNN-based models.

In my case, I'm learning the model using a GPU, and deploying on a virtual machine which does not have any. This explains for my setup (GPU first, CPU then).

**Comment by lostella** [comment]
@pbruneau did setting the `ctx="cpu"` in `.deserialize` work?

**Comment by pbruneau** [comment]
> @pbruneau did setting the `ctx="cpu"` in `.deserialize` work?

Yes, this gave the same output as using mxnet==1.9.1 (the non-CUDA version) or running from a non-CUDA container on the same hardware - which is expected, but saved the effort to have two different environments.
