### ISSUE TITLE
Store GluonTS Version with stored Model

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#278]
When we serialise a model, we should also store the current GluonTS version with it.

That way we can track backwards compatible or breaking changes.

**Comment by timoschowski** [comment]
PR https://github.com/awslabs/gluon-ts/pull/388 is a rather minimal answer to the issue. I was thinking whether it makes sense to check it during deserialization, but this didn't lead anywhere.

**Comment by jaheba** [comment]
As a follow-up, we should also read-out the version when we deserialise the model and do some checks on the version.
