### ISSUE TITLE
Plotting intervals do not work

### ISSUE THREAD

**Issue by abdulfatir** [awslabs/gluon-ts#2795]
Tried to go through [Tutorial](https://ts.gluon.ai/stable/tutorials/forecasting/quick_start_tutorial.html#Quick-Start-Tutorial), just copy/pasted code, plot function for SampleForecast entity  doesn't seems to work the way it should. 

![image](https://user-images.githubusercontent.com/59028817/230828945-7dab5775-7fa4-4f70-a663-2466a4eb7b6a.png)

_Originally posted by @ivanvoid in https://github.com/awslabs/gluonts/issues/2333#issuecomment-1501392375_

**Comment by abdulfatir** [comment]
Hi @ivanvoid,

I created a new issue from your comment. Let's discuss this here. 

The plotting issue you mentioned happens sometimes with me as well. As far as I understand, it's due to conflicts between how pandas plotting interacts with `plt.fill_between` when using a datetime index on the x-axis. Can you share your `gluonts`, `matplotlib` (and `seaborn`, if installed), and `pandas` versions?

As a workaround, you can go to [this function](https://github.com/awslabs/gluonts/blob/160a127f64002322586359e2729c7b586acd15fb/src/gluonts/model/forecast.py#L284) in your GluonTS installation and replace all instances of `self.index.to_timestamp()` in the function to `self.index`. This has worked for me in the past and we can merge this as a bug fix.

**Comment by jaheba** [comment]
In the future we ideally would not want to rely on `pandas`.

Another thing to do right with Zebras!

**Comment by abdulfatir** [comment]
Fixed by #2800
