### ISSUE TITLE
Different prediction length using .predict()

### ISSUE THREAD

**Issue by shebanova** [awslabs/gluon-ts#2801]
## Description
I want to produce forecasts with a different prediction length rather than specified as a parameter in a global model using the _.predict()_ method and its parameter _prediction_length_. 
## To Reproduce
For example, I use NBEATSEnsemble and DeepAR models with prediction_length = 20 (NBEATS) and prediction_length=2 (DeepAR) as models' hyperparameters and prediction_length=25 and prediction_length=4 as parameters for the _.predict()_ method.  

```python
history = TrainingHistory()

trainer = Trainer(
    ctx = mx.context.gpu(),
    epochs = 2, 
    learning_rate = 0.001,
    callbacks=[history]
)

estimator = n_beats.NBEATSEnsembleEstimator(
    freq = '1M',
    prediction_length = 20, 
    meta_context_length = [20],
    meta_loss_function = ['MASE'], 
    meta_bagging_size = 10,
    trainer = trainer,
    num_stacks = 2, 
    num_blocks = [3],
    widths = [256, 2048],
    sharing = [True],               
    batch_size = 128,
    expansion_coefficient_lengths = [3],
    stack_types = ['T', 'S'],        
    scale = True
    )

predictor = estimator.train(training_data=train_0)
forecasts = list(predictor.predict(dataset=train_0,
                                   prediction_length=25))
forecasts[0]
_______________________________________________________________
model = DeepAREstimator(
    prediction_length=2, 
    freq="M", trainer=Trainer(epochs=5)).train(train_0)

forecasts_2 = list(model.predict(dataset=train_0, num_samples=1,
                                   prediction_length=4))

forecasts_2[0]

```

## Error message or code output
However, the prediction_length remains unchanged in this case, and it is equal to 20 and 2 data points, as specified in global models' parameters. While I would like the output to be 25 and 4 points forecasts **without retraining the model**. Is that possible?
```
#nbeats forecast output
gluonts.model.forecast.SampleForecast(info=None, item_id='03028542122_4557_0000906082', samples=array([[5.561283 , 5.281584 ,
5.337186 , 5.2696896, 5.2367573, 5.308991 ,
        5.1670456, 5.349546 , 5.6135445, 4.872039 , 5.2462435, 4.9593   ,
        5.1794314, 4.9914875, 4.934436 , 5.01266  , 4.53573  , 4.99087  ,
        4.7765775, 5.384247 ]], dtype=float32), start_date=Period('2021-07', 'M'))

#deepar forecast output
gluonts.model.forecast.SampleForecast(info=None, item_id='03028542122_4557_0000906082', 
samples=array([[3.742881 , 2.9557085]], dtype=float32), start_date=Period('2021-07', 'M'))
```

## Environment
- Python version: 3.8.8
- GluonTS version: 0.12.6
- MXNet version: mxnet-cu114==1.9.1

**Comment by abdulfatir** [comment]
Hi @shebanova!

GluonTS does **not** support custom inference prediction length at the moment. We're discussing about this feature here: #2785. We would be happy to hear your thoughts about this.
