### ISSUE TITLE
Get started: A quick example runs over an hour (80 epochs)

### ISSUE THREAD

**Issue by AaronSpieler** [awslabs/gluon-ts#282]
## Description
The in-browser executable "quick example" found on https://gluon-ts.mxnet.io/ trains over an hour (> 80 epochs).

## To Reproduce
Without any editing click the play button, as instructed on the page.

## Error Message
Run-time stops executing?

<img width="861" alt="image" src="https://user-images.githubusercontent.com/25365592/64241783-a5345580-cf04-11e9-8251-c3f946e8f84d.png">

## Environment
- Operating system: Linux
- Python version: 3.7.4
- GluonTS version: 0.3.3

Additionally, in the beginning of the execution many packages are installed?

```
Successfully installed boto3-1.9.221 botocore-1.12.221 docutils-0.15.2 gluonts-0.3.3 graphviz-0.8.4 holidays-0.9.11 jmespath-0.9.4 mxnet-1.4.1 mxnet-mkl-1.5.0 numpy-1.15.4 pandas-0.25.1 pydantic-0.28 pytz-2019.2 s3transfer-0.2.1 tqdm-4.35.0 ujson-1.35
```

**Comment by lostella** [comment]
Thanks for reporting this, the default number of epochs for the Trainer class was set to 100 in https://github.com/awslabs/gluon-ts/pull/81, so this example has been "broken" for a while.

I think it's best if we add an import line to import the Trainer, and provide a `Trainer(epochs=10)` when constructing the estimator.

**Comment by lostella** [comment]
@jgasthaus did you put the quick example script somewhere on repl.it?

**Comment by AaronSpieler** [comment]
@szha Do you have access to this script? If yes, could you please change the script according to Lorenzos suggestion?

**Comment by szha** [comment]
Updated per request.
