### ISSUE TITLE
`training_network` is declared twice inside `train_model` method

### ISSUE THREAD

**Issue by pablovicente** [awslabs/gluon-ts#2833]
`training_network` is declared twice inside the `train_model` method on `torch/model/estimator.py`

https://github.com/awslabs/gluonts/blob/dev/src/gluonts/torch/model/estimator.py#L165
https://github.com/awslabs/gluonts/blob/dev/src/gluonts/torch/model/estimator.py#L190

Is there a reason for it? Otherwise I can submit a PR to fix it. Thanks!

**Comment by lostella** [comment]
@pablovicente thanks for spotting this! I don't see a reason for it, and looks like I'm to blame (#2249). The second construction is redundant?

Feel free to open a PR!

**Comment by pablovicente** [comment]
No worries, thanks for the great work! I will open the PR now.

**Comment by abdulfatir** [comment]
@lostella I think there's another thing here we should probably simplify. In my opinion, `create_training_data_loader` should not require the model/module object. Everything it needs should be available via the estimator class it resides in. 

https://github.com/awslabs/gluonts/blob/183c0a4bdcbdd7cca94715afeb7e873f71ffc730/src/gluonts/torch/model/estimator.py#L167-L171

As far as I see, the module object is used to access the `past_length` in DeepAR which I feel is a very awkward way to do that:
https://github.com/awslabs/gluonts/blob/183c0a4bdcbdd7cca94715afeb7e873f71ffc730/src/gluonts/torch/model/deepar/estimator.py#L330

In contrast, the MxNet version has `history_length` available via the estimator:
https://github.com/awslabs/gluonts/blob/183c0a4bdcbdd7cca94715afeb7e873f71ffc730/src/gluonts/mx/model/deepar/_estimator.py#L386

**Comment by lostella** [comment]
@abdulfatir agreed, that is probably better. Opened #2835 to track that and made it release-blocking (we can change that if we feel it's too late)
