### ISSUE TITLE
Add Holidays into the model

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#284]
## Description
Hello,

I am currently using deepAR to evaluate the model's performance on sales dataset.

I would like to ask a technical question related to holidays:

- If I define my holidays like this:

![holidays](https://user-images.githubusercontent.com/51836477/64339749-11719080-cfbb-11e9-98aa-fb8a8860de11.jpg)

0 = it is not holiday
1 = holiday

1 -) Is it enough to capture the impact of the holiday on previous days, and the difference between a holiday that happens on friday and a holiday that happens on thursday ?

Or should I write 3 arrays as dynamic features specifying:
- What is the closest holiday (eg. 0 - Christmas, 1, New Eve)
- Which weekday this closest holiday occurs
- Closest Holiday Distance (days)

2 -) In doing this second option, is it correct to use 3 different arrays ? Or because those 3 variables are correlated, I have to group them (3 dimensional arrays - somethings like this) ?

Thanks

**Comment by lostella** [comment]
Hi @kaleming, what the best features are to provide a model probably depends a lot on both the model on the data, and the only way to find out is by experiments. Your first option (holiday indicators, like in the picture) seems perfectly reasonable to me. Any other more complex set of features (which holiday, how far forward or back in time the holiday is, and so on) could also work, but it's up to experiments to tell that I guess.

Please note that the field name should be called "feat_dynamic_real", and that the layout is feature-by-time. So for example, in the following example
```python
"feat_dynamic_real": [
    [1, 0, 0, 0, 1, 1, 0, 0, 0],
    [3, 2, 1, 0, 0, 7, 6, 5, 4],
    [1, 1, 1, 1, 1, 1, 0, 0, 0]
]
```
we're setting 3 features, each spanning 9 time steps.

Hope that helps!

**Comment by kaleming** [comment]
Thank you @lostella,

I will make some experiments, and later on I can share some results.
