### ISSUE TITLE
AssertionError: Dataframe index is not uniformly spaced. If your dataframe contains data from multiple series in the same column ("long" format), consider constructing the dataset with `PandasDataset.from_long_dataframe` instead.

### ISSUE THREAD

**Issue by manitadayon** [awslabs/gluon-ts#2854]
### Discussed in https://github.com/awslabs/gluonts/discussions/2852

<div type='discussions-op-text'>

<sup>Originally posted by **manitadayon** May 11, 2023</sup>
Hi All, I am trying to use DeepAR estimator to multiple time series forecasting, by concatenating all the time series (Pandas DataFrame) and then use 
`train_ds = PandasDataset.from_long_dataframe(train_all_data, target='power', item_id=['product','Code'], datestamp = 'date', freq = 'D')
`
where train_all_date is the contanetation of 1000 time series (T1,T2, . . .  T1000) as follows:
```
T1:
date                    product    Code        power 
2022-11-01            'A'             1                     9
2022-11-02.           'A'             1                    10
. . .                          . . .                 . . .
```
Similarly  for T2, T3, . . .  T1000. These time series all have different lengths (There are lots of common days though, with different, product type) and they have different start date but their frequency is the same. 

Then train_all_data is the concatenation of these series vertically. I used the above commands with my estimator defined as follows here:

`estimator = DeepAREstimator(freq='D', context_length=100, prediction_length=400, num_layers=3,hidden_size = 64)
`

Then following command 

`estimator.train(train_ds)
`
returns 

`AssertionError: Dataframe index is not uniformly spaced. If your dataframe contains data from multiple series in the same column ("long" format), consider constructing the dataset with `PandasDataset.from_long_dataframe` instead.
`
The combination of code and product uniquely identify a time series. May be the way I added item_id is not correct. Maybe more than one element for item_id is not supported. Can someone help here? (since product or code cannot uniquely identify a time series)

It is telling me to use the long format but I thought I am already using the long format. Can you guys help identifying and solving my problem </div>

**Comment by lostella** [comment]
@manitadayon does the data contain on value for each of the spanned days, for all items T1 to T1000? What may be happening here (hard to say without looking at the data itself) is that there are some missing observations

**Comment by ManieTadayon** [comment]
@lostella thanks for your answer, the start and end date of the data are different (Therefore the time series have different length), but data for each time series is with daily frequency. Can you elaborate on what you mean by missing observations?
This is how data look like:
```
T1:
date                    product    Code        power 
2022-11-01            'A'             1                     9
2022-11-02.          'A'            1                    10
2022-11-03.          'A'.            1                     11
. . .                          . . .                 . . .

T2:
date                    product    Code        power 
2021-10-01            'B'             1                     1
2021-10-02.           'B'             1                    2
. . .                          . . .                 . . .

T3:
date                    product    Code        power 
2019-11-22            'C'             1                     12
2019-11-23.           'C'             1                    45
. . .                          . . .                 . . .
```
and so one (Length of T1 is 1000, length of T2 is 1400 and length T3 is 500, etc). May I know if DeepAR handle multiple time series with different length? if yes, then how do you recommend inputting it to the model and if no, then how would feed them to model (do you pad it with NAN values?)

**Comment by manitadayon** [comment]
@lostella Thanks for your response. The start and end date of each series are different, hence they have different lengths. Can you elaborate on what you mean by missing observation in this context? (Do you mean NAN, in that case there is no missing value)
This is how data look like:
```
T1:
date                    product    Code        power 
2022-11-01            'A'             1                     9
2022-11-02.           'A'             1                    10
      .                           .              .                      .
      .                           .              .                      .
      .                           .              .                      .
2023-02-  12.       'A'              1                     6

T2:
date                    product    Code        power 
2019-09-01            'B'             1                     1
2019-09-02.           'B'             1                    7
      .                           .              .                      .
      .                           .              .                      .
      .                           .              .                      .
2021-01-12.            'B'              1                     23


T3:
date                    product    Code        power 
2020-06-01            'C'             1                     4
2020-06-02.           'C'             1                    12
      .                           .              .                      .
      .                           .              .                      .
      .                           .              .                      .
2022-04-10.          'C'              1                     24
```

an so on. May I also know if DeepAR can handle multiple series with different length, if yes how would you recommend inputting this to model in my case if no, then what would be your recommendation for making them same length.

**Comment by lostella** [comment]
Take the T1 example above. Dates span from `2022-11-01` to `2023-02-12` as far as I can see (assuming they are sorted): are all days between these two dates covered? Or are some skipped?

DeepAR can be trained on a set of series each with different length.

**Comment by manitadayon** [comment]
@lostella thanks for the clarification. It is interesting, just checked that yes it contains every single days between `2022-11-01` to `2023-02-12`. However I found the function:
`is_uniform(pd.DatetimeIndex(T1['date']).to_period("D"))` 
returns false. I checked there is no duplicate across dates as well. Do you have any idea what can cause this? (The above commands returns true for 90%  of the time series). 
Can this cause the issue, (since this is the function being tested before it throws that error when I look at the code base)

**Comment by lostella** [comment]
If I set up the following list of strings:

```python
dates = pd.date_range(start="2022-11-01", end="2023-02-12", freq="D").astype(str).tolist()
```

then

```python
is_uniform(pd.DatetimeIndex(dates).to_period("D"))  # returns True
```

so I'm not sure what's going on. If you could share the data that would be easier to check.

**Comment by manitadayon** [comment]
Thanks, the problem after a lot of debugging was that, in fact some time indexes were missing.
