### ISSUE TITLE
Ability to set default_root_dir as per the pl trainer specifications

### ISSUE THREAD

**Issue by vmajor** [awslabs/gluon-ts#2887]
## Description
The ability to set the `default_root_dir` for checkpointing during `train()` of PyTorch Lighning GluonTS models seems to be missing. Being able to set `default_root_dir` arbitrarily would allow training of multiple models within the same root path and would simplify resource sharing.

Currently all models place their checkpoints and logs inside `lightning_logs` making it unnecessarily cumbersome to manage the trained models programmatically.

## References
Reference: https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html

```
# saves checkpoints to 'some/path/' at every epoch end
trainer = Trainer(default_root_dir="some/path/")
```

**Comment by lostella** [comment]
@vmajor is this something the `trainer_kwargs` argument to estimators does?

See [here](https://github.com/awslabs/gluonts/blob/268f68055eaeedde1dfcc5691e0c97cd554fa9e6/src/gluonts/torch/model/deepar/estimator.py#L176) and [here](https://github.com/awslabs/gluonts/blob/268f68055eaeedde1dfcc5691e0c97cd554fa9e6/src/gluonts/torch/model/estimator.py#L203)

**Comment by vmajor** [comment]
Yes it is and I tried this, but it was not working. Now I tried it again, and it is working... sigh. I will close this issue.

edit: thank you :)
