### ISSUE TITLE
The document contains errors

### ISSUE THREAD

**Issue by jibinggao** [awslabs/gluon-ts#2911]
**Quick Start Tutorial**

**Datasets**

Provided datasets

GluonTS comes with a number of publicly available datasets.

**from gluonts.dataset.repository import get_dataset, dataset_names**
------------------------------------------------

In the Quick Start Tutorial section of the documentation, the code contains errors and should be as follows：

**from gluonts.dataset.repository.datasets import get_dataset,dataset_names**

**Comment by lostella** [comment]
@jibinggao what version are you using? With the latest release it's working fine:

```python
In [1]: import gluonts

In [2]: gluonts.__version__
Out[2]: '0.13.1'

In [3]: from gluonts.dataset.repository import get_dataset, dataset_names

In [4]:
```

**Comment by jibinggao** [comment]
My version is 0.12.8

发自我的iPhone

**Comment by lostella** [comment]
I see; links to the documentation gets you to the latest version by default (0.13 now). You find the documentation for v0.12 at https://ts.gluon.ai/v0.12.x/ which indeed has the code as you suggest
