### ISSUE TITLE
Wavenet : cannot change default activation function - Gluonts 0.3.3

### ISSUE THREAD

**Issue by tdenimal** [awslabs/gluon-ts#295]
Hello,

It seems that there is an error, in Gluonts 0.3.3,  when you change the default activation function (ELU) for the  WAVENET estimator, for example by relu

>  estimator = WaveNetEstimator(
                    freq = "1W",
                    dilation_depth = 4,
                    train_window_length = 20,
                    prediction_length = 10,
                    act_type="relu")
>
> estimator.train(train)

Results in the following exception :

> TypeError                                 Traceback (most recent call last)
<ipython-input-274-dd55aba3404d> in <module>
----> 1 estimator.train(train)
>
> ~/anaconda3/envs/gluonts/lib/python3.7/site-packages/gluonts/model/wavenet/_estimator.py in train(self, training_data)
    294             params = self._get_wavenet_args(bin_centers)
    295             params.update(pred_length=pred_length)
--> 296             trained_net = WaveNet(**params)
    297 
    298         self.trainer(

> ~/anaconda3/envs/gluonts/lib/python3.7/site-packages/gluonts/model/wavenet/_network.py in __init__(self, bin_values, n_residue, n_skip, dilation_depth, n_stacks, act_type, cardinality, embedding_dimension, pred_length, **kwargs)
    192                 nn.ELU()
    193                 if act_type == "elu"
--> 194                 else nn.Activation(act_type=act_type)
    195             )
    196             self.cross_entropy_loss = gluon.loss.SoftmaxCrossEntropyLoss()
>
> TypeError: __init__() missing 1 required positional argument: 'activation'

Seems that the correct syntax should be : 

nn.Activation(activation=act_type)

See http://mxnet.incubator.apache.org/versions/1.4.1/api/python/gluon/nn.html#mxnet.gluon.nn.Activation

It seems to work when you change the syntax that way.

Best regards,

**Comment by vafl** [comment]
Thanks. This is indeed a bug. Could you perhaps send a PR for that?

**Comment by tdenimal** [comment]
ok done :)

**Comment by vafl** [comment]
Thanks!
