### ISSUE TITLE
What is a valid way to combine (aggregate) confidence intervals using Gluonts ?

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#296]
Hello,

Is there any method using `forecast` object that returns from a daily prediction a cumulative P90 of x  period (eg. 10 days) ?

![Prediction length](https://user-images.githubusercontent.com/51836477/64551611-c8e40b00-d30b-11e9-8824-6354a455e3f5.png)

**Comment by vafl** [comment]
There is currently no method implemented, but you can do it directly, if your forecasts are `SampleForecast` classes (most forecasters return this). These forecast object contain a 2d array  `.samples` of size `(num_samples, prediction_length)`. You can then aggregate this array over the second axis, i.e., the following would give you the p90 for the sum of the first 10 days:

```python
import numpy as np
np.percentile(forecast.samples[:, :10].sum(axis=1), 90)
```

**Comment by kaleming** [comment]
It makes sense.
Thanks @vafl.
