### ISSUE TITLE
what is meaning about sample paths?

### ISSUE THREAD

**Issue by halzing** [awslabs/gluon-ts#298]
when predicting , 
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  # test dataset
    predictor=predictor,  # predictor
    num_eval_samples=5,  # number of sample paths we want for evaluation
)
can you explain num_eval_samples?  what is sample paths?

**Comment by timoschowski** [comment]
A sample path is a potential realization of the time series into the future. Typically, such a trajectory is achieved by sampling from the trained model. If you sample multiple times, you obtain multiple such trajectories and hence a non-parametric representation of the predictive distribution. Therefore, the more samples you choose, the more accurate the representation of the distribution is going to be. In particular if you are interested in higher quantiles of the distribution, you'll need to change this value to much higher.

Figure 2 in https://arxiv.org/pdf/1704.04110.pdf explains this a bit more.
