### ISSUE TITLE
Failing to load my data and use GluonTS forecasting 

### ISSUE THREAD

**Issue by ArianKhorasani** [awslabs/gluon-ts#2992]
Dear @lcallot! I'm trying to do time series forecasting for vital signs data and already extracted the data from a Health dataset. I contains a bunch of CSV files. I'm trying to use GluonTS models to train it but before everything, I'm trying to load my data into ListDataset format! 

First of all, please consider the .head() of my data: 
<img width="594" alt="Screen Shot 2023-09-02 at 11 04 21 PM" src="https://github.com/awslabs/gluonts/assets/36475965/468174e5-65bd-4118-a6df-2117676bbd20">

I'm running the following code:

```
from gluonts.dataset.common import ListDataset
data = ListDataset([{
    "start": df["HR"].index[0],  # Start time is the index of the first row
    "target": df["HR"].values.tolist()  # Target is the "HR" column as a list
}], freq="1H")
```

My goal is to forecasting vital signs data here by using some models that you have already developed such as DeepAREstimator, Transformer, RNN, etc! but I'm getting the error as below after running that code:

`GluonTSDataError: Error "day is out of range for month: 0" occurred, when reading field "start"`

sorry if my question might be basic, but since I'm new to GluonTS tool, I'd be happy to help me get it, and if you have suggestions for running my experiments on the models that you developed based on PyTorch, please let me know! 

Thanks! :)

**Comment by lcallot** [comment]
I think @lostella might be better able to answer this question. My guess would be that your Index is not an actual timestamp which causes the error.

**Comment by ArianKhorasani** [comment]
> I think @lostella might be better able to answer this question. My guess would be that your Index is not an actual timestamp which causes the error.

Thanks! I will be waiting for @lostella's kind respond too! FYI, the ICULOS is increasing +1 in each patients data and the frequent of it is in hour. In the dataset that I'm trying to extract data from, there is no other timestamps that I should use.

**Comment by abdulfatir** [comment]
@ArianKhorasani In that case, you can specify a dummy start date with a frequency of 1H. An example,

```py
from gluonts.dataset.common import ListDataset
import pandas as pd

data = ListDataset([{
    "start": pd.Period("2012-12-21", freq="H"),  # Start time is the index of the first row
    "target": df["HR"].values.tolist()  # Target is the "HR" column as a list
}], freq="1H")
```

**Comment by lostella** [comment]
> @ArianKhorasani In that case, you can specify a dummy start date with a frequency of 1H. An example,
> 
> ```python
> from gluonts.dataset.common import ListDataset
> import pandas as pd
> 
> data = ListDataset([{
>     "start": pd.Period("2012-12-21", freq="H"),  # Start time is the index of the first row
>     "target": df["HR"].values.tolist()  # Target is the "HR" column as a list
> }], freq="1H")
> ```

That's correct; @ArianKhorasani could you try it out and confirm that it works for your use case?

**Comment by ArianKhorasani** [comment]
Dear @lostella and @abdulfatir Sorry for my late reply! I was out of office! 
Yes, I do confirm your valuable suggestions helped me to fix my issue. Now, I'm able to load my custom dataset and additionally, I did load my multivariate time series dataset to ListDataset as well!
