### ISSUE TITLE
API: number of samples

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#301]
## Summary

All predictors currently produce probabilistic forecasts using sampling and the `SampleForecast` class. The number of samples that a predictor produces (and that are used for evaluating forecasts) can be set in a number of places with inconsistent argument names and is a bit confusing in my opinion.

## Current status of things

* `Estimator` types accept a `num_parallel_samples` constructor argument ([see for example DeepAR](https://github.com/awslabs/gluon-ts/blob/6ca5d5d67565c24b72899792b6325a25b1341051/src/gluonts/model/deepar/_estimator.py#L130)) which is used to configure the resulting predictor (DeepAR does it [here](https://github.com/awslabs/gluon-ts/blob/6ca5d5d67565c24b72899792b6325a25b1341051/src/gluonts/model/deepar/_estimator.py#L270)). This is purely for optimization purposes, in that the `GluonPredictor` that such estimators produce allow for customizing the number of samples at inference time, see [here](https://github.com/awslabs/gluon-ts/blob/6ca5d5d67565c24b72899792b6325a25b1341051/src/gluonts/model/predictor.py#L314-L326).
However, some estimators call this constructor argument `num_eval_samples` (see e.g. [DeepState](https://github.com/awslabs/gluon-ts/blob/6ca5d5d67565c24b72899792b6325a25b1341051/src/gluonts/model/deepstate/_estimator.py#L148) and [DeepFactor](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deep_factor/_estimator.py#L102)).
* `make_evaluation_predictions` accepts a `num_eval_samples` and forwards it to the predict method. However, this is sometimes hidden in `**kwargs` and silently ignored, [for example by NPTS](https://github.com/awslabs/gluon-ts/blob/6ca5d5d67565c24b72899792b6325a25b1341051/src/gluonts/model/npts/_predictor.py#L204-L228)

## Proposed API

The way the number of samples is managed should be made uniform. To me, it makes sense to follow the following convention:

* Gluon-based `Estimator` types **do** have the `num_parallel_samples` option specified at construction time, in case their forecasts are sample-based.
* `Predictor`s **do not** have any `num_XXX_samples` option in the constructor.
* `Predictor.predict` method accepts the `num_samples` argument (optional, should have a default value e.g. 100).
* Note that I'm using `num_samples` and not `num_eval_samples`, since the `eval` part will be implied by the context (in case evaluations are being done).
* All predictors should be tested for the `num_samples` argument to be effective.

## References

List of PR/issues containing discussion or changes around this piece of API:
* #232

**Comment by jaheba** [comment]
Looks good, I'm all for it!

**Comment by lostella** [comment]
> Looks good, I'm all for it!

"Breaking changes? That's fun!"

**Comment by jaheba** [comment]
That's why we are still pre 1.0.

0.4 is gonna be big
