### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by robertdj** [awslabs/gluon-ts#3050]
## Description

I am using the DeepAR model, but I am having issues with outdated dependencies conflicting with other packages I'm using.

This is particularly on Linux where I get this peculiar error right after the training is done, but before it returns:
```
TypeError: The classmethod `DeepARLightningModule.load_from_checkpoint` cannot be called on an instance. Please call it on the class type and make sure the return value is used.
```
While it seems unrelated to the deps, I found the following [SO post](https://stackoverflow.com/questions/77325101/why-estimator-train-in-gluonts-deepar-returns-typeerror-classmethod-cannot-b) suggesting that an old version of NumPy can alleviate the situation. Unfortunately, I'm not able to downgrade far enough to make this work. 

(I'm not sure if this should be filed under "features".)

**Comment by lostella** [comment]
@robertdj what version of gluonts and pytorch lightning do you have installed?

**Comment by robertdj** [comment]
Yikes, it turns out that I was using an outdated version of gluonts (0.13.5). After updating to 0.14.0 the problem vanished. 
Thanks for your quick reply and my apologies for this noob question.
