### ISSUE TITLE
Only a single validation batch is used if `estimator.train` called with `cache_data=True`

### ISSUE THREAD

**Issue by shchur** [awslabs/gluon-ts#3059]
## Description
If we set `cache_data=True` when calling `estimator.train`, estimator only uses a single batch for validation. If `cache_data=False`, all validation batches are used.

## To Reproduce

```python
import pandas as pd
from gluonts.torch.model.deepar import DeepAREstimator

train = [{"start": pd.Period("2020-01-01", freq="H"), "target": list(range(100))} for _ in range(100)]
val = [{"start": pd.Period("2020-01-01", freq="H"), "target": list(range(100))} for _ in range(10000)]
estimator = DeepAREstimator(freq="H", prediction_length=1, trainer_kwargs={"accelerator": "cpu"})
# Uses full validation data
estimator.train(train, val, cache_data=False)
# Uses single validation batch
estimator.train(train, val, cache_data=True)
```

## Environment
- Operating system: Linux
- Python version: 3.10
- GluonTS version: 0.14.1
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@shchur thanks, great reproducer!

What puzzles me is that extrapolating the validation data loader constructor gives me the right length (i.e. number of validation batches) every time I go through them:

```python
from gluonts.itertools import Cached

module = estimator.create_lightning_module()
transformation = estimator.create_transformation()

transformed_validation_data = transformation.apply(val, is_train=True)
transformed_validation_data = Cached(transformed_validation_data)

validation_data_loader = estimator.create_validation_data_loader(
    transformed_validation_data,
    module,
)

print(len(list(validation_data_loader)))
print(len(list(validation_data_loader)))
print(len(list(validation_data_loader)))
print(len(list(validation_data_loader)))
```

yields

```
313
313
313
313
```

**Comment by shchur** [comment]
Not sure, it looks like some strange interplay with Lightning. I tried dropping a debugger [here](https://github.com/awslabs/gluonts/blob/dev/src/gluonts/torch/model/estimator.py#210), and both `len(validation_data_loader)` and `len(list(validation_data_loader))` are equal to the expected length. However, the trainer only takes 1 batch from the validation loader.

Could we just replace the `Cached` wrapper with `list`?
```python
if cache_data:
    transformed_validation_data = list(transformed_validation_data)
```

**Comment by jaheba** [comment]
A bit embarrassing, but there was a bug in `Cached`: #3060
