### ISSUE TITLE
Incorrect number of parameters in DeepARTrainingNetwork

### ISSUE THREAD

**Issue by lcallot** [awslabs/gluon-ts#310]
## Description

The number of parameters in the training network logged by DeepAR is incorrect. The number of parameters  

## To Reproduce
```python

from gluonts.model.deepar import DeepAREstimator
from gluonts.dataset.common import ListDataset
from gluonts.trainer import Trainer

import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/numenta/NAB/master/data/realTweets/Twitter_volume_AMZN.csv"
df = pd.read_csv(url, header=0, index_col=0)

training_data = ListDataset(
    [{"start": df.index[0], "target": df.value[:"2015-04-05 00:00:00"]}],
    freq = "5min"
)

def count_model_params(net) -> int:
    params = net.collect_params()
    num_params = 0
    for p in params:
        v = params[p]
        num_params += np.prod(v.shape)
    return num_params

trainer = Trainer(epochs=1,batch_size=1,num_batches_per_epoch=1)
estimator = DeepAREstimator(freq="5min", prediction_length=12, trainer=trainer)
predictor = estimator.train_model(training_data=training_data)
npar = count_model_params(net=predictor.trained_net)
print(f"Number of parameters counted after training: {npar}")
```

Output

```
INFO:root:Using CPU
INFO:root:Start model training
INFO:root:Number of parameters in DeepARTrainingNetwork: 13463
INFO:root:Epoch[0] Learning rate is 0.001
100%|██████████| 1/1 [00:00<00:00, 13.78it/s, avg_epoch_loss=5.52]
INFO:root:Epoch[0] Elapsed time 0.074 seconds
INFO:root:Epoch[0] Evaluation metric 'epoch_loss'=5.524269
INFO:root:Loading parameters from best epoch (0)
INFO:root:Final loss: 5.524268627166748 (occurred at epoch 0)
INFO:root:End model training

Number of parameters counted after training: 29743
```

Changing the length of `lags_seq` has no effect on the count before training, but does after. 

```python
trainer = Trainer(epochs=1,batch_size=1,num_batches_per_epoch=1)
estimator = DeepAREstimator(freq="5min", prediction_length=12, trainer=trainer,
                           lags_seq=[1])
predictor = estimator.train_model(training_data=training_data)
npar = count_model_params(net=predictor.trained_net)
print(f"Number of parameters counted after training: {npar}")
```
Output
```
INFO:root:Using CPU
INFO:root:Start model training
INFO:root:Number of parameters in DeepARTrainingNetwork: 13463
INFO:root:Epoch[0] Learning rate is 0.001
100%|██████████| 1/1 [00:00<00:00, 13.60it/s, avg_epoch_loss=5.18]
INFO:root:Epoch[0] Elapsed time 0.075 seconds
INFO:root:Epoch[0] Evaluation metric 'epoch_loss'=5.181353
INFO:root:Loading parameters from best epoch (0)
INFO:root:Final loss: 5.181352615356445 (occurred at epoch 0)
INFO:root:End model training

Number of parameters counted after training: 24463
```

## Error Message
No error

## Environment
- Operating system: Sagemaker notebook + training job (Amazon Linux?) 
- Python version: 3.7
- GluonTS version:3.3

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
The problem is that [these lines](https://github.com/awslabs/gluon-ts/blob/f20cf9e32bd9ae7e96cf87d21925373421fcd55e/src/gluonts/trainer/_base.py#L193-L196) should be executed after at least one forward pass, so moved further down in the training loop (with some flag guarding their execution).

**Comment by Patil2099** [comment]
I would like to take this up @lcallot  @lostella  Can you help me in solving this issue?

**Comment by lostella** [comment]
@Patil2099 sure! Thanks for the help.

The issue is in [the lines counting the parameters](https://github.com/awslabs/gluon-ts/blob/22da305e8d52d3fccadd4dd3000859b7c48e62e0/src/gluonts/trainer/_base.py#L193-L196): they are invoked before any forward pass on the network is performed, so the number of inputs to the network is unknown, and therfore the number of parameters in the network is inexact.

The forward pass happens [here](https://github.com/awslabs/gluon-ts/blob/22da305e8d52d3fccadd4dd3000859b7c48e62e0/src/gluonts/trainer/_base.py#L252), so you may want to move the parameter counting after this point. Note however that this should happens only once in the training loop, so you can put a safeguard that makes sure they are invoked only at the first iteration.

**Comment by timoschowski** [comment]
This PR https://github.com/awslabs/gluon-ts/pull/386 fixes the issue.
