### ISSUE TITLE
Connection between num_parallel_samples and make_evaluation_predictions?

### ISSUE THREAD

**Issue by lotsoffood** [awslabs/gluon-ts#311]
I notice that when running `make_evaluation_predictions` on a multi-core system, only one core is active. I'd like to parallelize this step (if it's not entirely done on the GPU with `ctx='gpu'`), and notice the argument `num_parallel_samples` for an `estimator` object. I'm not sure of the connection between `num_parallel_samples` and `make_evaluation_predictions` (if there is any).

Is it possible to go into more detail on what the argument `num_parallel_samples` actually does? And how it might be possible to speed up `make_evaluation_predictions` with the argument, or other methods?

**Comment by lostella** [comment]
@lotsoffood the `num_parallel_samples` argument decides how many sample paths the network used by the resulting predictor will produce at once. However, the total number of sample paths that the predictor uses to make forecasts can be set to a completely different value [when invoking `predict`](https://github.com/awslabs/gluon-ts/blob/f20cf9e32bd9ae7e96cf87d21925373421fcd55e/src/gluonts/model/predictor.py#L294-L338), in which case an appropriate number of “batches” of sample paths will be generated.

So I guess the “parallel” here may be a bit misleading: it just indicates how many sample paths *at once* the network draws.

**Comment by lostella** [comment]
Also, please note #301 for a related discussion and potential upcoming API changes.

**Comment by vafl** [comment]
Yes, In principle these samples should be parallelized by mxnet. Not sure why this is not giving higher cpu utilization. In any case, you can wrap your predictor in a ‘ParallelizedPredictor’, which should use all cores if you predict many series.
