### ISSUE TITLE
Cannot use iTransformer with GluonTS version 0.14.4

### ISSUE THREAD

**Issue by marcopeix** [awslabs/gluon-ts#3122]
## Description
The iTransformerEstimator cannot be imported and used. I have a clean install of the latest version of GluonTS (v. 0.,14.4)

## To Reproduce
Install GluonTS

```python
from gluonts.torch.model.i_transformer.estimator import iTransformerEstimator
```

## Error message or code output
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[21], line 1
----> 1 from gluonts.torch.model.i_transformer.estimator import iTransformerEstimator

ModuleNotFoundError: No module named 'gluonts.torch.model.i_transformer'

## Environment
- Operating system: Windows
- Python version: 3.10
- GluonTS version: 0.14.4

**Comment by kashif** [comment]
i believe its not in a release yet so you will need to use the git main branch for now

**Comment by lostella** [comment]
As @kashif said, this will be available in the next release (coming soon), but in the meantime, installing the dev branch will provide that.

```
pip install git+https://github.com/awslabs/gluonts.git@dev
```
