### ISSUE TITLE
Support pydantic-2.5.3

### ISSUE THREAD

**Issue by moghadas76** [awslabs/gluon-ts#3123]
## Description
Currently it requires pydantic-1.10.14 which is old!

## To Reproduce
pip install ...

## Environment
- Operating system:
- Python version:
- GluonTS version:
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@moghadas76 thanks, but not a bug

**Comment by lostella** [comment]
@moghadas76 again: what version of gluonts are you using? v0.14.x supports pydantic 2
