### ISSUE TITLE
Support numpy>= 2.0.0

### ISSUE THREAD

**Issue by suzhoum** [awslabs/gluon-ts#3225]
## Description
Hi Team,

With the increasing adoption of numpy>=2.0.0, and some prominent packages—such as spaCy—now requiring this version as a dependency (see [here](https://github.com/explosion/spaCy/blob/0d7e57fc3e57acfeeadf6f4291b2d587dccac247/pyproject.toml#L9-L10)), I would like to inquire if there are plans for GluonTS to support numpy>=2.0.0 in the near future.

Our team is actively working on AutoGluon, which relies on both spacy and gluonts. We have been receiving numerous requests from our users to support numpy>=2.0.0. Having compatibility with this version would greatly benefit our project and likely others in the ecosystem.

We would greatly appreciate your consideration of this request and any guidance you could provide on a potential timeline for supporting this upgrade.

Thank you for your continued efforts and support!

## References
- list reference and related literature
- list known implementations

**Comment by lostella** [comment]
Work in progress in #3226

**Comment by lostella** [comment]
Addressed in #3226 and #3227, which will be included in the upcoming 0.16 release

**Comment by lostella** [comment]
@suzhoum gluonts 0.16 is released, with support for numpy 2. Closing this for now, feel free to open any issues you may find with it. And thanks for opening the issue!

**Comment by suzhoum** [comment]
@lostella Thank you very much for the quick turnaround!
