### ISSUE TITLE
Unable to get several datasets

### ISSUE THREAD

**Issue by wwdda** [awslabs/gluon-ts#3229]
## Description
Error:"ValueError: Cannot obtain default prediction length from frequency `ME`." occured when getting 'cif_2016' dataset.
Error:"ValueError: Cannot obtain default prediction length from frequency `min`." occured when getting 'london_smart_meters_without_missing' dataset and 'wind_farms_minutely_dataset_without_missing_values' dataset.
## To Reproduce

```python
from gluonts.dataset.repository import get_dataset, dataset_names
print(f"Available datasets: {dataset_names}")
dataset = get_dataset("cif_2016") # or 'london_smart_meters_without_missing'```
```
## Error message or code output
<img width="1093" alt="Screenshot 2024-10-23 at 10 08 17 PM" src="https://github.com/user-attachments/assets/3d08b7ac-aa54-4086-9cf7-d7f8477c167c">

## Environment
- Python version: 3.10
- GluonTS version: 0.15.1

Could you please help update the prediction_length_map for 'ME' and 'min' in _tsf_datasets.py?

Thanks!

**Comment by lostella** [comment]
@wwdda being fixed in #3232, thanks for submitting the issue!
