### ISSUE TITLE
icdf does not work for negative binomial/poisson despite being in the code base?

### ISSUE THREAD

**Issue by jeycervantes** [awslabs/gluon-ts#3231]
## Description

A follow up on this question, as I realize its probably better categorized as a bug. https://github.com/awslabs/gluonts/discussions/3230

Basically, icdf method appears to be implemented, but it does not actually work, at least in databricks.

## To Reproduce
https://github.com/awslabs/gluonts/discussions/3230

## Environment
- Operating system: Databricks, 
<img width="497" alt="image" src="https://github.com/user-attachments/assets/37f6aa2c-b87b-4301-8adb-3e6edf424cc9">

- Python version:  3.11.0
- GluonTS version: 0.15.1
- MXNet version: 1.9.1

**Comment by lostella** [comment]
@jeycervantes see my answer in #3230
