### ISSUE TITLE
Trainer: batch_size and num_batches_per_epoch

### ISSUE THREAD

**Issue by ChaiBapchya** [awslabs/gluon-ts#335]
During instantiation of a GluonTS trainer, one can specify both `batch_size` and `num_batches_per_epoch` at the same time.  

However, 
```
num_batches_per_epoch = num_samples /batch_size
``` 
Since `num_samples` is taken from the training dataset directly, how can one specify both arguments at the same time?
 
Is it like we can specify one of these two arguments and the other one is calculated automatically? If that is the case, when we specify both, which one has the priority?

**Comment by lostella** [comment]
@ChaiBapchya the point is exactly that of breaking the relationship that you express, and allow for finer control of how long training should be.

The reason for this is the following: in many of the estimators, batches are formed by slicing out randomly sampled windows of data from the original dataset entries. Therefore, what you identify as `num_samples` can be *much* larger than the cardinality of the training dataset: in that case, even running 1 ”full epoch“ may take very long time. By explicitly setting how long an epoch should be, one has everything under control and knows exactly how many batches the training procedure will get to see.

**Comment by hantingxie** [comment]
It makes sense. I think it might be good to have this information in the code. 

In addition to that, does that mean by default we are only using 32 (batch_size) * 50 (num_batches_per_epoch) data points in one epoch no matter how many data samples are given in the training dataset? 

Do you think it might easier to understand if we set the default value of num_batches_per_epoch to be none (meaning it will be inferred by num_samples/batch_size), and if specified, we can still control the full epoch size?

**Comment by davidgilbertson** [comment]
As a newcomer, I find this confusing too. 

The actual problem I'm having is that I ran a model on a subset of my data, then ran it on a larger subset, but it took the same amount of time to run! At first I thought, _cool, free speed!_, then I thought, no this is probably bad, it's doing _less_ training per time series now.

I understand the use case for _allowing_ the user to define both `batch_size` and `num_batches_per_epoch`, but I don't get why it's the default.

I'm curious why it isn't done like this:
* an epoch is a full pass of the data.
* if you want to log or do validation more than once per epoch, define logging/validation steps (as is done in Lightning with `val_check_interval` and `log_every_n_steps`)
* If a user wants finer control of how long training goes for, use something like `max_steps` or `max_time` (ala Lightning)
* If an estimator wants to have overlapping batches/windows, it can do that and over-sample, but keep roughly the same total as the number of samples (e.g. by taking the partitioned windows and randomly shifting them)
