### ISSUE TITLE
DeepState plotting

### ISSUE THREAD

**Issue by mharvan** [awslabs/gluon-ts#337]
## Description
Plotting predictions made with a DeepState model fails.
The same plotting code works with a SimpleFeedForwardEstimator.

## To Reproduce
Please see the attached file
[benchmark_m4.py.txt](https://github.com/awslabs/gluon-ts/files/3647682/benchmark_m4.py.txt)
It is based on examples/benchmark_m4.py.

## Error Message
Length of passed values is 1, index implies 48

## Environment
Ubuntu 16.04
conda 4.7.10
Python 3.7.4

$ pip list | egrep 'gluon|mxnet'
gluonts 0.3.4.dev22+g515c45c /home/matus/src/gluon-ts/src
mxnet-cu101mkl 1.4.1

$ git log | head -n 1
commit 29ab758c9ddebdbba39a12597a1d5fcaaf906a97

**Comment by lostella** [comment]
#340 should solve this, let me know if this works and feel free to reopen if it doesn't

**Comment by mharvan** [comment]
Plotting works with #340, thanks for the fix!
