### ISSUE TITLE
Future values predictions, simple method

### ISSUE THREAD

**Issue by antonkiselevtdg** [awslabs/gluon-ts#338]
Hi,

Thank you very much for this tool. I would like to suggest the following:

Some time-series tools (FB Prophet, autoARIMA) allow to quickly and without efforts predict future values.

Let's suppose I have a dataset, end date is 2018-12-31 and I need to predict 7 days ahead and see these predictions.

Using FB Prophet all I need to do (after importing all libraries):

```
m = Prophet()
m.fit(dfs)
future = m.make_future_dataframe(periods=7)
future.tail(7)
forecast = m.predict(future)
forecast
```

And that is it. Sure, I can add train/test/evaluation, etc. But in order to simply predict I need to run just 6  short lines of code.

If GluonTS had a similar simple method to produce predictions - that would be great.

After working with current GluonTS examples I could not determine how to do smth similar.

**Comment by jaheba** [comment]
Hi,

I think it should be fairly simple to get a similar result with gluon-ts:

```python
from gluonts.model.prophet import ProphetPredictor  
from gluonts.dataset.common import ListDataset

dataset = ListDataset([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], freq="H")

predictor = ProphetPredictor("D", 7)
predictions = list(predictor.predict(dataset))

# results
predictions[0].samples
predictions[0].quantile(0.5)
```

**Comment by antonkiselevtdg** [comment]
Thanks! That is exactly what I wanted to understand.

**My next question would be - how to add my own dataset for predicting? 
And what format should it have?**

I have tried to use my own dataset with 2 columns (ds-date and y-value) - date and value (similar to https://raw.githubusercontent.com/numenta/NAB/master/data/realTweets/Twitter_volume_AMZN.csv). 

However, I am not sure I understand how to add it.

I have tried to do that using this guide:
https://github.com/awslabs/gluon-ts

```
dataset =  ListDataset(
    [{"start": df.index[0], "target": df.y[:"2015-04-05"]}],
    freq = "D"
)
```

I get the following:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind)
   5166             try:
-> 5167                 return self._searchsorted_monotonic(label, side)
   5168             except ValueError:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in _searchsorted_monotonic(self, label, side)
   5127 
-> 5128         raise ValueError("index must be monotonic increasing or decreasing")
   5129 

ValueError: index must be monotonic increasing or decreasing

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-91-cb8d51abc806> in <module>
      1 dataset =  ListDataset(
----> 2     [{"start": df.index[0], "target": df.y[:"2015-04-05"]}],
      3     freq = "D"
      4 )

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
   1108             key = check_bool_indexer(self.index, key)
   1109 
-> 1110         return self._get_with(key)
   1111 
   1112     def _get_with(self, key):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\series.py in _get_with(self, key)
   1113         # other: fancy integer or otherwise
   1114         if isinstance(key, slice):
-> 1115             indexer = self.index._convert_slice_indexer(key, kind="getitem")
   1116             return self._get_values(indexer)
   1117         elif isinstance(key, ABCDataFrame):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in _convert_slice_indexer(self, key, kind)
   3214         else:
   3215             try:
-> 3216                 indexer = self.slice_indexer(start, stop, step, kind=kind)
   3217             except Exception:
   3218                 if is_index_slice:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in slice_indexer(self, start, end, step, kind)
   5032         slice(1, 3)
   5033         """
-> 5034         start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
   5035 
   5036         # return a slice

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in slice_locs(self, start, end, step, kind)
   5252         end_slice = None
   5253         if end is not None:
-> 5254             end_slice = self.get_slice_bound(end, "right", kind)
   5255         if end_slice is None:
   5256             end_slice = len(self)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind)
   5168             except ValueError:
   5169                 # raise the original KeyError
-> 5170                 raise err
   5171 
   5172         if isinstance(slc, np.ndarray):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind)
   5162         # we need to look up the label
   5163         try:
-> 5164             slc = self.get_loc(label)
   5165         except KeyError as err:
   5166             try:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2897                 return self._engine.get_loc(key)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2901         if indexer.ndim > 1 or indexer.size > 1:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: '2015-04-05'

**Comment by jaheba** [comment]
It looks like your dataframe doesn't have the right format.

Generally, we support dictionaries of the form:

```json
{
  "start": "<timestamp>",
  "target": [...],
  "...": ...,
}
```

All dataset-classes are essentially only iterators over these dictionaries. See: https://github.com/awslabs/gluon-ts/blob/b7cf3431fca1e6f5f62078615e6640965e2187fa/src/gluonts/dataset/common.py#L153-L159

**Comment by antonkiselevtdg** [comment]
Thank you! I have adjusted the date format and it worked.

I was able to replicate your code with FB Prophet with my data.

**Would that be possible to do similar 7 days future  predictions with other methods (RNN/CNN) ?**

**Comment by jaheba** [comment]
> **Would that be possible to do similar 7 days future predictions with other methods (RNN/CNN) ?**

Yes, all methods in `/gluon-ts/tree/master/src/gluonts/model` should work similarly.

However, some require training first. For example, this is the  DeepAR-example from the README:

```python
estimator = DeepAREstimator(freq="5min", prediction_length=12, trainer=Trainer(epochs=10))
predictor = estimator.train(training_data=training_data)
```

**Comment by antonkiselevtdg** [comment]
Awesome! Thank you very much!

**Comment by xiaoyaoyang** [comment]
@jaheba a follow up question... looks like DeepAR learn multiple season at the same time, and from the paper it looks like it also allow to input similar things such as `holiday`... 

1, Does the model require future series as an input to predict the target series?
2, How to include the holiday information to the model?

**Comment by ramdhan1989** [comment]
> @jaheba a follow up question... looks like DeepAR learn multiple season at the same time, and from the paper it looks like it also allow to input similar things such as `holiday`...
> 
> 1, Does the model require future series as an input to predict the target series?
> 2, How to include the holiday information to the model?

did you get the answers?
