### ISSUE TITLE
Accessing weights and model parameters/too many values to unpack

### ISSUE THREAD

**Issue by antonkiselevtdg** [awslabs/gluon-ts#339]
Hi,

When I try to run the following:

You can use an estimator and call train_model in order to get access to the netword structure and parameters. train_model is an instance of DeepARTrainingNetwork, which in turn is derived from DeepARNetwork, which itself is derived from mxnet.gluon.block.HybridBlock. The following code demonstrates how to lookup the objects lineage.

**train_transformation, train_model = deepar_estimator.train_model(training_data)**

(after gluonts.model.deepar._network.DeepARTrainingNetwork.__bases__[0].__bases__[0])

I get the following error message:

## Error Message
ValueError                                Traceback (most recent call last)
<ipython-input-46-39199649ed98> in <module>
----> 1 train_transformation, train_model = deepar_estimator.train_model(training_data)

ValueError: too many values to unpack (expected 2)

I used 2 personal datasets (within 2000 data point each), changed train/test limits, but I always see this error.

**Comment by geoalgo** [comment]
Hi @antonkiselevtdg we changed the output of train_model to a class TrainOutput which is why this snipplet does not work anymore. The following should work:

`
train_output = deepar_estimator.train_model(training_data)
print(train_output.transformation)
print(train_output.trained_net)
`
