### ISSUE TITLE
Specifying which GPU to use on multi-GPU machine?

### ISSUE THREAD

**Issue by lotsoffood** [awslabs/gluon-ts#358]
Is there a way to specify which GPU to use for a machine with multiple GPUs? I.E. if I want to kick of multiple forecast training sessions.

**Comment by strawberrypie** [comment]
I think that you can use `CUDA_VISIBLE_DEVICES` environment variable to specify the GPU for the training script. For example, if your script is named `training.py` and you want to use GPU 1, you can select it like this:
```bash
CUDA_VISIBLE_DEVICES=1 python training.py
```
Note that index of the first GPU is 0.

**Comment by lotsoffood** [comment]
Thank you! I also found that using Ray's `tune` package and specifying 1-GPU resource per-trial allows me to hyper-parameter tune Gluon over multiple GPUs.

**Comment by CMobley7** [comment]
@lotsoffood, I'm interested in using Ray's `tune` package to perform [population based training](https://ray.readthedocs.io/en/latest/tune-schedulers.html#population-based-training-pbt) with several `gluon-ts` models. How did you enable [Save and Restore functionality](https://ray.readthedocs.io/en/latest/tune-usage.html#save-and-restore) with `gluon-ts`? Thanks in advance for any assistance you are able to provide.

**Comment by lotsoffood** [comment]
Hi @CMobley7 unfortunately I never got that aspect working.

**Comment by trunghlt** [comment]
@lotsoffood could you please paste a working example of using Ray's tune to tune GLuon over multiple GPUs? what value do you pass to Trainer's context? I set it as "gpu" and got GPU initialization error.
