### ISSUE TITLE
Use DeepAR for second-level data

### ISSUE THREAD

**Issue by changebo** [awslabs/gluon-ts#367]
When using `DeepAREstimator` for second-level data, both `get_lags_for_frequency` and `time_features_from_frequency_str` do not support `freq = 'S'`. It is possible to support second-level data in these two functions? Or is it possible to disable `lags_seq` and `time_features` in `DeepAREstimator`?

**Comment by lostella** [comment]
@changebo you can disable lags and time features by setting `lags_seq=[]` and `time_features=[]` when constructing a `DeepAREstimator`

**Comment by changebo** [comment]
Thanks @lostella for the quick response.

Setting `lags_seq=[]` gives the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-8d72adaab90e> in <module>
      3     context_length=args.context_length,
      4     lags_seq=[],
----> 5     time_features=[])

/redacted/python3.6/site-packages/gluonts/core/component.py in init_wrapper(*args, **kwargs)
    441                 self.__class__.__repr__ = validated_repr
    442
--> 443             return init(self, **all_args)
    444
    445         # attach the Pydantic model as the attribute of the initializer wrapper

/redacted/python3.6/site-packages/gluonts/model/deepar/_estimator.py in __init__(self, freq, prediction_length, trainer, context_length, num_layers, num_cells, cell_type, dropout_rate, use_feat_dynamic_real, use_feat_static_cat, cardinality, embedding_dimension, distr_output, scaling, lags_seq, time_features, num_parallel_samples)
    180         )
    181
--> 182         self.history_length = self.context_length + max(self.lags_seq)
    183
    184         self.num_parallel_samples = num_parallel_samples

ValueError: max() arg is an empty sequence
```

I guess a workaround is to set `lags_seq=[0]`. But setting `time_features=[]` gives a error message that's harder to decipher, when training the model.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-53d8e27af0c7> in <module>
----> 1 predictor = estimator.train(train_data)

/redacted/python3.6/site-packages/gluonts/model/estimator.py in train(self, training_data)
    201     def train(self, training_data: Dataset) -> Predictor:
    202
--> 203         return self.train_model(training_data).predictor

/redacted/python3.6/site-packages/gluonts/model/estimator.py in train_model(self, training_data)
    187             net=trained_net,
    188             input_names=get_hybrid_forward_input_names(trained_net),
--> 189             train_iter=training_data_loader,
    190         )
    191

/redacted/python3.6/site-packages/gluonts/trainer/_base.py in __call__(self, net, input_names, train_iter)
    243
    244                     with tqdm(train_iter) as it:
--> 245                         for batch_no, data_entry in enumerate(it, start=1):
    246                             if self.halt:
    247                                 break

/redacted/python3.6/site-packages/tqdm/_tqdm.py in __iter__(self)
   1020                 """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1021
-> 1022             for obj in iterable:
   1023                 yield obj
   1024                 # Update and possibly print the progressbar.

/redacted/python3.6/site-packages/gluonts/dataset/loader.py in __iter__(self)
    186         assert self._cur_iter is not None
    187         while True:
--> 188             data_entry = next(self._cur_iter)
    189             self._buffer.add(data_entry)
    190             if (

/redacted/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    345     ) -> Iterator:
    346         num_idle_transforms = 0
--> 347         for data_entry in data_it:
    348             num_idle_transforms += 1
    349             try:

/redacted/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    296         self, data_it: Iterator[DataEntry], is_train: bool
    297     ) -> Iterator:
--> 298         for data_entry in data_it:
    299             try:
    300                 yield self.map_transform(data_entry.copy(), is_train)

/redacted/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    296         self, data_it: Iterator[DataEntry], is_train: bool
    297     ) -> Iterator:
--> 298         for data_entry in data_it:
    299             try:
    300                 yield self.map_transform(data_entry.copy(), is_train)

/redacted/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    300                 yield self.map_transform(data_entry.copy(), is_train)
    301             except Exception as e:
--> 302                 raise e
    303
    304     @abc.abstractmethod

/redacted/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    298         for data_entry in data_it:
    299             try:
--> 300                 yield self.map_transform(data_entry.copy(), is_train)
    301             except Exception as e:
    302                 raise e

/redacted/python3.6/site-packages/gluonts/transform.py in map_transform(self, data, is_train)
    866             data[self.target_field], self.pred_length, is_train=is_train
    867         )
--> 868         self._update_cache(start, length)
    869         i0 = self._date_index[start]
    870         features = self._full_range_date_features[..., i0 : i0 + length]

/redacted/python3.6/site-packages/gluonts/transform.py in _update_cache(self, start, length)
    854         )
    855         self._full_range_date_features = np.vstack(
--> 856             [feat(self.full_date_range) for feat in self.date_features]
    857         )
    858         self._date_index = pd.Series(

/redacted/python3.6/site-packages/numpy/core/shape_base.py in vstack(tup)
    232
    233     """
--> 234     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    235
    236 def hstack(tup):

ValueError: need at least one array to concatenate
```

**Comment by lostella** [comment]
@changebo sorry, my bad - you must have at least one lag index. For example, `lag_seq=[1]`: this indicates that to output a predictive distribution for time t, the RNN takes as input z[t-1], where z is the time series. Regarding the empty list of time features, there must be some problem with stacking zero vectors, I'll have to look into this deeper, because I guess this should be allowed.

**Comment by changebo** [comment]
Thanks, @lostella! Let me know if there's anything I can help with. I would be happy to help fix it.

**Comment by alexcombessie** [comment]
Hi,

Does that mean that this trick allows to train on any sequence data, whatever the frequency? I am dealing with machine data with no timestamp, just order number. 

I am very interested in any workaround or future development you may have on this topic.

Thanks,

Alex

**Comment by alexcombessie** [comment]
Hello @lostella,

Quick followup, would you be able to help clarify the matter?

Thanks,

Alex

**Comment by lostella** [comment]
@alexcombessie we do rely on the assumption that observations have a fixed frequency; the fact that you have an absolute reference time for them is not really important I would say.

If there’s not even a concept of frequency, and you just have sequences of numbers, you can in principle apply the same models (sequence2sequence models are applied in NLP where there’s no time involved either) but whether or not they are well suited is for the experiments to say, I would say.

**Comment by alexcombessie** [comment]
Thanks for your reply. 

Although my data may not be sampled regularly, I plan to resample it before modeling at the second or millisecond level.

In that case, would DeepAR be a good fit ? If so, do you have any advice apart from the trick mentioned earlier in the thread ?

Related question: are there other models within gluon-ts which would be applicable to below second frequency?

**Comment by lostella** [comment]
@alexcombessie you may want to look into WaveNet: that was originally designed for generating audio signals.

**Comment by alexcombessie** [comment]
So within this library, you are suggesting: DeepAR, seq2seq and wavenet. Can I use the same syntax for the three of the them ?

What about other models such as deepstate or note?

**Comment by lostella** [comment]
Well I think the best thing is to try, since I don’t really know about your use case. Also be advised that lots of pieces in the models may have been tailored to larger granularities (say above 1min), so while I’m suggesting to try, I cannot say whether they will work well for sub-second data.

About the models settings, it’s better to check the docstring of each of them to see which options are supported.

**Comment by alexcombessie** [comment]
Alright, I will test and let you know what I find.

At some point it would be great to have seconds (and below) fully supported as canonical freq parameters. This is already the case for pandas.Timestamp so I would expect most models in gluon-ts to support it the same way. I understand that for some models there is a hard limit (for instance prophet cannot forecast below the minute). But there shouldn't be a global canonical frequency limit for all models.

**Comment by alexcombessie** [comment]
Hi @lostella,

Hope all is well. Just wondering what is the status of this feature request in your roadmap?

We are still interested on our side. While we understand there are some "non-official" ways to do it now, we would rather wait for an official support through pandas freq strings.

Cheers,

Alex

**Comment by ziranfeng** [comment]
Hi @lostella, 
`gluonts==0.5.0`
I followed the previous post by setting `lag_seq=[0]` in the training and the model is trained successfully while the in the evaluation using `backtest.backtest_metrics`, the following error shows up:
```
.local/lib/python3.6/site-packages/gluonts/model/deepar/_network.py in get_lagged_subsequences(F, sequence, sequence_length, indices, subsequences_length)
    150             f"{sequence_length}"
    151         )
--> 152         assert all(lag_index >= 0 for lag_index in indices)
    153 
    154         lagged_values = []

AssertionError: 
```
Is there a plan to enable the 0 lag training?

**Comment by lostella** [comment]
@ziranfeng I think you should set the lags to `[1]` (the error message should be fixed, since lags are supposed to be positive)

**Comment by alexcombessie** [comment]
FYI @StanislasGuinel
