### ISSUE TITLE
how to detect anomaly

### ISSUE THREAD

**Issue by vincentff7** [awslabs/gluon-ts#393]
how to modify the code to detect anomaly? can anyone give a demo or  some suggestions? 
thx!

**Comment by dai-ichiro** [comment]
This might be helpful:
[https://github.com/awslabs/gluon-ts/blob/master/examples/anomaly_detection.py](https://github.com/awslabs/gluon-ts/blob/master/examples/anomaly_detection.py)

**Comment by mbohlkeschneider** [comment]
Hi @vincentff7 ,

Thank you for using GluonTS. 

Currently, we don't have more anomaly detection capabilities then the example @dai-ichiro pointed out. 

Feel free to contribute if you happen to work on this!
