### ISSUE TITLE
Import of field names fails: No module named 'gluonts.dataset.field_names'

### ISSUE THREAD

**Issue by rmitsch** [awslabs/gluon-ts#394]
## Description
Following the extended forecast tutorial (https://github.com/awslabs/gluon-ts/blob/master/docs/examples/extended_forecasting_tutorial/extended_tutorial.md) I tried to create my own dataset. To do so, the tutorial utilizes `FieldName`, which is imported with `from gluonts.dataset.field_names import FieldName`. Running that import yields ```No module named 'gluonts.dataset.field_names'``` though.

## To Reproduce
`pip install gluonts`; `from gluonts.dataset.field_names import FieldName`. 

## Error Message
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-abd4351ece59> in <module>
     22 from gluonts.dataset.artificial._base import ComplexSeasonalTimeSeries
     23 from gluonts.dataset.common import ListDataset
---> 24 from gluonts.dataset.field_names import FieldName
     25 
ModuleNotFoundError: No module named 'gluonts.dataset.field_names'
```

## Environment
- Operating system: Linux Mint 19.2
- Python version: 3.7
- GluonTS version: 0.3.3

**Comment by jaheba** [comment]
Hello @rmitsch,

thanks for the issue. We accidentally pushed non-release changes to the website, and thus the website doesn't reflect the 0.3.3 release anymore.

You can see the changes here:
https://github.com/awslabs/gluon-ts/pull/292/files#diff-d79d81943152ab3258436542199054f7

This should be the right import:

```python
from gluonts.transform import FieldName
```

Alternatively, you can install gluon-ts from the master branch, which would let you import it from the new location.

**Comment by rmitsch** [comment]
That works. Thanks for the quick response!
