### ISSUE TITLE
Are static categorical features standardized to zero mean and unit variance?

### ISSUE THREAD

**Issue by lotsoffood** [awslabs/gluon-ts#398]
In the `DeepAR` paper, categorical features are normalized to zero mean and unit variance. Is this being done behind-the-scenes with `GluonTS` when using `static_cat_feats`?

**Comment by andmib** [comment]
@jaheba Any thoughts on this?

**Comment by mbohlkeschneider** [comment]
Hi @lotsoffood  and @andmib,

no, categorical features are not standardized.
