### ISSUE TITLE
Switch PyPi Deployment to GitHub Actions

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#400]
Currently we rely on travis-ci to publish new versions to PyPi.

Instead, we should use Actions instead.

See: https://github.com/pypa/gh-action-pypi-publish

**Comment by lostella** [comment]
@jaheba 0.4 seems like a good occasion to try this out!

**Comment by lostella** [comment]
@jaheba we missed trying this out with 0.4, let’s give it a shot with 0.4.1?

**Comment by lostella** [comment]
#1601 fixed this
