### ISSUE TITLE
Test against mxnet pre-releases and/or master

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#402]
Testing against future versions of mxnet can help both us and mxnet identify incompatibilities, bugs, and undesired breaking changes.

**Comment by jaheba** [comment]
I guess this would be something we would nightly?

**Comment by lostella** [comment]
> I guess this would be something we would nightly?

Is it easy to do with GitHub actions? Otherwise also having an additional stage to our PR setup could work. Maybe one that doesn’t prevent merging (“allow_failures” in Travis)

**Comment by jaheba** [comment]
I think we want to test less that a particular branch works, but more that there are no general issues with mxnet. The setup is similar, only the trigger would be different.

**Comment by jaheba** [comment]
Adressed by #471.

Mxnet release nightly builds to PyPi. We can install them via `pip install --pre mxnet`.
