### ISSUE TITLE
DeepAR model - support of dynamic categorical data?

### ISSUE THREAD

**Issue by rmitsch** [awslabs/gluon-ts#409]
## Description
Regarding the usage of additional features the `DeepAREstimator` in the current dev version 0.3.4  offers the flags 
* `use_feat_dynamic_real`, 
* `use_feat_static_real` and 
* `use_feat_static_cat`. 

Why is `use_feat_dynamic_cat` not offered? Is support for dynamic categorical data planned for `AREstimator`?

Closely related to #392.

**Comment by jaheba** [comment]
Thanks for the suggestion.

 So far we haven't planned adding this to DeepAR, but we are open for contributions!

Let me close this in favour of #392 and let's track the issue there.
