### ISSUE TITLE
Question regarding dirichlet distribution.

### ISSUE THREAD

**Issue by xidulu** [awslabs/gluon-ts#424]
https://github.com/awslabs/gluon-ts/blob/864250951e9b21033778acd626bda422feee9099/src/gluonts/distribution/dirichlet.py#L51

I'm little curious about the implementation of reparameterization gradient. 
As far as I'm concerned, reparameterization for gamma related distributions require some sophisticated tricks, but I cannot find them in the source code.

**Comment by lostella** [comment]
@xidulu you're correct: that should be `False`

@FadhelA this probably needs to be set to `False`, and `Dirichlet.sample` should be implemented instead of `Dirichlet.sample_rep`. Could you look into that?
