### ISSUE TITLE
Remove mxnet from requirements

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#428]
Having mxnet among the requirements creates a problem when people install GluonTS in environments that already have mxnet installed. The reason is that vanilla mxnet gets installed, while other flavors (eg cuda) may be there and needed. A recent case where this caused problems is #426 (but we heard this a lot).

I think we should remove mxnet from the requirements, and update the installation instructions to

```
pip install mxnet==1.4.1 gluonts 
```

an being very clear that mxnet can be omitted if already installed, and that other flavors can be specified if needed.

This is the way GluonCV and GluonNLP handle it too (see [here](https://gluon-cv.mxnet.io/#installation.html) and [here](https://gluon-nlp.mxnet.io/install.html)), and to me that makes perfect sense.

cc @jaheba @vafl

**Comment by jaheba** [comment]
Sounds good to me. Do we require version `1.4.1` or can we be a bit more relaxed?

**Comment by lostella** [comment]
We can be a bit more relaxed, but maybe not now since things will not work on linux with mxnet 1.5.*

**Comment by lostella** [comment]
As a matter of fact, installation instruction already agree with the proposal http://gluon-ts.mxnet.io/master/install.html

However, not quite in the homepage (at the bottom of the page): http://gluon-ts.mxnet.io/master/index.html

**Comment by jaheba** [comment]
Can we have a check that we require some version of mxnet? I guess not?

**Comment by lostella** [comment]
> Can we have a check that we require some version of mxnet? I guess not?

I guess not, we just have to be careful. Hopefully when 1.6 is released we can just omit any version number and just ask to `pip install --upgrade mxnet` together with `gluonts`. I really think that's fine for interactive usage in any case, but at least for now using mxnet 1.5 is out of the question for linux users, so...
