### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#446]
I've just tried to install gluon-ts locally using Python 3.8 and it failed. We just check on this and track what needs to happen to support it.

- [x] enable tests on 3.8 in CI
- [x] solve #1004

**Comment by tomzx** [comment]
I started working on this on my side (see https://github.com/TomzxForks/gluon-ts/runs/309082950) 

The main error that keeps showing up is **AttributeError: type object 'pandas._libs.tslibs.conversion._TSObject' has no attribute '__reduce_cython__'**.
```
test/dataset/test_stat.py:20: in <module>
    import pandas as pd
/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/pandas/__init__.py:30: in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/pandas/_libs/__init__.py:3: in <module>
    from .tslibs import (
/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/pandas/_libs/tslibs/__init__.py:3: in <module>
    from .conversion import localize_pydatetime, normalize_date
pandas/_libs/tslibs/conversion.pyx:234: in init pandas._libs.tslibs.conversion
    ???
E   AttributeError: type object 'pandas._libs.tslibs.conversion._TSObject' has no attribute '__reduce_cython__'
```

I'm not familiar with cython enough to determine what causes this however. Definitely interested to know though!

A quick search led to https://github.com/cython/cython/issues/1953#issuecomment-398128940, it might be useful to solve this issue.

**Comment by nicolaerosia** [comment]
seems to be working just fine

**Comment by lostella** [comment]
#1004 is related
