### ISSUE TITLE
GluonTS Nursery

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#448]
I'm thinking about how we want to split initiatives that are still under (heavy) development from "stable" gluon-ts. On one hand we want to integrate them as soon as possible, and allow people to use them, while at the same time we also want to mark these as experimental.

I like the idea of a "nursery", where projects can mature until they are ready to graduate to proper gluon-ts.

There are probably a few good ways to do it, but at the moment I like having a `gluonts.nursery` package, which generally mirrors gluon-ts' package structure.

For example, a new model `deep_x` would be put into `gluonts/nursery/model/deep_x`.

Thoughts?

**Comment by gjmulder** [comment]
Definitely a great idea! There's not much external visibility of stable versus experimental, currently.

As an active end-user, I want to try both the latest features and have a stable code base, which are inherently contradictory requirements.

With a release gluonts I can perform day-to-day modelling and my regression testing, while still having the option to easily smoke test against the nursery version to provide early feedback to the developers on bleeding edge features.

**Comment by islamalh** [comment]
Hi Thanks for Gluon-ts Nursery. I was trying to use it for production environment for the DeepAR model I trained with gluon-ts. I was looking for a README for it. Is it mature enough to use it in production Environment or do I have to wait for it?

Thanks
