### ISSUE TITLE
Using feat_static_cat

### ISSUE THREAD

**Issue by RXY3832** [awslabs/gluon-ts#451]
I've got a few questions around using feat_static_cat for time series with more than one category.

My data set that I'm wanting to create forecasts on includes both a store id and a product id, per time series.

I'm able to create the predictor object, but how do I request a forecast for a specific store id and product id?

Using the When the forecast is returned, will the data distinguish each time series by store id and product id? Right now, I'm just looking through the array, hoping the order of the array/forecast is the same order of the time series it learned off of. I'm not seeing anything that say for each store id and product id a forecast is for. 

It doesn't look like I'm able to use make_evaluation_predictions. Currently, when I use it on feat_static_cat with both a store id and product id, I get the following error on the returned forecast generator: AssertionError. However, if I use only store id to train the model, then use make_evaluation_predictions, it works fine.

Thanks!

**Comment by mbohlkeschneider** [comment]
Hi @RXY3832,

could you provide a minimal example and the exact error message output? That will help diagnosing the problem.

**Comment by RXY3832** [comment]
Sure thing.

I run the following lines, which run well, up to a point.


from gluonts.evaluation.backtest import make_evaluation_predictions
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  # test dataset
    predictor=predictor,  # predictor
    num_samples=1000,  # number of sample paths we want for evaluation
)

forecasts = list(forecast_it) **This line causes the error.
tss = list(ts_it)

error is:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-639-19e7d512cf80> in <module>()
----> 1 forecasts = list(forecast_it)
      2 tss = list(ts_it)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/model/predictor.py in predict(self, dataset, num_samples)
    307             freq=self.freq,
    308             output_transform=self.output_transform,
--> 309             num_samples=num_samples,
    310         )
    311 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/model/forecast_generator.py in __call__(self, inference_data_loader, prediction_net, input_names, freq, output_transform, num_samples, **kwargs)
    193         **kwargs
    194     ) -> Iterator[Forecast]:
--> 195         for batch in inference_data_loader:
    196             inputs = [batch[k] for k in input_names]
    197             outputs = prediction_net(*inputs).asnumpy()

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/dataset/loader.py in __iter__(self)
    229     def __iter__(self) -> Iterator[DataBatch]:
    230         buffer = BatchBuffer(self.batch_size, self.ctx, self.dtype)
--> 231         for data_entry in self.transform(iter(self.dataset), is_train=False):
    232             buffer.add(data_entry)
    233             if len(buffer) >= self.batch_size:

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    322     ) -> Iterator:
    323         num_idle_transforms = 0
--> 324         for data_entry in data_it:
    325             num_idle_transforms += 1
    326             try:

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    273         self, data_it: Iterator[DataEntry], is_train: bool
    274     ) -> Iterator:
--> 275         for data_entry in data_it:
    276             try:
    277                 yield self.map_transform(data_entry.copy(), is_train)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __iter__(self)
   1284 
   1285     def __iter__(self) -> Iterator[DataEntry]:
-> 1286         yield from self.transformations(self.base_dataset, is_train=True)
   1287 
   1288     def __len__(self):

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    277                 yield self.map_transform(data_entry.copy(), is_train)
    278             except Exception as e:
--> 279                 raise e
    280 
    281     @abc.abstractmethod

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in __call__(self, data_it, is_train)
    275         for data_entry in data_it:
    276             try:
--> 277                 yield self.map_transform(data_entry.copy(), is_train)
    278             except Exception as e:
    279                 raise e

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in map_transform(self, data, is_train)
    290 
    291     def map_transform(self, data: DataEntry, is_train: bool) -> DataEntry:
--> 292         return self.transform(data)
    293 
    294     @abc.abstractmethod

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform.py in transform(self, data)
    309 
    310     def transform(self, data: DataEntry) -> DataEntry:
--> 311         return self.func(data.copy())
    312 
    313 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/evaluation/backtest.py in truncate_target(data)
     84         target = data["target"]
     85         assert (
---> 86             target.shape[-1] >= prediction_length
     87         )  # handles multivariate case (target_dim, history_length)
     88         data["target"] = target[..., :-prediction_length]

AssertionError:

**Comment by AaronSpieler** [comment]
@RXY3832 
Did this problem resolve?
If not, could you please provide maybe a notebook that can be executed to reproduce this error?
