### ISSUE TITLE
Noob question: One "start" field, multiple "target" fields?

### ISSUE THREAD

**Issue by Math9999** [awslabs/gluon-ts#452]
I conducted all steps described in the quick start guide on "https://github.com/awslabs/gluon-ts" and it worked perfectly. 

What do I have to change with the following code, when I have e.g. three columns of "target" time series data (df.featurex, df.featurey, df.featurez). They all have same length, same frequency and are in the same pandas.dataframe. 

**Prepare training dataset:** 

training_data = ListDataset(
    [{"start": df.index[0], "target": df.value[:"2015-04-05 00:00:00"]}],
    freq = "5min"
)

**Prepare test dataset:**

test_data = ListDataset(
    [{"start": df.index[0], "target": df.value[:"2015-04-15 00:00:00"]}],
    freq = "5min"
)

Tried a lot but the only point I arrive at is where three subplots come up and plt.show() creates kind of a mess with three plots on the same window. I just do not get whether that´s correct. When I see the results of the "m4_hourly" forecasts (https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#1.-Datasets) I have to think that there must be only one plot as a result regardless of how many input target time series used. 

![image](https://user-images.githubusercontent.com/57505332/68975981-06c24b80-07f5-11ea-81c0-6a33d213a789.png)

It would be great if you could help me a bit. 

All the best

**Comment by dai-ichiro** [comment]
I'm not sure if it will help you, but try this code once.
```
target_num=3

forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_data,
    predictor=predictor,
    num_samples=100
)

plot_length = 60
prediction_intervals = (50.0, 90.0)

for x, y in zip(ts_it, forecast_it):
    for i in range(target_num):
        plt.subplot(target_num,1,i+1)
        x.iloc[-plot_length:, i].plot()
        y.copy_dim(i).plot(color='g', prediction_intervals=prediction_intervals)
        plt.grid(which='both')

plt.show()
```

**Comment by Math9999** [comment]
Thank you very much! It helped.
