### ISSUE TITLE
Reached maximum number of idle transformation calls.

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#457]
Hello I am testing this code on my forecasting problem but while training the dataset ,i am getting this error  

predictor = estimator.train(training_data=training_data)

Exception: Reached maximum number of idle transformation calls.
This means the transformation looped over GLUONTS_MAX_IDLE_TRANSFORMS=100 inputs without returning any output.
This occurred in the following transformation:
gluonts.transform.InstanceSplitter(forecast_start_field="forecast_start", future_length=24, is_pad_field="is_pad", output_NTC=True, past_length=745, pick_incomplete=True, start_field="start", target_field="target", time_series_fields=["time_feat", "observed_values"], train_sampler=gluonts.transform.ExpectedNumInstanceSampler(num_instances=1.0))

**Comment by gjmulder** [comment]
Have a look at it in the code: https://gluon-ts.mxnet.io/_modules/gluonts/transform.html

I've upped it to 1000 in my environment and I don't see it anymore when building 100's of models in parallel. It is likely a function of your data in that the sampler is not finding enough valid samples. Ideally you'd want to provide more time series, or longer time series.

**Comment by parimuns** [comment]
I am providing 3501 samples for training.Shall I provide more samples ?

**Comment by gjmulder** [comment]
Deep Learning is data hungry. Throw everything _relevant_ at it, but expect to train for a longer time.

I'll have to defer to the developers on the exact (data) conditions for this exception to be thrown.

**Comment by lostella** [comment]
@parimuns what type of estimator is giving you that error?

**Comment by parimuns** [comment]
> @parimuns what type of estimator is giving you that error?

I am using DeepAREstimator.Its giving error in training.My training data contains timestamp and power (35040 samples) of format shown below.


time | electricity
-- | --
01-01-2015 00:00 | 301.85
01-01-2015 01:00 | 298.528
01-01-2015 02:00 | 323.818
01-01-2015 03:00 | 322.328
01-01-2015 04:00 | 321.891




This is the code which i am using for wind forecasting problem 

import pandas as pd
wind = pd.read_csv('training.csv',index_col=0)
wind.head()
from gluonts.dataset.common import ListDataset
training_data = ListDataset(
    [{"start":wind.electricity["01-01-2015 00:00"] , "target": wind.electricity["30-12-2018 00:00"]}],
    freq = "1H")
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer
estimator = DeepAREstimator(freq="1H", prediction_length=100, trainer=Trainer(epochs=10,batch_size=32))
predictor = estimator.train(training_data=training_data)

**Comment by lostella** [comment]
@parimuns some things seem strange in your snippet, try setting your `training_data` as follows:

```python
training_data = ListDataset(
    [{"start": "01-01-2015 00:00" , "target": wind.electricity.values}],
    freq = "1H"
)
```

In fact, the data entries fields are supposed to contain:
* `"start"`: the initial *timestamp* of the time series
* `"target"`: the sequence of values in the time series (as a list or numpy array)

**Comment by parimuns** [comment]
Its working now..Thanks a lot :)

**Comment by ShaikhMS-ds** [comment]
I am getting same error on databricks. I had tried above solution also but not resolved yet
