### ISSUE TITLE
Update numpy in requirements.txt to avoid pip (warning) conflicts 

### ISSUE THREAD

**Issue by lcoulet** [awslabs/gluon-ts#470]
## Description
GluonTS currently states a depency towards Numpy 1.14.x (`~=1.14`)

numpy 1.14 is quite outdated, so when used with other libraries it generates a conflict in pip.
Can numpy be updated to latest (e.g. >=1.17.3), or simply to `>=1.14`?

**Comment by mbohlkeschneider** [comment]
I don't see an issue in doing so. Any concerns, @lostella ?

**Comment by lostella** [comment]
Sure, this makes perfect sense, and was already addressed in #456 (see also #465). The relaxed requirements will be part of the next bugfix release, likely to be issued tomorrow. For now, you will find the changes in the master branch if you want to try it out.

**Comment by lostella** [comment]
Sorry, I misread the issue: to be clear, I think `~=1.14` is fine in that it is equivalent to `>= 1.4, == 1.*` (where the comma means "and").

See: https://www.python.org/dev/peps/pep-0440/#compatible-release

**Comment by lostella** [comment]
@lcoulet `mxnet==1.4.1` has a dependency on `numpy<1.15`, which is what may be causing trouble when installing the package from scratch. You can upgrade to `mxnet>=1.5.0` if it works for you, we saw that it had some issues on Linux, so it's not our recommended version. But if you're on macOS or Windows than it should be fine.

**Comment by jaheba** [comment]
I've tried installing installing numpy to `1.17` and all tests pass. I guess, you should be fine with just upgrading numpy without the need for mxnet.

**Comment by mbohlkeschneider** [comment]
I've also not seen any issues with upgrading numpy. In fact, we have run all our experiments for the GluonTS port of the Gaussian Copula paper on numpy 1.16 and it was fine.

**Comment by mbohlkeschneider** [comment]
There will be error messages from mxnet with newer numpy versions, so we decided to keep it as it is until we can upgrade mxnet.
