### ISSUE TITLE
Refactoring transforms

### ISSUE THREAD

**Issue by mbohlkeschneider** [awslabs/gluon-ts#481]
## Description

Currently, transforms sit at the top level of the source code and we pack everything into one file (https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/transform.py). Since we have more model specific (and complex) transformations coming up (see #341 ), I think we should move this into a dedicated module and also split the transformations into appropriate modules. 

Any objections?

**Comment by jaheba** [comment]
Yes, I agree, that module deserves a closer look.

**Comment by mbohlkeschneider** [comment]
Since #499 is already merged, I'll close this issue.
