### ISSUE TITLE
Comparison with SARIMAX

### ISSUE THREAD

**Issue by aschmu** [awslabs/gluon-ts#487]
Hi, 
I've been experimenting with DeepAR as a way to forecast multiple correlated time series (depending on the setup I have 190 time series or 12000+ ). The time series target are counts (number of booked concert tickets over a 3 year period for each rate category [premium, mid-premium/advanced booking.]). I chose the Negative Binomial output distribution of course given the nature of the target variable, I also have some time varying exogenous variables (price, whether promotion was applied or not etc.)
The goal is to forecast the next 120 days of sold tickets.
Surprisingly SARIMAX seems to be performing pretty well for most individual time series and while Deep AR isn't terrible it's quite often below par compared to SARIMAX : it often underforecasts the target variable, even after optimizing for the prediction quantile.

Are there obvious things I should investigate before concluding that Deep AR isn't maybe the most accurate method here ?
My main reason for using deep AR is that 

- fitting 1 model (SARIMAX) for each time series would be time consuming, probably impossible for the 16k timeseries case
- I imagined that sharing model parameters would make a somewhat stronger forecasting model since the individual time series are correlated (for instance they share the same distribution channel/venue etc.)
- I'd like to have some sort of uncertainty estimate. While doable with SARIMAX under certain conditions, the sample based uncertainty I'd get should be much more robust than confidence intervals derived from SARIMAX.

I'd be grateful for any tips regarding this use case !
thanks

**Comment by mbohlkeschneider** [comment]
Hi @aschmu ,

thank you for using GluonTS. 

It is entirely possible that a different algorithm then DeepAR performs best on your dataset. 

Some questions:
1)  Is your comparison based on the 190 or 12000+ time series setup? 
2) > even after optimizing for the prediction quantile.

What do you mean by that? 

A few suggestions to improve performance: 
1) If you find systematic underforecasting/overforecasting, often this means that the model is not trained long enough. Sometimes it takes some good amount of training to get the time series means right. 
2) Even though negative binomial would be the "correct" choice for counts data, it might make sense to experiment with other outputs. In many cases, StudentT works best.

**Comment by aschmu** [comment]
Hello @mbohlkeschneider thanks for replying so quickly : 


> Is your comparison based on the 190 or 12000+ time series setup?

The comparison was done for the 190 time series setup. I suspect the same problems occur for 12000 though I haven't investigated nearly as much.

> even after optimizing for the prediction quantile.

> What do you mean by that?

Here I'm comparing the real counts with the estimator given by some quantile of the deep ar predictor : I tried optimizing the output quantile q in the range [.5, .8] at the moment on some held-out dataset, though I could also just use the mean I guess.

> If you find systematic underforecasting/overforecasting, often this means that the model is not trained long enough. Sometimes it takes some good amount of training to get the time series means right.

Yes that's something I meant to test try.

> Even though negative binomial would be the "correct" choice for counts data, it might make sense to experiment with other outputs. In many cases, StudentT works best.

Yes that was on my todo too. I'm thinking I should directly model the log counts with a Student distribution right (with some offset to avoid `log(0)` issues) ? otherwise I'd have no guarantee of positive predictions.

**Comment by mbohlkeschneider** [comment]
> Yes that was on my todo too. I'm thinking I should directly model the log counts with a Student distribution right (with some offset to avoid log(0) issues) ? otherwise I'd have no guarantee of positive predictions.

That would be one way of doing it. Of course, it would be nicer to make it work with the Negative Binomial.

**Comment by mbohlkeschneider** [comment]
Closing this for now. Feel free to reopen if there are more questions,
