### ISSUE TITLE
How does Gluon-ts deal with NaN value?

### ISSUE THREAD

**Issue by HanSangJun** [awslabs/gluon-ts#503]
Q1.
Hi, I'm looking for processing NaN value in your DeepAR code.

Can you let me know the mechanism or location of code?

Q2.
What is lags_seq in DeepAR? I cannot find details in DeepAR paper.

According to my understanding, it seems to be similar with data augmentation by lagging target data.  

Thanks a lot.

**Comment by jaheba** [comment]
Hello @HanSangJun,

there is no persistent strategy that models use. I.e., each model can decide how it wants to support NaN-values, if it even does so.

You can find the used default-lags here, which are derived from the frequency of the data: https://github.com/awslabs/gluon-ts/blob/fe065b42051225a8df317db7354d41e266adc1ea/src/gluonts/time_feature/lag.py#L30-L123

The `lags_seq` parameter allows to specify custom lag-values, which (as far as I can see) are not currently used in the code-base.
