### ISSUE TITLE
Question about Test Dataset

### ISSUE THREAD

**Issue by wizcheu** [awslabs/gluon-ts#507]
In the [tutorials](https://gluon-ts.mxnet.io/examples/forecasting/tutorial.html#GluonTS-datasets), we need the **test dataset** contains both training data and pure test data in it.
``` python
print(f"Length of forecasting window in test dataset: {len(test_series) - len(train_series)}")
print(f"Recommended prediction horizon: {dataset.metadata.prediction_length}")
print(f"Frequency of the time series: {dataset.metadata.time_granularity}")
```
> Length of forecasting window in test dataset: 48
Recommended prediction horizon: 48
Frequency of the time series: H

But in time series prediction, we may not have the test data, just to train our model to predict the future target value(s). I have looked over your tutorials and other docs and found no API I wanted. I wander if we can train on the only training data and predict the next `prediction_length` target value(s) in the future that we don't observe.

**Comment by wizcheu** [comment]
Later I set the test data equal to the training data and found little difference(RMSE) on my dataset, is that the way I want?

**Comment by davidlkl** [comment]
Hi Wizcheu, 
You can just train the model without a test dataset.

From the quick example in https://gluon-ts.mxnet.io/index.html:

trainer = Trainer(epochs=10)
estimator = deepar.DeepAREstimator(freq="5min", prediction_length=12, trainer=trainer)
predictor = estimator.train(training_data=data)

prediction = next(predictor.predict(data))
print(prediction.mean)

It is fine to make prediction for the training dataset. But if you are using covariates (aka dynamic_feat here), you need to provide the future value of those covariates in order to make predictions.

**Comment by jaheba** [comment]
As @davidlkl pointed out, the test-dataset is actually optional. It is there to evaluate how well the trained model performs, but it doesn't change anything about the model itself.

We use the test-dataset as the last step of our training to generate the evaluation-metrics and do not use the test-dataset during prediction.

Personally, I also find the naming a bit confusing, but it is the standard term used. See: 
 https://en.wikipedia.org/wiki/Training,_validation,_and_test_sets

**Comment by wizcheu** [comment]
@davidlkl @jaheba Thanks for your excellent reply!

**Comment by miteshyadav** [comment]
@davidlkl The predict function requires field 'TARGET' in the dataset for it to be able to make the prediction for future datasets. This did not quite make sense to me. I am providing the covariates for the future date in the test dataset in GluonTs data format. But it throws an error, saying that the dataset needs a TARGET field

`predictions = list(predictor.predict(test_ds))
mean_predictions = np.mean(predictions[0].samples, axis=0)`

GluonTSDataError                          Traceback (most recent call last)
<ipython-input-74-3e00a07cf00a> in <module>
----> 1 predictions = list(predictor.predict(test_ds))
      2 mean_predictions = np.mean(predictions[0].samples, axis=0)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/mx/model/predictor.py in predict(self, dataset, num_samples, num_workers, num_prefetch, **kwargs)
    169                 freq=self.freq,
    170                 output_transform=self.output_transform,
--> 171                 num_samples=num_samples,
    172             )
    173 

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/model/forecast_generator.py in __call__(self, inference_data_loader, prediction_net, input_names, freq, output_transform, num_samples, **kwargs)
    170         **kwargs
    171     ) -> Iterator[Forecast]:
--> 172         for batch in inference_data_loader:
    173             inputs = [batch[k] for k in input_names]
    174             outputs = predict_to_numpy(prediction_net, inputs)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/itertools.py in get_batch()
     49 
     50     def get_batch():
---> 51         return list(itertools.islice(it, batch_size))
     52 
     53     # has an empty list so that we have a 2D array for sure

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/dataset.py in __iter__(self)
     52     def __iter__(self) -> Iterator[DataEntry]:
     53         yield from self.transformation(
---> 54             self.base_dataset, is_train=self.is_train
     55         )

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
    128     ) -> Iterator:
    129         num_idle_transforms = 0
--> 130         for data_entry in data_it:
    131             num_idle_transforms += 1
    132             try:

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     79         self, data_it: Iterable[DataEntry], is_train: bool
     80     ) -> Iterator:
---> 81         for data_entry in data_it:
     82             try:
     83                 yield self.map_transform(data_entry.copy(), is_train)

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/dataset/common.py in __iter__(self)
    251 
    252             data = data.copy()
--> 253             data = self.process(data)
    254             data["source"] = SourceContext(source=source_name, row=row_number)
    255             yield data

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/dataset/common.py in __call__(self, data)
    451     def __call__(self, data: DataEntry) -> DataEntry:
    452         for t in self.trans:
--> 453             data = t(data)
    454         return data
    455 

~/opt/anaconda3/lib/python3.7/site-packages/gluonts/dataset/common.py in __call__(self, data)
    389         else:
    390             raise GluonTSDataError(
--> 391                 f"Object is missing a required field `{self.name}`"
    392             )
    393 

GluonTSDataError: Object is missing a required field `target`

**Comment by zhongxianmen2020** [comment]
> It is fine to make prediction for the training dataset. But if you are using covariates (aka dynamic_feat here), you need to provide the future value of those covariates in order to make predictions.

Can you please show us an example for the cases with covariates?
