### ISSUE TITLE
predict() with trained predictor and open questions

### ISSUE THREAD

**Issue by jaeniale-fd** [awslabs/gluon-ts#508]
Again, thank you for this great time-series prediction tool. I have some open questions left, that have not been answered in my last issue:

**About predicting with a trained model (not evaluating):**

I have an predictor that has been trained with
```
estimator = DeepAREstimator(freq="d",
                            prediction_length=prediction_length
                            , context_length=context_length,
                            trainer=Trainer(epochs=1), use_feat_dynamic_real=True)
predictor = estimator.train(training_data=training_data)
```
now i want to predict the future. To construct the dataset i want to predict on i use all my training data and the future values of my exogenous variables.

```
training_data = ListDataset(
    [{"start": df.index[0], "target": df.target[:split_date],
      'feat_dynamic_real': df.feature_1[:split_date:],
      'feat_dynamic_real': df.feature_2[:split_date:],
      'feat_dynamic_real': df.feature_3[:split_date:],
      }],
    freq="d"
)
prediciton = predictor.predict(training_with_exogen_future).__next__().mean_ts

```
Which throws me the error:

> ValueError: all the input array dimensions except for the concatenation axis must match exactly

It seems the predict method is complaining about the target variable array not having as many values as the exogenous variable in my ListDataset. Am i using the wrong method, or do i have to specify another parameter?

**About DeepAREstimator parameters:**
Does frequency only refer to the gap between two datapoints e.g. "D" or "H", or does it refer to the timeframe we see a pattern repeat, e.g. "7D". When i have a series of data points where 10 days lay in between, do i specify "10D" or "D"?
How do i determine the value for the context_length parameter? Do i do this with grid search?

**About the backtest (make_evaluation_prediction):**

The documentation says:

> Removes the final window of length prediction_length of the dataset.test that we want to predict
> The estimator uses the remaining data to predict (in the form of sample paths) the “future” window that was just removed

Does that mean it predicts my prediction_length at num_samples different random points in my test set to evaluate the model?

**About Evaluator()**
It has a parameter "seasonality". I could not find any further information in the documentation. How do i determine the best value for this parameter, and what does it actually mean in regards to my dataset?

**About feature importance:**
Is there anything implemented, that shows me how important/how much impact which of my exogenous variables is?

**About my specific hourly data problem:**
Since i actually have hourly data from 8am to 8pm, i think it is a total waste to look model each hour individually as daily data because i lose the influence of the previous hours. So what i did it i set my DeepAREstimator frequency to "H" and prediction length to 360 (15days x 24hours). Then i set the context length to 744 (31days x 4hours) because i want it to look at the last 31 days. I created a feature called store closed. The network should learn itself, that if that feature is 1, the sales are 0 as well, right?

It runs through, and the results make sense, i just want to know if i forgot something, that i did not think of.

**About Hyperparameter Tuning:**
How to find the optimal parameter for context_length / batch size? In my understanding batch size means how many batches of context length the epoch uses to train the network. The question here is do the batches overlap, e.g. batch 1 context of context_length 15 starts today and the other one tomorrow, or today and next one at least 15 days away? Also how do i determine how far back my model has to look? My seasonal pattern repeats every 7 days (determined by acf plot), but the time before that might also have an influence. Is context length just try and error? is there a thumb rule for batch size in relation to dataset size and context length?

Thanks in advance,
Alex

**Comment by jaeniale-fd** [comment]
To answer one of my questions myself: 
Question: 

> About predicting with a trained model (not evaluating)
So what i did is:
```
training = ListDataset(
        [{"start": df.index[0],
          "target": df.target[:split_date],
          "feat_dynamic_real": df.exogen_feature[:split_date]
          }],
        freq="d"
    )
    future = ListDataset(
        [{"start": df.index[0],
          "target": df.target[:split_date],
          "feat_dynamic_real": df.exogen_feature[:split_date + timedelta(days=prediction_length)]
          }],
        freq="d"
    )
    predictor = estimator.train(training_data=training)
    prediction = next(predictor.predict(future))
```
This returns me a Sampleforecast with the predicted values. What i would like to retrieve though is also the borders for the confidence interval. Are those included in the object?

**Comment by jaheba** [comment]
Hello Alex,

sorry for not replying earlier.

The error you are seeing is actually coming numpy. Make sure that your input-data for each time-series has the correct shape (but I think you fixed it in your second example).

> **About DeepAREstimator parameters:**
> Does frequency only refer to the gap between two datapoints e.g. "D" or "H", or does it refer to the timeframe we see a pattern repeat, e.g. "7D". 

---

Frequency is the dataset's granularity, so the time-gap between values. It does not refer to some pattern, since that's basically what we ask the model to find for us.

> When i have a series of data points where 10 days lay in between, do i specify "10D" or "D"?

10D.

---

> How do i determine the value for the context_length parameter? Do i do this with grid search?

I'm not sure how effective tuning this parameter is. I think a good default is 2x the prediction length.

---

> Does that mean it predicts my prediction_length at num_samples different random points in my test set to evaluate the model?

No. It cuts off `prediction_length` values from your test-time-series and compares that against the forecast to get metrics. `num_samples` refers to how many forecasts are generated for each time-series.

---

> It has a parameter "seasonality". I could not find any further information in the documentation. How do i determine the best value for this parameter, and what does it actually mean in regards to my dataset?

I think this argument is used to compare against a seasonal-naive forecast. E.g., if we have hourly frequency, how does our forecast compare against just taking last days value.

These are the default seasonalities used:

```python
    seasonalities = {"H": 24, "D": 1, "W": 1, "M": 12, "B": 5}
```

The parameter allows to use a custom offset value.

---

> Is there anything implemented, that shows me how important/how much impact which of my exogenous variables is?

No. Although I think that's an interesting topic, it's not on our roadmap.

---

> Since i actually have hourly data from 8am to 8pm, i think it is a total waste to look model each hour individually as daily data because i lose the influence of the previous hours. So what i did it i set my DeepAREstimator frequency to "H" and prediction length to 360 (15days x 24hours). Then i set the context length to 744 (31days x 4hours) because i want it to look at the last 31 days. I created a feature called store closed. The network should learn itself, that if that feature is 1, the sales are 0 as well, right?

Sounds reasonable.

However, in my view your `prediction_length` and `context_length` values are uncomfortably large. We use lagged-values to take more data into account than what is provided in `context_length`. You could try and reduce the values for `prediction_length` and `context_length`, but this of course could also worsen the result.

---

> This returns me a Sampleforecast with the predicted values. What i would like to retrieve though is also the borders for the confidence interval. Are those included in the object?

I think you could take quantiles `0` and `100` for that, or access the min and max values of the underlying data.

Still, I think you have to be cautious to not over-interpret the results and there is good reasons why p10 and p90 are common metrics.

**Comment by firmai** [comment]
I think my question relates to your, but this did not give me the right answer. I am in need of further clarification. 

https://github.com/awslabs/gluon-ts/issues/584

**Comment by ramdhan1989** [comment]
`training = ListDataset(
        [{"start": df.index[0],
          "target": df.target[:split_date],
          "feat_dynamic_real": df.exogen_feature[:split_date]
          }],
        freq="d"
    )
    future = ListDataset(
        [{"start": df.index[0],
          "target": df.target[:split_date],
          "feat_dynamic_real": df.exogen_feature[:split_date + timedelta(days=prediction_length)]
          }],
        freq="d"
    )
    predictor = estimator.train(training_data=training)
    prediction = next(predictor.predict(future))`

why target size for training and testing is same ? by looking at df.target[:split_date] in both of dataset

**Comment by ramdhan1989** [comment]
`training = ListDataset(
        [{"start": df.index[0],
          "target": df.target[:split_date],
          "feat_dynamic_real": df.exogen_feature[:split_date]
          }],
        freq="d"
    )
    future = ListDataset(
        [{"start": df.index[0],
          "target": df.target[:split_date],
          "feat_dynamic_real": df.exogen_feature[:split_date + timedelta(days=prediction_length)]
          }],
        freq="d"
    )`

is this for production? where you want to use all data for training and predict future values with known exog. how to configure the dataset for evaluation ?

**Comment by adasiitm** [comment]
Hi @jaeniale-fd, @jaheba, Does this work?
For me it didn't due to shape required can't be provided by below method.
"feat_dynamic_real": df.exogen_feature[:split_date + timedelta(days=prediction_length)]
Please let me know how you made it to work? Thanks!
