### ISSUE TITLE
Is it possible to use gluon on multivariate time series datasets?

### ISSUE THREAD

**Issue by jiwidi** [awslabs/gluon-ts#517]
Hey! Is it possible to use gluon on multivariate time series datasets? If so, is there any example? I have been looking around but haven't found anything.

By multivariate time series dataset I mean something like:

|Index| Date | Target | Feature 1 | Feature 2 | Feature 3|
|---|---|---|---|---|---|
|1|05-12-2019| 4| 1 | 2| 3|
|2|06-12-2019| 2|2| 2| 2|
|3|07-12-2019| 4 |1 | 5| 3|
|4|08-12-2019| 8 |15 | 2| 3|

Thanks!

**Comment by kaleming** [comment]
Yes, you can. 

See this documentation: 
[https://github.com/awslabs/gluon-ts/blob/master/docs/examples/extended_forecasting_tutorial/extended_tutorial.md](url)

Basically you have 4 types of features argument :

> feat_static_cat: static (over time) categorical features, list with dimension equal to the number of features
> feat_static_real: static (over time) real features, list with dimension equal to the number of features
> feat_dynamic_cat: dynamic (over time) categorical features, array with shape equal to (number of features, target length)
> feat_dynamic_real: dynamic (over time) real features, array with shape equal to (number of features, target length)
>

**Comment by jaeniale-fd** [comment]
Have a look at #494 as an example.

**Comment by jiwidi** [comment]
thanks @kaleming and @jaeniale-fd
