### ISSUE TITLE
Defining Prediction length by product

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#518]
Supposing I have a timeseries of many products, like this:

```
{'start': Timestamp('2019-04-01 00:00:00', freq='D'), 'target': array([ 0., 10.,  2.,  2., 21.,  6.,  5.,  3.,  5.,  4., 10.,  8.,  1.,
      ...
        1.,  1.,  1.,  0.,  2.,  0.], dtype=float32), 'feat_static_cat': array([  1, 904]), 'source': SourceContext(source='list_data', row=2)}


{'start': Timestamp('2019-01-01 00:00:00', freq='D'), 'target': array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  6., 16.,  7.,  
    ...
 2.,  2.,  2.,  0.,  5.,  0.], dtype=float32), 'feat_static_cat': array([  2, 904]), 'source': SourceContext(source='list_data', row=3)}
```

I usually train deepar model using a static Predition Length parameter on:

```
estimator = deepar.DeepAREstimator(
                       freq='D', 
                       prediction_length=7 ... )
```

Is it possible to define a prediction_length by product ? Something like this:

`{'start': Timestamp('2019-04-01 00:00:00', freq='D'), 'target': array([ 0., 10.,  2.]), **prediction_length=10**}`

**Comment by lostella** [comment]
Hi @kaleming, unfortunately that is not possible. The `prediction_length` is a property of the model, and defines together with other hyperparameters how the network internally works: this cannot depend on the data that the model is processing.

The only way to achieve what you need, as far as I can see, is to train different models for different products. That is, define:

```python
estimator_1 = deepar.DeepAREstimator(freq='D', prediction_length=7, ...)
estimator_2 = deepar.DeepAREstimator(freq='D', prediction_length=14, ...)

predictor_1 = estimator_1.train(training_data_product_1)
predictor_2 = estimator_2.train(training_data_product_2)
```

**Comment by kaleming** [comment]
It sounds a good solution. 

Thank you @lostella.

**Comment by lostella** [comment]
I’m closing this for now; I will add comments in case there are news about having such an option.
