### ISSUE TITLE
Min Max Scaler

### ISSUE THREAD

**Issue by AaronSpieler** [awslabs/gluon-ts#520]
## Description
Now that we have distributions like the Beta distribution, it only makes sense to create a Min-Max Scaler to map the input into the right input domain (support) for the distributions.

It would need to ne something like https://gluon-ts.mxnet.io/api/gluonts/gluonts.block.scaler.html?highlight=meanscaler#gluonts.block.scaler.MeanScaler the MeanScaler.

**Comment by michiboo** [comment]
Hi is this issue still available?

**Comment by AaronSpieler** [comment]
Yes it is. If you want, I can assign you.

**Comment by michiboo** [comment]
sure

**Comment by mbohlkeschneider** [comment]
Was this implemented in the end of the day?

**Comment by AaronSpieler** [comment]
Not that I know.

**Comment by mbohlkeschneider** [comment]
There will be somewhat more work to this. On top of implementing the scaler we need to change the scaler to implement the forward method that does an affine transformation. Also, this needs to be reflected in the graph(s) of the corresponding methods (maybe warranting an additional block).
