### ISSUE TITLE
make_evaluation_predictions() got an unexpected keyword argument 'num_eval_samples'

### ISSUE THREAD

**Issue by wangqing92** [awslabs/gluon-ts#522]
## Description
make_evaluation_predictions() got an unexpected keyword argument 'num_eval_samples'

## 
from itertools import islice
from gluonts.evaluation.backtest import make_evaluation_predictions
import matplotlib.pyplot as plt
# from gluonts.evaluation.backtest import make_evaluation_predictions
def plot_forecasts(tss, forecasts, past_length, num_plots):
    for target, forecast in islice(zip(tss, forecasts), num_plots):
        ax = target[-past_length:].plot(figsize=(12, 5), linewidth=2)
        forecast.plot(color='g')
        plt.grid(which='both')
        plt.legend(["observations", "median prediction",
                    "90% confidence interval", "50% confidence interval"],loc='lower left')
        plt.savefig("c9.png")
        plt.show()
        

forecast_it, ts_it = make_evaluation_predictions(test_data, predictor=predictor, num_eval_samples=100)
forecasts = list(forecast_it)
tss = list(ts_it)
plot_forecasts(tss, forecasts, past_length=150, num_plots=3)

## Error Message
(Paste the complete error message, including stack trace.)

## Environment
- Operating system:win10
- Python version:3.7
- GluonTS version:0.4.2

(Add as much information about your environment as possible, e.g. dependencies versions.)
i run the code ,it does not work, but it worked before i update the gluonts for 0.3 to 0.4

**Comment by lostella** [comment]
Hi, the "num_eval_samples" argument was renamed to "num_samples" in the 0.4.0 release. See #421, specifically [here](https://github.com/awslabs/gluon-ts/pull/421/files#diff-4e6bb59267ce6649972b425e93b99066R39-R102).
