### ISSUE TITLE
Forcast with Distributions and with Zeroes

### ISSUE THREAD

**Issue by alexhallam** [awslabs/gluon-ts#528]
I would like to know if it is possible to forecast a constant 0s forecast and collect error metrics for it. Also, I would like to forecast with the Poisson distribution. How would I do that with GluonTS?

**Comment by jaheba** [comment]
> I would like to know if it is possible to forecast a constant 0s forecast and collect error metrics for it.

There is a `ConstantValuePredictor`, which works like any other trained predictor:

```python
from gluonts.model.trivial.constant import ConstantValuePredictor

zero_forecaster = ConstantValuePredictor(
    prediction_length=...,
    freq=...,
    value=0.0
)
```


See:

https://github.com/awslabs/gluon-ts/blob/02131317b676467993df9f8dbea79215eb3eb314/src/gluonts/model/trivial/constant.py#L57-L93

**Comment by lostella** [comment]
The Poisson distribution is not currently implemented, thank you for pointing this out. I’ll open an issue about that, feel free to pick it up if you feel like it :-)

**Comment by jaheba** [comment]
Let's close this, and discuss poisson in #529
