### ISSUE TITLE
Implement Poisson distribution

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#529]
The Poisson distribution is currently missing.

**Comment by michiboo** [comment]
@lostella Can I have a go at this?

**Comment by jaheba** [comment]
Sure!

**Comment by lostella** [comment]
@michiboo you can take inspiration from other distributions to see how they are implemented, as well as they're companion "output" layers. See e.g. [negative binomial](src/gluonts/distribution/neg_binomial.py), which also has integer support.

**Comment by michiboo** [comment]
Hi I am unsure what to put in log_prob function, 
I found this formula on the internet but not sure if it is correct
https://mc-stan.org/docs/2_21/functions-reference/poisson-distribution-log-parameterization.html

**Comment by lostella** [comment]
@michiboo you should be implementing the [probability mass function](https://en.wikipedia.org/wiki/Poisson_distribution#Probability_mass_function)
