### ISSUE TITLE
Weekly prediction - from daily data

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#530]
Hi,

Supposing I have a daily timeseries of many products and I want to make a weekly prediction

`{'start': Timestamp('2019-04-01 00:00:00', freq='D'), 'target': array([ 0., 10.,  2.,  2., 21.,  6.,  5.,  3.,  5.,  4., 10.,  8.,  1., 1.,  1.,  1.,  0.,  2.,  0.], dtype=float32), 'feat_static_cat': array([  1, 904]), 'source': SourceContext(source='list_data', row=2)}`

Can I achieve this just changing this argument:

estimator = deepar.DeepAREstimator(freq='W')

And still keeping a daily train dataset ? Or I must resample all my daily dataset before ?

**Comment by mbohlkeschneider** [comment]
Hi @kaleming, 

you would have to resample the data before passing to GluonTS - GluonTS will not do the resampling for you. Changing the frequency in the estimator will just change the [features/lags ](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/time_feature/_base.py#L126)that are used in the model but will do nothing to the data itself.

**Comment by kaleming** [comment]
Thanks @mbohlkeschneider.

Just one more question:

My daily start day is '2019-04-01':

`{'start': Timestamp('2019-04-01 00:00:00', freq='D')

If I resample to weekly it will change to the closest sunday ('2019-04-06').

Does it make difference to keep the 'start' argument on 2019-04-01 (Tuesday) instead of sunday ('2019-04-06') ? Will Gluonts understand that it starts on the same week ?

**Comment by mbohlkeschneider** [comment]
The start field should contain the data in which the target time series starts. So if the resampled data starts on the Sunday, the field should also start on the Sunday.

**Comment by kaleming** [comment]
Ok. 

Thank you again.
