### ISSUE TITLE
Retraining DeepAR model

### ISSUE THREAD

**Issue by aschmu** [awslabs/gluon-ts#537]
Hello, 
I have the following problem : Everyday I have to forecast the next 120 days of some time series of counts given some exogenous features aligned with the said time series. 
Having trained a model once using daily historical data up to march 2019, I checked that the model was fairly good using data until July 2019.
I have now data until december 2019, however I noticed the forecasts weren't really good especially long term. 
I looked for any leaks in my exogenous features but coudn't find any some I'm wondering if the model should maybe be retrained every day using the last avaiable data to keep the same accuracy ?
Cheers

**Comment by ravikolanpaka** [comment]
Hi, were you able to figure this out, I have a use case where I get new data every day. I was wondering if you were able to update the model.
