### ISSUE TITLE
Getting evaluation metrics like prediction interval coverage probability(PICP)

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#543]
Hello ,I would like to ask few questions on evaluation :
1.I am getting results like  "MSE": 3660.0208333333335,
    "abs_error": 29178.109375,
    "abs_target_sum": 19184.365234375,
    "abs_target_mean": 33.306189643012154,
    "seasonal_error": 2.728197371922594,
    "MASE": 18.567732821857597,
    "sMAPE": 1.3565907568101567,
    "MSIS": 225.5677481427731,
    "QuantileLoss[0.1]": 6339.818550300599,
    "Coverage[0.1]": 0.3958333333333333,
    "QuantileLoss[0.5]": 29178.10952758789,
    "Coverage[0.5]": 0.7552083333333334,
    "QuantileLoss[0.7]": 33780.337918281555,
    "Coverage[0.7]": 0.7725694444444444,
    "QuantileLoss[0.75]": 32101.51523065567,
    "Coverage[0.75]": 0.7725694444444444,
    "QuantileLoss[0.8]": 29448.640180969236,
    "Coverage[0.8]": 0.7760416666666666,
    "QuantileLoss[0.85]": 25970.12318687439,
    "Coverage[0.85]": 0.78125,
    "QuantileLoss[0.9]": 21592.694770431517,
    "Coverage[0.9]": 0.796875,
    "QuantileLoss[0.95]": 15795.05863990784,
    "Coverage[0.95]": 0.8038194444444444,
    "RMSE": 60.49810603096045,
    "NRMSE": 1.8164223130715684,
    "ND": 1.5209317075927002,
    "wQuantileLoss[0.1]": 0.330467986448713,
    "wQuantileLoss[0.5]": 1.520931715546463,
    "wQuantileLoss[0.7]": 1.7608264597544852,
    "wQuantileLoss[0.75]": 1.6733165178243905,
    "wQuantileLoss[0.8]": 1.5350333368446543,
    "wQuantileLoss[0.85]": 1.3537129255827818,
    "wQuantileLoss[0.9]": 1.1255360553572664,
    "wQuantileLoss[0.95]": 0.823329750395175,
    "mean_wQuantileLoss": 1.2653943434692412,
    "MAE_Coverage": 0.12352430555555556

now i want to calculatePI coverage probability (PICP), PI normalized averaged width (PINAW),coverage width-based criterion (CWC) which requires 
1.Lower and upper bounds of ith PI
2.Predicted mean observed values

How these metrics can be used to give me the above required values

**Comment by jgasthaus** [comment]
Hi @parimuns,

the metrics you wish to calculate (PICP, PINAW, CWC) are not currently implemented in the GluonTS Evaluator. If you want to compute them, you have two options:

* Extend the ``Evaluator`` class to compute the metrics you want. This should be straightforward and is probably the way to go if you want to compute these metrics for several models going forward. If you go down this route you can also consider opening a pull request and contribute these changes back to GluonTS.

* Obtain the forecast distributions directly from the model and do the evaluation "by hand", e.g. you can use 

https://github.com/awslabs/gluon-ts/blob/4bf7f520c60af177942b4e513286a50650bd8e3d/src/gluonts/evaluation/backtest.py#L39-L46

to obtain pairs of true values and forecasts (represented as ``Forecast`` objects), which you can then compare to compute your required metrics.

Note that the ``Coverage[q]`` metrics in the output you posted are essentially "one-sided" versions of PICP, i.e. for a given quantile level q, ``Coverage[q]`` is the fraction of observations that falls below the q-quantile of the predictive distribution.

**Comment by parimuns** [comment]
Thanks for the help.But if we want to calculate the CRPS ,how we can evaluate that ?

**Comment by mbohlkeschneider** [comment]
Hi @parimuns, 

please see this answer from @jgasthaus below regarding CRPS (from #516):

> Hi @alexhallam,
> 
> the QuantileLoss here is the exactly the pinball loss, scaled by a factor of two (to make it agree with the absolute error for q=0.5), defined as:
> 
> https://github.com/awslabs/gluon-ts/blob/08ab434b1e0946c21010ddbb4248288f8f043599/src/gluonts/evaluation/_base.py#L346-L352

**Comment by mbohlkeschneider** [comment]
Please reopen if you have further questions.
