### ISSUE TITLE
How GluonTs handles non-continuous time stamps

### ISSUE THREAD

**Issue by tqdo** [awslabs/gluon-ts#545]
My data is hourly stock price. There is no missing values but everyday the data is only available from 10am to 4pm hourly. So there is a gap in the time stamps between 2 days (from 4pm until 10am the next day). 

Just curious how do models in GluonTs handle this type of data? Do they consider the gap in time stamps missing values? I don't want to just consider them hourly data starting from the 'start' time because I think the exact time stamp affects how DeepAR generates derived features.

**Comment by gjmulder** [comment]
You're probably going to want to define your own lags as the predefined lags for hourly data will be based around 24 hour days and 7 day weeks, not 6 hour days and 5 day weeks.

**Comment by tqdo** [comment]
@gjmulder Thanks a lot. I see that frequency 'B' for business day is supported but there is no lag for that frequency. Does it mean the models do not generate any addition features if we set the frequency to 'B'.

And if I decide to create my own lags for my case (business hour I guess), is there anything else I need to modify? I feel like the holiday may also be affected.

**Comment by gjmulder** [comment]
What I did is added a bit of debug logging to `lag.py` to see what lags were computed for the frequencies I was interested in, and then used the output as a template to generate my custom lags for the 6 day week daily frequency data I needed to work with. Also, make sure all of your data is in UTC as daylight savings time shifts can cause all manner of headaches.

I haven't used it yet myself, but there's (incomplete / USA) holiday support in [src/gluonts/time_feature/holiday.py](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/time_feature/holiday.py)

**Comment by mbohlkeschneider** [comment]
We head this issue coming up earlier and we do not have an official solution yet. @gjmulder is correct that lags would need to be modified. Currently, there is no "official" business hour support in GluonTS.
