### ISSUE TITLE
Add n-beats implementation

### ISSUE THREAD

**Issue by kashif** [awslabs/gluon-ts#551]
## Description
It might be helpful to add an n-beats implementation

## References
- https://arxiv.org/abs/1905.10437

**Comment by lostella** [comment]
@kashif good point, thanks! I know @AaronSpieler is already working on it, so I'll assign the issue to him to avoid overlaps

**Comment by lotsoffood** [comment]
I would love to give this a shot on my fairly large data set when an MVP branch is ready @AaronSpieler

**Comment by AaronSpieler** [comment]
> 
> 
> I would love to give this a shot on my fairly large data set when an MVP branch is ready @AaronSpieler
I can ping you when its ready.

**Comment by lotsoffood** [comment]
Awesome – please do. I’ll pull the branch down and compare to current best I have with DeepAR.

**Comment by lotsoffood** [comment]
@AaronSpieler Awesome – please do. I’ll pull the branch down and compare to current best I have with DeepAR.

**Comment by AaronSpieler** [comment]
@lotsoffood I havent done extensive testing yet, but thats up next. So feel free to run your own preliminary tests. If you can wait a week though I would recommend waiting until the model is merged into master though.

**Comment by lotsoffood** [comment]
Fantastic! I'll hold out for another week for the master (unless I get some spare time, will love to see how prelim tests look). Thank you for letting me know!

**Comment by AaronSpieler** [comment]
@lotsoffood N-Beats is now merged into master.
