### ISSUE TITLE
Is CANONICALRNNESTIMATOR is similar to RNN ?

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#559]
I want to use RNN for probbailistic time series forecasting.I want to confirm whether canonical RNN estimator is similar to RNN ? Because its results are very bad even worse than simple feed forward NN

**Comment by jgasthaus** [comment]
Hi @parimuns,

yes, `CanonicalRNNEstimator` is an RNN-based model. However, it's a fairly simple, bare-bones model, mostly meant as an example and building block for more complex models.

If you want good performance out of the box, you might want to try the `DeepAREstimator`, which is also an RNN-based model, but implements several improvements that are required for getting good predictive performance.
