### ISSUE TITLE
Forecasting new/unseen time series

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#561]
I know DeepAR model can forecast time series that was not at all used during training. 

What about situations where I don't have any historical data (no `'target'`) of a new product, but I have the next days of 'feat_dynamic_real' and 'feat_static_cat' (indicating similarities with others) ?

**Comment by mbohlkeschneider** [comment]
Hi @kaleming,

you're right, DeepAR can forecast in this case. I think no 'target' at all would not be valid data (at least I haven't tried that yet). In that case, you could just put in a single 'NaN' value to the target time series to mark that there is no data. The model should then generate a forecast in that case.

**Comment by kaleming** [comment]
Thanks @mbohlkeschneider,

It worked.
