### ISSUE TITLE
Are the features (or the covariates) of the target time-series scaled in GluonTS ?

### ISSUE THREAD

**Issue by SU0001** [awslabs/gluon-ts#567]
I understand that the target time series is/are scaled by default. Are the features or covariates, which are added for each target time series, scaled by default too ?  By referring to the original DeepAR paper (https://arxiv.org/pdf/1704.04110.pdf), I understood that the features are scaled to have a zero mean and unit variance. However, does the DeepAR implementation available in GluonTS follow the same ? Thanks in advance.

**Comment by lostella** [comment]
Hi @SU0001, the additional features you provide are *not* scaled at the moment, you can try to manually do the scaling before providing the data to the model, to see if that improves your results.

**Comment by SU0001** [comment]
Hi @lostella. Thank you for the information.
