### ISSUE TITLE
Training one model to work for many time series

### ISSUE THREAD

**Issue by islamalh** [awslabs/gluon-ts#595]
Do you have any advice on how to approach a 'problem' where you need to make forecasts/predictions for 100000+ different customers? In other words, each customer requires a different forecast/prediction. I have 5 years of historical data on hour level (i.e. consumption per hour per customer). Or in other word is it possible to perform hierarchical forecasting using Gluon-ts?

**Comment by kaleming** [comment]
You can make 100000+ individual predictions with gluonts.

First you need to select features from each costumer (e.g age, income, gender). 
Then you can create a global model, based on these features.

**Comment by islamalh** [comment]
Thanks
Is there any specific example of this kind?

**Comment by cesans** [comment]
A global model with extra features describing each client is probably a good model as @kaleming mentioned. DeepAR [[paper](https://arxiv.org/abs/1704.04110)][[gluon-ts](https://gluon-ts.mxnet.io/api/gluonts/gluonts.model.deepar.html)] is a good starting point and [this](https://gluonts-workshop.go-aws.com/part1/gettin_started_gluonts.html) is likely to be the minimal example, the [gluon-ts tutorials](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html) include more details on how to add extra features/covariates.

**Comment by ikramelmbarki** [comment]
does Gluon do the feature engineering steps?
