### ISSUE TITLE
Use of use_feat_static_cat / cardinality in DeepSSM

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#598]
Dear GluonTS Team,

I am trying to use the use_feat_static_cat/cardinality information during the training of deepstate.DeepStateEstimator. The help says

> cardinality – Number of values of each categorical feature
> cardinality: List[int]

I set the use_feat_static_cat = True. The data set looks like this

state | industry | series_id | turnover | time | month | year | LaborMonth | NewYearsMonth | ChristmasMonth
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | A3349849A | 4.4 | 1982-04-01 | 4 | 1982 | 0 | 0 | 0
1 | 1 | A3349849A | 3.4 | 1982-05-01 | 5 | 1982 | 1 | 0 | 0
1 | 1 | A3349849A | 3.6 | 1982-06-01 | 6 | 1982 | 0 | 0 | 0
1 | 1 | A3349849A | 4.0 | 1982-07-01 | 7 | 1982 | 0 | 0 | 0
1 | 1 | A3349849A | 3.6 | 1982-08-01 | 8 | 1982 | 0 | 0 | 0

It is a data set with different time series for different combinations of state/industry. State has 7 unique values, industry 20. The creation of the data set is done as follows

train_ds = ListDataset([{FieldName.TARGET: target, 
                         FieldName.START: start,
                         FieldName.ITEM_ID: item_id,
                         FieldName.FEAT_DYNAMIC_REAL: feat_dynamic_real,
                         FieldName.FEAT_STATIC_CAT: feat_static_cat} 
                        for (target, start, item_id, feat_dynamic_real, feat_static_cat) in zip(target_train,
                                                            start_train,
                                                            item_id_train,
                                                            feat_dynamic_real_train,
                                                            state_industry)],
                      freq = "1M")

I am not sure how to use the cardinality argument in the deepstate.DeepStateEstimator, something like [array([ 7, 20])]? Or is the cardinality expected to be a list, repeating array([ 7, 20]) several times. I tried to use 

estimator = deepstate.DeepStateEstimator(freq = "1M", 
                                         prediction_length = pred_h,
                                         add_trend = True,
                                         num_periods_to_train = 12,
                                         use_feat_dynamic_real = True,
                                         use_feat_static_cat = True,
                                         cardinality = [card_state_industry[0]], 
                                         scaling = True,
                                         trainer = trainer)

where [card_state_industry[0]] is a list with [0] entry [array([ 7, 20])], , but it throws an error 

INFO:root:Using CPU
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-43-1592a36cb92d> in <module>
     10                                          cardinality = [card_state_industry[0]],
     11                                          scaling = True,
---> 12                                          trainer = trainer)
     13                                          # num_layers = 5,
     14                                          # num_cells = 20) # ,distr_output = StudentTOutput()

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/core/component.py in init_wrapper(*args, **kwargs)
    422                 if name != "self"
    423             }
--> 424             model = PydanticModel(**{**nmargs, **kwargs})
    425 
    426             # merge nmargs, kwargs, and the model fields into a single dict

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/pydantic/main.cpython-36m-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for DeepStateEstimatorModel
cardinality -> 0
  value is not a valid integer (type=type_error.integer)

May I ask for advice.

**Comment by parimuns** [comment]
> Dear GluonTS Team,
> 
> I am trying to use the use_feat_static_cat/cardinality information during the training of deepstate.DeepStateEstimator. The help says
> 
> > cardinality – Number of values of each categorical feature
> > cardinality: List[int]
> 
> I set the use_feat_static_cat = True. The data set looks like this
> 
> state	industry	series_id	turnover	time	month	year	LaborMonth	NewYearsMonth	ChristmasMonth
> 1	1	A3349849A	4.4	1982-04-01	4	1982	0	0	0
> 1	1	A3349849A	3.4	1982-05-01	5	1982	1	0	0
> 1	1	A3349849A	3.6	1982-06-01	6	1982	0	0	0
> 1	1	A3349849A	4.0	1982-07-01	7	1982	0	0	0
> 1	1	A3349849A	3.6	1982-08-01	8	1982	0	0	0
> It is a data set with different time series for different combinations of state/industry. State has 7 unique values, industry 20. The creation of the data set is done as follows
> 
> train_ds = ListDataset([{FieldName.TARGET: target,
> FieldName.START: start,
> FieldName.ITEM_ID: item_id,
> FieldName.FEAT_DYNAMIC_REAL: feat_dynamic_real,
> FieldName.FEAT_STATIC_CAT: feat_static_cat}
> for (target, start, item_id, feat_dynamic_real, feat_static_cat) in zip(target_train,
> start_train,
> item_id_train,
> feat_dynamic_real_train,
> state_industry)],
> freq = "1M")
> 
> I am not sure how to use the cardinality argument in the deepstate.DeepStateEstimator, something like [array([ 7, 20])]? Or is the cardinality expected to be a list, repeating array([ 7, 20]) several times. I tried to use
> 
> estimator = deepstate.DeepStateEstimator(freq = "1M",
> prediction_length = pred_h,
> add_trend = True,
> num_periods_to_train = 12,
> use_feat_dynamic_real = True,
> use_feat_static_cat = True,
> cardinality = [card_state_industry[0]],
> scaling = True,
> trainer = trainer)
> 
> where [card_state_industry[0]] is a list with [0] entry [array([ 7, 20])], , but it throws an error
> 
> ## INFO:root:Using CPU
> ValidationError Traceback (most recent call last)
> in
> 10 cardinality = [card_state_industry[0]],
> 11 scaling = True,
> ---> 12 trainer = trainer)
> 13 # num_layers = 5,
> 14 # num_cells = 20) # ,distr_output = StudentTOutput()
> 
> ~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/core/component.py in init_wrapper(*args, **kwargs) 422 if name != "self" 423 } --> 424 model = PydanticModel(**{**nmargs, **kwargs})
> 425
> 426 # merge nmargs, kwargs, and the model fields into a single dict
> 
> ~/miniconda3/envs/gluonts/lib/python3.6/site-packages/pydantic/main.cpython-36m-x86_64-linux-gnu.so in pydantic.main.BaseModel.**init**()
> 
> ValidationError: 1 validation error for DeepStateEstimatorModel
> cardinality -> 0
> value is not a valid integer (type=type_error.integer)
> 
> May I ask for advice.

Is your problem solved ? Because i am facing similar issue..

**Comment by StatMixedML** [comment]
Hi @parimuns ,

See https://github.com/awslabs/gluon-ts/issues/606#issuecomment-583828237 for my answer.
