### ISSUE TITLE
Forecast Reconciliation

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#599]
I am not sure if GluonTS currently supports something like forecast reconciliation of hierarchical or grouped time series. This means that the sum of all forecasts that make up a hierarchy matches to the forecast of the hierarchy. Say, you forecast several time series that are within the same hierarchy + the time series of the total (e.g., all tourism visits in Australia within all territories + Total Tourism of the territories as an aggregate). What forecast reconciliation does it makes sure that the bottom level forecasts match the top-level aggregate forecast. You may find a very good overview here

https://otexts.com/fpp2/hierarchical.html 

As GluonTS is a probabilistic framework, we also need to make sure that the uncertainty attached to the forecasts are corrected. You may find the corresponding paper here

https://robjhyndman.com/publications/coherentprob/

Besides cross-sectional hierarchies, you may also want to include temporal hierarchies, so that you train the  model on daily, weekly and monthly data, and you make sure that all sum up to the monthly forecast. You may find a very good overview here

https://kourentzes.com/forecasting/2019/02/09/towards-the-one-number-forecast/

And a paper on how to combine cross-sectional and temporal aggregation here

https://kourentzes.com/forecasting/wp-content/uploads/2019/02/Kourentzes_2019_Cross_temporal_coherent_forecasts__the_case_of_Australian_tourism_flows.pdf

The paper shows that Cross-temporal coherent forecasts improve accuracy compared to not taking the information into account.

**Comment by timoschowski** [comment]
It doesn't currently! I'm aware of some of the papers, though and it's a line of research that I quite like, but I'd probably try something else instead -- e.g., a big model instead of many small models that you then reconciliate. 

For the moment, you can always try a multivariate model or a global model and use the hierarchy as categorical features. Or, of course, contribute reconcilation back to GluonTS :-)

**Comment by StatMixedML** [comment]
Thanks Tim! I see what I can do with respect to the reconciliation contribution :-)

A somewhat off-topic, I hope you don`t mind: is the deep-factor model still maintained? I am asking because I can find very little notebooks / examples. This is related to this [DeepFactor Question](https://github.com/awslabs/gluon-ts/issues/603#issue-560500196). Would great if you could help. Thanks!

**Comment by gmcaixeta** [comment]
Very relevant topic.
