### ISSUE TITLE
How to use Deep Factor Model

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#603]
Hello,

I am trying to use the Deep Factor Model model using a data set as follows:

state | industry | series_id | turnover | time | month | year 
-- | -- | -- | -- | -- | -- | -- 
7 | 20 | A3349435A | 163.0 | 2016-08-01 | 8 | 2016 
7 | 20 | A3349435A | 167.0 | 2016-09-01 | 9 | 2016 
7 | 20 | A3349435A | 169.7 | 2016-10-01 | 10 | 2016 
7 | 20 | A3349435A | 164.3 | 2016-11-01 | 11 | 2016 
7 | 20 | A3349435A | 175.3 | 2016-12-01 | 12 | 2016 

_state_ and _industry_ are categorical information. I am not sure though how to properly use the model. 

- I can`t find an argument that allows me to use **FEAT_STATIC_REAL**, **FEAT_DYNAMIC_REAL** or **FEAT_STATIC_CAT**.
- How does the model learn local behaviour and how do I properly specify the categorical information in the data? 
- What is the meaning of **num_factors** / **cardinality**?
-  Are there any example notebooks?
- Does the model itself infer time information like month and year?

Greatly appreciate any help!!

**Comment by StatMixedML** [comment]
@lovvge & @lostella 
Kindly asking for an update on this

**Comment by rmitsch** [comment]
I'm also interested in this, particularly in whether the Deep Factor implementation supports feat_static_real / feat_dynamic_real / feat_static_cat.

**Comment by StatMixedML** [comment]
@lovvge Given that some time has passed, is there any chance you can provide an example notebook on how to use deep-factor.

**Comment by kaijennissen** [comment]
@StatMixedML Have you figured out how to use these features?

**Comment by StatMixedML** [comment]
@kaijennissen Unfortunately no. I need to spend more time on going through the code implementation.
