### ISSUE TITLE
DeepState predictor error

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#606]
My data is of form 
	item_id	DEMAND	DryBulb	DewPnt
Timestamp				
01-01-2011 01:00	NH	1044.0	28	26
01-01-2011 02:00	NH	985.0	27	25
01-01-2011 03:00	NH	937.0	28	26
01-01-2011 04:00	NH	914.0	30	27
01-01-2011 05:00	NH	911.0	32	28

there are 3 different item_id .I have set cardinality to 3 and 'feat_static_cat'=True ,but when i use 
predictor = estimator.train(training_data=training_data),it gives me error 
KeyError: 'feat_static_cat'

How to handle categorical features in deep state .Is Deep state good for such kind of data ??
How we can improve accuracy & efficiency of this model ?

**Comment by StatMixedML** [comment]
Hi @parimuns,

you first need to make sure that your data is in a format like this

> train_ds = ListDataset([{FieldName.TARGET: target, 
                         FieldName.START: start,
                         FieldName.ITEM_ID: item_id,
                         FieldName.FEAT_DYNAMIC_REAL: feat_dynamic_real,
                         FieldName.FEAT_STATIC_CAT: feat_static_cat} 
                        for (target, start, item_id, feat_dynamic_real, feat_static_cat) in zip(target_train,
                                                            start_train,
                                                            item_id,
                                                            feat_dynamic_real,
                                                            feat_static_cat)],
                      freq = "1M")

That ensures that gluonts understands that there are additional categorical features in the data. Once that is done, we can move on to training the model

> estimator = deepstate.DeepStateEstimator(freq = "1M", 
                                         prediction_length = 12,
                                         add_trend = True,
                                         use_feat_dynamic_real = True,
                                         use_feat_static_cat = True,
                                         cardinality = card_static, 
                                         scaling = True)
predictor = estimator.train(training_data = train_ds)

*cardinality* has to be a list. Say, you have two categorical static features, with the first one having 7 unique values and the second 20, then *cardinality = [7, 20]*.

Hope that helps

**Comment by parimuns** [comment]
I have a CSV file ,I don't know how to convert in that format (I am new to python programming).Please guide.

**Comment by parimuns** [comment]
I have multiple time series data .i.e i have electricity demand data of 8 zones and I want to hourly predict  demand of all zones.

**Comment by arita37** [comment]
Suppose the cardinalities changed....
does it requires to re-train the full model ????
