### ISSUE TITLE
how to convert csv file to Gluon-TS data format ?

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#615]
I have large csv file having 5 columns  timestamp ,item_id,demand,feature1,feature2
How I can convert it to Gluon-TS data friendly ? (I am new to programming )

**Comment by AaronSpieler** [comment]
Hi,

first I would strongly recommend going through the basic and advanced tutorials, in particular the section [`Datasets`](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#1.-Datasets) in advanced tutorial.

After you went though them:

- you want to create two [`ListDataset`](https://gluon-ts.mxnet.io/api/gluonts/gluonts.dataset.common.html?highlight=listdataset#gluonts.dataset.common.ListDataset), one train and one test set. (The difference being that the test set has all the data the train set has but the time series in it are longer by `prediction_length` number of units.)
- A `ListDataset` is in essence an "Iterable object yielding all items in the dataset." which you will have to build based on your CSV. 
- Each Dict many possible fields, but in your case you probably want to specify:

```
["FieldName.ITEM_ID = 'item_id'",
 "FieldName.START = 'start'", # will depend on your timestamps
 "FieldName.TARGET = 'target'"] # this will be your `demand`
``` 

and 

```
 "FieldName.FEAT_STATIC_CAT = 'feat_static_cat'",
 "FieldName.FEAT_STATIC_REAL = 'feat_static_real'",
 "FieldName.FEAT_DYNAMIC_CAT = 'feat_dynamic_cat'",
 "FieldName.FEAT_DYNAMIC_REAL = 'feat_dynamic_real'",
```

depending on the type of `feature1`, `feature2`.

Additionally you will have to think about what frequency you data is in, i.e. hourly "H" or mostly "M" to define you metadata appropriately. Beyond that there remains the question of the `prediction_length`, which will define where you split your data into train/test.

To get an a feeling for these variables you can look at a provided dataset:
```
from gluonts.dataset.repository.datasets import get_dataset
dataset = get_dataset("m4_hourly", regenerate=True) 
print(list(dataset.train)[:5])
```

gl,
Aaron

**Comment by parimuns** [comment]
> Hi,
> 
> first I would strongly recommend going through the basic and advanced tutorials, in particular the section [`Datasets`](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#1.-Datasets) in advanced tutorial.
> 
> After you went though them:
> 
> * you want to create two [`ListDataset`](https://gluon-ts.mxnet.io/api/gluonts/gluonts.dataset.common.html?highlight=listdataset#gluonts.dataset.common.ListDataset), one train and one test set. (The difference being that the test set has all the data the train set has but the time series in it are longer by `prediction_length` number of units.)
> * A `ListDataset` is in essence an "Iterable object yielding all items in the dataset." which you will have to build based on your CSV.
> * Each Dict many possible fields, but in your case you probably want to specify:
> 
> ```
> ["FieldName.ITEM_ID = 'item_id'",
>  "FieldName.START = 'start'", # will depend on your timestamps
>  "FieldName.TARGET = 'target'"] # this will be your `demand`
> ```
> 
> and
> 
> ```
>  "FieldName.FEAT_STATIC_CAT = 'feat_static_cat'",
>  "FieldName.FEAT_STATIC_REAL = 'feat_static_real'",
>  "FieldName.FEAT_DYNAMIC_CAT = 'feat_dynamic_cat'",
>  "FieldName.FEAT_DYNAMIC_REAL = 'feat_dynamic_real'",
> ```
> 
> depending on the type of `feature1`, `feature2`.
> 
> Additionally you will have to think about what frequency you data is in, i.e. hourly "H" or mostly "M" to define you metadata appropriately. Beyond that there remains the question of the `prediction_length`, which will define where you split your data into train/test.
> 
> To get an a feeling for these variables you can look at a provided dataset:
> 
> ```
> from gluonts.dataset.repository.datasets import get_dataset
> dataset = get_dataset("m4_hourly", regenerate=True) 
> print(list(dataset.train)[:5])
> ```
> 
> gl,
> Aaron

Thanks for your reply.
I tried for my data  with code 

`from numpy import genfromtxt
data = genfromtxt('Git.csv', delimiter=',')
from gluonts.dataset.common import ListDataset
from gluonts.dataset.field_names import FieldName

train_ds = ListDataset([{'target': x, 'start':"01-01-2011 01:00"}
                        for x in data[:, :-prediction_length]],
                       freq=freq)

test_ds = ListDataset([{'target': x, 'start': "01-01-2011 01:00"}
                       for x in data],
                      freq=freq)`


but its showing in form 
[{'target': array([], dtype=float32), 'start': Timestamp('2011-01-01 01:00:00', freq='H'), 'source': SourceContext(source='list_data', row=1)}, {'target': array([], dtype=float32), 'start': Timestamp('2011-01-01 01:00:00', freq='H'), 'source': SourceContext(source='list_data', row=2)}, {'target': array([], dtype=float32), 'start': Timestamp('2011-01-01 01:00:00', freq='H'), 'source': SourceContext(source='list_data', row=3)}, {'target': array([], dtype=float32), 'start': Timestamp('2011-01-01 01:00:00', freq='H'), 'source': SourceContext(source='list_data', row=4)}, {'target': array([], dtype=float32), 'start': Timestamp('2011-01-01 01:00:00', freq='H'), 'source': SourceContext(source='list_data', row=5)}].

I guess its not the right form -


I have sample data in form 
[Git.xlsx](https://github.com/awslabs/gluon-ts/files/4191504/Git.xlsx)
where A,B,C are 3 different regions with 2 features each (dynamic features).Can you please paste code for such file  or correct my code

**Comment by AaronSpieler** [comment]
Hi,

based on the `Git.xlsx` that you sent me:

```
import pandas as pd
import numpy as np
from gluonts.dataset.field_names import FieldName
from gluonts.dataset.common import ListDataset

data = pd.read_csv("Git.csv", sep=";", index_col=0, thousands='.', decimal=',', dtype={col:np.float64 for col in ["A","A_f1","A_f2","B","B_f1","B_f2"]})


prediction_length = 5
freq= "H"

train_ds = ListDataset([{FieldName.TARGET: data["A"][:-prediction_length],
                         FieldName.FEAT_DYNAMIC_REAL: data[["A_f1","A_f2"]][:-prediction_length].values.T,
                         FieldName.START: data.index[0]}],
                         freq=freq)

test_ds = ListDataset([{FieldName.TARGET: data["A"], 
                        FieldName.FEAT_DYNAMIC_REAL: data[["A_f1","A_f2"]].values.T,
                        FieldName.START: data.index[0]}],
                        freq=freq)
```

I made a few assumption there, but I hope this will be enough to get you started.

Best,
Aaron

**Comment by parimuns** [comment]
> import pandas as pd
> import numpy as np
> from gluonts.dataset.field_names import FieldName
> from gluonts.dataset.common import ListDataset
> 
> data = pd.read_csv("Git.csv", sep=";", index_col=0, thousands='.', decimal=',', dtype={col:np.float64 for col in ["A","A_f1","A_f2","B","B_f1","B_f2"]})
> 
> 
> prediction_length = 5
> freq= "H"
> 
> train_ds = ListDataset([{FieldName.TARGET: data["A"][:-prediction_length],
>                          FieldName.FEAT_DYNAMIC_REAL: data[["A_f1","A_f2"]][:-prediction_length].values.T,
>                          FieldName.START: data.index[0]}],
>                          freq=freq)
> 
> test_ds = ListDataset([{FieldName.TARGET: data["A"], 
>                         FieldName.FEAT_DYNAMIC_REAL: data[["A_f1","A_f2"]].values.T,
>                         FieldName.START: data.index[0]}],
>                         freq=freq)

'DataFrame' object has no attribute 'DEMAND'
Thanks .I understood the concept well .

But last doubt ,it is showing ERROR  'DataFrame' object has no attribute 'A'

**Comment by AaronSpieler** [comment]
Well I don't know of course what exact data you're executing the code on, but in your `Git.xlsx` there is one. 

So overall I guess: welcome to the world of debugging...

**Comment by parimuns** [comment]
resolved the issue through Googling...:) Thanks a lot for your help.
