### ISSUE TITLE
GluonTS sets the root logger log-level, it should not

### ISSUE THREAD

**Issue by hdemers** [awslabs/gluon-ts#621]
## Description
GluonTS is configuring loggers, specifically it is setting the log level of the root logger. This prevents the application from properly configuring its loggers.

Generally speaking, configuring loggers should be avoided in libraries and left to the application. As per [The Hitchhiker's Guide to Python](https://docs.python-guide.org/writing/logging/#logging-in-a-library):
> Because the user, not the library, should dictate what happens when a logging event occurs, one admonition bears repeating:
>
> It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers.
>
> Best practice when instantiating loggers in a library is to only create them using the \_\_name__ global variable: the logging module creates a hierarchy of loggers using dot notation, so using \_\_name__ ensures no name collisions.

In two places at least in the code, the root logger is configured:
 - component.py, [line 41](https://github.com/awslabs/gluon-ts/blob/90587baff19a764aed02ffab752f70cf927f50e5/src/gluonts/core/component.py#L41)
 - log.py, [line 22](https://github.com/awslabs/gluon-ts/blob/90587baff19a764aed02ffab752f70cf927f50e5/src/gluonts/core/log.py#L22)

## To Reproduce
```python
import logging
log = logging.getLogger()
log.setLevel('DEBUG')

print(logging.getLevelName(log.getEffectiveLevel()))

from gluonts.model.deepar import DeepAREstimator

print(logging.getLevelName(log.getEffectiveLevel()))
```
This prints:
```
DEBUG
INFO
```
The second print should output `DEBUG` since this is how it was configured on line 3.

This prevents application using gluonts to properly configure their loggers. 

## Environment
- Operating system: Ubuntu
- Python version: 3.6
- GluonTS version: 0.4.2

**Comment by lostella** [comment]
Good point @hdemers, thanks for pointing this out! Let me know in case you intend to open a PR for this, otherwise this will be addressed as soon as someone picks it up

**Comment by hdemers** [comment]
Of course, no problem @lostella. I don't have the time right now to open a PR, but I might in the not too distant future.
