### ISSUE TITLE
How to normalize via transform?

### ISSUE THREAD

**Issue by ehsanmok** [awslabs/gluon-ts#632]
Given a multivariate time-series, it seems there's no builtin transformation to normalize the target according to for example the max value? Thought `AdhocTransform` could be useful but didn't find anyway of using it. Could be useful to add such transform with different normalization schema.

**Comment by mbohlkeschneider** [comment]
Hi @ehsanmok,

thank you for your question. Many of our models (for example [DeepAR](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepar/_estimator.py#L132)) support the `scaling` hyperparamter, which applies mean scaling in the model, which often does a fine job. 

Additionally, you can try the the **[CDtoGaussianTransformation](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/gpvar/_estimator.py#L216)** transformation (this is the marginal transformation from this [paper](https://arxiv.org/abs/1910.03002). Note that the latter one currently only works for multivariate time series.

**Comment by ehsanmok** [comment]
Thank you @mbohlkeschneider ! exactly what I was looking for.
