### ISSUE TITLE
Bayesian Optimization for parameter tuning

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#637]
Hi,

Even though GluonTS models provide competitive forecasts with default parameters, it would be great to have **Bayesian Optimization** to tune the model parameters. That would enhance the usability  and power of GluonTS even more. Grid Search and Random Search shouldn't be used, as Bayesian Optimization provides a more efficient way of finding an optimal set of parameters. Are there any plans to add Bayesian Optimization any time soon?

**Comment by mbohlkeschneider** [comment]
Hi @StatMixedML, 

we do not have any plans for Bayesian Optimization for HPO in GluonTS. 

Generally, we find that HPO does not make a lot of difference for many of our models (this might not apply to all models, of course). Especially DeepAR, which works quite well with default parameters and additional HPO often provides little gain (if any).

**Comment by mbohlkeschneider** [comment]
By the way, we often just use grid search in our studies (see [here](http://proceedings.mlr.press/v89/gasthaus19a/gasthaus19a-supp.pdf) and https://arxiv.org/abs/1910.03002). In our experience, it works just fine.

**Comment by StatMixedML** [comment]
Hi @mbohlkeschneider,

thanks for your fast response! I was asking as SageMaker provides hyperparameter tuning jobs [here](https://sagemaker.readthedocs.io/en/stable/tuner.html). 

Also thanks for the Paper links. Is there any chance you can share the code you used for grid search? That would be great! Despite HPO, are there plans to add **early_stopping** to the framework. For my applications, I do see some dependence of the accuracy on the number of epochs?

**Comment by lostella** [comment]
@StatMixedML this may be related to #617 I guess?

**Comment by StatMixedML** [comment]
Yes. Sorry, didn`t see the other issue. I close this one.

Thanks
