### ISSUE TITLE
Index of forecast is wrong in multivariate Time Series

### ISSUE THREAD

**Issue by mbataillou** [awslabs/gluon-ts#642]
## Description
When forecasting multivariate Time Series the index has the length of the target dimension instead of the prediction length

## To Reproduce

```python
import numpy as np

from gluonts.dataset.common import ListDataset
from gluonts.distribution import MultivariateGaussianOutput
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer
from gluonts.evaluation.backtest import make_evaluation_predictions


train_dataset = ListDataset(
    data_iter=[
        {
            "start": "2019-01-01 00:00:00",
            "target": np.ones(shape=(4, 4)),
        },
    ],
    freq="W",
    one_dim_target=False,
)

test_dataset = ListDataset(
    data_iter=[
        {
            "start": "2019-01-01 00:00:00",
            "target": np.ones(shape=(4, 5)),
        },
    ],
    freq="W",
    one_dim_target=False,
)

estimator = DeepAREstimator(
    'W', prediction_length=1, trainer=Trainer(epochs=3, hybridize=False),
    distr_output=MultivariateGaussianOutput(dim=4),
)

predictor = estimator.train(train_dataset)

forecast_it, ts_it = make_evaluation_predictions(dataset=test_dataset, predictor=predictor, num_samples=10)

forecast_list = list(forecast_it)
ts_list = list(ts_it)
```

## Error Message

DatetimeIndex(['2019-02-03', '2019-02-10', '2019-02-17', '2019-02-24'], dtype='datetime64[ns]', freq='W-SUN')

While it should only be ['2019-02-03']

## Environment
- Operating system: Amazon Linux
- Python version: 3.6
- GluonTS version: a96a0cc4 internal

**Comment by lostella** [comment]
@mbataillou how do you get that output? If I run you code using the master branch, and at the end I execute
```python
print(forecast_list[0].start_date)
print(forecast_list[0].samples.shape)
```

I get

```
2019-02-03 00:00:00
(10, 1, 4)
```

The first is the expected time stamp, the second is the expected layout of the samples: 10 samples, prediction length 1, dimension of the time series 4.

**Comment by mbataillou** [comment]
Hi, I forgot to add it `forecast_list[0].index` is what returns the above.
