### ISSUE TITLE
Wrong way of re-scaling negative binomial output  parameters when using TSMeanScaler

### ISSUE THREAD

**Issue by humcasma** [awslabs/gluon-ts#646]
## Description
In the DeepAR paper, when using a negative binomial distribution as output, the authors suggest dividing the input data by `v_i` and then multiplying the predicted `mean` and `alpha` by `v_i` and `1/sqrt(v_i)`, respectively. However, in the [GluonTS implementation](https://github.com/awslabs/gluon-ts/blob/a4e5584ed52e453b39cef1e08e07eecb700fec46/src/gluonts/distribution/neg_binomial.py#L133)  the predicted `alpha` is multiplied by `sqrt(1 + v_i)`.

**Comment by lostella** [comment]
Related to #604

**Comment by lostella** [comment]
@humcasma I believe the particular scaling which is applied here is motivated by the fact that it works better in practice. The one you propose in #604 was tried, but didn’t appear to perform as good.

Note that the distribution scaling is not necessarily related to the way data is scaled before getting to the input layer of the model. Moreover, in the case of NegativeBinomial, the target data is not scaled down to compute the log likelihood, but rather the distribution’s parameters are scaled up and likelihood is computed directly in the original space (as opposed to other distributions, for which likelihood is computed in the scaled space, and then corrected with the Jacobian determinant).

So, this “upscaling” of the parameters is really arbitrary (as long as it spans the whole parameter range, and only that) and is just needed to help the model guess the distribution parameters quicker.

**Comment by lostella** [comment]
Relabeling and closing this and #604, feel free to continue the discussion here.
