### ISSUE TITLE
Tutorial/example notebooks for GluonTSFramework.

### ISSUE THREAD

**Issue by AaronSpieler** [awslabs/gluon-ts#647]
## Description
Currently, there are no official tutorial notebooks for how to use the GluonTSFramework, which significantly impairs the usability. Therefore, I think we should add one for the `run` and `train` method each.

## References
- Previous attempts at providing those notebooks: https://github.com/awslabs/gluon-ts/commit/df7224985dbbf7c0ad49a6311f53936623067a49

**Comment by lostella** [comment]
+1, that's a good idea. You can look into [here](https://github.com/awslabs/gluon-ts/tree/master/docs/examples) for how other documentation notebooks are included on the webpage. In particular, they are checked in as markdown files: you can export a notebook as markdown, and this will then be converted back to a notebook during the docs build *and executed*. This last bit is maybe an issue in the case of GluonTSFramework, since you probably don't want to spawn a SageMaker job every time you build the docs.

**Comment by AaronSpieler** [comment]
@lostella spawning SageMaker jobs should not be an issue as for that our internal ecr images and bucket paths would have to be in the notebook, which should not be the case anyways.

I was less thinking of an actual executable notebook then more of a notebook where if you fill in your paths and credentials it does what the commenta say it will.

**Comment by lostella** [comment]
> I was less thinking of an actual executable notebook then more of a notebook where if you fill in your paths and credentials it does what the commenta say it will.

Or maybe a notebook that you can load onto a SageMaker Notebook instance and run out of the box? In that case I think no paths nor credentials or roles need to be included.

**Comment by AaronSpieler** [comment]
Thats a fantastic idea! (there should, however, still be comments maybe as to how to do it if one runs them locally)

**Comment by lostella** [comment]
> (there should, however, still be comments maybe as to how to do it if one runs them locally)

(and also instructions on how to build the container!)

**Comment by AaronSpieler** [comment]
> > (there should, however, still be comments maybe as to how to do it if one runs them locally)
> 
> (and also instructions on how to build the container!)

There are already the Readme files: https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/nursery/sagemaker_sdk/docker_images/cpu_serving/README.md 
Personally I think they are enough, since most of the complexity is hidden away in the Makefile that takes care of everything, once you paste your configuration into the appropriate (marked) spots in the file.

**Comment by AaronSpieler** [comment]
This is fixed by #678
