### ISSUE TITLE
Tutorial notebook gets pushed to webpage with empty dataset folder

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#66]
When I download the [tutorial notebook](https://gluon-ts.mxnet.io/_downloads/forecasting.zip) the archive contains also the empty "m4_hourly" directory. As a result, the cell containing
```
dataset = get_dataset("m4_hourly", regenerate=False)
```
fails.

**Comment by jgasthaus** [comment]
The packaging is done here:

https://github.com/awslabs/gluon-ts/blob/master/Makefile#L63

It looks like we are excluding the data files (with `-x "*.json"`) but the empty directory remains.

**Comment by jgasthaus** [comment]
Resolved via #73.
