### ISSUE TITLE
Tracking: mxnet 1.6

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#671]
### To update

- [ ] documentation
- [ ] README.md
- [ ] test-dependencies

### Fix

- [ ] https://github.com/awslabs/gluon-ts/issues/583

### Other

- [ ] Update `numpy~1.18`

**Comment by gitpaulsmith** [comment]
Hi gluonts team! We have been using your package in our research with remarkable success. Thank you for all the work that you have put into it.

Unfortunately, we need to use mxnet-1.6 in our system, and we can't use gluonts anymore until it is updated to mxnet-1.6. Do you have a timeline for releasing this update? Thank you!

**Comment by lostella** [comment]
@gitpaulsmith we don't have a timeline yet, but it appears that #583 is the only blocking issue (yay!). I'll keep you posted as soon as I have more info.

**Comment by lostella** [comment]
@gitpaulsmith we just merged #709 into master, which fixes some issues we had noticed with mxnet 1.6, and updates the tested and recommended version in the README and docs to 1.6.

**Comment by gitpaulsmith** [comment]
@lostella great news--thank you!
