### ISSUE TITLE
forecasts = list(forecast_it) tss = list(ts_it)  it Is very slow. Can someone please help.

### ISSUE THREAD

**Issue by rt3722** [awslabs/gluon-ts#674]
After building the model, the flowing steps are taking lot of time
forecasts = list(forecast_it)
tss = list(ts_it)

Is there any efficient way to do it.

**Comment by rt3722** [comment]
it literally taking more time than training the model? is anyone facing same issue

**Comment by jaheba** [comment]
Do you have a more complete example?

**Comment by rt3722** [comment]
`estimator = WaveNetEstimator(
    prediction_length=custom_ds_metadata['prediction_length'],
    freq=custom_ds_metadata['freq'],
    trainer=Trainer(ctx="cpu",
                    epochs=500,
                    learning_rate=1e-3,
                    hybridize=False,
                    num_batches_per_epoch=200
                   )
)

predictor = estimator.train(train_ds)

forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  # test dataset
    predictor=predictor,  # predictor
    num_samples=10,  # intially i tried 100 it was slow so changed it to 10 even then it is slow

)

forecasts = list(forecast_it)
tss = list(ts_it)`

**Comment by rt3722** [comment]
> Do you have a more complete example?

Do you need more details?

**Comment by mbohlkeschneider** [comment]
Depending on several factors (dataset size, the actual prediction length), the inference can take a while. Note that when casting a list on the forecast iterator you will generate all forecasts (which is might be slow if you have a big dataset).
