### ISSUE TITLE
How to use models like NPTS

### ISSUE THREAD

**Issue by rt3722** [awslabs/gluon-ts#675]
I am trying to use built in NPTS estimator. But i could not figure out how to make predictions with model. Can someone please provide a skeleton example on how to train and predict.

Thank you.

**Comment by jaheba** [comment]
NPTS can be directly used by calling its predictor:

```python
from gluonts.model.npts import NPTSPredictor
from gluonts.dataset.common import ListDataset

predictor = NPTSPredictor(prediction_length=10, freq="D")

data = ListDataset([{"start": "2020", "target": [1, 2, 3, 4, 5, 6]}], freq="D")

predictions = list(predictor.predict(data))
```

**Comment by rt3722** [comment]
Thank you.
