### ISSUE TITLE
Supporting other backends apart from mxnet e.g. PyTorch

### ISSUE THREAD

**Issue by kashif** [awslabs/gluon-ts#686]
## Description
Here I am documenting some changes that would be helpful to use the core gluon-ts library with different backends e.g. PyTorch 

## Changes
- move out `validated` from `gluonts.core.component`
- Dataloader needs to be different for each backend
- `cdf_to_gaussian_forward_transform` should just take numpy arrays
- `DistributionForecast` is coupled to a backend's distribution class
- `ForecastGenerator` classes are backend specific

I will add more recommendations as I progress.

**Comment by AaronSpieler** [comment]
@kashif If you have gathered any more insight, it would be greatly appreciated.

**Comment by kashif** [comment]
@AaronSpieler sure... let me collect up some more points... is it ok if I add them to this issue or would you like me to add it to another?

**Comment by AaronSpieler** [comment]
> @AaronSpieler sure... let me collect up some more points... is it ok if I add them to this issue or would you like me to add it to another?

I think this issue should be fine for now.

**Comment by kashif** [comment]
Cool! The other issues I had involve the dataset and dataloader, ideally the dataset should only be numpy only and thus framework specific dataloaders can use them...

**Comment by AaronSpieler** [comment]
> Cool! The other issues I had involve the dataset and dataloader, ideally the dataset should only be numpy only and thus framework specific dataloaders can use them...

Perfect, we have a concept pull request regarding this: https://github.com/awslabs/gluon-ts/pull/898
We would greatly appreciate if you left some insight regarding this matter there!
