### ISSUE TITLE
Undefined name

### ISSUE THREAD

**Issue by cclauss** [awslabs/gluon-ts#69]
flake8 testing of https://github.com/awslabs/gluon-ts on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./src/gluonts/model/predictor.py:677:35: F821 undefined name 'gluonts'
    def __init__(self, estimator: 'gluonts.model.estimator.Estimator'):
                                  ^
1     F821 undefined name 'gluonts'
1
```

**Comment by geoalgo** [comment]
You are using Python 3.71 but we only support Python 3.6. Could you try with Python 3.6?

**Comment by cclauss** [comment]
Same result.

**Comment by lostella** [comment]
Can you confirm that #86 solved the issue?

**Comment by cclauss** [comment]
I confirm.  Nice work.  Closing.
