### ISSUE TITLE
How can we add covariates to the dataset

### ISSUE THREAD

**Issue by husnejahan** [awslabs/gluon-ts#693]
(Please state your question in the title, and add here any relevant details,
like a description of the problem, code snippets, examples, and so on.)
Hi,

I am curious to add covariates(day of the week, weather information, week of the month, etc) on our dataset. 

Is there any way to do this with gluonts.model.deep_factor package/gluonts.model.deepstate package?

**Comment by antonkiselevtdg** [comment]
It all depends on your dataset. If you add temperature to it - it will be there.

If you want to add features based on your date:

 Creates time series features from datetime index
    
   ```
 df['date'] = df.index
    df['hour'] = df['date'].dt.hour
    df['dayofweek'] = df['date'].dt.dayofweek
    df['quarter'] = df['date'].dt.quarter
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year
    df['dayofyear'] = df['date'].dt.dayofyear
    df['dayofmonth'] = df['date'].dt.day
    df['weekofyear'] = df['date'].dt.weekofyear
```

**Comment by husnejahan** [comment]
Thank you for the description, but if we have some special days in our dataset like sales event or weekend then how could we teach the model those?

**Comment by antonkiselevtdg** [comment]
> Thank you for the description, but if we have some special days in our dataset like sales event or weekend then how could we teach the model those?

You can add a list of holidays/sales events as an additional dimension.  Then it becomes a multivariate time-series. As for national holidays - if it affects data, univariate model will capture that. But if you want to add marketing/sales events - it needs to be added separately. Also, if you want to exclude weekends (let's suppose, there are 0 sales on weekends or holidays), you might want to try models that work well with intermittent data.

**Comment by husnejahan** [comment]
Any example tutorial for using those with gluon-ts packages?

**Comment by lostella** [comment]
@husnejahan many models support so-called dynamic real features (that is, time-dependent, continuous features) through the “feat_dynamic_real” field in datasets. See for example section 1.3 here: http://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#1.-Datasets

For example, in

```python
from gluonts.dataset.common import ListDataset

dataset = ListDataset(
    data_iter=[
        {”start”: ..., “target”: ..., “feat_dynamic_real”: [[1, 2, 3], [5, 6, 7]]},
        ...
    ]
)
```

The first time series in the dataset is accompanied by two time-dependent features, each of (time) length 3.

Note however that many models (including DeepState) automatically enrich the data with so-called “calendar features”, like hours of the day, day of the week, and so on. Still, other information like promotions, prices and so on you can provide by encoding them in the above mentioned field.

**Comment by SaeidShamsaliei** [comment]
> @husnejahan many models support so-called dynamic real features (that is, time-dependent, continuous features) through the “feat_dynamic_real” field in datasets. See for example section 1.3 here: http://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#1.-Datasets
> 
> For example, in
> 
> ```python
> from gluonts.dataset.common import ListDataset
> 
> dataset = ListDataset(
>     data_iter=[
>         {”start”: ..., “target”: ..., “feat_dynamic_real”: [[1, 2, 3], [5, 6, 7]]},
>         ...
>     ]
> )
> ```
> 
> The first time series in the dataset is accompanied by two time-dependent features, each of (time) length 3.
> 
> Note however that many models (including DeepState) automatically enrich the data with so-called “calendar features”, like hours of the day, day of the week, and so on. Still, other information like promotions, prices and so on you can provide by encoding them in the above mentioned field.

Hi,
I thought only DeepAR and DeepState are supporting the feat_dynamic_features since they have ‘use_feat_dynamic_real’ and others just ignore it. So, which models are using it? does N_Beats and seq2seq models using it?
Thank you so much in advance.

**Comment by husnejahan** [comment]
Thank you all
