### ISSUE TITLE
extraction of st.dev of samples

### ISSUE THREAD

**Issue by AIAficionado** [awslabs/gluon-ts#711]
## Description
I was wondering how I can extract the standard deviation without manually calculating from the confidence intervals from the plot graph 

def plot_prob_forecasts(ts_entry, forecast_entry,name):
    plot_length = 1000
    prediction_intervals = (50.0, 90.0)
    legend = ["observations", "median prediction","mean prediction"] + [f"{k}% prediction interval" for k in prediction_intervals][::-1]
    colors = sns.color_palette()
    c1, c2 = colors[0], colors[1]
    fig, ax = plt.subplots(1, 1, figsize=(10, 7))
    ts_entry[-plot_length:].plot(ax=ax)  # plot the time series
    forecast_entry.plot(prediction_intervals=prediction_intervals, show_mean=True,color=c2)
    plt.title("Forecast for {}".format(name))
    
    #ax.plot(ts_entry,forecast_entry.mean, lw=1, color=c2, label='forcecast')  
    plt.grid(which="both")
    plt.legend(legend, loc="upper right")
    plt.show()

## References
- Need standard deviation of my predictions

**Comment by lostella** [comment]
@AIAficionado I'm assuming that the forecast object you get from your model (which model are we talking about?) is of type [SampleForecast](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/forecast.py#L305). If said forecast object is called `forecast, then you can simply do

```
np.var(forecast._sorted_samples(), axis=0)
```

which will give you the variance at each predicted time step.

Feel free to leave the issue open, in case the request is that of adding a method to directly get that.

**Comment by AIAficionado** [comment]
> @AIAficionado I'm assuming that the forecast object you get from your model (which model are we talking about?) is of type [SampleForecast](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/forecast.py#L305). If said forecast object is called `forecast, then you can simply do
> 
> ```
> np.var(forecast._sorted_samples(), axis=0)
> ```
> 
> which will give you the variance at each predicted time step. Can you confirm that this works for you?
> 
> Feel free to leave the issue open, in case the request is that of adding a method to directly get that.
Yes the forecast is sample forecast type, however 
np.var(forecast.samples , axis=0) works and not the forecast.sorted_samples() as sorted_samples() is not a method in the sampleforecast object. 

However, this method provides the sample variance not a population variance, is there a way to extract a population variance?

**Comment by lostella** [comment]
> However, this method provides the sample variance not a population variance, is there a way to extract a population variance?

No, there is no way to do that currently. Once the prediction is included in a SampleForecast, the distributions that generated the samples are lost.

Are you using the DeepAREstimator? Because in that case the model uses sampling internally to obtain multi-step predictions, so I think it’s hard to do that differently.

For models returning a DistributionForecast object instead, no sampling is involved and the original predicted distributions are given. I don’t think any of the models in the package currently do that, but some may be updated to avoid sampling (for example, the SimpleFeedForwardEstimator).
