### ISSUE TITLE
Confidence Intervals

### ISSUE THREAD

**Issue by AIAficionado** [awslabs/gluon-ts#712]
I used a small size of training set and my confidence interval was smaller, surely the confidence interval should be bigger with a smaller size of training set?

This was was using the .plot method on gluonts via the forecasts,tss =  make_evaluation_predictions
(...)

forecests.plot...

**Comment by lostella** [comment]
> surely the confidence interval should be bigger with a smaller size of training set?

I’m not sure one should expect that. Quite the opposite: intuitively, it should be easier to overfit a smaller training set, and get an over-confident model as a result.

**Comment by lostella** [comment]
Closing for now, let me know if something still puzzles you!
