### ISSUE TITLE
Shouldn't The Monkey Patch Have Been Removed When Upgrading to Numpy 1.18

### ISSUE THREAD

**Issue by CMobley7** [awslabs/gluon-ts#715]
In regards to #709, shouldn't [this file](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/monkey_patch/monkey_patch_take_along_axis.py) and all references to it have been removed?

**Comment by lostella** [comment]
That’s likely the case, thanks for pointing that out. Do you want to open a PR for that?
