### ISSUE TITLE
Gluonts DeepAREstimator vs Sagemaker DeepAR Forecasting

### ISSUE THREAD

**Issue by gaganchane** [awslabs/gluon-ts#720]
I'm new to deep-learning based time series forecasting. Could someone explain what the difference is between gluonts deepAR and sagemaker deepAR forecasting? 

I'm trying to replicate the DeepAR results for the M4-hourly dataset (page 8), but realized that this paper refers to the sagemaker deepAR algorithm. 
https://papers.nips.cc/paper/8004-deep-state-space-models-for-time-series-forecasting.pdf

The following gluonts documentation states that this model's code is unrelated to sagemaker DeerAR algorithm. https://gluon-ts.mxnet.io/api/gluonts/gluonts.model.deepar.html

Thanks in advance!

**Comment by jaheba** [comment]
Maybe "unrelated" is a bit misleading, I think independent is a better term. Both versions implement the same algorithm (DeepAR) and thus both implementations can be seen as related.

As the name suggests, the gluon-ts version is a re-implementation and uses mxnet's gluon API, while the version in SageMaker does not.

Generally speaking, both versions should behave similarly, but one shouldn't draw conclusions from the result of one version onto the other.
