### ISSUE TITLE
GluonTS & DeepAR approved for Gov Cloud/IL5?

### ISSUE THREAD

**Issue by ksriniAZ** [awslabs/gluon-ts#723]
Are GluonTS and DeepAR approved for use for government agencies?  Specifically, can anyone please let me know if it is IL5 approved?  If not, are there other libraries you would recommend that are?

Thanks a lot for your help.

**Comment by mbohlkeschneider** [comment]
I don't know what that means, so I guess the answer is no? I cannot comment on other libraries either. Maybe @lostella can?

**Comment by jaheba** [comment]
@ksriniAZ I'm not aware of any approval for gluon-ts. It is also not an AWS product with official support.

There is [DeepAR](https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html) as part of the SageMaker offering, which is not a library, but a service for Forecasting in AWS and should be available in AWS gov regions.
