### ISSUE TITLE
How is transformation function automatically called inside DeepAREstimator class?

### ISSUE THREAD

**Issue by abubakar12** [awslabs/gluon-ts#730]
I was trying to configure that how can i insert create_transformation inside DeepARE estimator class, when i read documentation i felt that i need to use DataLoader class for feeding the transformed data in to the model. But when i checked DeepARE estimator class source code, **create_transformation()** function was already present. I think when i call DeepAREstimator class, this function create_transformation automatically is called and transforms my ListDataset object. is this true? How is create_transformation function automatically called when the DeepARE estimator is used. Should we first call create_transformation() from the DeepARE object. 

Tutorials are not clear about how to add transformations in built in models. Are they automatically applied when we provide then ListDataset().

**Comment by jaheba** [comment]
`create_transform` is called automatically during training:

https://github.com/awslabs/gluon-ts/blob/ed847c9895fb2a225eed0596073a98babd3f31c6/src/gluonts/model/estimator.py#L173-L176

At the moment, only `GluonEstimator` implements that logic. I agree, that we can improve how we handle this generally and update the documentation.

**Comment by abubakar12** [comment]
This has really solved my issue, thank you!
