### ISSUE TITLE
Tutorial [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by DaleThomas68** [awslabs/gluon-ts#75]
I am trying to run the tutorial.  I get FileNotFoundError when running the below piece of code. I have installed gluonts in an Anaconda environment with Python 3.6 on Windows Home 10 version 1803 OS Build 17134.765.  

`from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer

estimator = DeepAREstimator(freq="5min", prediction_length=12, trainer=Trainer(epochs=10))
predictor = estimator.train(training_data=training_data)`

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-9f9f6b8d83d8> in <module>
      3 
      4 estimator = DeepAREstimator(freq="5min", prediction_length=12, trainer=Trainer(epochs=10))
----> 5 predictor = estimator.train(training_data=training_data)

~\Anaconda3\envs\GluonTS\lib\site-packages\gluonts\model\estimator.py in train(self, training_data)
    187     def train(self, training_data: Dataset) -> Predictor:
    188 
--> 189         training_transformation, trained_net = self.train_model(training_data)
    190 
    191         # ensure that the prediction network is created within the same MXNet

~\Anaconda3\envs\GluonTS\lib\site-packages\gluonts\model\estimator.py in train_model(self, training_data)
    180             net=trained_net,
    181             input_names=get_hybrid_forward_input_names(trained_net),
--> 182             train_iter=training_data_loader,
    183         )
    184 

~\Anaconda3\envs\GluonTS\lib\site-packages\gluonts\trainer\_base.py in __call__(self, net, input_names, train_iter)
    177 
    178         with tempfile.TemporaryDirectory(
--> 179             prefix='gluonts-trainer-temp-', dir='/tmp'
    180         ) as gluonts_temp:
    181 

~\Anaconda3\envs\GluonTS\lib\tempfile.py in __init__(self, suffix, prefix, dir)
    790 
    791     def __init__(self, suffix=None, prefix=None, dir=None):
--> 792         self.name = mkdtemp(suffix, prefix, dir)
    793         self._finalizer = _weakref.finalize(
    794             self, self._cleanup, self.name,

~\Anaconda3\envs\GluonTS\lib\tempfile.py in mkdtemp(suffix, prefix, dir)
    368         file = _os.path.join(dir, prefix + name + suffix)
    369         try:
--> 370             _os.mkdir(file, 0o700)
    371         except FileExistsError:
    372             continue    # try again

FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp\\gluonts-trainer-temp-nodyqafj'

**Comment by lostella** [comment]
This looks like a hand-written path somewhere (the “/tmp” path on Windows means nothing).

Thanks, looking into it.

**Comment by lostella** [comment]
#77 should have fixed the issue. Until a new release is tagged, you can try out the master branch by doing

```
cd gluon-ts
pip install .
```

and verify that the tutorial notebook works fine (fingers crossed).

**Comment by DaleThomas68** [comment]
Thank you for the super quick assistance!  That apparently took care of the initial issue that caused things to error out immediately, and I was now able to get to the end of model training.  However, at that point, I hit another (similar) error.
…
INFO:root:End model training
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-9f9f6b8d83d8> in <module>
      3 
      4 estimator = DeepAREstimator(freq="5min", prediction_length=12, trainer=Trainer(epochs=10))
----> 5 predictor = estimator.train(training_data=training_data)

~\Anaconda3\envs\GluonTS\lib\site-packages\gluonts\model\estimator.py in train(self, training_data)
    192         # context as the one that was used during training
    193         with self.trainer.ctx:
--> 194             return self.create_predictor(training_transformation, trained_net)

~\Anaconda3\envs\GluonTS\lib\site-packages\gluonts\model\deepar\_estimator.py in create_predictor(self, transformation, trained_network)
    246         )
    247 
--> 248         copy_parameters(trained_network, prediction_network)
    249 
    250         return RepresentableBlockPredictor(

~\Anaconda3\envs\GluonTS\lib\site-packages\gluonts\support\util.py in copy_parameters(net_source, net_dest)
    126     """
    127     with tempfile.TemporaryDirectory(
--> 128         prefix='gluonts-estimator-temp-'
    129     ) as model_dir:
    130         model_dir_path = str(Path(model_dir) / 'tmp_model')

~\Anaconda3\envs\GluonTS\lib\tempfile.py in __init__(self, suffix, prefix, dir)
    790 
    791     def __init__(self, suffix=None, prefix=None, dir=None):
--> 792         self.name = mkdtemp(suffix, prefix, dir)
    793         self._finalizer = _weakref.finalize(
    794             self, self._cleanup, self.name,

~\Anaconda3\envs\GluonTS\lib\tempfile.py in mkdtemp(suffix, prefix, dir)
    368         file = _os.path.join(dir, prefix + name + suffix)
    369         try:
--> 370             _os.mkdir(file, 0o700)
    371         except FileExistsError:
    372             continue    # try again

FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp\\gluonts-estimator-temp-tth7mv0n'


Sent from Mail for Windows 10

**Comment by lostella** [comment]
That's really weird, because `tempfile` should now use the right default temporary directory for windows (`c:\temp` or something like that).

Maybe something got cached? Did you try installing the master branch on a brand new environment?

**Comment by DaleThomas68** [comment]
Thanks so much for the suggestions and your very timely responses!  I tried installing the master branch both by downloading the files, changing to the directory, and then using ‘pip install .’ and by pip install git+https://github.com/awslabs/gluon-ts.git.  Both errored out for me, and I could not successfully install.  So, I manually edited the two files after using pip gluonts in a new environment and also cleared my temp directory to handle the possible caching issue.  After all of that, things ran successfully. Thanks again!

Here was the error that was reported (I probably made a simple mistake, and I would love to know what it is so I will know in the future if you have time to answer):
(gluon_ts) C:\Users\dalet\Desktop\gluon-ts-master\gluon-ts-master>pip install .
Processing c:\users\dalet\desktop\gluon-ts-master\gluon-ts-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Complete output from command 'C:\Users\dalet\Anaconda3\envs\gluon_ts\python.exe' 'C:\Users\dalet\Anaconda3\envs\gluon_ts\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\dalet\AppData\Local\Temp\tmpg8xig0yc':
  ERROR: Traceback (most recent call last):
    File "C:\Users\dalet\Anaconda3\envs\gluon_ts\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\Users\dalet\Anaconda3\envs\gluon_ts\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\dalet\Anaconda3\envs\gluon_ts\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\dalet\AppData\Local\Temp\pip-build-env-azzwbim1\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\dalet\AppData\Local\Temp\pip-build-env-azzwbim1\overlay\Lib\site-packages\setuptools\build_meta.py", line 126, in _get_build_requires
      self.run_setup()
    File "C:\Users\dalet\AppData\Local\Temp\pip-build-env-azzwbim1\overlay\Lib\site-packages\setuptools\build_meta.py", line 234, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\dalet\AppData\Local\Temp\pip-build-env-azzwbim1\overlay\Lib\site-packages\setuptools\build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 47, in <module>
      stdout=open("/dev/null", "w"),
  FileNotFoundError: [Errno 2] No such file or directory: '/dev/null'
  ----------------------------------------
ERROR: Command "'C:\Users\dalet\Anaconda3\envs\gluon_ts\python.exe' 'C:\Users\dalet\Anaconda3\envs\gluon_ts\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\dalet\AppData\Local\Temp\tmpg8xig0yc'" failed with error code 1 in C:\Users\dalet\AppData\Local\Temp\pip-req-build-aqz77ara

Sent from Mail for Windows 10

**Comment by lostella** [comment]
I think there is a problem in the package build process on Windows. I’ll open a dedicated issue for that.

Good to hear that the fix works though, you will be able to properly get the upgraded package with pip install —upgrade once we release a new version.

**Comment by mabdulal** [comment]
hi, Could you please help me in this error:

Traceback (most recent call last):
  File "C:/Users/mohammed/PycharmProjects/TensorFlowProject/tajrebe.py", line 30, in <module>
    ds_train = tf.keras.preprocessing.image_dataset_from_directory(
  File "C:\Users\mohammed\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\preprocessing\image_dataset.py", line 175, in image_dataset_from_directory
    image_paths, labels, class_names = dataset_utils.index_directory(
  File "C:\Users\mohammed\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\preprocessing\dataset_utils.py", line 65, in index_directory
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users\\mohammed\\PycharmProjects\\TensorFlowProject\\cancer_data\\Train_subfolders/'
