### ISSUE TITLE
model_handler.py for sagemaker multi model endpoint deployment using gluonts

### ISSUE THREAD

**Issue by Jonny-G13** [awslabs/gluon-ts#752]
Hi there,

I had a question regarding loading gluonts models from s3 into a multi model endpoint docker container. I have been looking at the mxnet multi model container code found here:

https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/multi_model_bring_your_own 

My question is regarding the model_handler.py which i'm assuming is built for standard mxnet models. I was wondering if someone could give me some pointers or show me how to go about  loading in the gluonts models in for inference. 

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/container/model_handler.py

**Comment by RutujaWanjari** [comment]
I am also stuck for the same.
I have executed mxnet multimodel, and its running fine.

But I want to write model_handler.py for keras model and scikit -learn model in the same file.
Till now no success. If anyone has any lead on this, please share.

**Comment by yinsong1986** [comment]
https://github.com/aws-samples/amazon-sagemaker-predict-electricity-demand-with-custom-gluonts-container/blob/main/container/model_handler.py
