### ISSUE TITLE
Best pratices with bottom-up aggregation

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#753]
Hello,

I have noticed that DeepAR performs very well using a global model to predict individual sku, however it occurs a 'Over forecasting' when I aggregate it by stores, department or states. I will use M5 competition dataset to illustrate my point:

Here is a nice forecast for an individual product using DeepAR (with the output distribution set to Negative Binomial):

![image_deepar1](https://user-images.githubusercontent.com/51836477/79252396-e8ba4f00-7e57-11ea-93ff-7776c0a511e4.png)

Here is a aggregated forecast (bottom-up) by department using DeepAR:

![image_deepar2](https://user-images.githubusercontent.com/51836477/79253076-04722500-7e59-11ea-8268-345e01807bc8.png)

One solution could be using a top-down approach instead, but:

> "Because historical proportions used for disaggregation do not take account of how those proportions may change over time, top-down approaches based on historical proportions tend to produce less accurate forecasts at lower levels of the hierarchy than bottom-up approaches." (Athanasopoulos, & Hyndman).

Another solution could be something like forecast reconciliation proposed here (#599)

I have seen [this implementation](https://github.com/pyro-ppl/Pyro-M5-Starter-Kit/blob/master/model3.py) using pyro repository that uses a Middle-out approach. They also have these [Deeper hierarchical models](https://pyro.ai/examples/forecasting_iii.html#Deeper-hierarchical-models).

There is also [this implementation](https://github.com/carlomazzaferro/scikit-hts-examples/blob/master/notebooks/M5.ipynb) from scikit-hts repository. 

Have you guys tried some approach with DeepAR (or any gluonts model like gpvar, deepvar) that supports and works fine with hierarchical or grouped time series when using bottom-up aggregation ?

**Comment by samosun** [comment]
I think this is a very practical and inspiring question, how can we add knowledge of internal hierarchical structure into the model?
