### ISSUE TITLE
LSTNet's scaling 

### ISSUE THREAD

**Issue by kashif** [awslabs/gluon-ts#765]
## Description
The scaling in LSTNet is only valid for `NTC` tensors however we are feeding it `NCT` tensors since `output_NTC=False` and thus are not using the scaled values.

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)

```python
put code here
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
put error or undesired output here
```

## Environment
- Operating system:
- Python version:
- GluonTS version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
Thanks @kashif, you’re right. I think this requires having an `axis` option in scaler blocks, what do you think?

**Comment by kashif** [comment]
@lostella right I have that working, also the the LSTNet implementation is wrong, and so I can send both the fixes in 1 PR... is that ok?

**Comment by lostella** [comment]
> @lostella right I have that working, also the the LSTNet implementation is wrong, and so I can send both the fixes in 1 PR... is that ok?

Hey thanks for that, it would be best to have two separate PRs I think

**Comment by kashif** [comment]
ok PR with `axis` coming first

**Comment by kashif** [comment]
fixed
