### ISSUE TITLE
Can not import gluonts.trainer import Trainer

### ISSUE THREAD

**Issue by CEnricoP** [awslabs/gluon-ts#771]
Hi, 

I want to run gluonts on databricks runtime version 6.5 ML, I have installed gluonts and mxnet versions '0.4.2', '1.6.0'.
If I try to import from gluonts.trainer import Trainer I get the following

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-655196341635993> in <module>
----> 1 from gluonts.trainer import Trainer

/databricks/python/lib/python3.7/site-packages/gluonts/trainer/__init__.py in <module>
     14 # Relative imports
     15 from . import learning_rate_scheduler as lrs
---> 16 from ._base import Trainer
     17 
     18 __all__ = ["lrs", "Trainer"]

/databricks/python/lib/python3.7/site-packages/gluonts/trainer/_base.py in <module>
     29 from gluonts.core.component import get_mxnet_context, validated
     30 from gluonts.core.exception import GluonTSDataError
---> 31 from gluonts.dataset.loader import TrainDataLoader, ValidationDataLoader
     32 from gluonts.support.util import HybridContext
     33 from gluonts.gluonts_tqdm import tqdm

/databricks/python/lib/python3.7/site-packages/gluonts/dataset/loader.py in <module>
     23 # First-party imports
     24 from gluonts.core.component import DType
---> 25 from gluonts.dataset.common import DataEntry, Dataset
     26 from gluonts.transform import Transformation
     27 

/databricks/python/lib/python3.7/site-packages/gluonts/dataset/common.py in <module>
     40 from gluonts.core.exception import GluonTSDataError
     41 from gluonts.dataset import jsonl, util
---> 42 from gluonts.dataset.stat import (
     43     DatasetStatistics,
     44     calculate_dataset_statistics,

/databricks/python/lib/python3.7/site-packages/gluonts/dataset/stat.py in <module>
     27 
     28 
---> 29 class ScaleHistogram:
     30     """
     31     Scale histogram of a timeseries dataset

/databricks/python/lib/python3.7/site-packages/gluonts/dataset/stat.py in ScaleHistogram()
     49         bin_counts: Optional[dict] = None,
     50         empty_target_count: int = 0,
---> 51     ) -> None:
     52         self._base = base
     53         self.bin_counts = defaultdict(

/databricks/python/lib/python3.7/site-packages/gluonts/core/component.py in validator(init)
    396                 model_name=f"{init_clsnme}Model",
    397                 __config__=BaseValidatedInitializerModel.Config,
--> 398                 **init_fields,
    399             )
    400         else:

TypeError: create_model() missing 1 required positional argument: '__model_name'
```

**Comment by lostella** [comment]
@CEnricoP this problem occurs when using Pydantic==1.5, can you try downgrading it to Pydantic==1.4? The problem is solved on the master branch, so with the next release Pydantic==1.5 will work fine

**Comment by CEnricoP** [comment]
Thanks @lostella downgrading pydantic fixes the problem!
