### ISSUE TITLE
Nightly build on latest release

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#785]
It sometimes happens that dependencies introduce breaking changes, despite not bumping the major version number. This appears to have happened a few days ago with pydantic (see #768).

Since most of the developers work on the master branch anyway, it would be nice to catch whenever a dependency breaks. One idea to do this would be to have nightly builds installing the latest released tag and running tests.

**Comment by jaheba** [comment]
@arangatang Can you have a look?

This should be similar to the nightly tests we have for mxnet nightly: https://github.com/awslabs/gluon-ts/blob/master/.github/workflows/mxnet_nightly.yml

**Comment by arangatang** [comment]
Ill look into it
