### ISSUE TITLE
ValueError: could not broadcast input array from shape (283) into shape (1)

### ISSUE THREAD

**Issue by Jonny-G13** [awslabs/gluon-ts#808]
Hi there, I am trying to train a multivariate time series model with a dataset containing over 400 time series with a related time series data for each series in the dataset. The data is recorded at a daily interval over the period of approx 1 year. 

Whilst running some initial baseline tests I ran into an issue. While I managed to train both the DeepAR and DeepState models without any problem, when I attempted to train the MQCNN, MQRNN, WaveNET, MLP and DeepFactor models with my training data I got the following error: 

ValueError: could not broadcast input array from shape (283) into shape (1)

and with the test dataset : 

ValueError: could not broadcast input array from shape (71) into shape (1)

However, when I make my test dataset smaller and use only 31 data points the models all train successfully. 

Does anyone know why this is the case and is there any way to get around the issue. I'm only using a portion of my total dataset at the moment. I was hoping to train a model on a dataset containing thousands of time series. 

Any help would be appreciated.

**Comment by lostella** [comment]
@Jonny-G13 could you include a minimal working example, which shows how you set up data & models and raises the errors you encounter?
