### ISSUE TITLE
Forecasting target series without out-of-sample dynamic features

### ISSUE THREAD

**Issue by vblagoje** [awslabs/gluon-ts#815]
Is there a way to forecast target series without dynamic features from the "future"? In my use case, multiple dynamic features `feat_dynamic_real` influence the target series. I had no issues creating the model, using `make_evaluation_predictions` and so on. Once I tried to do actual real-life forecasting my initial attempts were failing in `VstackFeatures` transformer (the `np.vstack(r)` invocation). I realized my `feat_dynamic_real` series are `prediction_length` short so I concluded they are necessary to do forecasting. However, in real-life, I will not have these values when doing forecasting! Am I doing something wrong? What are my options? Thanks in advance.

**Comment by vblagoje** [comment]
I found the answer. @benidis explained everything in his post [here](https://github.com/awslabs/gluon-ts/issues/280#issuecomment-531170377).

**Comment by QiuSYang** [comment]
> Is there a way to forecast target series without dynamic features from the "future"? In my use case, multiple dynamic features `feat_dynamic_real` influence the target series. I had no issues creating the model, using `make_evaluation_predictions` and so on. Once I tried to do actual real-life forecasting my initial attempts were failing in `VstackFeatures` transformer (the `np.vstack(r)` invocation). I realized my `feat_dynamic_real` series are `prediction_length` short so I concluded they are necessary to do forecasting. However, in real-life, I will not have these values when doing forecasting! Am I doing something wrong? What are my options? Thanks in advance.
I encountered the same problem. There was no 'feat_dynamic_real' characteristic in the prediction. If the make_evaluation_predictions() function is used to measure, the target length will be removed in the process, but predict() function will not. How can I solve this problem?

**Comment by Saifbenhmida** [comment]
@QiuSYang  did you solve the problem cause after 3 years i have the same problem  there is a problem with the predict methode in my side but it work with the make_evaluation_prediction
