### ISSUE TITLE
reference to negative binomial distribution formulations

### ISSUE THREAD

**Issue by samosun** [awslabs/gluon-ts#816]
different from ![image](https://user-images.githubusercontent.com/20217808/81472067-1a8cbe80-9228-11ea-9913-82884320b20f.png),
I think negative binomial distribution in gluonts/distribution/neg_binomial.py is a more general form, where can I find more references to the negative binomial probability function defined in this form? Any suggestions? Thank you very much.
I tried on wiki, but to find NB defined only on intergers.

```
class NegativeBinomial(Distribution): 
    def log_prob(self, x: Tensor) -> Tensor:
        alphaInv = 1.0 / self.alpha
        alpha_times_mu = self.alpha * self.mu
        F = self.F
        ll = (
            x * F.log(alpha_times_mu / (1.0 + alpha_times_mu))
            - alphaInv * F.log1p(alpha_times_mu)
            + F.gammaln(x + alphaInv)
            - F.gammaln(x + 1.0)
            - F.gammaln(alphaInv)
        )
        return ll
```

**Comment by lostella** [comment]
@samosun I believe the Wikipedia article covers it: under "alternative formulations" you can find how the probability mass function can be expressed in terms of the gamma function. Note that we're parametrizing negative binomial distributions using directly the mean `mu = p*r/(1-p)` and `alpha = 1/r`.

**Comment by samosun** [comment]
@lostella thank you for replying, I should have been more clear with my question, I thought X in Wiki has "Support"
![image](https://user-images.githubusercontent.com/20217808/82214722-da74bc80-9948-11ea-9c91-6ae196aeb7ef.png), defined only on intergers. but in the code X can be any real number, I think there's a more general form comparing to X is counting number?

**Comment by lostella** [comment]
> defined only on intergers

I think it's defined almost everywhere in the complex plane (with the exception of numbers with negative integer real part). For example, if `x` in the code is nonnegative real then the expression should evaluate with no problems. I think the wikipedia article talks about k = 0, 1, 2, ... because that's where the interpretation in terms of Bernoulli trials makes sense.
