### ISSUE TITLE
FileDataset - (ValueError: setting an array element with a sequence)

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#820]
## Description
Hello, 

I am saving my files (training/test) into a json file. Then I use the FileDataset function to load the dataset:

## To Reproduce
```
data = FileDataset(path, freq="D")
list(test_data)
```

## Error message or code output
However it is returning an error, when I try to load:

```
----> 1 list(test_data)

~/anaconda3/envs/numba/lib/python3.6/site-packages/gluonts/dataset/common.py in __iter__(self)
    215         for json_line_file in self._json_line_files:
    216             for line in json_line_file:
--> 217                 data = self.process(line.content)
    218                 data["source"] = SourceContext(
    219                     source=line.span.path, row=line.span.line

~/anaconda3/envs/numba/lib/python3.6/site-packages/gluonts/dataset/common.py in __call__(self, data)
    470     def __call__(self, data: DataEntry) -> DataEntry:
    471         for t in self.trans:
--> 472             data = t(data)
    473         return data
    474 

~/anaconda3/envs/numba/lib/python3.6/site-packages/gluonts/dataset/common.py in __call__(self, data)
    405         value = data.get(self.name, None)
    406         if value is not None:
--> 407             value = np.asarray(value, dtype=self.dtype)
    408 
    409             if self.req_ndim != value.ndim:

~/anaconda3/envs/numba/lib/python3.6/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    490 
    491     """
--> 492     return array(a, dtype, copy=False, order=order)
    493 
    494 

ValueError: setting an array element with a sequence.
```

## Environment
- Operating system:Ubuntu 18.04
- Python version: 3.6.7
- GluonTS version: 0.5

It is a json file that looks like this:

`
{"start": "2011-01-29", "feat_static_cat": [0, 0, 0, 0], "feat_dynamic_real": [[30, 30, 30, 30, 30, 30 ..], [4, 4, 4, 4, 4, 4, 4, ...], [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4....], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2...], [0, 0, 0, 1, 1, 1...], [2.240234375, 2.240234375, 2.240234375, 2.240234375 ...]], "target": [5, 5, 1, 1, 0, 3, 3, 4, 9, 4, 7, 1, 2, 4, 14 ...]}`

**Comment by kaleming** [comment]
It seems the error is cause by trying to create an array from lists or arrays of differing length. Without the dtype the following creates an object dtype array; with a numeric dtype it raises this error.

I will check if there are feat_dynamic_real arrays with different sizes.

**Comment by lostella** [comment]
> I will check if there are feat_dynamic_real arrays with different sizes.

Yes, those should all have the same length

**Comment by kaleming** [comment]
The problem was solved. 
There was some arrays with different sizes (inside feat_dynamic_real).
