### ISSUE TITLE
Run nightly tests failing since new release 

### ISSUE THREAD

**Issue by arangatang** [awslabs/gluon-ts#821]
## Description
Updating the release with new requirements to install breaks the nightly builds.
see issue #785 for nightly build pull request

The added requirements are       
```bash
requirements/requirements-extras-sagemaker-sdk.txt
requirements/requirements-extras-m-competitions.txt
```

## To Reproduce
 run the nightly builds.

## Error message or code output
See:
https://github.com/awslabs/gluon-ts/actions/runs/103054335
https://github.com/awslabs/gluon-ts/actions/runs/103048935

## Environment
- GluonTS version: V 0.5.0

**Comment by lostella** [comment]
is this a problem in the package itself or just the nightly tests setup?

**Comment by arangatang** [comment]
Just the nightly tests as I understand it as we are now depending on Sagemaker but the dependencies are currently not installed as part of the `requirements-tests.txt` from which all previous dependencies was installed.  
Now the Sagemaker tests are installed from separate requirements files.
