### ISSUE TITLE
Evaluating GPVAREstimator for multivariate series prediction

### ISSUE THREAD

**Issue by vblagoje** [awslabs/gluon-ts#832]
I am trying to understand how to use GPVAREstimator for multivariate series prediction. For the sake of simplicity, let's use a readily available exchange_rate dataset. Here is what I think one should do:

```
from gluonts.dataset.common import TrainDatasets
from gluonts.dataset.multivariate_grouper import MultivariateGrouper
from gluonts.dataset.repository.datasets import get_dataset
from gluonts.evaluation.backtest import make_evaluation_predictions
from gluonts.model.gpvar import GPVAREstimator
from gluonts.trainer import Trainer

num_of_series = 8  # num of series in dataset


def load_multivariate_dataset(dataset_name: str):
    ds = get_dataset(dataset_name)
    grouper_train = MultivariateGrouper(max_target_dim=num_of_series)
    grouper_test = MultivariateGrouper(max_target_dim=num_of_series)
    return TrainDatasets(
        metadata=ds.metadata,
        train=grouper_train(ds.train),
        test=grouper_test(ds.test),
    )


dataset = load_multivariate_dataset("exchange_rate")
metadata = dataset.metadata

estimator = GPVAREstimator(
    prediction_length=dataset.metadata.prediction_length,
    target_dim=num_of_series,
    freq=metadata.freq,
    trainer=Trainer(
        epochs=2
    )
)
predictor = estimator.train(training_data=dataset.train)

forecast_it, ts_it = make_evaluation_predictions(
    dataset.test, predictor=predictor, num_samples=100
)

```

When I inspect the values of the forecast_it I can see that predictions are generated for all eight series, using the horizon of 30 days. Predictions seem ok. 

Am I doing everything correctly up there?

If so, how would I tune GPVAREstimator with Evaluator similar to this approach [here](https://github.com/awslabs/gluon-ts/blob/master/examples/evaluate_model.py)? The evaluator does not seem to handle additional dimensions easily. Any suggestions on how to do evaluations with Evaluator for multivariate series?

**Comment by mbohlkeschneider** [comment]
Hi @vblagoje, 

try the `[MultivariateEvaluator](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/evaluation/_base.py#L560)` instead.

**Comment by vblagoje** [comment]
Wow, cool, it works @mbohlkeschneider . I get individual dimension stats and aggregate as well. I can really start playing now. Thanks a lot!
