### ISSUE TITLE
Deepstate model parameters

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#838]
I am running deep state model with add_trend=True ,its running fine but now if I want to use issm ,how can I use that and how can I get parameters from that like transition coefficient etc ? What changes need to be done in estimator ?
`.estimator=DeepStateEstimator(freq='H',
        prediction_length=48,
        cardinality=[10],
        add_trend= True,
        num_periods_to_train= 4,
        trainer= Trainer(
            epochs=20, num_batches_per_epoch=50, hybridize=False),
        num_layers= 3,
        num_cells= 40,
        cell_type= "lstm",
        num_parallel_samples = 100,
        dropout_rate= 0.1,
        use_feat_dynamic_real = False,
        use_feat_static_cat = False,
        embedding_dimension = None,
        issm = None,
        scaling = True,
        time_features = None,
        noise_std_bounds = ParameterBounds(1e-6, 1.0),
        prior_cov_bounds = ParameterBounds(1e-6, 1.0),
        innovation_bounds = ParameterBounds(1e-6,  @0.01))`
@rshyamsundar

**Comment by lostella** [comment]
Hi @parimuns, the linear dynamical system coefficients are output by the RNN, so you will need to look into the network to inspect those:
* [here](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepstate/_network.py#L228-L238) the network computes the coefficient in the "conditioning" time range (i.e. the past, where data is available).
* [here](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepstate/_network.py#L254-L263) the network does the same for the "prediction" time range.

These are not exposed at the moment, so the best way to inspect them is to put a breakpoint in the network. Hope this helps!

**Comment by parimuns** [comment]
Thanks a lot.
