### ISSUE TITLE
prediction interval coverage width

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#845]
Hello
I am evaluating my models using Gluon-Ts and as I understand "coverage" tells the coverage probability and MSIS rewards and penalises the coverage width. But if I only want to evaluate the coverage width, how can I obtain that? Also, is it possible to obtain lower and upper bounds of my predicted values using gluont-ts.evaluator?

**Comment by lostella** [comment]
Hey @parimuns what do you mean exactly by “coverage width”? And what upper and lower bounds are you interested in?

**Comment by lostella** [comment]
To be clear: the **coverage** which is computed in evaluations is associated with a quantile level, and indicates how much of the data is below the predicted quantile for the given level. In pseudocode:

    coverage(x, alpha) = mean(x < predicted_quantile(alpha))

where `x` is the observed data, and `alpha` is the quantile level between 0 and 1. In actual code this is computed here:

https://github.com/awslabs/gluon-ts/blob/00b138bf2b2ff9612d00f6c13c9d866206d70d50/src/gluonts/evaluation/_base.py#L439-L440

This is useful to understand how "calibrated" the predicted distribution is: ideally one would want `coverage(x, alpha) = alpha` for any `alpha` between 0 and 1.

This said, I'm not sure what you mean by coverage width and upper/lower bounds.

**Comment by parimuns** [comment]
Thanks for replying. I understood the "coverage".Now, for probabilistic forecasting,I have to forecast the range that my prediction will lie in between these intervals and there must be some lower bound and there must be some upper bound. So,I want to evaluate those bounds and the difference between these bounds is the "coverage width".

For example, Assuming some probability distribution I predicted that my output at certain time instant will be 628 and I predicted my bounds will be 500 and 1000 ,so my coverage width is "500" and lower bound is 500 and upper bound is 1000.I hope you understand my query. I guess MSIS score takes into account "coverage width" and penalises the values which are below and above these bounds but I specifically want the "bounds" and "width". 

So, how can I obtain these values using gluon-ts?

**Comment by lostella** [comment]
@parimuns in the Evaluator class, the upper and lower bounds which are evaluated with MSIS are controlled through the constructor parameter alpha, see relevant documentation here: https://github.com/awslabs/gluon-ts/blob/f76bf434177ce07c00c72d2109b55e3842c66562/src/gluonts/evaluation/_base.py#L86

By default alpha=0.05, which means that the predicted 0.025-quantile and 0.975-quantile will be used as lower and upper bounds, respectively.

However, the internal logic is a bit more complicated than that unfortunately, so you must also include those quantile levels as part of the “quantiles” argument: https://github.com/awslabs/gluon-ts/blob/f76bf434177ce07c00c72d2109b55e3842c66562/src/gluonts/evaluation/_base.py#L309

I’m opening an issue about it, but I hope this clarifies a bit how to get what you need.

**Comment by parimuns** [comment]
Thanks for answering.I didn't understand 
"However, the internal logic is a bit more complicated than that unfortunately, so you must also include those quantile levels as part of the “quantiles” argument:

gluon-ts/src/gluonts/evaluation/_base.py"

Or can you please suggest me some reference, where the internal calculations of lower and upper bounds for MSIS  used in GLUON-TS  are explained?

**Comment by lostella** [comment]
@parimuns I’ve opened issue #848 with the goal of making it more explicit. For now the link to the code I posted in my previous message is the most accurate description of what’s going on. I’ll propose something for #848, I think it should be easy to clarify the interface & documentation.

Thanks for raising the issue!

**Comment by parimuns** [comment]
Ok..Thanks a lot..

**Comment by lostella** [comment]
@parimuns #848 was resolved with #849. The situation should now be much clearer:

The Evaluator has a parameter `alpha`, which controls the upper and lower predicted quantiles used to compute MSIS. By default `alpha=0.05`, in which case `L` is the 0.025-quantile and `U` is the 97.5 quantile: between them lies 95% of the distribution (`1-alpha`).

If you want to access these bounds, you can simply take the all your `forecast` objects and use

    forecast.quantile(0.025)
    forecast.quantile(0.975)
