### ISSUE TITLE
Using gluonts models in production

### ISSUE THREAD

**Issue by Jonny-G13** [awslabs/gluon-ts#847]
Hi there, just had a question regarding using gluonts models in production. Is there a reason why one wouldn't do so? I think I read somewhere that amazon use some gluonts models for production purposes. So I just wanted to know if there are any potential show stoppers that I should be aware of.

Also I noticed that when the I save my model after training the following warning message is given: 

"WARNING:root:Serializing RepresentableBlockPredictor instances does not save the prediction network structure in a backwards-compatible manner. Be careful not to use this method in production."

Is there an alternative method to saving the models that I don't know about? 

Thanks in advance. 

Jonny

**Comment by jaheba** [comment]
Hey,

generally speaking, there is no reason not to use gluon-ts in production.

However, we don't have backward-compatible guarantees at the moment. So, given a trained model we can't promise that it will keep working with a new release. Thus, you should make sure that you employ the same code which was used to train the model when loading it again. 

> Is there an alternative method to saving the models that I don't know about?

@lostella pointed out `as_symbol_block_predictor` to me. However, I don't know if we have any experience using it:

https://github.com/awslabs/gluon-ts/blob/f76bf434177ce07c00c72d2109b55e3842c66562/src/gluonts/model/predictor.py#L487-L508

**Comment by lostella** [comment]
> @lostella pointed out as_symbol_block_predictor to me. However, I don't know if we have any experience using it

@Jonny-G13 serializing a `RepresentableBlockPredictor` will store the model parameters only. In case the `mx.gluon.HybridBlock` network code gets updated, the model parameters cannot be guaranteed to be loadable back onto the model.

On the other hand, if you use `.as_symbol_block_predictor` you will get a `SymbolBlockPredictor` instead, which you can `.serialize` more safely: in this case the network gets also serialized together with the parameters, as a symbolic graph, so this is safer *for what concerns the model's network*.

However, a predictor contains more than just a network: for example all the input data transformation pipeline is just Python code and does not involve MXNet. So @jaheba 's recommendation about relying on a specific version of GluonTS applies in general.

**Comment by Jonny-G13** [comment]
Ok thanks guys that's really useful information. I'll be sure to check out the .as_symbol_block_predictor for saving. I plan to be retraining my models regularly so if i just keep the same mxnet and gluonts versions I shouldn't have a problem correct?

**Comment by lostella** [comment]
> I plan to be retraining my models regularly so if i just keep the same mxnet and gluonts versions I shouldn't have a problem correct?

That’s correct

**Comment by bibinmjose** [comment]
@lostella Is there way to extract the model from predictor and save it in a backward compatible way, so that it can be loaded independently. I can see that `mxnet` models cab be save using the files mentioned below with each file having the information to recreate original model.

```
SYMBOL_PATH = 'model-symbol.json'
PARAMS_PATH = 'model-0000.params'
SHAPES_PATH = 'model-shapes.json'
```

Also, when you save using serialize we get this warning. What is the preferred method?

```
WARNING:root:Serializing RepresentableBlockPredictor instances does not save the prediction network structure in a backwards-compatible manner. Be careful not to use this method in production.
```

**Comment by lostella** [comment]
@bibinmjose the warning you see there is alerting you that the serialized model will in fact *not* be backwards compatible (changes in the python code of the network may render the saved parameters incompatible). To store a `predictor` object in a backwards compatible way you can use the `as_symbol_block_predictor` method first:

```python
sb_predictor = predictor.as_symbol_block_predictor(dataset)
sb_predictor.serialize(path)
```

After you run the second line, you can check in the `path` for what happened: as you say, the MXNet serialization mechanism will be used to store JSON network representation, shapes, and parameter values using MXNet serialization mechanism. More information will be stored there about the feature pre-processing needed for proper data loading.

If you're curious, you can check [how exactly mxnet-based predictors serialize](https://github.com/awslabs/gluon-ts/blob/da8442a8dd7d4e6b0251e7d44a3be39419bee131/src/gluonts/mx/model/predictor.py#L194-L220) and [how the network is specifically handled in the case of `SymbolBlockPredictor`](https://github.com/awslabs/gluon-ts/blob/da8442a8dd7d4e6b0251e7d44a3be39419bee131/src/gluonts/mx/model/predictor.py#L245-L246)

**Comment by pd3nbplus** [comment]
@lostella when I use the as_symbol_block_predictor, I pass a `next(iter(train_ds))` as the batch, but It raise the Error that `KeyError: 'feat_static_real'` But actually I didn't use the `feat_static_real` as my train_ds. How can I deal with it?

**Comment by lostella** [comment]
@pd3nbplus try to invoke the method by giving it the `dataset` argument, and all necessary preprocessing and batching (which includes creating the `feat_static_real` field) will happen internally:

```python
predictor.as_symbol_block_predictor(dataset=train_ds)
```

In fact, this should be the preferred mode of invocation for `as_symbol_block_predictor`, whenever one obtains the `predictor` out of the built-in `train` method from estimators.
