### ISSUE TITLE
DeepState on GPU

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#850]
Hello
I am working on deepstate and I found that it does not support GPU.However,I tried implementing the solution given in #336 ,to use in trainer ctx=mx.context.gpu(0).But whenever I use this ,my Google Colab crashes ...
PS:It works well with DeepAR and other models.
Please suggest how to use GPU for deepstate

**Comment by AaronSpieler** [comment]
Could you please provide more information? e.g. error logs?
