### ISSUE TITLE
Framework agnostic sub-packages

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#877]
The goal is to become framework agnostic. This means, that most of our modules should not rely on mxnet, but instead mxnet related code should move to a dedicated `mx` module.

- [x] core
- [x] dataset
- [x] evaluation
- [x] shell
- [x] support
- [x] testutil
- [x] transform

**Comment by kashif** [comment]
Feel free @jaheba to assign me some todos for this. I would love to help.

**Comment by jaheba** [comment]
Except models in `module` and `mx`, no other sub-package requires `mxnet` to be installed.
