### ISSUE TITLE
shell or sagemaker_sdk for production

### ISSUE THREAD

**Issue by dzhang** [awslabs/gluon-ts#881]
Hi

I trained my DeepAR model on SageMaker notebook, now want to deploy the model in production on SageMaker. 

there seems to be two ways to do this, one is shell, one is sagemaker_sdk, I saw the example notebook for sagemaker_sd, but could not find any docs or examples for shell.

I plan to create a docker container for my code, and use SageMaker batch transform for prediction, which one of these is a better option?

Thanks
Dong

**Comment by jaheba** [comment]
I think the shell module is the right tool here.

Let me add some documentation on how to use it.

**Comment by jaheba** [comment]
@dzhang I've added some documentation: https://github.com/awslabs/gluon-ts/pull/882/files#diff-987529ebff8bd4061737ac60da87a484
