### ISSUE TITLE
Using Gluon-TS for anomaly detection

### ISSUE THREAD

**Issue by alecalma** [awslabs/gluon-ts#888]
Hi,

I had a look at the tutorials and they are all forecasting related.
I would like to know if I could use the library for anomaly detection among different time series.
Let me explain better: I have a big dataset with hundreds of time series which should be all very similar to each other. I would like to run an automated tool that identifies anomalous time-series and is able to cluster them based on some similarity metric.

Would this be possible with Gluon-TS?

Thank you.

**Comment by jaheba** [comment]
Hello @alecalma,

the short answer is no: gluon-ts is not suited to detect anomalous time-series in a dataset.

Surely, some components could be reused, but the general idea of gluon-ts is to be a forecasting oriented library, making predictions about the future. There are ideas to use gluon-ts to detect anomalous values by making predictions and then compare the result to the real value, but I think that's a fundamentally different problem from yours.
