### ISSUE TITLE
When I use the #898 code, there are some problems

### ISSUE THREAD

**Issue by k-user** [awslabs/gluon-ts#940]
In the past, when I used gluon-ts-0.5.0, num_workers>1 could not be set. I saw the code lostella released in #898 the other day and pulled it down for use. Num_workers can be set to greater than 1, but there are some problems. Could you please take a look at these problems for me? The following is some logs of the problem. @lostella 

100%|███| 50/50 [00:01<00:00, 31.63it/s, epoch=194/10000, avg_epoch_loss=-.0183]
100%|███| 50/50 [00:01<00:00, 31.55it/s, epoch=195/10000, avg_epoch_loss=0.0884]
WARNING:root:Serializing RepresentableBlockPredictor instances does not save the prediction network structure in a backwards-compatible manner. Be careful not to use this method in production.
Running evaluation: 100%|████████████████████| 336/336 [00:02<00:00, 112.13it/s]

Train process 0 ,Epochs 10000, Batch_size: 32, Learning_rate: 0.01, Num_cells: 40, Num_layers: 4, cell_type: lstm
  0%|                                                    | 0/50 [00:00<?, ?it/s][06:25:22] src/engine/threaded_engine_perdevice.cc:101: Ignore CUDA Error [06:25:22] /home/ubuntu/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./tensor_gpu-inl.h:35: Check failed: e == cudaSuccess: CUDA: initialization error
Stack trace:
  [bt] (0) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6b8b5b) [0x7ff3de97fb5b]
  [bt] (1) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37ab842) [0x7ff3e1a72842]
  [bt] (2) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37ceece) [0x7ff3e1a95ece]
  [bt] (3) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c19d1) [0x7ff3e1a889d1]
  [bt] (4) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37b74a1) [0x7ff3e1a7e4a1]
  [bt] (5) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37b83f4) [0x7ff3e1a7f3f4]
  [bt] (6) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(mxnet::NDArray::Chunk::~Chunk()+0x3c2) [0x7ff3e1cada42]
  [bt] (7) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6bc30a) [0x7ff3de98330a]
  [bt] (8) /home/cjk/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(MXNDArrayFree+0x54) [0x7ff3e19e89c4]

Some parameters:
epoch=10000,Batch_size=32,num_workers=2, num_prefetch=96

Problem 1: when epoch reaches about 200, the training will end.
Problem 2: CUDA initialization error occurs when training the next target.

Thank you very much for your time.

**Comment by lostella** [comment]
@k-user could you wrap code and log sections between triple-backticks? That will improve readability. Thanks!

**Comment by lostella** [comment]
> In the past, when I used gluon-ts-0.5.0, num_workers>1 could not be set.

It seems like this would deserve an issue on its own. @k-user could you open a dedicated bug report with a self-contained code example? Please use the "bug" option when opening the issue. Thanks.

**Comment by k-user** [comment]
> > In the past, when I used gluon-ts-0.5.0, num_workers>1 could not be set.
> 
> It seems like this would deserve an issue on its own. @k-user could you open a dedicated bug report with a self-contained code example? Please use the "bug" option when opening the issue. Thanks.

Ok, thank you very much. I will feedback this problem to the BUG. Since this is the first time For me to ask a question, there is a problem with the format. Next time I'll pay attention.

**Comment by lostella** [comment]
Sure, no problem, and thanks for reporting this! I will close this in favor of the bug report
