### ISSUE TITLE
Does context length include past features as well?

### ISSUE THREAD

**Issue by GabrielDeza** [awslabs/gluon-ts#960]
Hi,

From the extended tutorial, it seems that `context length` defines the number of time steps to look back to predict the next `predict length` time steps. Does the model only look at the past time series in the `context length` window or does it also look at the features?

If this is confusing, here is why this is a concern for me. I have a time series which I would like to predict, with 1 dynamic real features (ie: volume of an item sold). If I have a `context length` and `predict length` of 4, do I have to add 3 more features which are lagged version of this feature to cover t, t-1, t-2, t-3 in total? Or do the models such as DeepAR and DeepState look at lagged features as well?

Thank you :)

**Comment by StatMixedML** [comment]
@GabrielDeza You might find Section 4.2 of the [DeepAR Paper](https://www.sciencedirect.com/science/article/pii/S0169207019301888) helpful. 

![image](https://user-images.githubusercontent.com/41187941/89005752-82bdde80-d305-11ea-8f23-7a2a1c570f8a.png)

The ```context_length``` refers to the length of the unrolled RNN, i.e., the encoder. 

> The conditioning range corresponds to the encoder range introduced in Section 3 and the prediction range to the decoder range. During training, both ranges have to lie in the past so that the z_i,t are observed, but during prediction, z_i,t is only available in the conditioning range.

The  covariates that are assumed to be known for **all time points**. Hence, you can include them, as long as the covariates’ values are available in the prediction range as well. This is also depicted in the following illustration.

![image](https://user-images.githubusercontent.com/41187941/89005971-fb249f80-d305-11ea-8a2c-36b732ed3578.png)
