### ISSUE TITLE
Test minimal viable dependencies

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#98]
We had the issue that our specified minimal version of mxnet (`1.3.0`) did not work.

When doing a fresh install with `pip`, it will install a newer version which still satisfies `>=1.3.0` and thus this mistake wasn't detected (fixed with #96).

Thus, we should think about testing the minimal versions of our dependecies.

**Comment by lostella** [comment]
@jaheba anything to do here? otherwise we could close

**Comment by jaheba** [comment]
Closing this as a no-fix. In the end there is always a danger of not specifying the dependencies correctly. Luckily, after two years we didn't have a similar incident like this one.
