### ISSUE TITLE
The deepar example code (dynamic_feat) on sagermaker make me confued

### ISSUE THREAD

**Issue by samemelody** [awslabs/gluon-ts#981]
I am a beginner at Deepar. The Deepar example code of sagemaker is different from GluonTS. Sagemaker uses "dynamic_feat" and "cat" as extension features.But GluonTS use "feat_dynamic_real" and "feat_static_cat". The "feat_dynamic_real" feature time series should be as long as "target + predict" length.  So when I first try to using Deepar I used "dynamic_feat"  It seems not to work. The code of field name also has "FEAT_DYNAMIC="feat_dynamic"
How do sagemaker "dynamic_feat" and "cat" feature work? Thanks a lot.
I want to add extension features but the length is as long as "target".

**Comment by jaheba** [comment]
The DeepAR version in SageMaker is not the same as the one implemented as part of GluonTS.

GluonTS renamed `cat` to `feat_static_cat` and `dynamic_feat` to `feat_dynamic_real`.

Thus, if you want to use the GluonTS-based model, you need to rename the field-names accordingly.

**Comment by samemelody** [comment]
> 
> 
> The DeepAR version in SageMaker is not the same as the one implemented as part of GluonTS.
> 
> GluonTS renamed `cat` to `feat_static_cat` and `dynamic_feat` to `feat_dynamic_real`.
> 
> Thus, if you want to use the GluonTS-based model, you need to rename the field-names accordingly.

Thanks for your reply. I see the example from Chinese video websites. I didn't see special treatment about "dynamic_feat".  And the "feat_dynamic_real" feature needs to be the same length as “target+predict_length”. Any suggestions about this problem? Maybe should I use my feature as another  "target" of different "feat_static_cat"?

**Comment by jaheba** [comment]
> > The DeepAR version in SageMaker is not the same as the one implemented as part of GluonTS.
> > GluonTS renamed `cat` to `feat_static_cat` and `dynamic_feat` to `feat_dynamic_real`.
> > Thus, if you want to use the GluonTS-based model, you need to rename the field-names accordingly.
> 
> Thanks for your reply. I see the example from Chinese video websites. I didn't see special treatment about "dynamic_feat". And the "feat_dynamic_real" feature needs to be the same length as “target+predict_length”. Any suggestions about this problem? Maybe should I use my feature as another "target" of different "feat_static_cat"?

I think that's a requirement during prediction, where you need to pass the feature-values for `feat_dynamic_real` as well.

During training, the lengths of the `feat_dynamic_real` time-series should match the one of the corresponding target.

**Comment by samemelody** [comment]
> 
> 
> > > The DeepAR version in SageMaker is not the same as the one implemented as part of GluonTS.
> > > GluonTS renamed `cat` to `feat_static_cat` and `dynamic_feat` to `feat_dynamic_real`.
> > > Thus, if you want to use the GluonTS-based model, you need to rename the field-names accordingly.
> > 
> > 
> > Thanks for your reply. I see the example from Chinese video websites. I didn't see special treatment about "dynamic_feat". And the "feat_dynamic_real" feature needs to be the same length as “target+predict_length”. Any suggestions about this problem? Maybe should I use my feature as another "target" of different "feat_static_cat"?
> 
> I think that's a requirement during prediction, where you need to pass the feature-values for `feat_dynamic_real` as well.
> 
> During training, the lengths of the `feat_dynamic_real` time-series should match the one of the corresponding target.

Yes. The feature-value in the future is also unknown. The training has no problem, but when predict. I thought I can get results without pass the feature values. Maybe I should predict the feature values first.

**Comment by jaheba** [comment]
> Yes. The feature-value in the future is also unknown. The training has no problem, but when predict. **I thought I can get results without pass the feature values**. Maybe I should predict the feature values first.

This is not possible with DeepAR. It requires that you pass features also in the prediction range.
