### ISSUE TITLE
Shape & Type of Class Objects in GluonTS

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#983]
# Question

Dear GluonTS-Team, 

- I was wondering what the shape&type of the prediction object for different Networks are. 
- How can I infer the shape&type of any object within a defined `class`

##  Example 1: Simple Feedforward Network

Described [here:](https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/examples/extended_forecasting_tutorial/extended_tutorial.html#5.1-Point-forecasts-with-a-simple-feedforward-network)

```python
class MyTrainNetwork(MyNetwork):
    def hybrid_forward(self, F, past_target, future_target):
        prediction = self.nn(past_target)
        # calculate L1 loss with the future_target to learn the median
        return (prediction - future_target).abs().mean(axis=-1)
```

What is the shape&type of `prediction`?

##  Example 2: Probabilistic RNN

Described [here:](https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/examples/extended_forecasting_tutorial/extended_tutorial.html#5.4-From-feedforward-to-RNN)

```python
class MyProbTrainRNN(MyProbRNN):
    def hybrid_forward(self,
                       F,
                       past_target,
                       future_target,
                       past_observed_values,
                       future_observed_values):

        net_output, _, scale = self.unroll_encoder(F,
                                                   past_target,
                                                   past_observed_values,
                                                   future_target,
                                                   future_observed_values)

        # output target from -(context_length + prediction_length) to end
        target_out = F.concat(
            past_target, future_target, dim=-1
        ).slice_axis(
            axis=1, begin=-(self.context_length + self.prediction_length), end=None
        )

        # project network output to distribution parameters domain
        distr_args = self.proj_distr_args(net_output)

        # compute distribution
        distr = self.distr_output.distribution(distr_args, scale=scale)

        # negative log-likelihood
        loss = distr.loss(target_out)
        return loss
```

What is the shape&type of `net_output` & `target_out`?

**Comment by PascalIversen** [comment]
Hey, 
the type is always a mxnet `NDarray`.
In your first example, the shape of `prediction` is `(batch_size, prediction_length) `which is the same as the shape of future target.
The shape of `net_output` and `target_out` of your second example is `(batch_size, context_length + prediction_length, num_cells)` and `(batch_size, context_length + prediction_length)`, respectively. 

You can always check the shape by adding a print statement e.g. `print(net_output.shape )` to the method you are interested in and then run the method/start the training.

**Comment by StatMixedML** [comment]
@PascalIversen Thanks for your detailed comment!
