### ISSUE TITLE
Getting DeepAR gradients of output w.r.t to inputs (covariates)

### ISSUE THREAD

**Issue by GabrielDeza** [awslabs/gluon-ts#991]
Hi,
I am looking to calculate the gradient of the output of DeepAR w.r.t to it's inputs. In more detail, I have a single time series/target and 10 covariates. I would like to get a vector of length 10 which is the gradient of the output of the model w.r.t to each covariate. I have been going through the DeepAR code (network.py and estimator.py) and from what I understand, the RNN model is defined in the DeepARNetwork init function (shown below)
<img width="714" alt="Screen Shot 2020-08-17 at 12 54 59 PM" src="https://user-images.githubusercontent.com/53381889/90422447-de6bc400-e088-11ea-96a3-79da7bde41ab.png">
 
I am new to MxNet and found the [grad() function](https://mxnet.apache.org/versions/1.6/api/python/docs/api/autograd/index.html#mxnet.autograd.grad) which I think might be useful, but I don't know how to define the "heads" and "variable" input to the grad() function as all the variables are within the RNN API call. This question might be more suited to a MxNet forum than here but I thought I would test my luck if anyone has run into this task before. 

A separate question (less important but just curious)
At the same time, I am reading the DeepAR code and in the paper, the distribution parameters are trained as well via a projection layer. For example, the mean of the gaussian distribution is given by an affine transformation of the RNN output via w and b. (shown below). The paper states that in training, the RNN parameters as well as the distribution parameters (w and b) are learnt.  Where in the code is this final projection layer defined and then updated during training?
<img width="505" alt="Screen Shot 2020-08-17 at 1 01 10 PM" src="https://user-images.githubusercontent.com/53381889/90423011-bb8ddf80-e089-11ea-806c-f1edeb64e2b6.png">

Thank you for any help or advice regarding these two questions, it is greatly appreciated!

**Comment by kashif** [comment]
so the linear layer is in the arg_proj of the distribution output class i.e. https://github.com/awslabs/gluon-ts/blob/a37620ffd4100b3762fc85075c35328dd3d62679/src/gluonts/mx/distribution/distribution_output.py#L60-L70

and then the domain mapping happens in each distribution's version of the distribution output i.e. https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/mx/distribution/gaussian.py#L161 for the softplus on the sigma of the gaussian.

**Comment by GabrielDeza** [comment]
I figured it out so closing.

**Comment by bradyneal** [comment]
@GabrielDeza Do you have any pointers? I'm having the same issue. The lest specific to DeepAR (and more general), the better.
