### ISSUE TITLE
NBEATS doesn't work properly

### ISSUE THREAD

**Issue by skybullet1987** [awslabs/gluon-ts#994]
NBEATS doesn't work with parameters that I described here:
https://github.com/awslabs/gluon-ts/issues/988

I have tried to use other estimators such as DeepARE - it works fine. Only NBEATS is causing issues.

System Windows 10
GluonTS 0.5.1
MXnet 1.6
Python 3.7.7

**Comment by PascalIversen** [comment]
Hey @skybullet1987 , 

thank you for the bug report.

Could you please provide a minimal example code that reproduces the bug?

I do not experience issues using your hyperparameters like this:
```
import mxnet as mx
from gluonts.dataset.common import ListDataset
from gluonts.model.n_beats import NBEATSEstimator

dataset = ListDataset(
    [{"start": "2020-01-01", "target": list(range(50))}],
    freq="1D"
)
estimator = NBEATSEstimator(freq="D", prediction_length=1, context_length = 5,trainer=Trainer(epochs=10,ctx="gpu"))
predictor = estimator.train(training_data=dataset)

predictor.predict(dataset)
```

**Comment by skybullet1987** [comment]
Hi!

Code example:
test_data = ListDataset([{"start": df.index[0], 
                              "target": df.Close[:prediction_date]}], 
                            freq="D")

    estimator1 = NBEATSEstimator(freq="D", prediction_length=1, trainer=Trainer(epochs=120,ctx="gpu"))
    predictor1 = estimator1.train(training_data=test_data)


Let's suppose I do a 1 day prediction (Sep 1) based on all the data that I have (Aug 31 and earlier).
prediction_date = Sep 1

My dataset structure is:

Jan 1  100
Jan 2  80
...
Aug 31 105
**Sep 1 NaN**

The error that I am getting:

Epoch[0] gave nan loss
 16%|█▌        | 8/50 [00:01<00:08,  5.09it/s, epoch=1/120, avg_epoch_loss=557]
---------------------------------------------------------------------------
GluonTSUserError                          Traceback (most recent call last)
<ipython-input-3-40bea97317d4> in <module>
    117 
    118     estimator1 = NBEATSEstimator(freq="D", prediction_length=1, trainer=Trainer(epochs=120,ctx="gpu"))
--> 119     predictor1 = estimator1.train(training_data=test_data)
    120 
    121     predictions = list(predictor1.predict(test_data))

C:\Anaconda3\lib\site-packages\gluonts\model\estimator.py in train(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, **kwargs)
    269             num_prefetch,
    270             shuffle_buffer_length,
--> 271             **kwargs,
    272         ).predictor

C:\Anaconda3\lib\site-packages\gluonts\model\estimator.py in train_model(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, **kwargs)
    242             input_names=get_hybrid_forward_input_names(trained_net),
    243             train_iter=training_data_loader,
--> 244             validation_iter=validation_data_loader,
    245         )
    246 

C:\Anaconda3\lib\site-packages\gluonts\mx\trainer\_base.py in __call__(self, net, input_names, train_iter, validation_iter)
    372                         if best_epoch_info["epoch_no"] == -1:
    373                             raise GluonTSUserError(
--> 374                                 "Got NaN in first epoch. Try reducing initial learning rate."
    375                             )
    376 

GluonTSUserError: Got NaN in first epoch. Try reducing initial learning rate.


If I use same parameters (same dataset), but DeepAREstimator - everything works.

**Comment by PascalIversen** [comment]
Thank you. 

1. Are you sure there are no `NaN` target values in the training data? The DeepAR transformations handle missing values, but NBEATS does not do this by default. If there are any, you can replace them yourself as a quick fix.
2. If there are no missing values, can you try to reduce the learning rate, by adjusting `learning_rate` parameter of the `Trainer`?

**Comment by skybullet1987** [comment]
Thank you for clarifications.

1)Could you pleas tell - if my dataset doesn't have a specific target value (for e.g. sales for tomorrow, and I don't know what they are, but I want to predict them with NBEATS), what should I use instead of NaN for that 1 day into the future prediction that I described?

If I use existing data point (for e.g. Aug 31 with some sales value) and use Aug 31 as prediction_date (all same code as above) - I can see that NBEATS produces very accurate results (very close to Aug 31).

2)The only missing value is the target value (which I don't know, because that is exactly what I am trying to predict). What learning rate parameter should I try?

I am just trying to use NBEATS to produce a 1 day prediction into the future.

**Comment by PascalIversen** [comment]
If you want to predict a specific date of a time series, this time point should not be in the training dataset. Create a training and a test dataset. For the test dataset, you have to provide the context for your prediction (note the `context_length` parameter, which defaults to `2*prediction_length` for the `NBEATSEstimator`)

Here is a toy example on how to do a one day prediction:
```python
from gluonts.dataset.common import ListDataset
import pandas as pd
import numpy as np
from gluonts.model.n_beats import NBEATSEstimator
from gluonts.mx.trainer import Trainer
from datetime import timedelta
start = pd.Timestamp("01-01-2019", freq='D')
end = pd.Timestamp("01-01-2019", freq='D') + timedelta(days=100)
timerange = pd.date_range(start=start, end=end, freq="D")
target = np.append(np.random.randn(99), np.nan)

training_data = ListDataset([{"start": start,
                              "target": target[:-1]}],
                            freq="D")

estimator = NBEATSEstimator(freq="D", context_length=2, prediction_length=1, trainer=Trainer(epochs=10, ctx="cpu"))
predictor = estimator.train(training_data=training_data)

test_data = ListDataset([{"start": timerange[-3],
                              "target": target[-3:-1]}],
                            freq="D")
s = predictor.predict(test_data)
sf = next(s)
print(sf)

```

**Comment by skybullet1987** [comment]
Thank you very much for your example.

Could you please clarify some lines of your code:

I am trying to understand the following:

your timerange represents 101 days:
dtype='datetime64[ns]', length=101, freq='D'

However, target has only 100 elements:
print(np.count_nonzero(np.isnan(target)))
print(np.count_nonzero(~np.isnan(target)))
1 - nan
99 - some values

Why do you have 2 days without any values, instead of one (day that you want to predict)?

Your training dataset uses everything up to day 100. But value for day 100 is already 0, just as day 101.

**Comment by skybullet1987** [comment]
Awesome!

Checked on my dataset - it works just as intended! Thank you!

**Comment by PascalIversen** [comment]
Great! Could you please close the issue?
